### ISSUE TITLE
Remove the Java arrays standard library from the Ballerina distribution

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1034]
According to the latest discussions, we have agreed to remove the Java arrays standard library from the final Ballerina distribution. 

Still, the upcoming releases will be available in the [Ballerina central](https://swanlake.central.ballerina.io/) and users will be able to pull the library from there.

**Comment by daneshk** [comment]
We decided not to remove java.arrays from the distribution.
