### ISSUE TITLE
Introduce a centralized Gradle configurations for standard libraries

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1035]
Recently, we came across several configuration changes to the Gradle files that we configured initially to the stdlibs. Change 30+ configuration files is cumbersome and time-consuming work.

To solve this, we can introduce a centralized Gradle configuration file(Or perhaps multiple config files). In this centralized config file, we can add the common configurations such as:
- native build
- Ballerina test, build, and push phases
- unpack jBallerina and stdlib dependencies etc.

Since Gradle support importing other Gradle scripts via HTTP URLs, this will be a straightforward implementation. For more details:
-  https://stackoverflow.com/questions/2566685/is-there-a-way-to-split-factor-out-common-parts-of-gradle-build
-  https://docs.gradle.org/current/userguide/userguide_single.html#sec:configuring_using_external_script

**Comment by daneshk** [comment]
I think we can close this now. @BuddhiWathsala

**Comment by BuddhiWathsala** [comment]
Closing this since the [Gradle plugin](https://github.com/ballerina-platform/plugin-gradle) provides these functionalities.
