### ISSUE TITLE
Add coverage data from integration tests when generating Codecov report

### ISSUE THREAD

**Issue by anjaleeps** [ballerina-platform/ballerina-standard-library#1037]
Jacoco XML report  being sent to Codecov does not contain coverage data taken by running integration tests. 
The log module currently creates a new process to run the unit tests using the `os:exec` function. 

```
os:Process|error execResult = os:exec(bal_exec_path, {}, (), "run", LOG_LEVEL_TEST_FILE);
```
Since the `os:exec` function is expected to undergo changes, a method to capture the coverage data from integration tests is not implemented in the log module. Once the `exec` function changes are finalized, introduce a method to capture integration test coverage in the log module.

**Comment by daneshk** [comment]
Log module coverage is improved and `os:Process` feature is removed from the os module. Hense closing this issue
