### ISSUE TITLE
Change println and print functions to accept raw template

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#1050]
Current `io:println` and `io:print` functions accepts var args of `any|error`. We need to change this to accepts only `anydata|error|RawTemplate` like below,

```
type Printable anydata|error|PrintableRawTemplate;

type PrintableRawTemplate object {
  *object:RawTemplate;
  Printable[] insertions;
};

function println(Printable...);
```

So that user can pass multiple Raw Template value like below,

```
io:println(`hello ${name}`, “good afternoon”);
```

**Comment by BuddhiWathsala** [comment]
@daneshk, I'm wondering why we need to use a customized raw template `PrintableRawTemplate` instead of directly using the `object:RawTemplate`.

**Comment by hasithaa** [comment]
@BuddhiWathsala , you need to define how toString works for Printable and PrintableRawTemplate, and use that in io:println function when constructing final the string value. You can't do this by using `object:RawTemplate` type.
