### ISSUE TITLE
RemoteFileSystemServerConnector cannot be stopped 

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-standard-library#108]
**Description:**
[RemoteFileSystemServerConnectorImpl](https://github.com/wso2/transport-file/blob/master/components/org.wso2.transport.remote-file-system/src/main/java/org/wso2/transport/remotefilesystem/server/connector/contractimpl/RemoteFileSystemServerConnectorImpl.java#L33) does not have any option to stop/close the server connector object, at the moment.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
FTP connector 0.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Bhashinee** [comment]
This needs to be addressed in the `org.wso2.transport.remotefilesystem` package. As we are re-writing we can fix this along with this issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1506
