### ISSUE TITLE
Enable ignored test cases in db clients after new time APIs migration

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-standard-library#1098]
There were some test cases commented out in db client packages when introducing new Time module APIs.

Need to enable and restore those commented out test cases in db clients.  

Related PRs
> sql: https://github.com/ballerina-platform/module-ballerina-sql/pull/150
> java.jdbc: https://github.com/ballerina-platform/module-ballerinax-java.jdbc/pull/97
> mysql: https://github.com/ballerina-platform/module-ballerinax-mysql/pull/93

**Comment by daneshk** [comment]
Tests are enabled, hence closing the issue
