### ISSUE TITLE
The functions to convert current time to time of another time zone and format the time is not supported in slalpha3-SNAPSHOT 

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-standard-library#1117]
**Description:**
I'm using a function which uses the ballerina time module to convert the current time to the time of time-zone `Europe/London` and format that time in `EEE, dd MMM yyyy HH:mm:ss z` format. 

**Describe your problem(s)**
This function which I have used in slalpha2 uses 3 functions from older time module
1. Function to get current time 
``` ballerina  
time:Time currentTime = time:currentTime();
```
2. Function to convert this time to time of `Europe/London`
```ballerina
time:Time timeWithZone = check time:toTimeZone(currentTime, "Europe/London");
```
3. Function to format that time to `EEE, dd MMM yyyy HH:mm:ss z` format
```ballerina
string finalValue = check time:format(timeWithZone, "EEE, dd MMM yyyy HH:mm:ss z");
```
but  the new slalpha3-SNAPSHOT version have support for [1] above only. 

**Describe your solution(s)**
Provide support for the functions which can be used for similar kind of operations in [2] and [3] in SL Alpha3 release.

**Comment by BuddhiWathsala** [comment]
To address that, we need to following APIs which we planned for phase 02:
```ballerina
// Converts to RFC 5322
function civilToEmailString(Civil civil, HeaderZoneHandling)
returns string;

// Handler of 5322
function civilFromEmailString(string) returns Error|Civil;

type UtcZoneHandling "0" | "GMT" | "UT" | "Z";

// Include seconds, include day of week
// Follow HTTP subset apart from zone
function utcToEmailString(Utc utc, UtcZoneHandling zh = "0")
   returns string;

```
@daneshk shall we prioritize these APIs for the next release.

**Comment by daneshk** [comment]
If I get the problem correctly, The problem is we don't support converting ballerina records to different time formats. We only support [RFC 3339](https://tools.ietf.org/html/rfc3339) time format. 

Can we know bit more details about the use case. Can't we use `UTC` time, instead of a specific time zone?

**Comment by sachinira** [comment]
In Azure Cosmos DB connector, to generate the Authorization header we need to include current time also. For that we need to format the current date according to  [RFC 7231 Date/Time Format](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) as per the [documentation] (https://docs.microsoft.com/en-us/rest/api/cosmos-db/access-control-on-cosmosdb-resources). So I have used `time:toTimeZone` and `time:format` functions for formatting the date.

**Comment by daneshk** [comment]
As Buddhi mentioned, we will provide support to convert to RFC 7231 Date/Time Format.
As a workaround, we need to add conversion logic in each connector. sample impl https://gist.github.com/daneshk/85ab0650ee81cd16fb8a3f5377902b5f

**Comment by BuddhiWathsala** [comment]
@sachinira could you please give some counterexamples that we can test?.

**Comment by sachinira** [comment]
@daneshk There are some examples found in current connector implementations. They are summarized in this code
```ballerina
import ballerina/io;
import ballerina/time;

public function main() {

    time:Time standardTime = checkpanic time:toTimeZone(time:currentTime(), "GMT");
    
    string storageTime = time:format(standardTime, "EEE, dd MMM yyyy HH:mm:ss z");
    string amzDate = time:format(standardTime, "yyyyMMdd'T'HHmmss'Z'");
    string dateStamp = time:format(standardTime, "yyyyMMdd");
    
    io:println(storageTime);
    io:println(amzDate);
    io:println(dateStamp);
}
```
Azure Storage Service Connector
https://github.com/LakshanSS/module-ballerinax-azure-storage-service/blob/main/modules/utils/utils.bal#L24

Amazon SQS Connector
https://github.com/kapilraajP/module-ballerinax-aws.sqs/blob/f332da79b7b9447c0d1fb8a19197721306e45766/endpoint.bal#L219

**Comment by daneshk** [comment]
@sachinira ISO 8601 Data Time Format is `YYYY-MM-DDThh:mm:ss.sTZD` not `yyyyMMdd'T'HHmmss'Z'` as per [1].

1. https://www.w3.org/TR/NOTE-datetime

**Comment by sachinira** [comment]
> @sachinira ISO 8601 Data Time Format is `YYYY-MM-DDThh:mm:ss.sTZD` not `yyyyMMdd'T'HHmmss'Z'` as per [1].
> 
>     1. https://www.w3.org/TR/NOTE-datetime

Amazon SQS connector needs the `basic format` of ISO 8601 Date Time format without punctuation for setting the  `X-Amz-Date` header as per [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/CommonParameters.html)

**Comment by daneshk** [comment]
We are not going to support all the Date Time format conversions from the Time module. The best approach is to support these connector-specific date format conversions in each connector.
