### ISSUE TITLE
ballerina-standard-library is a python project

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-standard-library#1125]
**Description:**
![Screenshot 2021-03-23 at 11 33 22](https://user-images.githubusercontent.com/1496990/112100927-ddc18000-8bcb-11eb-8090-916825c18775.png)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
This is now resolved.
