### ISSUE TITLE
Architecture diagram failed to load in IO doc page

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-standard-library#1126]
**Description:**

![Screenshot 2021-03-23 at 11 31 55](https://user-images.githubusercontent.com/1496990/112101073-15302c80-8bcc-11eb-9627-af445c9f97f8.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by BuddhiWathsala** [comment]
Related to this https://github.com/ballerina-platform/ballerina-lang/issues/29946

**Comment by daneshk** [comment]
@BuddhiWathsala Can we temporarily remove this diagram from the API Doc if the issue not fix soon

**Comment by BuddhiWathsala** [comment]
+1

**Comment by BuddhiWathsala** [comment]
Closing this since we removed the architecture diagram.
