### ISSUE TITLE
Broken link in ballerinax/rabbitmq

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-standard-library#1128]
**Description:**

In https://central.ballerina.io/ballerinax/rabbitmq, There is a broken link to `QoS Settings Example` at the very bottom of the page.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Ballerina Swan Lake - Alpha3

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
This entire page was redone in https://github.com/ballerina-platform/module-ballerinax-rabbitmq/pull/177. This issue is no longer valid. 
To verify visit: https://central.ballerina.io/ballerinax/rabbitmq
