### ISSUE TITLE
[Team VCoDeS] No method for get file Name

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#113]
**Description:**
Refer https://github.com/ballerinalang/ballerina/issues/3022 for more details

**Comment by kalaiyarasiganeshalingam** [comment]
File module has [`baseName()`](https://docs.central.ballerina.io/ballerina/file/0.7.0-beta.1/functions#basename) which is equivalent method for `java.io.File.getName()`. Hence, Closing this issue.
