### ISSUE TITLE
Improvements to generated code with gRPC clients

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-standard-library#1130]
**Description:**
Consider the following protobuf definition.

```
syntax = "proto3";

import "google/protobuf/wrappers.proto";

service Validator {
	rpc validate(stream google.protobuf.StringValue)
			returns (google.protobuf.BoolValue);
}
```

**Describe your problem(s)/solution(s)**
1. in the `ValidateStreamingClient` generated for this the name of the send string method is `sendstring`. Shouldn't this be `sendString`?
2. In the generated `main` function (`--mode client`), the `main` function has a rest param. Shouldn't we generate the `main` function with no params instead?
3. Some union types have parentheses around them (e.g.,  `validate` in `ValidatorClient`). We don't need them, right? This doesn't seem to happen with all unions though,

**Comment by MaryamZi** [comment]
The new lines added between different constructs (e.g., between two type definitions, between two methods of a class) also seem to be inconsistent.

**Comment by daneshk** [comment]
This is fixed in the latest SL release. We are now using the Ballerina syntax tree to generate the code.
