### ISSUE TITLE
Email module BBE example throws compilation errors

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-standard-library#1134]
**Description:**

Email module BBE example throws compilation errors.

Please check https://ballerina.io/1.2/learn/by-example/send-and-receive-emails.html

**Steps to reproduce:**

Please try https://ballerina.io/1.2/learn/by-example/send-and-receive-emails.html

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Maninda** [comment]
Fixed in the Beta 1 release
