### ISSUE TITLE
[VCoDeS] - Windows: File System Server Connector 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#114]
**Description:**
Refer https://github.com/ballerinalang/ballerina/issues/3024 for more details

**Comment by kalaiyarasiganeshalingam** [comment]
You can get the latest directory listener [here ](https://ballerina.io/learn/by-example/directory-listener). I have checked this sample with Windows OS. It worked without any issue Hence, Closing this issue.
