### ISSUE TITLE
Errors running RabbitMQ BBEs

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-standard-library#1143]
**Description:**

Tried running the following two examples:
https://ballerina.io/learn/by-example/rabbitmq-producer.html
https://ballerina.io/learn/by-example/rabbitmq-consumer.html - (had to change log:print to log:printDebug)

But I get the following error at runtime:
![image](https://user-images.githubusercontent.com/6542630/112131396-86350b80-8bef-11eb-8731-674afe2d9896.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-dev-website/issues/2031 

**Suggested Labels (optional):**

Version/SLAlpha3

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
This issue is resolved in Ballerina version Swan Lake Beta 1
<img width="662" alt="Screenshot 2021-06-10 at 14 30 14" src="https://user-images.githubusercontent.com/39673615/121496820-7233c580-c9f8-11eb-95b8-4eab0feda628.png">
