### ISSUE TITLE
Wrong service type example for NATS listener

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-standard-library#1148]
**Description:**
The example provided in the doc as well as found in the source repo is like the below.

```ballerina
// Binds the consumer to listen to the messages published to the 'demo' subject.
@nats:ServiceConfig {
    subject: "demo"
}
service demo on new nats:Listener() {

    remote function onMessage(nats:Message msg) {
    }
}
```

This results in a compilation error 

```
ERROR [service.bal:(7:9,7:13)] unknown type 'demo'
error: compilation contains errors
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-distribution/pull/1472
