### ISSUE TITLE
[VCoDeS] Windows: file system server connector

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#115]
**Description:**
Refer https://github.com/ballerinalang/ballerina/issues/3025 for more details.

**Comment by kalaiyarasiganeshalingam** [comment]
You can get the latest directory listener [here](https://ballerina.io/learn/by-example/directory-listener). I have checked this sample with Windows OS. Directory listener returned the following correct path name:
`C:\Users\ashak\OneDrive\Documents\test.bal`
But The above BBE print the path with extra slash as log is using additional validation to [escape invalid characters.](https://github.com/ballerina-platform/ballerina-standard-library/issues/1192) The output of the log:printInfo: 
 `time = 2021-07-02T16:15:40.885+05:30 level = INFO module = "" message = "Modify: C:\\Users\\ashak\\OneDrive\\Documents\\test.bal"`
@daneshk @MadhukaHarith92 I think we need to improve the escape invalid character impl according to the OS

**Comment by daneshk** [comment]
@kalaiyarasiganeshalingam this is because the backslash is a special character and we are escaping special characters from the message printing it to console.

**Comment by kalaiyarasiganeshalingam** [comment]
File listener works fine. Hence, closing this issue.
