### ISSUE TITLE
Inconsistent behaviour with gRPC bidirectional streaming

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-standard-library#1151]
**Description:**
When the BBE is modified to attempt a receive without a single send, the receive seems to block. If at least one is sent, `grpc:EOS` seems to be received as expected after receiving the expected messages. 

Is this the expected behaviour expected?

**Steps to reproduce:**
Modify https://ballerina.io/learn/by-example/grpc-bidirectional-streaming.html to not call

```ballerina
streamingClient->sendChatMessage(msg)
```

The behaviour is the same when `check streamingClient->complete();` is present/removed.

Also, if instead of the stream return type, the service returns `error?` and keeps calling ``checkpanic cl->sendString(string `${chatMsg.message}: ${chatMsg.name}`);`` per message, the behaviour changes a bit.
- it still blocks when both `sendChatMessage` and `complete` are removed
- but when `complete` is not removed (only `sendChatMessage` is removed), it does not block

**Affected Versions:**
slalpha3

**Comment by daneshk** [comment]
Bidirectional Streaming BBE is updated with a proper sample. Send Request and Receive Response should be in two different worker threads because sending and receiving can be done simultaneously
