### ISSUE TITLE
Async Client link is broken in Websockets Documentation

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-standard-library#1153]
**Description:**
$subject. No documentation found on writing an Async client.

**Steps to reproduce:**
![Screenshot 2021-03-23 193155](https://user-images.githubusercontent.com/4398820/112158768-7c6ed080-8c0e-11eb-9a41-7da7993d4173.png)

**Affected Versions:**
SL Alpha3

**OS, DB, other environment details and versions:**
Windows

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Bhashinee** [comment]
Closing the issue as we no longer support Async Client
