### ISSUE TITLE
Unable to implement a websub usecase

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-standard-library#1155]
**Description:**
I am trying to implement a websub use case but not able to get it done.
I have tried using https://github.com/ballerina-platform/ballerina-distribution/blob/master/examples/websub-hub-client-sample/subscriber_service.bal , but I am not able to build it because of the following errors:

```
PS C:\Users\hemik\github\bifinance-trading-bot> bal build

Compiling source
        hemik/bifinance_trade_bot:0.1.0
ERROR [main.bal:(18:36,18:55)] unknown type 'Notification'
ERROR [main.bal:(21:13,21:66)] undefined function 'print'
ERROR [main.bal:(21:13,21:66)] undefined module 'log'
ERROR [main.bal:(23:13,24:49)] undefined function 'printError'
ERROR [main.bal:(23:13,24:49)] undefined module 'log'
error: compilation contains errors
```

It seems the BBEs are also missing:
![Screenshot 2021-03-23 195938](https://user-images.githubusercontent.com/4398820/112162721-521f1200-8c12-11eb-9d88-38b32b44956a.png)

**Describe your problem(s)**
Attempting to implement for https://docs.binance.org/api-reference/dex-api/ws-connection.html

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
@hemikak I think you have to refer to websockets not websub.

**Comment by hemikak** [comment]
@gimantha , I may have been wrong. But I was planning to subscribe to a websocket. See "Method 2: Subscribe to streams on demand" section.

**Comment by ayeshLK** [comment]
@hemikak we have done an API upgrade for `websub module`. You could refer to [following BBE ](https://ballerina.io/learn/by-example/websub-webhook-sample.html) on updated implementation.

**Comment by ayeshLK** [comment]
This issue is not relevant to latest `websub` framework. Hence closing the issue.

**Comment by praneesha** [comment]
Closing as per the above comment.
