### ISSUE TITLE
All NATS related examples contain <@untainted> reference when constructing NATS messages 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-standard-library#1157]
**Description:**
All NATS examples from learn page have `@untainted>` when creating NATS message as bytes. This is not needed anymore.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-distribution/pull/1851
