### ISSUE TITLE
Secured Service with JWT Auth BBE link returns 404 page

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-standard-library#1159]
First filtered link ([https://ballerina.io/learn/by-example/secured-service-with-jwt-auth.html](https://ballerina.io/learn/by-example/secured-service-with-jwt-auth.html))  for JWT documentation drives to 404 page when searching documentation and BBEs for JWT module by googling with `ballerina jwt` key words. 
[https://www.google.com/search?q=ballerina+jwt&oq=ballerina+jwt&aqs=chrome..69i57j69i60l3.4447j0j7&sourceid=chrome&ie=UTF-8](https://www.google.com/search?q=ballerina+jwt&oq=ballerina+jwt&aqs=chrome..69i57j69i60l3.4447j0j7&sourceid=chrome&ie=UTF-8)

**Comment by praneesha** [comment]
Closing since this is addressed in https://ballerina.io/learn/by-example/http-service-jwt-auth.html now.
