### ISSUE TITLE
Allow specifying a file name for `email:Attachment`

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-standard-library#1162]
**Description:**
Can we add a file name for an attachment, other than the filePath and the contentType? 
The attached document will have `noname` as the file name ATM.
```
email:Attachment att = {filePath: "/home/xxx/abc.pdf", contentType: mime:APPLICATION_PDF};
```
![Screenshot from 2021-03-24 07-30-12](https://user-images.githubusercontent.com/19838787/112243086-fa64c300-8c72-11eb-8acf-e4c94f85d7b7.jpg)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Maninda** [comment]
Attachment file name should be set automatically, taken from the `filePath`. Therefore, will set this as a bug.
