### ISSUE TITLE
Issue with resolving public cert path in HTTP client with OAuth2 client credentials grant type

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-standard-library#1165]
Path with `../public.cert` in `secureSocket` record won't be resolve when client is secured with OAuth2 client credentials grant Type. It returned this error message 
```
error: error Error ("Failed to call the token endpoint.",error("Failed to init SSL context. Failed to get the public key from Crypto API. Certificate file not found at: /home/hansani/Ballerina_project/release_check/projects/alpha3_hackathon/scenario_01/../public.cert"))
```
  but it works with `./public.cert`

```ballerina
http:Client securedEP = check new("https://localhost:9443", {
    auth: {
        tokenUrl: "https://localhost:9443/oauth2/token",
        clientId: "s6BhdRkqt3",
        clientSecret: "7Fjfp0ZBr1KtDRbnfVdmIw",
        scopes: ["Customer"],
        clientConfig: {
            secureSocket: {
                cert: "../public.cert"
            }
        }
    },
    secureSocket: {
        cert: "./public.cert"
    }
});
```

**Comment by ldclakmal** [comment]
Yes. This is due to the cert file path you provided for the client which is used to call the authorization endpoint is invalid. AFAIU, this behavior and error message is correct. Please clarify the bug you are referring to.

**Comment by lnash94** [comment]
As discussed offline, now it is clear for having path `../public.cert` and `./public.cert`. Appeared there is no issue with the paths given and it is an expected error message. +1 to close this issue since this is not a bug.
