### ISSUE TITLE
[SQL] Problem occurs while migrating to new Ballerina Time types

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#1168]
**Description:**
We migrated Ballerina Date, Time type to new [Ballerina types](https://github.com/ballerina-platform/module-ballerina-sql/blob/master/sql-ballerina/types.bal#L252-L294), We encountered the following problems when migrating DB modules to the new Time module.

**Problem 01**
Some databases like (HSQLDB, PostgreSQL) supports the TIME_WITH_ZONE type. We don't have a specific type to support it in the time module.

**Proposed Solution**
Introduce new record type in SQL module like,

```
public type TimeWithZoneOffset record {	
    *time:TimeOfDay;	
    time:ZoneOffset utcOffset?;
}
```
and add this record to the `TimeValue` type in SQL like below,

```
public class TimeValue {
    public string|int|time:TimeWithZoneOffset? value;

    public isolated function init(string|int|time:TimeWithZoneOffset? value = ()) {
        self.value = value;
    }
}
```

**Problem 02**
Previously, we allowed initiating DateValue, TimeValue, DateTimeValue, and TimestampValue by passing int values like below,
which represents the millisecond value from the epoch time. As now, we have a `time:Utc` record which captures the same value in nanoseconds precious, shall we allow passing `time:Utc` record
 
```
public class DateTimeValue {
    public string|int|time:Civil? value;

    public isolated function init(string|int|time:Civil? value = ()) {
        self.value = value;
    }
}
```

**Proposed Solution**
With the proposed change, Ballerina type for Database Date type will look like,

```
# Represents Date SQL field.
#
# + value - Value of parameter passed into the SQL statement
public class DateValue {
    public string|time:Utc|time:Date? value;

    public isolated function init(string|time:Utc|time:Date? value = ()) {
        self.value = value;
    }
}

# Represents Time SQL field.
#
# + value - Value of parameter passed into the SQL statement
public class TimeValue {
    public string|time:Utc|time:TimeWithZoneOffset? value;

    public isolated function init(string|time:Utc|time:TimeWithZoneOffset? value = ()) {
        self.value = value;
    }
}

# Represents DateTime SQL field.
#
# + value - Value of parameter passed into the SQL statement
public class DateTimeValue {
    public string|time:Utc|time:Civil? value;

    public isolated function init(string|time:Utc|time:Civil? value = ()) {
        self.value = value;
    }
}

# Represents Timestamp SQL field.
#
# + value - Value of parameter passed into the SQL statement
public class TimestampValue {
    public string|time:Utc? value;

    public isolated function init(string|time:Utc? value = ()) {
        self.value = value;
    }
}
```

**Comment by lahirusamith** [comment]
Comparison Document: https://docs.google.com/document/d/1mgJAcL5EyhsFHzeE1mieNJ7g-ZG_l16sTkCJFmJeaOU/edit?usp=sharing

**Comment by daneshk** [comment]
@jclark could you please share your thoughts on the approach

**Comment by jclark** [comment]
This doesn’t look good to me.  I think we will need a call.

**Comment by daneshk** [comment]
We had a discussion and came to a conclusion and implemented it in alpha 4. Hense closing. @lahirusamith please link the PR

**Comment by lahirusamith** [comment]
related PR: https://github.com/ballerina-platform/module-ballerina-sql/pull/161
