### ISSUE TITLE
Add examples on working with attachments, options etc in `ballerina/email` package

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-standard-library#1169]
**Description:**
Better if some examples can be added on working with attachments, options, etc in the `ballerina/email` package since the BBE content only covers a few basic concepts.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Maninda** [comment]
As API docs cover all the remaining features like in other modules, we can consider adding more content to BBEs as required in the future.
