### ISSUE TITLE
Open record type does not append additional fields in the resultStream

### ISSUE THREAD

**Issue by suhand** [ballerina-platform/ballerina-standard-library#1174]
**Description:**
Open record type does not allow additional fields in the resultStream to be added to the record.
https://ballerina.io/learn/by-example/records

**Steps to reproduce:**
1. Create a type record
```
type engagementRecord record {
    string id;
    string customer_name;
};
```
2. Create a MySQL DB query with an additional parameter
```
string GET_10_ENGAGEMENTS = string `
    SELECT id, customer_name, username
    FROM engagement 
    LIMIT 10
`;
```
3. Execute the SELECT query by setting the resultStream to type record.
```
    stream<record{}, error> resultStream = mysqlClient->query(GET_10_ENGAGEMENTS, engagementRecord);

    error? e = resultStream.forEach(function(record { } result) {
            io:println("Username: ", result["username"]);
            io:println("Customer Name: ", result["customer_name"]);
        });

    if (e is error) {
        io:println("ForEach operation on the stream failed!", e);
    }
```
_ERROR_:
`ForEach operation on the stream failed!error ApplicationError ("No mapping field found for SQL table column 'username' in the record type 'engagementRecord'")`

**Affected Versions:**
Version/SLAlpha3

**OS, DB, other environment details and versions:**
OS: macOS Big Sur V11.1 [latest]
MySQL

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
Type/Bug
Version/SLAlpha3

**Suggested Assignees (optional):**
daneshk

**Additional Information/Workaround**
Following is working for now with the open record type concept.
`engagementRecord cloneWithType = checkpanic result.cloneWithType(engagementRecord);
`
For now we can access cloneWithType["username"] until the issue is fixed.

**Comment by shayanmalinda** [comment]
Have the same issue with 1.2.10 also

**Comment by daneshk** [comment]
We are not going to support this in Swan Lake release. We will check after and update the issue

**Comment by daneshk** [comment]
This is fixed and merged to the master branch. Hence closing the issue
