### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#1184]
**Description:**
Couldn't get any error, when adding any string value instead of a time.

**Steps to reproduce:**
Run the following code. [[Test case](https://github.com/ballerina-platform/module-ballerinax-mysql/pull/102/files#diff-e36362f2fd4a40f11c77d31219f82cdd32c13f1edf355c54467784c89eb1b334R562)]
```ballerina
    sql:TimeValue typeVal = new ("xx:xx:xx");
    sql:ParameterizedQuery sqlQuery = `SELECT * from DateTimeTypes WHERE time_type = ${typeVal}`;
    record{}|error? returnVal = trap queryMysqlClient(sqlQuery);
```

**Comment by daneshk** [comment]
This test failure is fixed in PR ballerina-platform/module-ballerinax-mysql#104. Hence closing this issue
