### ISSUE TITLE
Add changelog to each standard library repository 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1198]
This issue is created to track the progress of below tasks,

* Add change log as [here](https://keepachangelog.com/en/1.0.0/). Start with alpha4 release.
* Add the template as [here](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/.github/pull_request_template.md)
* Add the publish change as [here](https://github.com/ballerina-platform/module-ballerina-sql/pull/173/files)

**Modules**

- [x] io 
- [x] url 
- [x] java.arrays
- [x] random
- [x] regex
- [x] task
- [x] time
- [x] xmldata
- [x] crypto
- [x] os 
- [x] xslt
- [x] uuid
- [x] log
- [x] cache 
- [x] file
- [x] ftp
- [x] mime
- [x] nats
- [x] stan 
- [x] tcp
- [x] udp 
- [x] auth
- [x] email 
- [x] http
- [x] jwt 
- [x] oauth2 
- [x] graphql 
- [x] grpc 
- [x] websocket 
- [x] websub 
- [x] websubhub
- [x] kafka
- [x] rabbitmq
- [ ] transaction 
- [x] sql
- [x] java.jdbc
- [x] mysql

**Comment by daneshk** [comment]
Change logs are added to all standard library modules. Hense closing the issue
