### ISSUE TITLE
Standard library release actions fail due to uncommitted changes

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1228]
**Description:**
It seems most of the stdlib release actions are failed in the latest release due to the following Gradle failure.
```
> Task :module-ballerina-io:preTagCommit FAILED
Running [git, push, --porcelain, origin, release-0.6.0-alpha7] produced an error: [error: failed to push some refs to 'https://github.com/ballerina-platform/module-ballerina-io'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.]
Release process failed, reverting back any changes made by Release Plugin.


> Task :release FAILED
FAILURE: Build failed with an exception.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
* What went wrong:
Use '--warning-mode all' to show the individual deprecation warnings.
Execution failed for task ':module-ballerina-io:preTagCommit'.
See https://docs.gradle.org/6.4/userguide/command_line_interface.html#sec:command_line_warnings
> Failed to push to remote - [To https://github.com/ballerina-platform/module-ballerina-io
1 actionable task: 1 executed
  !	refs/heads/release-0.6.0-alpha7:refs/heads/release-0.6.0-alpha7	[rejected] (non-fast-forward)
  Done
  ][error: failed to push some refs to 'https://github.com/ballerina-platform/module-ballerina-io'
  hint: Updates were rejected because the tip of your current branch is behind
  hint: its remote counterpart. Integrate the remote changes (e.g.
  hint: 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  ]
```
Some of the stdlibs are not failed because those stdlibs set the configuration `failOnPublishNeeded = false` [1, 2]. Since the stdlib release action commits changes automatically, we shouldn't need this. And that is why previous releases have passed without this error.

Most probably, a recent change might be the cause and we need to fix this in stdlibs.

[1] https://github.com/ballerina-platform/module-ballerina-grpc/blob/master/build.gradle#L182
[2] https://github.com/ballerina-platform/module-ballerina-grpc/runs/2275322110?check_suite_focus=true

**Failure builds**
- https://github.com/ballerina-platform/module-ballerina-io/runs/2275321634?check_suite_focus=true
- https://github.com/ballerina-platform/module-ballerina-url/runs/2275321669?check_suite_focus=true

**Comment by niveathika** [comment]
@BuddhiWathsala Check the action history, these failed release builds are due to retriggering the release with same version.
