### ISSUE TITLE
Keep Ballerina.toml file up-to-date during the standard library publish-to-central task

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1232]
**Description:**

During the SwanLake alpha4 release, a set of stdlibs failed to publish to central. The reason for this issue is, the `Ballerina.toml` file contained an incorrect version. Since the `Ballerina.toml` file contained an incorrect version, the `bal push` did not work as expected. Actually, in here, the `Ballerina.toml` contained the templated variable.

Before, the `ballerinaPublish`, we run the `ballerinaBuild` task that finalized by the `revertTomlFile` task. Even though the `ballerinaPublish` depends on with `updateTomlFile` task, it seems the TOML file didn't update properly during the release.

Therefore, we need to rearrange the task order to solve this issue.

**Steps to Reproduce**
Build this branch - https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays/tree/central-v0.10.0-alpha7-issue

```sh
./gradlew ballerinaPublish
```

**Comment by hemikak** [comment]
Would'nt it be better to move the source code to a different file path and update the versions and then publish ?. Then theres no hassle in reverting the changes back. Suggested by @azinneera .

**Comment by BuddhiWathsala** [comment]
@hemikak yes, that would be a possible solution.

**Comment by BuddhiWathsala** [comment]
Fixed from https://github.com/ballerina-platform/ballerina-standard-library/issues/1247
