### ISSUE TITLE
Improve Ballerina SerDes support

### ISSUE THREAD

**Issue by TharindaDilshan** [ballerina-platform/ballerina-standard-library#1234]
**Description:**
As of now, the SerDes package supports serialization/deserialization of Ballerina anydata except for table type, and enum. The supported types can be expressed as a subset of anydata,

`type serdesAnydata ()|boolean|int|float|decimal|string|map<serdesAnydata>|serdesAnydata[];`

The functionality of the SerDes package needs to be improved to support the following,

1. table type
2. enum 
3. json

**Comment by MohamedSabthar** [comment]
We are closing this issue because the serdes module has been deprecated.
