### ISSUE TITLE
Improve array type manipulation in data clients

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-standard-library#124]
**Description:**
Some database support only a given type in an array, but some allow mixed types. 
In current source, it is assumed that all elements are of the same type and in some places type is determined by checking the type of the first element of the array which is error-prone in case the first element is null. This needs to be revisited and fixed.

**Comment by niveathika** [comment]
@kalaiyarasiganeshalingam Isn't this handled in the latest implementation?

**Comment by kalaiyarasiganeshalingam** [comment]
> @kalaiyarasiganeshalingam Isn't this handled in the latest implementation?

All the array types in our modules are allowed mixed types. We have the test cases in SQL and PostgreSQL with the first element as null but It seems we haven't tested MySQL, JDBC, OracleDB, and MySQL modules. So we need to test those modules.
SQL:
https://github.com/ballerina-platform/module-ballerina-sql/blob/master/ballerina/tests/execute-params-query-test.bal#L463
Postgresql:
https://github.com/ballerina-platform/module-ballerinax-postgresql/blob/main/ballerina/tests/execute-params-test.bal#L1395
