### ISSUE TITLE
Change the time format in log messages

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#1246]
**Description:**
Currently, the time format in log messages is in ISO 8601 format which is the current local time.
```
time = 2021-04-15 11:49:06.880 level = INFO  module = "" message = "info message"
```

The `utcToString` function in `time` module converts a given `time:Utc` time to an RFC 3339 timestamp(e.g. `2007-12-03T10:15:30.00Z`). The following is the corresponding log message if this format is used. 

```
time = 2021-04-15T16:36:50+05:30 level = INFO  module = "" message = "info message"
```

However, please note that this is the UTC time and not the current local time. Should we change the time format in log messages to RFC 3339 timestamp using `time:utcToString(time:utcNow())`.

**Comment by daneshk** [comment]
@jclark could you please share your thoughts on the time format and the time(UTC or Local) we need to use for the log message output.

**Comment by jclark** [comment]
I think you should change to use RFC3339 format.
