### ISSUE TITLE
Reorganise the standard library test, build, and publish order

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1247]
**Description:**
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1232

**Reference**
https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays/pull/86

**Packages**

- [x] io 
- [x] url 
- [x] java.arrays
- [x] random
- [x] regex
- [x] task
- [x] time
- [x] xmldata
- [x] crypto
- [x] os 
- [x] xslt
- [x] uuid
- [x] log
- [x] cache 
- [x] file
- [x] ftp
- [x] mime
- [x] nats
- [x] stan 
- [x] tcp
- [x] udp 
- [x] auth
- [x] email 
- [ ] http
- [x] jwt 
- [x] oauth2 
- [x] graphql 
- [x] grpc 
- [x] websocket 
- [x] websub 
- [x] websubhub
- [x] kafka
- [x] rabbitmq
- [ ] transaction 
- [x] sql
- [x] java.jdbc
- [x] mysql

**Comment by niveathika** [comment]
@BuddhiWathsala Shall we close this? This work is completed
