### ISSUE TITLE
Add Logic and Testcases for Oracle Specific Data Type Select Operation

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-standard-library#1256]
**Description:**
`module-ballerinax-oracledb` currently does not support selecting of oracledb specific data types; namely `INTERVAL YEAR TO MONTH`, `INTERVAL DAY TO SECOND`, `OBJECT TYPES`, `VARRAY` etc.

**Describe your problem(s)**
The selection of these types do not function as expected.

**Describe your solution(s)**
Implement logic for select operation of these types and add test coverage for them.

**Suggested Labels (optional):**
`Type/Improvement`, 'module/oracledb'

**Comment by daneshk** [comment]
@lahirusamith check and close this issue. If we already done

**Comment by lahirusamith** [comment]
Closing the issue as the select is working now for oracledb specific `INTERVAL YEAR TO MONTH`, `INTERVAL DAY TO SECOND`, `OBJECT TYPES`, `VARRAY` data types.
