### ISSUE TITLE
Use Docker Image with Oracle DB Express Edition for Tests in Module OracleDB

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-standard-library#1260]
**Description:**
`module-ballerinax-oracledb` is currently using a docker image with oracle database enteprise edition in it. The docker image is 3.44GB in size which needs to be downloaded for running test cases locally. It also takes a considerable time (3-5 minutes) to build the image and run the container every time the tests need to be run. The docker image does not facilitate running scripts at the time of initializing the database which is helpful to run DDL queries needed for setting up tables needed for testing.

**Describe your task(s)**
Replace the current docker image with a oracle express edition docker image. This will be smaller in size and possibly result in smaller startup times. It will also provide functionality to run scripts on setting up the DB.

https://stackoverflow.com/questions/54940302/is-there-official-docker-image-of-oracle-xe-database

https://blogs.oracle.com/oraclemagazine/deliver-oracle-database-18c-express-edition-in-containers

**Suggested Labels (optional):**
`Type/Task`, `module/oracledb`

**Comment by lahirusamith** [comment]
This issue can be closed since another issue created to address the same problem. Similar issue:  https://github.com/ballerina-platform/ballerina-standard-library/issues/1641
