### ISSUE TITLE
Error when using union types in GraphQL

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1307]
Consider the below service resource,

```ballerina
type SearchResult Lift|Trail;

resource function get search (string status) returns SearchResult[] {
        string status2 = status;

        TTrail[] trails = from var trail in trailTabel where trail.status == status2 select trail;
        SearchResult[] searchResult = trails.map(function (TTrail trail) returns Trail => new Trail(trail));

        TLift[] lifts = from var lift in liftTable where lift.status == status2 select lift;
        lifts.forEach(function (TLift lift) returns () => searchResult.push(new Lift(lift)));

        return searchResult;
 }
```

I get the the below error when compiling the above,

`error: Unsupported type for schema field: Lift`

I have attached the complete program as well.

[service.txt](https://github.com/ballerina-platform/ballerina-standard-library/files/6383776/service.txt)

**Comment by ThisaruGuruge** [comment]
By the first look, seems like this is related to #1250

@DimuthuMadushan shall we add this as a test and check?

**Comment by ThisaruGuruge** [comment]
> By the first look, seems like this is related to #1250
> 
> @DimuthuMadushan shall we add this as a test and check?

Seems like this isn't an issue with the returning values, but an issue in the schema generation. Will have a look.
