### ISSUE TITLE
Incorrect consistency in module descriptions

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#1319]
**Description:**
$subject in [1] 
[1] https://docs.central.ballerina.io/

<img width="839" alt="image" src="https://user-images.githubusercontent.com/16300038/117004105-535c5800-ad03-11eb-9e71-aa64437b812d.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shehan360** [comment]
I think this issue is related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/1323

**Comment by daneshk** [comment]
We fixed the inconsistency in the module description in slbeta1. hence closing the issue
