### ISSUE TITLE
Deprecate math module APIs that are already supported in langl.float module

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#132]
**Description:**
Some math module APIs are already supported in lang.float module. Therefore math module APIs need to be depricated.

**Steps to reproduce:**
Run the following sample.
```
import ballerina/lang.'float as floats;
import ballerina/io;
import ballerina/math;

public function main() {
    float x = floats:sqrt(123.456);
    float y = math:sqrt(123.456);

    io:println(x);
    io:println(y);
}
```
x and y output are the same.

**Affected Versions:**
slp2

**Comment by daneshk** [comment]
We already removed `Math` module from the ballerina SL release. Hence closing
