### ISSUE TITLE
Refactor content of Package.md and Module.md

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-standard-library#1323]
**Description:**
As per the discussion on 29th March 2021 [1], it was decided to use the Package.md file to store the content shown in Central, and the Module.md file to store content shown in API Docs.

As an example, https://swanlake.central.ballerina.io/ballerina/time will show the content from Package.md, https://docs.central.ballerina.io/ballerina/time/latest should ideally only display content of Module.md.

Currently for API Docs we are appending the Package.md on top of the Module.md, because most modules dont have a Module.md. We hope to remove this by Beta Release.

[1] - https://docs.google.com/document/d/1htfDD8eXpB5dfZDQ67AWH8H6mJRyknuZUCU_0xYZcV8/edit#heading=h.3n85qn2qphsn
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
We completed this task in slbeta1. @shehan360 can we close this issue now?

**Comment by chamil321** [comment]
> We completed this task in slbeta1. @shehan360 can we close this issue now?

Closing as per the comment
