### ISSUE TITLE
Release stable versions of the standard library modules with Swan Lake Beta1

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-standard-library#1334]
Can we do the $subject? At least for the standard library modules with stable APIs.  I don't see a reason to keep releasing pre-release versions. This will solve the following issue as well. 

A pre-release version is not compatible with another pre-release version. It is very common to get two pre-release versions of the same module in the dependency graph of a Ballerina application.  In fact, this has happened many times with Ballerina Swan Lake alpha releases. Here is an example. 

Here my_app depends on `ballerina/http` and `ballerinas/github` modules. The `github` module was released with Swan Lake Alpha4 and the `http` module is released with Swan Lake Alpha5. The `github` module is yet to be released with Swan Lake Alpha5. Therefore the `github` module uses an older `ballerina/io` version. 
```
my_app --> ballerina/http --> ballerina/io (2.0.0-alpha.6)
my_app --> ballerinax/github --> ballerina/io (2.0.0-alpha.5)
```

Compiler throws an incompatible versions error because `2.0.0-alpha.5` is compatible with `2.0.0-alpha.6`.

**Comment by sameerajayasoma** [comment]
Here is a related conversation in slack. https://ballerina-platform.slack.com/archives/C47EAELR1/p1620769417263400

**Comment by sameerajayasoma** [comment]
We've decided to release stable versions of standard library packages with the Ballerina Beta3 release.

**Comment by sameerajayasoma** [comment]
Here is how I would decide on the stable versions for each standard library package. We need to look at the standard library versions in Ballerina 1.2.x release. 

- If the package version in 1.2.x is an initial version (major version is zero), then bump it up the 1.0.0. 
- If the package version is a stable version, then bump it up to the next major version. 

Examples:
- `ballerina/io` version in 1.2.x is `0.5.0`. Io version in Swan Lake Beta3 should be `1.0.0`
- `ballerina/http` version in 1.2.x is `1.0.0`. Http version in Swan Lake Beta3 should be `2.0.0`

If we agree, can we list out all the versions in the standard library?

**Comment by shafreenAnfar** [comment]
Yeah, let's go ahead with this approach. 

We will list down the versions.

**Comment by daneshk** [comment]
I list down the 1.2.x version, current version, and suggested version. 
@sameerajayasoma @shafreenAnfar Can you check and give your thoughts


| Module | 1.2.x version | current version | New version |
| ------- | ------------ | ------------ | ------------- |
| io | 0.5.0 | 0.6.0 | 1.0.0 |
| jballerina/java.arrays | 0.0.0 | 0.10.0 | 1.0.0 |
| random | N/A | 0.10.0 | 1.0.0 |
| regex | N/A | 0.7.0 | 1.0.0 |
| time | 1.0.0 | 2.0.0 | 2.0.0 |
| url | 1.0.0(encoding) | 1.1.0 | 2.0.0 |
| xmldata | 0.5.0(xmlutils)| 1.1.0 | 2.0.0 |
| crypto | 1.0.0 | 1.1.0 | 2.0.0 |
| log | 1.0.0 | 1.1.0 | 2.0.0 |
| os | 0.6.0 | 0.8.0 | 1.0.0 |
| task | 1.1.0 | 2.0.0 | 2.0.0 |
| xslt | 1.0.0 | 1.1.0 | 2.0.0 |
| cache | 2.0.0 | 2.1.0 | 3.0.0 |
| file | 0.5.0 | 0.7.0 | 1.0.0 |
| ftp | 1.0.5 | 1.1.0 | 2.0.0 |
| mime | 1.0.0 | 1.1.0 | 2.0.0 |
| nats | 1.0.0 | 1.1.0 | 2.0.0 |
| stan | 1.0.0(nats) | 1.1.0 | 2.0.0 |
| tcp | 0.6.0(socket) | 0.8.0 | 1.0.0 |
| udp | 0.6.0(socket) | 0.9.0 | 1.0.0 |
| uuid | N/A | 0.10.0 | 1.0.0 |
| auth | 1.0.0 | 1.1.0 | 2.0.0 |
| email | 0.6.0 | 1.1.0 | 2.0.0 |
| jwt | 1.0.0 | 1.1.0 | 2.0.0 |
| oauth2 | 1.0.0 | 1.1.0 | 2.0.0 |
| http | 1.0.0 | 1.1.0 | 2.0.0 |
| graphql | N/A | 0.2.0 | 1.0.0 |
| grpc | 0.7.0 | 0.8.0 | 1.0.0 |
| websocket | 1.0.0(http) | 1.2.0 | 2.0.0 |
| websub | 1.0.0 | 1.2.0 | 2.0.0 |
| websubhub | N/A | 0.2.0 | 1.0.0 |
| kafka | 2.0.0 | 2.1.0 | 3.0.0 |
| rabbitmq | 0.0.0 | 1.1.0 | 2.0.0 |
| sql | 0.0.0 | 0.6.0 | 1.0.0 |
| java.jdbc | 0.0.0 | 0.6.0 | 1.0.0 |
| mysql | 0.0.0 | 0.7.0 | 1.0.0 |
| postgresql | N/A | 0.7.0 | 1.0.0 |
| mssql | N/A | no yet release | 1.0.0 |
| oracle | N/A | no yet release | 1.0.0 |

**Comment by sameerajayasoma** [comment]
LGTM.

**Comment by ThisaruGuruge** [comment]
Let's update this list after updating the versions.

- [ ] io
- [ ] java.arrays
- [ ] random
- [ ] regex
- [ ] time
- [ ] url
- [ ] xmldata
- [ ] crypto
- [ ] log
- [ ] os
- [ ] task
- [ ] xslt
- [ ] cache
- [ ] file
- [ ] ftp
- [ ] mime
- [ ] nats
- [ ] stan
- [ ] tcp
- [ ] udp
- [ ] uuid
- [ ] auth
- [ ] email
- [ ] jwt
- [ ] oauth2
- [ ] http
- [ ] graphql
- [ ] grpc
- [ ] websocket
- [ ] websub
- [ ] websubhub
- [ ] kafka
- [ ] rabbitmq
- [ ] sql
- [ ] java.jdbc
- [ ] mysql 
- [ ] postgresql
- [ ] mssql

**Comment by ThisaruGuruge** [comment]
Closing since all the modules are now shifted to stable versions, as mentioend.
