### ISSUE TITLE
Correlate logs with traces

### ISSUE THREAD

**Issue by tharinduwijewardane** [ballerina-platform/ballerina-standard-library#1342]
**Description:**
We need to automatically add traceId and spanId into logs when tracing is enabled and if the current request is sampled.

We have already migrated tracing to Open Telemetry standard so that we can obtain traceId and spanId from observability runtime.

**Comment by MadhukaHarith92** [comment]
Currently blocked since https://github.com/ballerina-platform/ballerina-lang/blob/master/observelib/observe/src/main/ballerina/natives.bal#L78 needs to be `isolated`.

**Comment by tharinduwijewardane** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/31034

**Comment by tharinduwijewardane** [comment]
> Currently blocked since https://github.com/ballerina-platform/ballerina-lang/blob/master/observelib/observe/src/main/ballerina/natives.bal#L78 needs to be `isolated`. @tharinduwijewardane

https://github.com/ballerina-platform/ballerina-lang/pull/31034

**Comment by MadhukaHarith92** [comment]
Blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/31089

**Comment by tharinduwijewardane** [comment]
> Blocked due to [ballerina-platform/ballerina-lang#31089](https://github.com/ballerina-platform/ballerina-lang/issues/31089)

Fix merged https://github.com/ballerina-platform/ballerina-lang/pull/31104

**Comment by MadhukaHarith92** [comment]
Blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/31130

**Comment by tharinduwijewardane** [comment]
> Blocked due to [ballerina-platform/ballerina-lang#31130](https://github.com/ballerina-platform/ballerina-lang/issues/31130)

Fix https://github.com/ballerina-platform/ballerina-lang/pull/31129

**Comment by MadhukaHarith92** [comment]
Reopening since the feature was reverted from SL Beta2. Will be shipped in SL Beta 3.
