### ISSUE TITLE
Support for GraphQL Interfaces 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1364]
**Description:**
More information can be found [here](https://spec.graphql.org/June2018/#sec-Interfaces).

**Comment by ThisaruGuruge** [comment]
Interface support can be provided using three different ways:

1. Record types - Tracked via #1625 
2. Service classes - Tracked via #1624 
3. Service types - TBD

**Comment by ThisaruGuruge** [comment]
This is now related to #2047.

**Comment by ThisaruGuruge** [comment]
This depends on #2047. Since we had a blocker for this, the task completion time will be extended. We are going to finish this by the [Sprint 53](https://github.com/ballerina-platform/ballerina-standard-library/projects/109#card-80445056)
