### ISSUE TITLE
How to Turn Off Logs From a Particular Module

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#1384]
**Description:**
Is there a way to turn off logs from a given module?

I looked in the API docs, but couldn't find any documentation on the $Subject.

Example:

I am writing a module `A`, which uses module `B`. I want to turn off all the logs from module `B` when I run module `A`. How can I do this?

**Comment by daneshk** [comment]
Rather than having another logging level, we need to provide config to enable/disable logs in certain modules

**Comment by MadhukaHarith92** [comment]
We decided to have a configuration called `enabled` which can be used to enable/disable logs globally and module-wise.
The following turns OFF logs globally.
```
[ballerina.log]
enabled = false
```

The following turns OFF logs for module `foo`
```
[[ballerina.log.modules]]
name = "myorg/foo"
enabled = false
```

**Comment by ThisaruGuruge** [comment]
> Rather than having another logging level, we need to provide config to enable/disable logs in certain modules

Why can't we have a log level for this? I think most of the logging libraries handle this use case by introducing the `OFF` level for the logs. Having a different approach to turn them off seems a bit unintuitive for me.

**Comment by daneshk** [comment]
> > Rather than having another logging level, we need to provide config to enable/disable logs in certain modules
> 
> Why can't we have a log level for this? I think most of the logging libraries handle this use case by introducing the `OFF` level for the logs. Having a different approach to turn them off seems a bit unintuitive for me.

I have different thoughts on this. Log level is a property of log messages/events generated at runtime and it is a piece of information telling how important a log message is. Introducing another level for the purpose of disabling logs and it is not used for log messages is not correct. We are kind of mixing the objectives.

Golang uses [`SetOutput`](https://golang.org/pkg/log/#SetOutput) function to set log writer which can also uses to disable logging like below,

 ```log.SetOutput(ioutil.Discard)```

@sameerajayasoma WDYT?

**Comment by ThisaruGuruge** [comment]
> I have different thoughts on this. Log level is a property of log messages/events generated at runtime and it is a piece of information telling how important a log message is. Introducing another level for the purpose of disabling logs and it is not used for log messages is not correct. We are kind of mixing the objectives.
> 
> Golang uses [`SetOutput`](https://golang.org/pkg/log/#SetOutput) function to set log writer which can also uses to disable logging like below,
> 
> `log.SetOutput(ioutil.Discard)`
> 
> @sameerajayasoma WDYT?

This makes sense. +1 for the suggested method.

**Comment by daneshk** [comment]
As per the recent discussion, we came up with another approach to handle the requirement along with the flexibility to select where the logs write to,

There is another requirement to give an option for the developer to select where to print the logs, a detailed discussion about this requirement can be found in issue #135

Suggested Approach:

* Provide a configuration to set output as follows.
```
[ballerina.log]
output = stdout|stderr|levelbased|discard
```

* stdout - Write logs to the stdout stream.
* stderr - Write logs to the stderr stream.
* levelbased - Write ERROR logs to the stderr stream while writing INFO, WARN, and DEBUG logs to the stdout stream.
* discard - Turn off logs.

WDYT?

**Comment by sameerajayasoma** [comment]
`levelBased` doesn't sound right to me. What is the default?

**Comment by daneshk** [comment]
> `levelBased` doesn't sound right to me. What is the default?

The default is writing logs to the stderr stream. We now write all logs to stderr.

`levelBased` option is come up to satisfy the requirement discussed in #135. The requirement is to select where to write based on the log level. only `Error` logs should write to `stderr` others write to `stdout`.

**Comment by daneshk** [comment]
I went through some of the languages further, all only support switching between `stdout` and `stderr` and support writing custom impl handle/hooks for those use cases, e.g:

in Rust language,
https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/log.html#log-to-stdout-instead-of-stderr

in Golang,
https://github.com/sirupsen/logrus#hooks

in Python,
https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler

We can leave it for now, support it through custom impl in the future. and support only switching `stderr`, `stdout` and `discard`

WDYT?

**Comment by daneshk** [comment]
But still there is a problem in the approach, at module level, user don't want to where to write logs. only `discard` log is needed. @MadhukaHarith92 wdyt?

**Comment by MadhukaHarith92** [comment]
> But still there is a problem in the approach, at module level, user don't want to where to write logs. only `discard` log is needed. @MadhukaHarith92 wdyt?

Yes. Users need not differentiate where the log is written based on the module. For instance, `ballerina/http` module logs and `ballerina/grpc` logs should be written to either `stderr` or `stdout` but not both. However, IMO it won't be an issue since the global level and module level configurations are separate.

```
[ballerina.log]
output = stdout|stderr|discard
```

```
[[ballerina.log.modules]]
name = "ballerina/http"
output = discard
```

**Comment by sameerajayasoma** [comment]
We can approach this from another angle. 

We use the log API to publish logs. When we publish logs, we don't care about the particular log format or the output. All we care about is the log message as in the key/values pairs and the particular log level (severity). 

When we configure the `ballerina/log` module via configurable variables, we control the log output. We can change the log format and the output stream. What do we mean by setting the `level` configurable variables? Setting `level=" INFO"` means that only logs with "INFO" and above can be sent to the output. I've seen some logging frameworks in Go that use the level to turn off log messages. e.g., `allowed-level=NONE`. Just my 2 cents.

**Comment by daneshk** [comment]
Analyzing the facts, the best way is to have another config level to turn off the logs in a certain module. The next question is do we really need to turn off logs completely, In the production environment, it is recommended to keep at least up to error logs, So the amount of logs printed is low and also we get abnormalities in the modules through error logs.

Even for the dev and staging environment, it is good to enable at least up to error logs for any debugging purposes.

**Comment by MadhukaHarith92** [comment]
Closing the issue as per the conclusion to not turn off logs completely (Need to keep at least up to `ERROR` level). Therefore if a user wants to turn off `INFO`, `WARN`, and `DEBUG` logs for a certain module, he can achieve that by setting that module's log level to `ERROR`.
