### ISSUE TITLE
Remove the Countdown latch in Websocket implementation

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1385]
**Description:**
Pointed code needs to be written in reactive way. Otherwise, this code could struggle running in constrained environments. 

https://github.com/ballerina-platform/module-ballerina-websocket/blob/main/websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketUtil.java#L271

**Comment by Bhashinee** [comment]
Fixed with the above PR.
