### ISSUE TITLE
gRPC CLI JARs are not packed into the distribution

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1387]
**Description:**
With the recent Gradle config changes, it seems the gRPC CLI JARs are not properly packed to the ZIP artefact. That leads to an error called gRPC CLI not found in the final distribution.

**Comment by hevayo** [comment]
We should add test to distribution repo to check if gRPC cli is packed

**Comment by BuddhiWathsala** [comment]
We added tests, but currently, those are being disabled. That was the reason for the failure. We'll enable those after this fix.
