### ISSUE TITLE
Do lines returned by io:fileReadLines include the line terminator?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-standard-library#1393]
io:fileReadLines needs to document whether the line-terminator is included in each of the lines in the list it returns. I tested it and it appears that it is not included at the moment.  This has the consequence that for the last line you lose the information about whether it has terminating newline or not. fgets in C includes the newline. I suggest seeing what other languages do before deciding the right behaviour.

**Comment by BuddhiWathsala** [comment]
Here is how other programming languages handle the terminating carriage.

### Java
Documentations: 
- https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#readAllLines
- https://docs.oracle.com/javase/8/docs/api/java/io/BufferedReader.html

Java `BufferReader` and `Files.readAllLines` do not return the terminating carriage. 

### Python 
Documentation: https://python-reference.readthedocs.io/en/latest/docs/file/readlines.html

Python behaviour is similar to Java, it does not return the terminating carriage.

### C#

Documentation: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalllines?view=net-5.0

It seems C# also does not return the terminating carriage.

### Go
Documentation: https://golang.org/pkg/bufio/#Reader.ReadLine

Currently, Go does not have a direct API to read all lines[1]. 

[1] https://stackoverflow.com/questions/5884154/read-text-file-into-string-array-and-write

**Comment by jclark** [comment]
I think not including the line terminating characters (whether CR, LF or CRLF) is the right thing to do, given that `io:println` adds them.
