### ISSUE TITLE
Need variant of io:println that prints to stderr

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-standard-library#1394]
This was closed in #558, but it is absolutely essential functionality for writing command-line apps.

A well-behaved command-line app that writes its normal output to stdout (like mostUnix utilities) needs to write error messages intended for the user to stderr, in order to ensure that normal output can be redirected/piped separately from the error messages.

Logging is not a substitute: it does not output messages in a format suitable for display to the user.

**Comment by BuddhiWathsala** [comment]
How about adding two new APIs as mentioned here https://github.com/ballerina-platform/ballerina-standard-library/issues/558#issuecomment-730218362?.

```ballerina
public function eprint((any|error)... values) {};
public function eprintln((any|error)... values) {};
```

**Comment by jclark** [comment]
The names `eprint` and `eprintln` don't feel harmonious with normal Ballerina naming conventions (`println` doesn't either, but we are stuck with that). Compare with the `log` module that uses e.g. `printError`.

Would this work?

```
const stdout = 1;
const stderr = 2;
type PrintOptions record {|
   (stdout|stderr) file = stdout;
|};
public println(*PrintOptions, any|error... values) {}

// Use like:
println("foo", "bar", file=io:stderr);
```

This is similar to what Python does: https://docs.python.org/3.0/whatsnew/3.0.html

**Comment by jclark** [comment]
I also don't mind:

```
fprintln(io:stderr, "foo", "bar");
```

The C precedent is enough to make `fprint` OK for me: `eprint` just feels too weird.

`sprint` would also be useful, and would return a string.
