### ISSUE TITLE
Logging API insufficient for command-line app

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-standard-library#1395]
The logging API is completely unusable for a command-line app at the moment. The app needs to be able to control where the log is written to. Imagine trying to write the `bal` command in ballerina: it would not be acceptable for the bal command to spew all its logging information onto stderr by default.

**Comment by MadhukaHarith92** [comment]
@jclark Is it sufficient, if we provide the config to switch between `stderr` and `stdout`. Something like,
```
[ballerina.log]
output = stdout
```
We also have two other requirements which we are thinking about addressing along with this issue.

1. Disabling logs for a particular module. This is further discussed in [[1]](https://github.com/ballerina-platform/ballerina-standard-library/issues/1384). 

2. Writing the log messages to `stdout` or `stderr` based on the log level. Write Error logs to `stderr` and other levels(`INFO`, `WARN`, `DEBUG`) logs to `stdout`. This is further discussed in [[2]](https://github.com/ballerina-platform/ballerina-standard-library/issues/135).

To accommodate all these requirements, we thought of providing a configuration as follows.

```
[ballerina.log]
output = stdout|stderr|levelbased|discard
```

- stdout - Write logs to the `stdout` stream.
- stderr - Write logs to the `stderr` stream.
- levelbased - Write `ERROR` logs to the `stderr` stream while writing `INFO`, `WARN`, and `DEBUG` logs to the `stdout` stream.
- discard - Turn off logs.

[1] https://github.com/ballerina-platform/ballerina-standard-library/issues/1384
[2] https://github.com/ballerina-platform/ballerina-standard-library/issues/135

**Comment by jclark** [comment]
@MadhukaHarith92 I don't see how that addresses the point I made.

**Comment by MadhukaHarith92** [comment]
@jclark since the above-mentioned solution does not fulfill your requirement, would it be sufficient if we provided a set of APIs to let the command-line app control where the log is written to during the runtime?

**Comment by jclark** [comment]
Yes, that is what is needed. Imagine writing the ‘bal’ command in Ballerina.

**Comment by MadhukaHarith92** [comment]
@jclark we thought of providing an API as follows.
```
public isolated function setOutput(Writer writer)
```
`Writer` is an object which encapsulates a method called `printLog` which handles where the log is written to.
```
public isolated type Writer object {
    public isolated function printLog(string logMessage);
}
```

The cli-application can then implement this object and write the log to any desired location. For eg:
```
import ballerina/io;
import ballerina/log;

public isolated class BallerinaCliWriter() {
    *log:Writer;
    string logFilePath;

    public isolated function init(string filePath) {
        logFilePath = filePath;
    }

    public isolated function printLog(string logMessage) {
         io:fileWriteString(logFilePath, logMessage);
    }
}

public isolated function main() {
    log:setOutput(new log:BallerinaCliWriter("./files/logs.txt"));

    log:printInfo("initializing Ballerina CLI");
}
```

Furthermore, we thought of providing a set of pre-defined Writers. For instance `StdoutWriter` will print the log to the `stdout` stream as follows.
```
public isolated class StdoutWriter() {
    *Writer;

    public isolated function printLog(string logMessage) {
         io:println(logMessage);
    }
}
```

**Comment by jclark** [comment]
That's too Java-ish and too complicated. We're trying to provide a non-Java like experience in the standard library, where simple things take a single line of code.  Look at what the `io` module has done.

I think the main user-facing API should be just me a function to set the name of the file to write to (perhaps with an option to choose whether to append or truncate an existing file).

**Comment by MadhukaHarith92** [comment]
@jclark we thought of providing an API as follows.
```
public isolated function fileWriteOutput(string path, FileWriteOption option = OVERWRITE)
```

With the options to overwrite and append.
```
public enum FileWriteOption {
    OVERWRITE,
    APPEND
}
```

One concern we have is once this function is called, should we write all the subsequent logs of the entire application to the file or should we only write the logs of the module from which the `fileWriteOutput()` function was called.

For instance, suppose a project with the following structure.

```
log-project
├── Ballerina.toml
├── Config.toml
├── main.bal
└── modules
    ├── bar
    │   └── bar.bal
    └── foo
        └── foo.bal
```

main function:
```
import myorg/myproject.foo;
import myorg/myproject.bar;

public function main() {
    foo:hello();
    bar:hello();
}
```

If `log:fileWriteOutput("./foo.txt");` is called from the `foo` module, should the logs of `bar` module also be written to `foo.txt` or should the logs of only the `foo` module be written to `foo.txt`

**Comment by MadhukaHarith92** [comment]
The problem with an API is that the application will lose its control over the location of log output to an imported module. For instance, suppose `foo` module has called `log:fileWriteOutput("./foo.log");` from its `hello()` function. Once `foo:hello()` is called from the user's application, all the subsequent logs of the application will get written to `foo.log` file. This is an unexpected behavior from the application's perspective. There are some ways to mitigate this problem:

1. Execute the `fileWriteOutput()` function only when it's being called from the **default module**. This way the application developer would have full control over the location of log output.
2. Support this feature through a configuration file. Uber-go/zap[[1]](https://github.com/uber-go/zap) has a similar approach[[2]](https://pkg.go.dev/go.uber.org/zap#example-package-BasicConfiguration) in which the location of the file can be configured. We could adopt this and define the file location in the `Config.toml` as follows.
```
[ballerina.log]
outputPath = "./foo.log"
``` 

Additionally, we can define the output stream as well.
```
[ballerina.log]
outputPath = ["stdout", "/foo.log"]
``` 
This way all the logs will get written to the location of the file defined by the application developer.

[1] https://github.com/uber-go/zap
[2] https://pkg.go.dev/go.uber.org/zap#example-package-BasicConfiguration

**Comment by jclark** [comment]
I don't see the problem. A module should not call `log:fileWriteOutput` unless its goal is to change the file to which all the logs of the application are written. I might write an app with a module that does logging on top of the `log` module; such a module might well want to call `log:fileWriteOutput`.

Allowing it to be configurable is fine. But still the app needs to be able to specify somewhere other than stderr/stdout if the user does not configure it.

**Comment by jclark** [comment]
BTW, I don't think `fileWriteOutput` is a good name: it sounds like it is writing something, but it is changing the behaviour of subsequent logging calls.  I guess you have tried to make the name similar to `io` module, but the situation is not analogous.  I would use something like `setOutputFile`.
