### ISSUE TITLE
Debug logs of Ballerina modules are also getting printed when debug logs enabled for a service

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-standard-library#1399]
**Description:**
I tried to get the debug logs of a ballerina service that I deployed. But there are other debug logs related to Ballerina standard library modules such as HTTP.

```log
[ballerina/http] started HTTP/WS listener 0.0.0.0:8092
time = 2021-05-26T10:38:53.817+05:30 level = DEBUG module = ballerina/http message = "Created HTTP caching client" 
time = 2021-05-26T10:38:53.836+05:30 level = DEBUG module = ballerina/http message = "Cached response not found for: \'GET /1\'" 
time = 2021-05-26T10:38:53.837+05:30 level = DEBUG module = ballerina/http message = "Sending new request to: /1" 
time = 2021-05-26T10:38:53.968+05:30 level = DEBUG module = ballerina/http message = "Created HTTP caching client" 
time = 2021-05-26T10:38:53.969+05:30 level = DEBUG module = ballerina/http message = "Cached response not found for: \'GET /1\'" 
time = 2021-05-26T10:38:53.969+05:30 level = DEBUG module = ballerina/http message = "Sending new request to: /1" 
```

I was not expecting those debug logs since I was only concern about the debug logs in my application.
This will be very cumbersome to find a user-specified debug log when we have these type of debug logs printed by other ballerina modules.
We need to turn off the debug logs related to the standard libraries or need to give the control to the user to turn it on if 

**Affected Versions:**
Ballerina SL Alpha5

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-standard-library/issues/1384

**Comment by MadhukaHarith92** [comment]
By default, all the packages have the `INFO` log level. You can configure the log level for each module. For example, consider the following project which also imports the` ballerina/http` module.
```
myproject
├── Ballerina.toml
├── Config.toml
├── main.bal
└── modules
    └── foo
        └── foo.bal 
```

You can configure the `Config.toml` file as follows.
```
[ballerina.log]
level = "WARN"

[[ballerina.log.modules]]
name = “madusha/myproject"
level = "DEBUG"

[[ballerina.log.modules]]
name = "ballerina”/http
level = "ERROR"
```
In this example `madusha/myproject` will have `DEBUG` log level and `ballerina/http` module will have `ERROR` log level. All the other modules will have `WARN` log level since that is the global log level.

**Comment by madushajg** [comment]
@MadhukaHarith92 Thanks for the clarification.

I tried the given configs and this satisfies my requirement. Hence closing the issue.
