### ISSUE TITLE
Ability to set sender's name when sending emails using email module

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-standard-library#1408]
**Description:**
Currently theres no way to set sender's name in the email when using the email module.

**Describe your problem(s)**
Set sender's name

**Describe your solution(s)**
Implement setting sender's name
Refer: https://stackoverflow.com/questions/11212257/java-mail-senders-address-displayed-rather-than-his-name/11212669

**Comment by Maninda** [comment]
Can specify the sender's name in the `'from` field like `John Doe<jhon@example.com>` which would set the associate the name with the email address.
