### ISSUE TITLE
Unable to connect to NATS streaming server using TLS

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#1423]
**Description:**
Attempting to connect to a NATS streaming sever using the STAN module produces the following error:
`https://github.com/kaneeldias/module-ballerinax-stan/tree/tls_test2/stan-ballerina/tests`

Nats streaming server is up and running but not recognizing any connection attempts.
![image](https://user-images.githubusercontent.com/6332902/120747399-91c17e80-c51e-11eb-9443-fd878c4e014e.png)

**Steps to reproduce:**
Tests and certificates can be found [**here**](https://github.com/kaneeldias/module-ballerinax-stan/tree/tls_test2/stan-ballerina/tests). 

**Affected Versions:**
Ballerina Swan Lake Alpha 5

**Suggested Labels (optional):**
module/stan

**Suggested Assignees (optional):**
@aashikam

**Comment by ldclakmal** [comment]
@aashikam I also tried the same scenario and the issue was reproducible. Got the following error message from both client and listener.
```bash
error: internal error while creating streaming connection Unable to connect to NATS servers: nats://localhost:4222. {}
```
