### ISSUE TITLE
Migrate Stdlib Release Workflows to SwanLake

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#1428]
**Description:**
Since now we are moving to SwanLake, the release pipeline should be migrated to Swan Lake.
There are some issues we have, that can be avoided using SwanLake. (Eg.: https://github.com/ballerina-platform/ballerina-standard-library/issues/566)

**Comment by niveathika** [comment]
Closing as this task is done
