### ISSUE TITLE
Pending fixes for Ballerina-1.2.x which already solved in Swan Lake

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#1434]
**Description:**
> Change is applied to SL via https://github.com/ballerina-platform/module-ballerina-http/pull/432 and https://github.com/ballerina-platform/module-ballerina-http/pull/434. This should go to ballerina-1.2.x branch.

**Affected version**
ballerina-1.2.x

**Comment by chamil321** [comment]
Following 2 issue has been fixed in SL beta2 and should ship to the ballerina-1.2.x as well
ballerina-platform/ballerina-standard-library#1095
ballerina-platform/ballerina-standard-library#342

**Comment by shafreenAnfar** [comment]
Closing this we will do it on demand.
