### ISSUE TITLE
gRPC client streaming and bidirectional streaming fail to pass headers

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1458]
**Description:**
$title

**Steps to reproduce:**
Try gRPC client and bidirectional streaming with headers.

**Affected Versions:**
SL Beta 1 and 1.1

**Comment by daneshk** [comment]
Please find the sample test case to reproduce the issue: https://gist.github.com/daneshk/ff0cc9921cb7ebb509202894cceb3c1d

**Comment by daneshk** [comment]
Seems like we didn't capture send headers on the client-side. We have two options here, 

Option 01:
Pass the header values when we do the remote call, like
```
Chat39StreamingClient streamingClient = check chat39Ep->chat39(headers: {"x-id": "0987654321"});
```

Option 02:
Pass the header values when we send the first message using the streaming client,
```
Chat39StreamingClient streamingClient = check chat39Ep->chat39();
check streamingClient->sendContextChatMessage39({content: {name: "Sam", message: "Hi"}, headers: {"x-id": "0987654321"}});
```

**Comment by BuddhiWathsala** [comment]
Did not add these kinds of changes to the Ballerina level because it will unnecessarily break the previously generated stubs. Instead, handle context in Java similar to what we followed in the caller.

> Seems like we didn't capture send headers on the client-side. We have two options here,
> 
> Option 01:
> Pass the header values when we do the remote call, like
> 
> ```
> Chat39StreamingClient streamingClient = check chat39Ep->chat39(headers: {"x-id": "0987654321"});
> ```
> 
> Option 02:
> Pass the header values when we send the first message using the streaming client,
> 
> ```
> Chat39StreamingClient streamingClient = check chat39Ep->chat39();
> check streamingClient->sendContextChatMessage39({content: {name: "Sam", message: "Hi"}, headers: {"x-id": "0987654321"}});
> ```
