### ISSUE TITLE
Update links in module Package.md

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#1462]
**Description:**
Update all links in  Package.md file to following the standard: 
https://github.com/ballerina-platform/ballerina-standard-library/issues/1462#issuecomment-860568897

Ref PR: https://github.com/ballerina-platform/module-ballerinax-stan/pull/170

Standard library modules: 
- [x] io 
- [x] url 
- [x] java.arrays
- [x] random
- [x] regex
- [x] task
- [x] time
- [x] xmldata
- [x] crypto
- [x] os 
- [x] xslt
- [x] uuid
- [x] log
- [x] cache 
- [x] file
- [x] ftp
- [x] mime
- [x] nats
- [x] stan 
- [x] tcp
- [x] udp 
- [x] auth
- [x] email 
- [x] http
- [x] jwt 
- [x] oauth2 
- [x] graphql 
- [x] grpc 
- [x] websocket 
- [x] websub 
- [x] websubhub
- [x] kafka
- [x] rabbitmq
- [x] sql
- [x] java.jdbc
- [x] mysql

**Comment by shafreenAnfar** [comment]
Let's fall back to this for all the links 

`<a target="_blank" href="https://ballerina.io/"> Ballerina</a>`
