### ISSUE TITLE
Remove countdown latch from the implementation 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1473]
**Description:**
https://github.com/ballerina-platform/module-ballerinax-rabbitmq/blob/master/rabbitmq-native/src/main/java/org/ballerinalang/messaging/rabbitmq/RabbitMQResourceCallback.java#L72

**Comment by aashikam** [comment]
Closed since after having a discussion on this, it was decided that we will keep this as it is. The countdown latch is kept to ensure the order of the messages dispatched and removing it will not preserve the message order.
