### ISSUE TITLE
Ability to configure CORS

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1475]
I get this when trying to connect with https://www.graphqlbin.com/v2/new

```
shafreen:snowtooth shafreen$ bal run

Compiling source
	graphql/snowtooth:0.1.0

Running executable

[ballerina/http] started HTTP/WS listener 0.0.0.0:9000
time = 2021-06-15 12:10:59,089 level = INFO  module = "" Failed to process CORS : access control request method not allowed
```
We need to be able to configure CORS as in https://ballerina.io/learn/by-example/http-cors

**Comment by ThisaruGuruge** [comment]
There's a requirement from Choreo for this. Therefore increase the priority

**Comment by DimuthuMadushan** [comment]
This is temporarily blocked until merging the lang PR [Add closure support for object constructor](https://github.com/ballerina-platform/ballerina-lang/pull/32697).
