### ISSUE TITLE
When using http:Caller returning nil should result in 500

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1524]
**Description:**
This is the text from the design doc.

Returning () can have two meanings in success case
1. The application wants to return nothing which means the protocol engine will generate a 202 accepted response back to the caller. 
2. The application has dealt with the response already by responding via the http:Caller.
Returning () in the error case means that the application has not responded despite returning (). 500 Internal server error responses should be sent back to the caller.

**Comment by chamil321** [comment]
point 1 is fixed via https://github.com/ballerina-platform/module-ballerina-http/pull/472
In point 2, I assume what meant from error case is that returning `()` when `http:Caller` present in the resource and have not used it.
```ballerina
    resource function get errorCaller(http:Caller caller, boolean err) returns error? {
        if err {
            return; //500 response
        }
        check caller->respond("success");
    }
```
