### ISSUE TITLE
Getting an error by the SQL query

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#1528]
**Description:**
`ParameterizedQuery` only supports getting the records values. When trying to add the table name or database name or fields name, getting an error.

**Steps to reproduce:**
Update the `updateQuery` query in the [ BBE](https://ballerina.io/learn/by-example/mysql-execute-operation) with this
```ballerina
string tableName = "Customers";
// Creates a parameterized query for the record update.
sql:ParameterizedQuery updateQuery =
`UPDATE ${tableName} SET creditLimit = ${newCreditLimit} where customerId = 1`;
```
**Error:**
```ballerina
error: Error while executing SQL query: UPDATE  ?  SET creditLimit =  ?  
            where customerId = 1. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Customers'  SET creditLimit =  'Peter'  
            where customerId = 1' at line 1. {"errorCode":1064,"sqlState":"42000"}
```
**Affected Versions:**
SLBeta1

**Comment by niveathika** [comment]
This is intended behaviour. We do not support parameterising the table name

**Comment by niveathika** [comment]
This can be supported by improving the batchExecute() api to support string array. This is tracked in https://github.com/ballerina-platform/ballerina-standard-library/issues/1529
