### ISSUE TITLE
Change Native Package Names to Comply with the Standards

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#1530]
**Description:**
Currently, there are different naming conventions in different modules, when it comes to naming the native packages.
Some packages use `org.ballerinalang.stdlib.<module_name>`, some using `org.ballerinalang.<module_name>`, etc.

These namings should be standardized to follow the same convention in every standard library packages. The ballerina-runtime team has already started to follow a standard naming using the `io.ballerina.` prefix.
 
The convention to follow in the standard libraries is to use the pattern `io.ballerina.stdlib.<package_name>`. We have to update this in every module and any of the native package usages in other places.

Let's update this list once it is done. Please link the issue with the relevant PRs.

- [ ] io 
- [ ] url 
- [ ] java.arrays
- [ ] random
- [ ] regex
- [ ] task
- [ ] time
- [ ] xmldata
- [ ] crypto
- [ ] os 
- [ ] xslt
- [ ] uuid
- [ ] log
- [ ] cache 
- [ ] file
- [ ] ftp
- [ ] mime
- [ ] nats
- [ ] stan 
- [ ] tcp
- [ ] udp 
- [ ] auth
- [ ] email 
- [ ] http
- [ ] jwt 
- [ ] oauth2 
- [x] graphql 
- [ ] grpc 
- [ ] websocket 
- [x] websub 
- [x] websubhub
- [ ] kafka
- [ ] rabbitmq
- [ ] sql
- [ ] java.jdbc
- [ ] mysql 
- [ ] postgresql

**Comment by ayeshLK** [comment]
`websub` and `websubhub` currently follows the mentioned package naming convention.
- **websub**: io.ballerina.stdlib.websub
- **websubhub**: io.ballerina.stdlib.websubhub

**Comment by ThisaruGuruge** [comment]
We may have to change the `group` entry in the `gradle.properties` file too. @shafreenAnfar @daneshk WDYT?

Otherwise, the artifact name in the published package will have `org.ballerinalang` as the group name.

**Comment by daneshk** [comment]
> We may have to change the `group` entry in the `gradle.properties` file too. @shafreenAnfar @daneshk WDYT?
> 
> Otherwise, the artifact name in the published package will have `org.ballerinalang` as the group name.

Yes, we also need to change the gradle file.

**Comment by niveathika** [comment]
This will also affect the test coverage filter, won't it?

**Comment by ThisaruGuruge** [comment]
> This will also affect the test coverage filter, won't it? 

Yes. We have to update it as well in the same PR.

**Comment by ThisaruGuruge** [comment]
Closing since this is tracked by #1623
