### ISSUE TITLE
Improve sql:ParameterizedQuery to access table names using ${}

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-standard-library#1534]
**Description:**
`ParameterizedQuery` doesn't support table name access using ${}. When trying to add the table name, gives an error.

**Describe your problem(s)**
Update the selectQuery query in the [BBE](https://ballerina.io/learn/by-example/mysql-query-operation.html) with this
```
string tableName = "Customers";
// Creates a parameterized query for SELECT.
sql:ParameterizedQuery selectQuery = `SELECT * FROM ${tableName}`
```
Error:
Error while executing SQL query: SELECT * FROM  ? . Unable to retrieve columns for table [?].

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-standard-library/issues/1528
https://github.com/ballerina-platform/ballerina-standard-library/issues/1529

Affected Versions:
SLAlpha5, SLBeta1

**Comment by lahirusamith** [comment]
As per the current implementation, `ParameterizedQuery` is only designed to add variable values to column fields in a query. In other words, parameterized query have not designed to have table names, database names.

Eg: 

```ballerina
string tableName = "Customers";
sql:ParameterizedQuery selectQuery = `SELECT * FROM ${tableName}`;
```
gives an error while, 

```ballerina
string customerName = "Joe";
sql:ParameterizedQuery selectQuery = `SELECT * FROM Customers where customer_name = ${customerName}`;
```
is an correct `ParameterizedQuery` 

So As a workaround you can create these dynamic queries as strings by doing string manipulations and pass those string type queries to `query`, `execute` and `batchExecute` remote methods.  

We will make arrangements in future to re-think and provide a best solution to support this specific requirement.

**Comment by niveathika** [comment]
Closing this as per the above comment
