### ISSUE TITLE
Heading hasn't correct formating

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#1556]
**Description:**
<img width="265" alt="Screenshot 2021-06-28 at 1 33 58 PM" src="https://user-images.githubusercontent.com/12771261/123602049-fcac5f80-d815-11eb-8661-ff7611eaa9cd.png">

**Comment by Maninda** [comment]
Resolved with https://github.com/ballerina-platform/module-ballerina-ftp/pull/302
