### ISSUE TITLE
nativeBatchExecute in SQL module fails with connectors which do not support getGeneratedKeys on batch execute

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#1568]
**Description:**
Microsoft SQL Server and OracleDB JDBC connectors do not support the retrieval of generated keys with batch execute functions.

SQL Server: [https://github.com/microsoft/mssql-jdbc/issues/358](https://github.com/microsoft/mssql-jdbc/issues/358)
Oracle DB: [https://docs.oracle.com/database/121/JJDBC/jdbcvers.htm#JJDBC28099](https://docs.oracle.com/database/121/JJDBC/jdbcvers.htm#JJDBC28099)

**Steps to reproduce:**
For MSSQL connector:
https://github.com/ballerina-platform/module-ballerinax-mssql/blob/main/mssql-ballerina/tests/batch-execute-query-test.bal

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-standard-library/issues/1501

**Suggested Labels (optional):**
module/sql

**Suggested Assignees (optional):**
@kaneeldias

**Comment by daneshk** [comment]
Provide add a new parameter to handle generate keys in different connectors. hence closing this issue
