### ISSUE TITLE
JDBC does not support Timestamp and Time with timezone

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#157]
**Description:**
$subject in all places such as parameters, insert, data retrieval etc.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lahirusamith** [comment]
This PR https://github.com/ballerina-platform/module-ballerina-sql/pull/161 resolves this issue.
