### ISSUE TITLE
Improve sql:ParameterizedQuery updateQuery to dynamically handle column names

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-standard-library#1573]
**Description:**
sql:ParameterizedQuery updateQuery cannot dynamically handle column names. 

**Describe your problem(s)**
Consider a scenario where we have a record called `Issue`
```
public type Issue record {
   readonly int Id?;
   string Description?;
   string Summary?;
   string Labels?;
}
```
We are trying to update `Issue` table by using passing a `Issue` record as a parameter to a remote function called `remote function updateIssue(Issue issue) returns string|error? {}`
```
sql:ParameterizedQuery updateQuery = `UPDATE Issue 
                                      SET Description = ${issue?.Description}, Summary = ${issue?.Summary}, Labels = ${issue?.Labels} 
                                      WHERE Id = ${issue?.Id}`;
```
Imagine the `Issue` table already has a value filled in `Summary` field for a certain issue `Id`. Currently if we try to update this specific row by passing an `Issue` record to the updateIssue() function where this `Summary` field is nil (), it will rewrite the `Summary` field in the table with an empty value. But ideally the relevant field should update only if the user passes a value to this `Summary` field in the record. Currently I couldn't handle this scenario without dynamic query support. If we can dynamically pass the key value pairs to be set in the sql:ParameterizedQuery updateQuery, I could have handled this scenario.

**Comment by niveathika** [comment]
@RolandHewage IMO this should be handled at the data layer level. As far as the database is concerned, you are passing a query that should update the summary field with the value passed in the Issue record(This can be a value or nil). 

Maybe you can change the query as 
```
UPDATE Issue 
SET Description = ${issue?.Description}, Summary = ${issue?.Summary}, Labels = ${issue?.Labels} 
WHERE Id = ${issue?.Id} AND ${issue?.Summary} != null
```
