### ISSUE TITLE
Migrate to a Common Gradle Version in Standard Library Package Builds

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#1595]
**Description:**
Currently, different Standard Library repositories are using different Gradle versions in their builds. Ideally, all the modules should be using the same Gradle version, which will make life easier from an outsider's point of view.

Think someone tries to build two different Standard Library modules locally, and they have to download different Gradle versions for that!

Additionally, there are places some deprecated Gradle syntaxes are used.
For example, `compile group` usage is deprecated and instead `implementation group` is the recommended way. In future Gradle versions, `compile` will be removed. We should be following these guidelines. 

## Gradle Versions
Currently, Gradle has the following latest Versions
- `7.1`
- `6.9`

All the Standard Library modules are using Gradle `6.x.x` versions as of now. So might be the feasible option is to migrate to `6.9`. Migrating to 6.9 will not have any major impacts, except for a couple of changes as suggested above.

What are your thoughts?
@shafreenAnfar @daneshk @BuddhiWathsala @niveathika

**Comment by niveathika** [comment]
+1

**Comment by BuddhiWathsala** [comment]
+1

**Comment by ThisaruGuruge** [comment]
The final decision is to migrate to Gradle `7.1` version. 

To update, `gradle wrapper --gradle-version 7.1` can be used. 
After running this command, commit and push the `gradlew` files and the `gradle-wrapper.jar` file.

**Comment by ThisaruGuruge** [comment]
Closing since this is tracked via #1618
