### ISSUE TITLE
Improve behavior of isolated functions in native java code

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-standard-library#161]
**Description:**
All the APIs in the system module are marked as isolated. So getting the system properties and environment variables from java interop native code have to be rewritten in a thread-safe manner. 

Related PR: https://github.com/ballerina-platform/module-ballerina-system/pull/7

**Comment by daneshk** [comment]
We can't make get system properties as isolated.

**Comment by Bhashinee** [comment]
Closing the issue as this is no longer valid.
