### ISSUE TITLE
Add duration type support for gRPC

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1610]
**Description:**
Need to support protobuf duration support in,
- runtime level
- code generation level

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/43

**Comment by BuddhiWathsala** [comment]
In protobuf, the type Duration is represented using a message like below, refer to [this link](https://github.com/protocolbuffers/protobuf/blob/4b77b733699f9c39b517a124da737c018b1164e2/src/google/protobuf/duration.proto) for more details.
```proto
message Duration {
  // Signed seconds of the span of time. Must be from -315,576,000,000
  // to +315,576,000,000 inclusive. Note: these bounds are computed from:
  // 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
  int64 seconds = 1;

  // Signed fractions of a second at nanosecond resolution of the span
  // of time. Durations less than one second are represented with a 0
  // `seconds` field and a positive or negative `nanos` field. For durations
  // of one second or more, a non-zero value for the `nanos` field must be
  // of the same sign as the `seconds` field. Must be from -999,999,999
  // to +999,999,999 inclusive.
  int32 nanos = 2;
}
```

According to the above structure, syntactically it is possible to represent the `Duration` type in Ballerina using `time:Utc`; because `time:Utc` is a tuple that holds seconds and nanoseconds(as a fraction) values. However, semantically it is invalid to represent a time duration using `time:Utc`.

The optimal way to represent time duration in Ballerina is `time:Seconds`. Even, in the time package, we use `time:Seconds` to represent durations according to [the following API](https://github.com/ballerina-platform/module-ballerina-time/blob/3b2897f20f4bbd731832b1d9e0d2775c16d351cc/time-ballerina/time_apis.bal#L68). 

```ballerina
public isolated function utcAddSeconds(Utc utc, Seconds seconds) returns Utc {}
```

Also, `time:Seconds` is nothing but a decimal type that represent seconds(as the whole number) and nanoseconds(as the fraction). 

@daneshk @shafreenAnfar @dilanSachi WDYT?

**Comment by daneshk** [comment]
Yes, correct. `time:Seconds` type is more appropriate for the protobuf duration type.
