### ISSUE TITLE
Support external import paths in gRPC CLI

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1612]
**Description:**
ATM, gRPC CLI does not support specifying external import paths, similar to `-IPATH` in `protoc`.
```sh
$ protoc -h
Usage: protoc [OPTION] PROTO_FILES
Parse PROTO_FILES and generate output based on the options given:
  -IPATH, --proto_path=PATH   Specify the directory in which to search for
                              imports.  May be specified multiple times;
                              directories will be searched in order.  If not
                              given, the current working directory is used.
                              If not found in any of the these directories,
                              the --descriptor_set_in descriptors will be
                              checked for required proto file.
```

Suggestions for argument name:
- `--include_path`
- `--inlcude`

@daneshk @shafreenAnfar @MadhukaHarith92 @dilanSachi WDYT?

**Comment by praminda** [comment]
+1 for this.
Without this feature its bit hard to maintain multi package proto structures for different dependent micro-services. We are planning to implement something similar to [kubernetes/api](https://github.com/kubernetes/api), [data-plane-api](https://github.com/envoyproxy/data-plane-api) for choreo. For maintaining that type of complex proto structures we need `--include` param, otherwise proto import need to be changed with relative proto paths. That doesn't look good.

**Comment by daneshk** [comment]
+1
Issue #397 also captures the same. We can close it and discuss it here.

**Comment by daneshk** [comment]
will `include` option conflict with `--include-imports`, `--include-source-info` options in proto commands?
one option is to go with `--proto_path` like in the proto command

**Comment by MadhukaHarith92** [comment]
+1 to go with `--proto_path` option.

**Comment by praminda** [comment]
When can we expect this to be included in a release?

**Comment by MadhukaHarith92** [comment]
> All,
> When can we expect this to be included in a release?

Will try to ship the feature in SL Beta3.

**Comment by MadhukaHarith92** [comment]
Please note that the input .proto file **should** reside within the path specified using `--proto_path`. Therefore you must specify a `--proto_path` which encompasses the .proto file. This is the behavior in `protoc` and we decided to have the same behavior in grpc tool. 

The following is a valid directory structure where `child.proto` is the root proto file and `parent.proto` is the dependent proto file.

```
myproj
├── foo
│   └── bar
│       └── child.proto
└── parent.proto
```

The grpc command (executed from the dir outside "myproj" dir):
`bal grpc --input myproj/foo/bar/child.proto --proto_path myproj --output stubs`
