### ISSUE TITLE
GET generated OpenAPI document during runtime

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1616]
**Description:**
In oder to to something useful with the exposed REST APIs, consumers of the APIs need to know the protocol semantics and application semantics. Protocol semantics basically explains _how_ to consume the service and application semantics explain _what_ is at the end of link. In other words, how to interpret the representations.  

An openAPI doc can help us bridge this gap. However, at the moment, the openAPI file for a given API could be generated only using the openAPI tool. But not during the runtime. Therefore, the generated `yml` file needs to be  hosted in some place for API consumers. 

But what if the openAPI doc can be generated (or retrieved) at runtime when requested from the hosted service itself.  This would make the service self-contained. 

For instance, say you have hosted a service under `host:9000/foo`. In order to get the openAPI doc for this service, API consumer can send an OPTIONS request as follows.

```
curl host:9000/foo -v -X OPTIONS
```  
Which would return a response as follows,
```
HTTP/1.1 204 No Content
allow: OPTIONS, GET, HEAD, POST
date: Thu, 13 Oct 2016 11:45:00 GMT
server: ballerina
link: </foo/openapi-doc-dygixywsw>;rel="openapi-doc"
```
Now the developer can send a GET request to the dynamically generated URL in the `link` header with the relation `openapi` to get the openAPI definition for the service.

**Comment by shafreenAnfar** [comment]
There are four reason for this two step process,

1) URL that points to the openAPI doc never collides with users API URLs.
2) This gives a unified way of retrieving openAPI docs across all the Ballerina services.
3) `HEAD` and `OPTION` can be used to introspect services (in a primitive way). OpenAPI is also part of the service introspection. They all basically serves meta information about the service.
4) Users only needs to know the well-known URL of the service which is the case for well-written REST APIs.

We can let the user configure this behavior by having a simple config section as below in the `@http:ServiceConfig`. When the config points to a file, it will use that as the openAPI doc which is exposed under the generated URL.

```ballerina
type openapi record {|
    string file;
    boolean enable;
|}
```

**Comment by shafreenAnfar** [comment]
@sanjiva we would like to get your opinion on this.

**Comment by shafreenAnfar** [comment]
The other option is to go for a fixed URI as below,

```
https://host:9090/foo/.meta/openapi-doc
```

**Comment by sanjiva** [comment]
I prefer the OPTIONS approach as that doesn't intrude to user space. Is the rel value you're using a standard? Is there no convention for runtime discovery like this?

How much of compiler level code do we need to have in the runtime to dynamically generate this? Or are we planning to generate the core of the spec at compile time and only put the endpoints in at runtime?

**Comment by shafreenAnfar** [comment]
> I prefer the OPTIONS approach as that doesn't intrude to user space. Is the rel value you're using a standard? Is there no convention for runtime discovery like this?

We will go ahead with OPTIONS approach. I also like the fact that it doesn't intrude the user space. 

`rel` value is not a standard. [Here](https://www.iana.org/assignments/link-relations/link-relations.xhtml) is the IANA registered relations.  There is a RFC under [well-known](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) URIs called [CoRE](https://www.rfc-editor.org/rfc/rfc6690.html) which talks about REST API discovery. But none of those talks about openAPI document. After all, it is not a pure REST thing.

> How much of compiler level code do we need to have in the runtime to dynamically generate this? Or are we planning to generate the core of the spec at compile time and only put the endpoints in at runtime?

We are planning to do the latter. Generate the openAPI document during compile time and put the endpoint at runtime.

**Comment by sanjiva** [comment]
Have you looked at doing this in a service type agnostic way? We need to handle GraphQL and gRPC too as they also go thru the same HTTP listener (that's the one that processes the OPTIONS call right?).

From the descriptions it seems that `service-desc` is the most appropriate.

**Comment by shafreenAnfar** [comment]
> Have you looked at doing this in a service type agnostic way? We need to handle GraphQL and gRPC too as they also go thru the same HTTP listener (that's the one that processes the OPTIONS call right?).

Yeah, `http:Listener` is the one that process OPTIONS request. We haven't looked into doing this in service type agnostic way. We could return the relevant `service-desc` for each service type.

We haven't drilled down the implementation detail yet. Along with that we will look into doing this in a service type agnostic way.  We will update this issue with the implementation details soon.

P.S. gRPC is not using  `http:Listener` but the underlying Netty based transport implementation.

**Comment by chamil321** [comment]
**Meeting notes of Implementation details discussion**

Participants: Jo, Chamil, Ayesh, Sumudu, Buddhi, Shafreen


**OpenAPI doc generation**

- Use a built in plugin  as part of openapi code base to perform OpenAPI doc generation using syntax tree and semantic model. This code is executed only if there is a http:Service in the project. 

- Add generated JSON document into a resource dir of the produced jar. 

- Add a file with a random generated string to the same location Which will be used when constructing the unique URL for the generated openAPI doc.

**HTTP Resource injection**
- Using the HTTP compiler plugin 

  - Read the file with the random string and construct the complete URL and the resource. Ex.  /foo/openapi-doc-{random string}

  - Inject a new resource with with the generated URL to the dispatching tree

- Update OPTIONS request flow to add the link header for the new resource which returns Open API json content.

If API developers want more control over this behavior, API developers can use the openapi annotation and control it. Such as configuring openAPI version, using the enriched openAPI documentation, etc.

**Comment by sameerajayasoma** [comment]
Do we get different URLs for each build of the service?

**Comment by shafreenAnfar** [comment]
Yes, for each build there will be a different URL. IMO, it is not a problem because as this is expected to use by API consumers.

**Comment by ayeshLK** [comment]
Since we are implementing this feature as a built-in compiler extension the common approach is to publish the extension to github packages and fetch it from there and pack it into ballerina distribution.

Hence we need a proper package name for the open-api extension. Following are few suggestions;
1. openapi-http-extension
2. openapi-compiler-plugin

**Comment by shafreenAnfar** [comment]
Assuming that above names are as per the convention, how about something like ? `service-to-openapi-plugin`

**Comment by shafreenAnfar** [comment]
> Yes, for each build there will be a different URL. IMO, it is not a problem as this is expected to use by API consumers.

On second thoughts, what we need to achieve is having a unique URL for a given service. Therefore, having a fixed random string is fine. For instance, say we have two services one with basepath `foo` and the other with `bar`, in that case the URLs would look like,

- http://mydomain.com/foo/openapi-doc-dygixywsw
- http://mydomain.com/bar/openapi-doc-dygixywsw

Even though the random string is the same, the complete URL is unique.

**Comment by ayeshLK** [comment]
Currently we have implemented the functionality in our OpneAPI built-in plugin. As an improvement we need to incorporate compiler-plugin code-generators to OpenAPI plugin. Since this is an improvement we will close this issue and the remaining work will be captured in [#2472](https://github.com/ballerina-platform/ballerina-standard-library/issues/2472).
