### ISSUE TITLE
Remove the repetition of package name in the folders 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1619]
**Description:**
At the moment in each standard library repo we repeat the package name in the folder structure. For instance, if you take IO repo. Each folder in IO repo is prefixed with `io` which is not needed.  For instance,

- io-ballerina
- io-native
- io-test-utils 

We need to remove this prefix in all the repos. For instance,

- ballerina
- native
- test-utils

**Comment by ThisaruGuruge** [comment]
Closing since this is tracked by #1623
