### ISSUE TITLE
Unexpected response content type 

### ISSUE THREAD

**Issue by bondowe** [ballerina-platform/ballerina-standard-library#1621]
**Description:**

The following code returns a response with a `text/plain` content type header when I expected `text/html`. 

```ballerina
import ballerina/http;

listener http:Listener ep = new(8788);

service on ep {
    resource function get . () returns http:Ok {
        return {
            headers: {
                "Content-Type": "text/html; charset=UTF-8"
            },
            body: "<h1>HI</h1>"
        };
    }
}
```
![image](https://user-images.githubusercontent.com/1747482/124751320-64516180-df1e-11eb-8bbc-2ccd06b21a70.png)

**Affected Versions:**

slbeta1

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**

**Suggested Labels (optional):**

ballerina/http

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
Tested in beta2: 
```
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.6
```
Output
```
curl -v localhost:8788
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8788 (#0)
> GET / HTTP/1.1
> Host: localhost:8788
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: text/html;charset=UTF-8
< content-length: 11
< server: ballerina
< date: Thu, 8 Jul 2021 11:20:43 +0530
< 
* Connection #0 to host localhost left intact
<h1>HI</h1>* Closing connection 0
```
The issue has been fixed in beta2, hence closing the issue
