### ISSUE TITLE
Support a directory with protos as input for gRPC gen command

### ISSUE THREAD

**Issue by renuka-fernando** [ballerina-platform/ballerina-standard-library#1626]
**Description:**
ATM, gRPC CLI only supports one proto file as an input for `bal grpc` command.

```sh
bal grpc --input protos/app_service.proto --output api
```

**Suggestion**
Support a dir as an input or multiple protos with wildcard support.

**Comment by daneshk** [comment]
Can you a bit more about the use case? Normally protobuf supports providing one root definition and multiple dependent proto files. Do you want to run the generate command for all the proto files in a directory?

**Comment by renuka-fernando** [comment]
> Can you a bit more about the use case? Normally protobuf supports providing one root definition and multiple dependent proto files. Do you want to run the generate command for all the proto files in a directory?

Yes, run the generate command for all the proto files in a directory.

**Comment by daneshk** [comment]
@MadhukaHarith92 shall we check the possibility?
