### ISSUE TITLE
Invalid samples in Module.md in MySQL module

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#1633]
**Description:**
As shown below, the sample codes for Connection Pool Handling in MySQL's module.db references invalid code. The connection url string cannot be directly provided in the MySQL module (and other DB connectors)

![image](https://user-images.githubusercontent.com/6332902/125044821-f80b6500-e0b9-11eb-85b3-799273ac1520.png)

**Describe your task(s)**
Update with correct sample code.
`    mysql:Client|sql:Error dbClient = new ("localhost", "rootUser", "rootPass");
`

**Suggested Labels (optional):**
module/mysql

**Comment by niveathika** [comment]
@kaneeldias Could you send the fix as well?

**Comment by kaneeldias** [comment]
> @kaneeldias Could you send the fix as well?

Will do
