### ISSUE TITLE
Support to have multiple gRPC stubs in the same module

### ISSUE THREAD

**Issue by slahirucd7** [ballerina-platform/ballerina-standard-library#1635]
**Description:**
If there are multiple gRPC stub files (pb.bal files)  in the same ballerina module, compiler gives below error.
```
ERROR [service1_pb.bal:(79:14,79:29)] redeclared symbol 'ROOT_DESCRIPTOR'
ERROR [service1_pb.bal:(81:19,81:35)] redeclared symbol 'getDescriptorMap'
```

**Describe your problem(s)**

**_Example scenario:_**

When we are implementing a gRPC service that requires to call another gRPC service within the main gRPC service implementation, we need to add below stubs (by  being in the same module).

`Stub relevant to the main gRPC service (to implement service)`
`Stub relevant to the second gRPC service (to implement client)`

![image](https://user-images.githubusercontent.com/40932779/125050044-39524380-e0bf-11eb-955e-d32599463f59.png)

But in the stub files,

`const string ROOT_DESCRIPTOR` variable name will be the same for all required stubs. We can change this variable to overcome the issue caused by this. But in actual use cases we are not allowed to change the auto generated stubs for gRPC services.
The variable name change becomes a compulsory thing if there is a need to have multiple stub files (pb.bal files) in the same module

**Describe your solution(s)**

When automatically generating the `ROOT_DESCRIPTOR` variable name we can append the relevant proto file's name to the variable. Then there won't be similar named variable values.

Ex : `ROOT_DESCRIPTOR_SERVICE1`

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by praminda** [comment]
@BuddhiWathsala @daneshk

**Comment by daneshk** [comment]
yes, this is a limitation we have in the current impl. as a workaround, we can rename the variables and usages. 

@BuddhiWathsala @MadhukaHarith92 shall we append the proto filename to those generated variables. WDYT?

**Comment by BuddhiWathsala** [comment]
Yes, +1 to add the proto file name into the variable name. For example:
- ROOT_DESCRIPTOR_<PROTO_FILE_NAME> - proto file name in block letters
- getDescriptorMap<Proto_File_Name> - proto file name in camel case

PS: We can replace all the non-alphabetic characters to underscore.

**Comment by praminda** [comment]
renaming variable name inside the generated code is bit problematic when code is regenerated. 
+1 to append service name to make it unique

**Comment by MadhukaHarith92** [comment]
+1 to append the proto file name. And also, do we apply this only to `ROOT_DESCRIPTOR` and `getDescriptorMap`. What about other variable names like context record params. eg:
```
public type ContextStringStream record {|
    stream<string, error?> content;
    map<string|string[]> headers;
|};
```
@daneshk

**Comment by BuddhiWathsala** [comment]
IMO, we don't need to update the context names. AFAIR, we removed the repetitive generation of these context variables sometimes back. Thus, it shouldn't cause such an issue.

**Comment by slahirucd7** [comment]
Above scenario obtained when there are client and service related stubs (for two different proto files) are placed in a same module.
![image](https://user-images.githubusercontent.com/40932779/125392855-85a1ca00-e3c4-11eb-94e0-3fd4e56f4709.png)

**Comment by daneshk** [comment]
The problem occurs if these two service definitions have the same input/output message definitions. If so, create a new proto file with those message definitions and add dependency in the service definition. but still, I see a problem with generated context record types.

**Comment by MadhukaHarith92** [comment]
@BuddhiWathsala we fixed repetitive variable generation in a single bal file in [[1]](https://github.com/ballerina-platform/ballerina-standard-library/issues/1404). IINM, the current problem is with the duplicate variables being generated in multiple bal files in the same module.  Let's say`hello1.proto` and `hello2.proto` had the services like below:

**hello1.proto**
```
service hello1 {
	rpc call1(google.protobuf.StringValue) returns (stream google.protobuf.StringValue);
}
```

**hello2.proto**
```
service hello2 {
	rpc call2(google.protobuf.StringValue) returns (stream google.protobuf.StringValue);
}
```

In this scenario, the below records will be generated in both files.
```
public type ContextStringStream record {|
    stream<string, error?> content;
    map<string|string[]> headers;
|};

public type ContextString record {|
    string content;
    map<string|string[]> headers;
|};
```

[1] https://github.com/ballerina-platform/ballerina-standard-library/issues/1404

**Comment by BuddhiWathsala** [comment]
I think, here also, we should remove that repetition. @daneshk WDYT?

**Comment by MadhukaHarith92** [comment]
@BuddhiWathsala I don't think removing those repetitions is practical here for a couple of reasons. 

1. Let's say we generated the bal file for `hello1.proto`. Then we need to scan the bal files in that module to check if any of them contains `ContextString` record. 
2. Even if we did that (remove `ContextString` from `hello2_pb.bal`), the user will not be able to delete `hello2_pb.bal` thereafter since it is tightly coupled to `hello1_pb.bal`.
3. This could lead to a chain of dependencies like `hello1_pb.bal` -> `hello2_pb.bal` -> `hello3_pb.bal`

Therefore it would be better if we keep the bal files in the same module independent from eachother.

**Comment by slahirucd7** [comment]
Is it possible to change `getDescriptorMap()` function's default visibility to `public`  (`public` access modifier)?
Ex : `public isolated function getDescriptorMap() returns map<string> {...}`
@BuddhiWathsala @MadhukaHarith92

**Comment by MadhukaHarith92** [comment]
> Is it possible to change `getDescriptorMap()` function's default visibility to `public` (`public` access modifier)?
> Ex : `public isolated function getDescriptorMap() returns map<string> {...}`
> @BuddhiWathsala @MadhukaHarith92

Yeah, it's possible. Will update.

**Comment by daneshk** [comment]
@slahirucd7 How you are going to structure the ballerina project?

**Comment by slahirucd7** [comment]
> @slahirucd7 How you are going to structure the ballerina project?
We are placing all the stubs generated in a separate module called `api`. Main service resides in the root directory (outside of ballerina modules folder).

**Comment by MadhukaHarith92** [comment]
We discussed having the following approach.

Single proto file:

No change to the current behavior, i.e for `hello1.proto` file `hello1_pb.bal` file will be generated **without** any changes to variable names.

Directory of proto files:

If the directory name is `choreo` and it contains 2 proto files; `hello1.proto`, `hello2.proto`. and the output-dir is `stubs`
```
choreo
├── hello1.proto
└── hello2.proto
```
The following bal files will be generated inside the `stubs` directory.
```
stubs
├── choreo_grpc_pb.bal
├── hello1_pb.bal
└── hello2_pb.bal
```
`choreo_grpc_pb.bal` will contain variables common to `hello1_pb.bal` and `hello2_pb.bal`.

The proto file name will be appended to`ROOT_DESCRIPTOR` and `getDescriptorMap` when running as a directory.

@praminda @slahirucd7 WDYT.

Shall we have the common bal file name as `<DIRECTORY_NAME>_grpc_pb.bal` @daneshk @BuddhiWathsala ?

**Comment by slahirucd7** [comment]
> We discussed having the following approach.
> 
> Single proto file:
> 
> No change to the current behavior, i.e for `hello1.proto` file `hello1_pb.bal` file will be generated **without** any changes to variable names.
> 
> Directory of proto files:
> 
> If the directory name is `choreo` and it contains 2 proto files; `hello1.proto`, `hello2.proto`. and the output-dir is `stubs`
> 
> ```
> choreo
> ├── hello1.proto
> └── hello2.proto
> ```
> 
> The following bal files will be generated inside the `stubs` directory.
> 
> ```
> stubs
> ├── choreo_grpc_pb.bal
> ├── hello1_pb.bal
> └── hello2_pb.bal
> ```
> 
> `choreo_grpc_pb.bal` will contain variables common to `hello1_pb.bal` and `hello2_pb.bal`.
> 
> The proto file name will be appended to`ROOT_DESCRIPTOR` and `getDescriptorMap` when running as a directory.
> 
> @praminda @slahirucd7 WDYT.
>  +1 for the above approach.

> Shall we have the common bal file name as `<DIRECTORY_NAME>_grpc_pb.bal` @daneshk @BuddhiWathsala ?
