### ISSUE TITLE
HATEOAS link support

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1637]
**Description:**
Can we have the below as part of HTTP library.

```ballerina
enum Methods {
    GET,
    POST,
    PUT,
    DELETE,
    PATCH
}

type Link record {|
    string rel;
    string href;
    string[] types?;
    Methods[] methods;
|};

type Links record {|
    Link[] links;
|};

```

Then we can use it as below,

```ballerina
type Location record {|
    *Links;
    string name;
    string id;
    string address;
|};
```

**Comment by chamil321** [comment]
Some improvement on the suggestion
1.  Add `HEAD` and `OPTIONS` as enums
2.  Make `Link` record an open record as there can be many other field. Otherwise payload binding can be failed.
```JSON
"links" : [
    {
      "rel": "search",
      "href": "/products",
      "schema": {
        "type": "object",
        "properties": {
          "size": { "enum": ["xs", "m"] },
          "priceGreaterThan": { "type": "number" },
          "priceLessThan": { "type": "number" }
        }
      }
    }
  ]
  ```
  3. Make `Action[] actions;` field also optional

**Comment by shafreenAnfar** [comment]
In addition to adding the record shall we also check what next steps we can take. The below is a good start.

https://docs.spring.io/spring-hateoas/docs/current/reference/html/

**Comment by shafreenAnfar** [comment]
[HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) and [Siren](https://github.com/kevinswiber/siren) both talk about adding hypelinks to JSON format document but none of them seems to be popular.

**Comment by chamil321** [comment]
@TharmiganK, we have a requirement to move the API doc description of each record field inside the record. Shall we do that? 
Eg: 
https://github.com/ballerina-platform/module-ballerina-http/blob/example/examples/snowpeak/service/modules/representations/representations.bal#L48

**Comment by IMS94** [comment]
@shafreenAnfar @chamil321 Do we have support for [links in headers](https://datatracker.ietf.org/doc/html/rfc5988#section-5)? If not, is there a plan to implement that?

**Comment by TharmiganK** [comment]
With the [`Proposal: Introducing Initial Support for HATEOAS #2391`](https://github.com/ballerina-platform/ballerina-standard-library/issues/2391), the initial support is provided with the Links.

Hence closing the issue
