### ISSUE TITLE
Any type support in gRPC

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1647]
**Description:**
Need to support [gRPC Any type](https://github.com/protocolbuffers/protobuf/blob/7b1f7938bc89b2346582464dba2767891509d550/src/google/protobuf/any.proto).

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/43

**Comment by BuddhiWathsala** [comment]
The most suitable Ballerina type that we can represent gRPC `Any` type is `anydata`. Even the current CLI implementation generates `anydata` type for gRPC `Any` type. However, we need a mechanism to find out the message type because gRPC `Any` data is represented using two values:
1. type URL - URL representation of the message type
2. value - data as a byte sequence

Therefore, I think we need to generate another specific record for the `Any` data representation in Ballerina. Even other languages have their unique mechanisms to obtain the message type as in [here](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Any).

@daneshk any input for this?.

**Comment by BuddhiWathsala** [comment]
As per our previous discussions, we planned to use a predefined record to represent the protobuf `Any` type as follows.
```ballerina
public type Any record {|
    string type_url;
    anydata value;
|};
```

We need an API (called `pack`) like below to create this record when a server or client needs to generate the `Any` record before sending. 
```ballerina
import ballerina/protobuf.types.'any;

public isolated function pack(record{} rec) returns 'any:Any; 
```

However, there is confusion about whether we need an API to unpack or not. The possible API we can give here is:

```ballerina
public isolated function unpack('any:Any) returns anydata; 
```
But it won’t be really useful because, at the end of the day, users anyway have to do a typecast to get the specific message. Check the user experience with and without the `unpack` API.

#### With Unpack API
```ballerina
'any:Any anyValue = check client->callRpc();
Person p = <Person>grpc:unpack(anyValue);
```

#### Without Unpack API
```ballerina
'any:Any anyValue = check client->callRpc();
Person p = <Person>(anyValue.value);
```

@daneshk @shafreenAnfar @dilanSachi WDYT?. Do we need this `unpack` API.

**Comment by dilanSachi** [comment]
```ballerina
'any:Any anyValue = check client->callRpc();
Person p = grpc:unpack(anyValue, Person);
```

Can't we introduce something like this?

**Comment by BuddhiWathsala** [comment]
> ```ballerina
> 'any:Any anyValue = check client->callRpc();
> Person p = grpc:unpack(anyValue, Person);
> ```
> 
> Can't we introduce something like this?

@dilanSachi this `Person` type could be anything, so we cannot implement a generic API to do that kind of conversion.

**Comment by shafreenAnfar** [comment]
I am thinking if we should stick to the protobuf definition,

```ballerina
public type Any record {|
    string type_url;
    byte[] value;
|};
```
Because I think what we've been doing so far is going from proto definition to Ballerina. If we have `anydata` instead of the `byte[]` then it could include other types such as `table`, which could complicate things. 

If we stick to `byte[]`, then as in other languages we need `pack` and `unpack` or something similar. Also there is a possibility that, type needs to be fetched from a type server before unpacking, which could be implemented inside the unpack functions.

**Comment by BuddhiWathsala** [comment]
I'm not sure this will be convenient to implement in Ballerina. Using only bytes, we cannot easily generate the relevant record because unlike Java and Go, we don’t have descriptor level information in Ballerina record itself.

**Comment by BuddhiWathsala** [comment]
As a safe side for getting rid of tables, how about defining a new type that includes all the types that support by Any?

**Comment by shafreenAnfar** [comment]
> I'm not sure this will be convenient to implement in Ballerina. Using only bytes, we cannot easily generate the relevant record because unlike Java and Go, we don’t have descriptor level information in Ballerina record itself.

```ballerina
// Pack
Person p = {age:70, name:"Jo"};
grpc:Any pp = grpc:pack(p);

// Unpack
Person p = grpc:unpack(pp, Person);
```
We should be able to implement this right ?

**Comment by BuddhiWathsala** [comment]
According to an offline discussion, we have discussed introducing the following APIs to pack and unpack protobuf Any data.

Definitions in the `protobuf.types.any` submodule.

```ballerina
public type SubTypesOfAny int|float|string|boolean|time:Utc|time:Seconds|record{}|();
public type SubTypesOfAnyTypeDesc typedesc<SubTypesOfAny>;

public type Any record {|
    string type_url;
    SubTypesOfAny value;
|};

public isolated function pack(SubTypesOfAny value) returns Any;
public isolated function unpack(Any anyValue, SubTypesOfAnyTypeDesc targetTypeOfAny = <>) returns targetTypeOfAny;
```

Usages from the user perspective:

```ballerina
import ballerina/protobuf.types.'any;

// Pack
Person p = {age:70, name:"Jo"};
'any:Any pp = 'any:pack(p);

// Unpack
Person p = 'any:unpack(pp, Person);
```

Please provide your feedback on this.

**Comment by BuddhiWathsala** [comment]
Here is the proposal for Any type support. in Ballerina gRPC https://github.com/ballerina-platform/ballerina-standard-library/issues/2365
