### ISSUE TITLE
Add test cases for the issue when retrieving the timestamp value

### ISSUE THREAD

**Issue by Biruntha** [ballerina-platform/ballerina-standard-library#165]
**Description:**
When retrieving the timestamp value is not converted to current timestamp. Need to add test cases for this fix [1].

[1] ballerina-platform/ballerina-lang#16210

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
These are added and verified here, https://github.com/ballerina-platform/module-ballerina-sql/pull/161
