### ISSUE TITLE
Improve code coverage in oracledb module

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-standard-library#1656]
**Description:**
This task is to track the progress of the code coverage in the oracledb module. Currently, coverage is around 67%. We need to get this above 80%

**Suggested Labels (optional):**
module/oracledb

**Suggested Assignees (optional):**
Lahiru Malepathirana

**Comment by MadhukaHarith92** [comment]
Closing since the task is completed.
