### ISSUE TITLE
Need an API to get the current local time

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#1690]
**Description:**
ATM, `time` module  has an API to get the current UTC time but not the current local time. However, in `log` module the current local time is printed in log messages. Since there is no Ballerina API to get the current local time, a Java native function[[1]](https://github.com/ballerina-platform/module-ballerina-log/blob/master/native/src/main/java/io/ballerina/stdlib/log/Utils.java#L59) is being used as a workaround. It would be better if there was a Ballerina API this since we are planning to remove all Java native code from `log` module.

[1] https://github.com/ballerina-platform/module-ballerina-log/blob/master/native/src/main/java/io/ballerina/stdlib/log/Utils.java#L59

**Comment by BuddhiWathsala** [comment]
This issue is resolved with this fix https://github.com/ballerina-platform/module-ballerina-time/pull/337.

You can use the following sample to obtain the current local time.
```ballerina
import ballerina/time;

public function main() returns error? {

    time:Zone systemZone = check time:loadSystemZone();
    time:Civil currentSystemCivil = systemZone.utcToCivil(time:utcNow());
}
```
