### ISSUE TITLE
oauth2:OutboundOAuth2Provider is not renewing access token when downstream web API returns 403

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-standard-library#17]
**Description:**
We are using [Azure log analytics REST API](https://dev.loganalytics.io/documentation/Authorization/OAuth2) and authenticate requests using `client_credentials` grant type with https://login.microsoftonline.com as the token endpoint.
We noticed that Azure log analytics REST API returns an HTTP response with`403` status code and the below payload when the token is expired.
```
{
    "error": {
        "message": "The provided authentication is not valid for this resource",
        "code": "InvalidTokenError",
        "innererror": {
            "code": "InvalidTokenError",
            "message": "Could not validate the request. Challenge failed: TokenExpired"
        }
    }
}
```
Due to this (not received `401` response), the `oauth2:OutboundOAuth2Provider` is not attempting to renew the token, instead uses the same expired token.

**Affected Versions:**
Ballerina Swan Lake Preview 2

**Comment by ldclakmal** [comment]
@madushajg Shall we verify the issue with the attached `.jar` in SLP5?

[oauth2-ballerina-1.0.1.jar.zip](https://github.com/ballerina-platform/ballerina-standard-library/files/5443914/oauth2-ballerina-1.0.1.jar.zip)

**Comment by madushajg** [comment]
> @madushajg Shall we verify the issue with the attached `.jar` in SLP5?
> 
> [oauth2-ballerina-1.0.1.jar.zip](https://github.com/ballerina-platform/ballerina-standard-library/files/5443914/oauth2-ballerina-1.0.1.jar.zip)

Ack. Will verify with the provided jar.

**Comment by madushajg** [comment]
> @madushajg Shall we verify the issue with the attached `.jar` in SLP5?
> 
> [ballerina-oauth2-1.0.1.jar.zip](https://github.com/ballerina-platform/ballerina-standard-library/files/5446042/ballerina-oauth2-1.0.1.jar.zip)

@ldclakmal The issue is not there with the provided `.jar`

**Comment by ldclakmal** [comment]
This issue is fixed with https://github.com/ballerina-platform/module-ballerina-http/pull/142 and no longer valid with the new design.
