### ISSUE TITLE
Provide a better way to send with `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1705]
**Description:**
At the moment we need to do the following to send a request with `application/x-www-form-urlencoded`.

```ballerina
http:Client clientEp = check new ("https://sample.com");
string payload = string `key1=value1&key2=value2`;
string encodedPayload = check url:encode(payload, "UTF-8");
http:Response response = check checkclientEp->post("/update", encodedPayload, mediaType=mime:APPLICATION_FORM_URLENCODED);
```

It requires too much code and we need a better way.

**Comment by shafreenAnfar** [comment]
This can be easily improved as follows.

```ballerina
http:Response response = check snowpeak->post("/update", 
    {
        "key1": "value1",
        "key2": "value2"
    }, 
    mediaType=mime:APPLICATION_FORM_URLENCODED
);
```
Then the underline implementation can do the needful and send it to the back-end.

**Comment by shafreenAnfar** [comment]
I think we can improve the implementation a bit.

```ballerina
map<string> pairs = {
  "key1": "value1",
  "key2": "value2"
};
http:Response response = check snowpeak->post("/update", pairs);
```
If the code looks like the above, the user do not need to explicitly mention the media type. We can do a type checking for `map<string>` and default it to `x-www-form-urlencoded`.

This also means the below types also will fall under `x-www-form-urlencoded` instead of `json`

```ballerina
readonly & json j = {key1: "foo", key2: "bar"};
record {|
    string key1;
    string key2;
|} r = {key1: "foo", key2: "bar"};
record {|
    string...;
|} r = {"key1": "foo", "key2": "bar"};
```
80%  of the time `json` would include more than `string` type. Therefore, it shouldn't be a problem.

**Comment by shafreenAnfar** [comment]
This would also make the inbound and outbound implementations identical.

**Comment by shafreenAnfar** [comment]
The same applies for the service side as well. At the moment a service that consumers and produces `x-www-form-urlencoded` would look like the below.

```ballerina
// this maps to x-www-form-urlencoded
type KeyValueOk record {|
    *http:Ok;
    string mediaType = mime:APPLICATION_FORM_URLENCODED;
    map<string> body;
|};

service / on new http:Listener(9000) {
    resource function get foo(@http:Payload map<string> keyvalue) returns KeyValueOk {      
    }
}
```

**Comment by shafreenAnfar** [comment]
Currently, the default mapping for `map<string>` is `application/json`. Therefore, when generating OpenAPI for `x-www-form-urlecnoded` the service should be as follows.

```ballerina
// this maps to x-www-form-urlencoded
service / on new http:Listener(9000) {
    resource function get foo(@http:Payload { mediaType: mime:APPLICATION_FORM_URLENCODED} map<string> keyvalue) 
            returns @http:Payload { mediaType: mime:APPLICATION_FORM_URLENCODED} map<string> {
        
    }
}
```

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/module-ballerina-http/pull/968

Binding and the conversion happens based on the diagram of https://github.com/ballerina-platform/ballerina-standard-library/issues/2530#issuecomment-1011271021
