### ISSUE TITLE
Update the code snippets in Module.md after the SQL query return stream type change

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-standard-library#1717]
**Description:**
$title

**Describe your task(s)**
change the code snippets in the Module.md file after the change of adding completion type as nil in SQL query return stream type.

**Related Issues (optional):**
ballerina-platform/ballerina-standard-library#1654
ballerina-platform/ballerina-standard-library#1710

**Suggested Labels (optional):**
module/sql
module/java.jdbc
module/mysql
module/postgresql
module/mssql
module/oracledb

**Suggested Assignees (optional):**
Lahiru Malepathirana
Kalaiyarasi 
Kaneel Dias

**Comment by lahirusamith** [comment]
For oracledb, a separate issue was created so that this task for oracledb will be carried out separately  https://github.com/ballerina-platform/ballerina-standard-library/issues/1710

**Comment by daneshk** [comment]
@kalaiyarasiganeshalingam please check in PostgreSQL connector and close this issue
