### ISSUE TITLE
[Client] Open records cannot be passed to actions

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1719]
**Description:**
Consider the below client. if you make Reservation and Payment records open, it doesn't work.

https://github.com/ballerina-platform/module-ballerina-http/tree/example/examples/snowpeak/client

It gives the below error,

`ERROR [main.bal:(43:91,43:102)] incompatible types: expected 'ballerina/http:1.1.0-beta.2:RequestMessage', found 'snowpeak/client.representations:1.0.0:Reservation'`

**Comment by chamil321** [comment]
Root cause for this error is not allowing records in the RequestMessage. JSON compatible records (closed records) are passed as JSON.

**Comment by chamil321** [comment]
With the introduction of records, user cannot pass inline JSON as an argument
```ballerina
string res2 = check httpClient->post("/keepAliveTest2", { "name": "Ballerina" });
```
Error: `ambiguous type 'ballerina/http:1.1.0-beta.3:RequestMessage'`

Reason: The given input is compatible with both JSON and Record. Compiler cannot distingush it. So user has to be a bit specific
```ballerina
string res2 = check httpClient->post("/keepAliveTest2", <json> { "name": "Ballerina" });
```
Same issue was discussed in https://github.com/ballerina-platform/ballerina-lang/issues/30131

**Comment by chamil321** [comment]
By introducing `anydata` type we can avoid this ambiguity. I'll change the types accordingly as it is the end goal.
```ballerina
public type RequestMessage Request|anydata|byte[]|mime:Entity[]|stream<byte[], io:Error?>;
public type ResponseMessage Response|anydata|byte[]|mime:Entity[]|stream<byte[], io:Error?>;
```

**Comment by chamil321** [comment]
> By introducing `anydata` type we can avoid this ambiguity. I'll change the types accordingly as it is the end goal.
> 
> ```ballerina
> public type RequestMessage Request|anydata|byte[]|mime:Entity[]|stream<byte[], io:Error?>;
> public type ResponseMessage Response|anydata|byte[]|mime:Entity[]|stream<byte[], io:Error?>;
> ```

This change has a problem with a byte[] and xml being serialised as json. This could be solved with serdes implementation. Until that, if user wants to send open records, they has to make it json compatible and send.
1. Make exclusive record
2. Have json rest param in inclusive records 
3. Call .toJson() and pass as a json
