### ISSUE TITLE
Handle internal enum types without repetitions

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1735]
**Description:**
The stub generation of the following protobuf file has repeated enum values. Those repetitions should handle gracefully.

##### Proto file

```proto
syntax = "proto3";

message FileInfo {
    enum Type {
        UNKNOWN = 0;
        FILE = 1;
        DIRECTORY = 2;

    }
    Type type = 1;
}

message Log {
    enum Type {
        UNKNOWN = 0;
        STDOUT = 1;
        STDERR = 2;

    }
    Type type = 1;
}
```

##### Generated stub

```ballerina
public type FileInfo record {|
    Type 'type = UNKNOWN;
|};

public enum Type {
    UNKNOWN,
    FILE,
    DIRECTORY
}

public type Log record {|
    Type 'type = UNKNOWN;
|};

public enum Type {
    UNKNOWN,
    STDOUT,
    STDERR
}
```

 

**Steps to reproduce:**
Generate stub file using the aforementioned proto file.

**Affected Versions:**
Ballerina SL beta 2

**OS, DB, other environment details and versions:**
- Java 11
- macOS

**Comment by BuddhiWathsala** [comment]
I tried this with Golang and it seems they add the root message name for the generated value. 
```go
FileInfo_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "FILE",
	2: "DIRECTORY",
}
FileInfo_Type_value = map[string]int32{
	"UNKNOWN":   0,
	"FILE":      1,
	"DIRECTORY": 2,
}
```

@MadhukaHarith92 @daneshk @dilanSachi, I think we can follow the same approach.

**Comment by daneshk** [comment]
AFAIU, we follow a similar approach for nested messages in Ballerina

**Comment by MadhukaHarith92** [comment]
Suggested stub:
```
public type FileInfo record {|
    FileInfo_Type 'type = UNKNOWN;
|};

public enum FileInfo_Type {
    UNKNOWN,
    FILE,
    DIRECTORY
}

public type Log record {|
    Log_Type 'type = UNKNOWN;
|};

public enum Log_Type {
    UNKNOWN,
    STDOUT,
    STDERR
}
```

@daneshk , @BuddhiWathsala WDYT

**Comment by MadhukaHarith92** [comment]
**Update**: Please note that the field names of the enums need to have the message name as the prefix. Otherwise, a redeclared symbol error will be thrown (`UNKNOWN` in this case). So the correct stub file would look like the following:

```
public type FileInfo record {|
    FileInfo_Type 'type = FileInfo_Type_UNKNOWN;
|};

public enum FileInfo_Type {
    FileInfo_Type_UNKNOWN,
    FileInfo_Type_FILE,
    FileInfo_Type_DIRECTORY
}

public type Log record {|
    Log_Type 'type = Log_Type_UNKNOWN;
|};

public enum Log_Type {
    Log_Type_UNKNOWN,
    Log_Type_STDOUT,
    Log_Type_STDERR
}
```

**Comment by daneshk** [comment]
@MadhukaHarith92 redeclare issue is fixed in language with ballerina-platform/ballerina-lang#31485. we should be able to define it now

**Comment by MadhukaHarith92** [comment]
> @MadhukaHarith92 redeclare issue is fixed in language with [ballerina-platform/ballerina-lang#31485](https://github.com/ballerina-platform/ballerina-lang/issues/31485). we should be able to define it now

Ack. Updated as in the initial stub example.
