### ISSUE TITLE
gRPC builds fails due to ballerina stream type change

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#1745]
**Description:**
The build fails due to outdated return type in [`streaming_client.bal`](https://github.com/ballerina-platform/module-ballerina-grpc/blob/a572dfdc7b44a325e715285c578a9392e673054a/ballerina/streaming_client.bal#L128)

**Steps to reproduce:**
Build the module with the latest dependency update
**Affected Versions:**
SL Beta 3

**Suggested Labels (optional):**
module/grpc

**Suggested Assignees (optional):**
@dilanSachi

**Comment by daneshk** [comment]
This issue is fixed in the master branch, hence closing this issue
