### ISSUE TITLE
Feature Request: Support variable types other than records for JDBC select

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-standard-library#175]
**Description:**
Following code fragment will not compile.
```ballerina
var result = dbClient->select("SELECT id from mytable where user_id = ?", int, 20);
```
it gives me an error like this:
```
incompatible types: expected 'typedesc<record {| anydata...; |}>?', found 'typedesc<int>'

```
I think this is something we should support.

**Affected Versions:**
v1.2.8

**Suggested Assignees (optional):**
@niveathika @anupama-pathirage

**Comment by niveathika** [comment]
@ramith FRom Swanlake version onwards we are returning a stream from DB query. However, as per the stream spec, we can only return a record from the stream and not ballerina basic types
