### ISSUE TITLE
Review SQL Errors and Error Hierarchy

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#1758]
**Description:**
Currently, SQL modules support the following Error types,

1. Application Error: Any data mismatches, configurations issues, the client already closed issues 
2. Database Error: Anything other than Application Error is considered as Database Errors
3. NoRowsError: When queryRow returns an empty result set
4. BatchExecuteError: Execution failed during batch execute

In my opinion, this is disorganized and the user has to parse the error message to take the required action.

I have reviewed the Error scenarios in SQL modules and have come up with a draft proposal,

1. DatabaseError - This is used to indicate any errors from the database side, such as connection issues, specific operations not supported by the drivers, SQL syntax errors, Constraint violation. (In a log run we can create types for each of these scenarios)
2. NoRowsError: Execution of queryRow failure with an empty result set returned
3. BatchExecuteError: Execution failed during batch execute
4. ApplicationError: This is to indicate configuration/usage issues such as (Call Query Number of typedesc does not match, Invalid Configurations like URL, Operation on closed stream/closed client)
    - DataError: Errors during the processing of the returned data or parameters. (Moved inside ApplicationError for compatibilty issues)
        - TypeMismatchError - The returned result is of a different type than what the user expected. For instance, string type cannot be matched to time type.
        - ConversionError - The returned result is of expected type but the error occurs due to corrupted data (Json conversion, XML conversion, String to time)
        - FieldMismatchError - The returned data cannot be converted to the expected record. For instance, the returned data has a lower number of fields
        - UnsupportedTypeError - The parameter is not supported for the query. (If the user extends the Value and send it through the API

**Comment by kaneeldias** [comment]
Would it make sense to move `NoRowsError` into `DataError`? Having a separate type of that specific scenario doesn't seem right. 

+1 for everything else.

**Comment by daneshk** [comment]
+1 to splitting Error types, but we also need to think of doing it without breaking the existing code. We may have to make `DataError` as a subset of `ApplicationError` to avoid breaking the existing code.

**Comment by kalaiyarasiganeshalingam** [comment]
Do we need both `TypeMismatchError` and `UnsupportedTypeError` under the `DataError`? There seems to be a connection between these. If type mismatch,  Can not be considered an unsupported type?

**Comment by niveathika** [comment]
@kaneeldias Yes even though it can be a subtype, I wanted to specifically differentiate it since this can only happen with the queryRow API.

@daneshk I will update the hierarchy

@kalaiyarasiganeshalingam I wanted to differentiate between parameters and returned results. `UnsupportedTypeError` is only used for parameters passed in the query and `TypeMismatch` only occurs for results conversions.

**Comment by niveathika** [comment]
Since the design is accepted following tasks are pending,

- [ ] Introduce the improved error hierarchy API
- [ ] Improve native code design to include the improved error types
- [ ] Review Error messages in SQL modules

**Comment by niveathika** [comment]
Closing this issue as design is finalised and separate issues have been opened to track the implementation of the design.
