### ISSUE TITLE
Avoid java class names printed as error message in DB connectors

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-standard-library#1775]
**Description:**
$title since some error messages have java class names printed in all db connectors as all db connectors have extended the sql module

Eg: 

When trying to connect an oracle database server using ssl connection and If the user give a wrong cert file to connect to the server, An error message is coming

```
Error in SQL connector configuration: Failed to initialize pool: IO Error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException
```
as this error message is originated in 

https://github.com/ballerina-platform/module-ballerina-sql/blob/feb050d02ace978178fcb2ae2416358c47a7edb0/native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java#L354

**Steps to reproduce:**

**Affected Versions:**
0.6.0-beta.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
module/sql

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
Fixed in https://github.com/ballerina-platform/module-ballerina-sql/pull/421
