### ISSUE TITLE
Create example for JDBC connector using Snowflake

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#1793]
**Description:**
Create a real-world example of using the jdbc connector to connect to the [Snowflake](https://www.snowflake.com/) API and perform standard operations.

**Suggested Labels (optional):**
module/java.jdbc

**Suggested Assignees (optional):**
@kaneeldias

**Comment by daneshk** [comment]
Reference:
https://docs.snowflake.com/en/api-reference.html 
https://docs.snowflake.com/en/user-guide-getting-started.html 
https://docs.snowflake.com/en/user-guide/jdbc.html
