### ISSUE TITLE
Implement immediateStop in HTTP listener

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-standard-library#1794]
**Description:**
Currently, the listener's `immediateStop` method is not implemented. Need to do a feasibility study on this.

**Comment by Bhashinee** [comment]
In the implementation, as per the [current design](https://github.com/ballerina-platform/module-ballerina-http/blob/master/native/src/main/java/io/ballerina/stdlib/http/api/DefaultHttpWsConnectorFactoryHolder.java#L27), we are using a shared boss and worker EventLoopGroups over all the listeners as well as clients.

As per Netty documentation, in order to shut down a Netty application, you need to shut down the EventLoopGroup. As we have been sharing this eventloop group among other listeners and clients, it is not possible to shutdown it immediately.

It is not possible to create eventloopgroups per listener as it can result in an issue similar to [this](https://github.com/ballerina-platform/ballerina-lang/issues/24705).

**Comment by shafreenAnfar** [comment]
I think what we need to do is instead of sharing the EventLoop group, we should share the thread pool.  It seems we can do that by sharing a thread executor pool.

https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoopGroup.java#L72

**Comment by chamil321** [comment]
> I think what we need to do is instead of sharing the EventLoop group, we should share the thread pool. It seems we can do that by sharing a thread executor pool.
> 
> https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoopGroup.java#L72

Once the suggestion was implemented(Share  instead of EventLoop group), local build facing `Too many open files` issue. According to a similar issue[1], this behaviour is seen when multiple event loop groups were created. 

[1] https://github.com/netty/netty/issues/639#issuecomment-9167403

**Comment by chamil321** [comment]
> > I think what we need to do is instead of sharing the EventLoop group, we should share the thread pool. It seems we can do that by sharing a thread executor pool.
> > https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoopGroup.java#L72
> 
> Once the suggestion was implemented(Share instead of EventLoop group), local build facing `Too many open files` issue. According to a similar issue[1], this behaviour is seen when multiple event loop groups were created.
> 
> [1] [netty/netty#639 (comment)](https://github.com/netty/netty/issues/639#issuecomment-9167403)

As the proper solution, closed the socket pipeline of the server channel initializer after sharing the Eventloop groups again.

Sorted https://github.com/ballerina-platform/ballerina-standard-library/issues/2990
