### ISSUE TITLE
Improve Error message description in SQL to be more user friendly

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#1807]
**Description:**
$subject as discussed in https://github.com/ballerina-platform/ballerina-standard-library/issues/1758

**Comment by daneshk** [comment]
Related issue #1775

**Comment by niveathika** [comment]
This is based on https://github.com/ballerina-platform/ballerina-standard-library/issues/1806

Following connectors need to be updated based on the improve error types,

- [ ] jdbc
- [ ] mysql
- [ ] mssql
- [ ] postgresql
- [ ] Oracle

**Comment by niveathika** [comment]
Closing this as all connectors are updated.
