### ISSUE TITLE
Generated unique-service-path should not be changed after compilation

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#1813]
**Description:**
In `websub:SubscriberService` we would generate a unique, random service path if the service path is not specified by the user. But currently generated service path is dynamic and it will change time to time when we stop and restart the `websub:SubscriberService`.

**Solution**
It would be better if we could generate this at compile-time and cache it. Then we could use it whenever we run the service and the service-path will not change when ever we re-start the service.

**Describe your task(s)**
We would implement this feature by writing compile-time generated service-path to `service-info.csv` file and packing it to ballerina executable jar. Then we would use this information at runtime to bind the `websub:SubscriberService` to generated service-path.
- [x] Improve WebSub compiler plugin to generate `service-info.csv` file and pack it to executable jar.
  - [x] Generate unique-service path and add that information to `service-info.csv` file.
  - [x] Pack generated `service-info.csv` file into ballerina executable jar.
- [x] Read `service-info.csv` file at runtime and attach `websub:SubscriberService` to generated service-path if user has not provided service path information.

**Comment by ayeshLK** [comment]
Since we there could be scenarios where developer could implement multiple-subscriber services in one ballerina project, we might need to provide information to identify which service-path for which service. Hence, `service-info.txt` will contain CSV and file name will be changed to `service-info.csv`.

**Comment by shafreenAnfar** [comment]
Isn't this problem the same as the problem we had in HTTP implementation ?

**Comment by ayeshLK** [comment]
Yes, that is why we need to use this.
