### ISSUE TITLE
Check the oracle DB client supports array type manipulation

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#1816]
**Description:**
$Subject

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-standard-library/issues/124

**Comment by lahirusamith** [comment]
as go through the code, It is found that in oracledb module, it uses a complex object to support arrays implementation but this current design  need to be changed to support these mix type array support in oracledb module.

**Comment by lahirusamith** [comment]
PR is merged. Hence closing the issue.
