### ISSUE TITLE
Verify the impact on gRPC runtime with protobuf package changes

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#1824]
**Description:**
We need to verify the impact on gRPC runtime with protobuf package changes.

Related PR: ballerina-platform/module-ballerina-grpc#403

**Describe your task(s)**
Related issue: #1635

* Add/Modify test cases to check the impact of this change

**Comment by MadhukaHarith92** [comment]
Closing this issue since the task is completed.
