### ISSUE TITLE
Revisit the license of the modules when the external JARs are packed

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#1829]
**Description:**
Need to revisit the compatibility of license of the modules when external JARs are shipped with the module. 
Need to update the `license` field of 'Ballerina.toml' (which will be shown at Ballerina Central) and the `LICENSE` file of the GitHub repository.

**Comment by aashikam** [comment]
Kafka, NATS and NATS streaming java clients are under Apache 2.0 license. 
NATS: https://github.com/nats-io/nats.java/blob/main/LICENSE 
NATS Streaming: https://github.com/nats-io/stan.java/blob/master/LICENSE
Kafka: https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients/2.8.0

RabbitMQ java client is [triple licensed](https://github.com/rabbitmq/rabbitmq-java-client/blob/main/LICENSE). This is currently under discussion.

**Comment by niveathika** [comment]
MySQL driver license is verified as in https://github.com/ballerina-platform/module-ballerinax-mysql.driver/issues/15

**Comment by niveathika** [comment]
Closing this as all license conflicts are verified.
