### ISSUE TITLE
Getting same element name twice in JSON output of xmldata module toJson function

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-standard-library#1842]
**Description:**
When the following xml is converted to json using `toJson` function of the xmldata module , it provides an output as follows.
1. when we remove all namespaces with prefixes : no repetitively named objects
2. when we add namespaces
it gives output like this
``` xml element = xml `<xmlns_prefix:A><xsi:B>test_Value</xsi:B></xmlns_prefix:A>`;
json value = check xmldata:toJson(element, {preserveNamespaces: false}); ```
 output:
``` {"A":{"B":{"B":"test_Value","@xsi":"test.com"}},"@xmlns_prefix":"wso2.com"} ```

**Steps to reproduce:**
1. Use the above-mentioned ballerina code and print output.

**Affected Versions:**

Ballerina Swan Lake Beta2

**OS, DB, other environment details and versions:**
Ubuntu

**Comment by kalaiyarasiganeshalingam** [comment]
Closing this issue as this is fixed and [tested](https://github.com/ballerina-platform/module-ballerina-xmldata/blob/master/ballerina/tests/xml_to_json_test.bal#L352) now.
