### ISSUE TITLE
Unable to retrieve binary payload from large file response

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/ballerina-standard-library#1846]
**Description:**
Unable to retrieve binary payload from ~5MB file response using `getBinaryPayload`.  This is an intermittent error.

Error log
``` 
error("Error occured while accessing binary content from the http response",error GenericClientError 
("Error occurred while retrieving the binary payload from the response", error ParserError ("Error occurred while 
extracting content from message : Idle timeout triggered while reading inbound response entity body")))
```
Identified following records in the Wireshark.
![image](https://user-images.githubusercontent.com/24509926/131656706-13f4dc5e-b382-4f67-a7c1-b1a01c500391.png)

**Steps to reproduce:**

- Upload a large file(>5MB) in an AWS S3 bucket and call [getObject()](https://github.com/ballerina-platform/module-ballerinax-aws.s3/blob/2f22a2b75225ef397d39641c0bad7a6b2e134512/s3/client.bal#L166) method
- This [getObject()](https://github.com/ballerina-platform/module-ballerinax-aws.s3/blob/2f22a2b75225ef397d39641c0bad7a6b2e134512/s3/client.bal#L166) method internally uses `getBinaryPayload` to retrieve the payload from the response.

```ballerina
import ballerina/log;
import ballerina/lang.'string as strings;
import ballerinax/aws.s3;

string accessKeyId = "";
string secretAccessKey = "";
string region = "";
string bucketName = "";

s3:ClientConfiguration amazonS3Config = {
    accessKeyId: accessKeyId,
    secretAccessKey: secretAccessKey,
    region: region
};

s3:Client amazonS3Client = check new (amazonS3Config);

public function main() returns error? {
    var getObjectResponse = amazonS3Client->getObject(bucketName, "large.csv");
    if (getObjectResponse is s3:S3Object) {
        log:printInfo(getObjectResponse.toString());
        byte[]? byteArray = getObjectResponse["content"];
        if (byteArray is byte[]) {
            string content = check strings:fromBytes(byteArray);
            log:printInfo("Object content: " + content);
        }
    } else {
        log:printError("Error: " + getObjectResponse.toString());
    }
}
```

**Affected Versions:**
SL Beta2

**Related Issues (optional):**
https://github.com/wso2-enterprise/choreo/issues/7935

**Comment by chamil321** [comment]
@Chuhaa Thanks for the info. By any chance can we get a complete wireshark record from Client SYN?

**Comment by Chuhaa** [comment]
Please find the complete Wireshark record [here](https://drive.google.com/file/d/1VGFov-cfLyxPwyW12n2CQYLppUUyaAOG/view?usp=sharing)
