### ISSUE TITLE
Design for Directives in GraphQL Queries

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#1852]
**Description:**
Sub task of: [#741](https://github.com/ballerina-platform/ballerina-standard-library/issues/741)

**Comment by DimuthuMadushan** [comment]
# Design for GraphQL Directives
## GraphQL Directives
Directives provide a way to describe alternate runtime execution and type validation behavior in a GraphQL document. Directives can be used to
* conditionally including or skipping a field during execution
* describe additional information for types, fields, fragments and operations
(Ex: new configurable execution capabilities of future versions)

There are two different types of directives depending on the location of use.
1. Query type - directives applicable in [TypeSystemDirectiveLocation](https://spec.graphql.org/June2018/#ExecutableDirectiveLocation)
2. Schema type - directives applicable in [ExecutableDirectiveLocation ](https://spec.graphql.org/June2018/#TypeSystemDirectiveLocation)

Schema type directives are defined in the schema and executed when building the schema. Query type directives are visible to the user and can be accessed through the query. More details on GraphQL directives can be found [here](https://spec.graphql.org/June2018/#sec-Type-System.Directives).

#### Default directives in GraphQL
1. [Skip](https://spec.graphql.org/June2018/#sec--skip)
2. [Include](https://spec.graphql.org/June2018/#sec--include)
3. [Deprecated](https://spec.graphql.org/June2018/#sec--deprecated)

# Implementation
As the first step, here we proposed a design for default directives ```skip``` and ```include```.

## Design for __skip__ and __include__ directives
**Skip** and **Include** directives can be used to conditionally exclude or include fields, fragment spreads, and inline fragments. Currently these two directives can be handled within the validation phase in ballerina GraphQL.

* Users can define the queries including directives as in the spec.
```graphql 
{
    getTeacher($skipName: Boolean! = true) {
        name @skip(if: $skipName)
        email
        subject
    }
}
```
* Do not need to explicitly define the “skip” and “include” directives since these are supported as defaults directives.
* In the parser, validate any directives that are defined. 
* Create a directive node and put it in the field node which defines the directive. An array will be added to the field node to keep the directives of that field.
* According to the spec these two types can be used only with `FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT` locations. Currently we have a set of directive locations in the `DirectiveLocations` type.

Ex: Directive node:
```bal
public class Directive {

    private string name;
    private Location location;
    private ArgumentNode[] argumentNodes;
    private DirectiveLocations[] directiveLocations;

    public isolated function init(string name, Location location) {
        self.name = name;
        self.location = location;
        self.argumentNodes = [];
        self.directiveLocations = [];
    }

    public isolated function getName() returns string {
        return self.name;
    }

    public isolated function getLocation() returns Location {
        return self.location;
    }

    public isolated function addArgument(ArgumentNode argNode) {
        self.argumentNodes.push(argNode);
    }

    public isolated function getArguments() returns ArgumentNode[] {
        return self.argumentNodes;
    }

    public isolated function addDirectiveLocation(DirectiveLocation dirLocation) {
        self.directiveLocations.push(dirLocation);
    }

    public isolated function getDirectiveLocations() returns DirectiveLocations[] {
        return self.directiveLocations;
    }

}
```
* To validate the directives, add a new class `DirectiveValidator` and include the validation logic within this. In validation, the directive name and the argument value are checked and according to the argument value skipped fields can be removed in this phase.
* Since we support only “skip” and “include” directives, other directives defined in the query are invalidated in this phase and return error.(Ex: “User specific directives are not supported yet”)
* After this validation phase, queries do not include any directives. There for after this phase, query will be executed as general query.

### Complete Example
Schema
```bal
type Teacher record {
      string name;
      string email;
      string subject;
};

Teacher T1 = {
      name: “Walter”,
      email: “Walter@gmail.com”,
      subject: “chemistry”
}

Teacher T2 = {
      name: “Watson”,
      email: “Watson@gmail.com”,
      subject: “science”
}

service /graphql on new graphql:Listener(9090) {
    resource function get getTeacher() returns Teacher[] {
         return [T1,T2];
    }
}
```
Document
```graphql
{
    getTeacher($skipName: Boolean! = true) {
        name @skip(if:$skipName)
       email
       subject
    }
}
```
Response
```json
{
  "data": {
    "getTeacher": [
      {
          "email": "Walter@gmail.com",
          "subject": "chemistry"
      },
      {
          "email": "Watson@gmail.com",
          "subject": "science"
      }
    ]
  }
}
```

**Comment by ThisaruGuruge** [comment]
Closing the issue since this is now completed.
