### ISSUE TITLE
No informative logging available for http services and authentication (jwt/oauth2)

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-standard-library#1859]
**Description:**
I was trying to implement the following scenario. 
1. Use WSO2 IS to obtain a JWT
2. Use that JWT to authenticate the following http service

First, due to wrong configuration at IS side, my JWT authentication failed. Then, the scope validation failed since my scope claim was an array and there's a limitation in beta 2. In both cases, I had to do trail and error blindly for a long time to fix the issue since there wasn't any log output. IMO, logs are needed to investigate and fix configuration issues.

As per the observation, when `OAuth2` authentication was used, it atleast printed that the validation failed (just mentioned that calling introspection endpoint failed). But the `JWT` validator did not print anything.

```ballerina
@http:ServiceConfig{
    auth: [
        {
            jwtValidatorConfig: {
                signatureConfig: {
                    certFile: "./is.cert"
                },
                scopeKey: "groups"
            },
            scopes: ["manager"]
        }
        // {
        //     oauth2IntrospectionConfig: {
        //         url: "https://localhost:9443/oauth2/introspect",
        //         clientConfig: {
        //             customHeaders: {"Authorization": "Basic YWRtaW46YWRtaW4="},
        //             secureSocket: {
        //                 // disable: true
        //                 cert: "./is.cert"
        //             }
        //         }
        //     },
        //     scopes: ["openid"]
        // }
    ]
}
isolated service /products on new http:Listener(8080) {

    private mysql:Client? cl = ();

    resource function get .() returns Product[]|error? {
        mysql:Client mysqlClient = check self.getClient();
        stream<Product, error?> prodStream = mysqlClient->query("select id, product_name as productName, price, currency from products", Product);
        Product[] products = [];
        error? e = prodStream.forEach(function(Product p) {
            products[products.length()] = p;
        });

        if e is error {
            return e;
        }

        log:printDebug("Found products", products = products);

        return products;
    }
}
```

Appreciate if this can be addressed soon.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 2

**Comment by chamil321** [comment]
@IMS94 Is this about not having proper tracelogs to trace the internal requests and responses? If so, that is brought back for beta 3 via https://github.com/ballerina-platform/module-ballerina-http/pull/528.

**Comment by chamil321** [comment]
Talked to @IMS94 his requirement is solved 50% by the HTTP tracelogs. Rest should come from Auth error handling flow.

**Comment by ldclakmal** [comment]
As per the offline discussion with @IMS94 the developer experience for authorization phase can be further improved with adding debug logs. That need to be addressed.
