### ISSUE TITLE
module-ballerina-grpc: can't dynamically attach a gRPC service to an gRPC listener

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-standard-library#1868]
**Description:**
Can't dynamically assign a gRPC service to an gRPC listener.

**Steps to reproduce:**

```bash
# clone demo repository
$ git clone https://bitbucket.org/gubaer/ballerina-issue-dynamic-grpc.git
$ cd ballerina-issue-dynamic-grpc

# building and/or compiling works 
$ bal build  
# OK

$ bal build -c
# OK

# running fails with an error message
$ bal run
grpc_sample_generate: starting grpc service on 'localhost:10001'
failed to attach listener - error InternalError ("Error while registering the service. Couldn't find the service descriptor.")
error: Error while registering the service. Couldn't find the service descriptor.
	at ballerina.grpc.0_8_0-beta_2:externRegister(service_endpoint.bal:137)
	   ballerina.grpc.0_8_0-beta_2.Listener:attach(service_endpoint.bal:66)
	   gubaer.grpc_sample_dynamic.0_0_1:runServer(main.bal:24)
	   gubaer.grpc_sample_dynamic.0_0_1:main(main.bal:41)
```

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Linux integrationbox 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by BuddhiWathsala** [comment]
@Gubaer, it seems the way you set the gRPC descriptors was incorrect. Please check the following sample on how to dynamically attach a gRPC service object to a listener.

- [Service implementation](https://github.com/ballerina-platform/module-ballerina-grpc/blob/3e286c18abd62243ed8755f5050dddc33240f4bd/ballerina-tests/tests/20_unary_client_for_anonymous_service.bal#L21)
- [Service attachment](https://github.com/ballerina-platform/module-ballerina-grpc/blob/3e286c18abd62243ed8755f5050dddc33240f4bd/ballerina-tests/tests/20_unary_client_for_anonymous_service_client.bal#L24)

**Comment by Gubaer** [comment]
Thanks. My bad. Works for me now.
