### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException thrown when creating a Table from a CSV file

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-standard-library#1871]
**Description:**
java.lang.ArrayIndexOutOfBoundsException is thrown when creating a Table from a CSV file. 

![Screenshot from 2021-09-06 10-16-27](https://user-images.githubusercontent.com/1388997/132162006-4bca77ec-eb2f-4aa0-ba91-804e8f73c691.png)

The sample code which threw this exception is shown below.

```
import ballerina/http;
import ballerina/io;

const int NUMBER_OF_COLUMNS_IN_CSV = 2;

type LibraryCatalogRecordSummary record {|
    string show_id;
    string type_of_media;
    string title;
    string director;
    string cast;
    string country;
    string date_added;
    string release_year;
    string rating;
    string duration;
    string listed_in;
    string description;
|};

service / on new http:Listener(8090) {
    resource function get count() returns string|error {
        io:ReadableByteChannel|error summaryChannel = io:openReadableFile("movies-tv-shows.csv");
        if (summaryChannel is io:ReadableByteChannel) {
            byte[] byteArray = check summaryChannel.readAll();
            io:ReadableCharacterChannel readableCharacterChannel = new (check io:createReadableChannel(byteArray), "UTF-8");
            io:ReadableCSVChannel csvChannel = new (readableCharacterChannel, io:COMMA, 0);

            table<LibraryCatalogRecordSummary> tblResult = <table<LibraryCatalogRecordSummary>>check csvChannel.getTable(LibraryCatalogRecordSummary);

            int tvShowCount = 0;
            error? e = tblResult.forEach(function(LibraryCatalogRecordSummary entry) {
                if entry.type_of_media.equalsIgnoreCaseAscii("TV Show") && entry.country.equalsIgnoreCaseAscii("United States") {
                    tvShowCount += 1;
                }
            });

            return string `The CSV file contains the information of ${tvShowCount} TV shows from the United States.`;
        } else {
            return error("Error: unexpected content");
        }
    }
}

```

**Steps to reproduce:**
- Create a new Ballerina file (e.g., `sample.bal`) with the above code
- Copy the attached CSV file ([movies-tv-shows.csv](https://github.com/ballerina-platform/ballerina-standard-library/files/7113377/movies-tv-shows.csv)) to the same location
- Run the Ballerina file (i.e., `bal run sample.bal`)
- Invoke the connection using curl (e.g., `curl http://localhost:8090/count`)

**Affected Versions:**
- Ballerina Swan Lake Alpha 5.11
- Ballerina Swan Lake Beta 2

**OS, DB, other environment details and versions:**
Ubuntu 20.04, JDK 11.0.8

**Related Issues (optional):**
N/A

**Comment by kaneeldias** [comment]
Issue is due to a table being created without a key. The `[table.forEach()](https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.table/src/main/java/org/ballerinalang/langlib/table/Foreach.java#L56)` method requires the key field(s) to be specified.

**Comment by kaneeldias** [comment]
The current implementation of tables do not support creating one without a key. The above error is due to `io:ReadableCSVChannel:getTable()` being called without specifying the key fields. 

In order to avoid similar confusions in the future, the `getTable()` API has been deprecated and `toTable()` has been introduced, making the `keyFieldNames` parameter mandatory.
