### ISSUE TITLE
Convert all string queries to parameterized queries

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#1880]
**Description:**
$subject. we need to change all string query usages in test cases, examples, BBEs, API documentation to parameterized queries.

We need to depreciate the use of string queries in the DB connector documentation.

**Comment by niveathika** [comment]
@kaneeldias @lahirusamith Shall we verify if the bbes also do not use strings and close this?

**Comment by kaneeldias** [comment]
JDBC BBEs do not have any string usages in queries.

**Comment by lahirusamith** [comment]
@niveathika MySQL BBEs do not have any string query usages as well

**Comment by niveathika** [comment]
Closing this as all the tasks are done.
