### ISSUE TITLE
[GraphQL] Context support is needed for graphQL library

### ISSUE THREAD

**Issue by yashodgayashan** [ballerina-platform/ballerina-standard-library#1906]
**Description:**
Currently graphQL is not support contexts and it is impossible to pass any metadata for the query through the request. 

**Describe your problem(s)**
In Choreo project concept, graphQL server is user to query and mutate data using another gRPC and REST calls. For those gRPC calls we need some parameters to be passed which should be injected as context (metadata) to the graphQL server.

**Describe your solution(s)**
Provide context support for graphQL

**Related Issues (optional):**
https://github.com/wso2-enterprise/choreo/issues/8087

**Suggested Labels (optional):**
GraphQL

**Suggested Assignees (optional):**

**Comment by shafreenAnfar** [comment]
I think this is a good proposal to start with. A few things to consider would be as follows. 

Instead of `updateContext`  what if we have `initContext` as below,

```ballerina
public function initContext(http:RequestContext rctx, http:Request req) returns graphql:Context|Error
```
I think it improves the code readability a bit compared to `updateContext`.  As the function pointer default value, we can have a function which simply returns the vanilla context. 

> **Note**: RequestContext is not implemented yet but proposed [here](https://github.com/ballerina-platform/ballerina-standard-library/issues/692#issuecomment-916936087). We are planning to implement it in the next sprint.

For the context, it is better to let users pass isolated objects and functions as well. Basically it opens up more possibilities for users. 

```ballerina
public isolated class Context {
    private final map<value:Cloneable|isolated object {}> attributes = {};

    public isolated function add(string 'key, value:Cloneable|isolated object {} value) {
        if value is value:Cloneable {
            lock {
                self.attributes['key] = value.clone();
            }
        }
        else {
            lock {
                self.attributes['key] = value;
            }   
        }
    }

    public isolated function get(string 'key) returns value:Cloneable|isolated object {} {
        lock {
            return self.attributes.get('key);
        }
    }

    public isolated function remove(string 'key) {
        lock {
            value:Cloneable|isolated object {} _ = self.attributes.remove('key);
        }
    }
}
```
> ** Note **: `value:Cloneable` includes isolated function pointers and `error` type as well.

**Comment by ThisaruGuruge** [comment]
> I think this is a good proposal to start with. A few things to consider would be as follows.
> 
> Instead of `updateContext` what if we have `initContext` as below,
> 
> ```ballerina
> public function initContext(http:RequestContext rctx, http:Request req) returns graphql:Context|Error
> ```
> 
> I think it improves the code readability a bit compared to `updateContext`. As the function pointer default value, we can have a function which simply returns the vanilla context.

+1. This is better.
> 
> > **Note**: RequestContext is not implemented yet but proposed [here](https://github.com/ballerina-platform/ballerina-standard-library/issues/692#issuecomment-916936087). We are planning to implement it in the next sprint.
> 
> For the context, it is better to let users pass isolated objects and functions as well. Basically it opens up more possibilities for users.
> 
> ```ballerina
> public isolated class Context {
>     private final map<value:Cloneable|isolated object {}> attributes = {};
> 
>     public isolated function add(string 'key, value:Cloneable|isolated object {} value) {
>         if value is value:Cloneable {
>             lock {
>                 self.attributes['key] = value.clone();
>             }
>         }
>         else {
>             lock {
>                 self.attributes['key] = value;
>             }   
>         }
>     }
> 
>     public isolated function get(string 'key) returns value:Cloneable|isolated object {} {
>         lock {
>             return self.attributes.get('key);
>         }
>     }
> 
>     public isolated function remove(string 'key) {
>         lock {
>             value:Cloneable|isolated object {} _ = self.attributes.remove('key);
>         }
>     }
> }
> ```

For the initial implementation, removing an attribute is not considered, since the GraphQL reference implementation recommends that the destructive modifications should not be done to the context. Given that this is not a concrete rule, we can add the remove function. 
> 
>  > ** Note **: `value:Cloneable` includes isolated function pointers and `error` type as well.

**Comment by ldclakmal** [comment]
+1 for the suggested proposal with the suggested modifications.
