### ISSUE TITLE
Create a "Fragment Node" Instead of "Selection Type Record" when Parsing a Named Fragment Spread

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#1922]
**Description:**
Consider the following document:
```graphql
query {
    ... QueryFragment
}

fragment QueryFragment on Query {
    teacher {
        name
        address
    }
}
```
When parsing this document, A fragment node should be created at the spread location of `QueryFragment` to keep the fragment details. Currently we do not create a fragment node there. Instead of creating a fragment node, we create a selection type record. 
Selection record:
```ballerina
public type Selection record {|
    string name;
    boolean isFragment;
    ParentNode node?;
    Location location;
    Location spreadLocation?;
|};
```
Ideally, This should be a `fragment node`.

**Comment by ThisaruGuruge** [comment]
This is a prerequisite for #741
