### ISSUE TITLE
Integrate GraphiQL into GraphQL services

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1936]
Maybe we can expose it under `/graphiql` as the default.

**Comment by ThisaruGuruge** [comment]
We can connect with a Ballerina GraphQL service using the GraphiQL client, by providing the link to the Ballerina service. The only drawback is that the user has to download the GraphiQL client (or use an online GraphQL client) to connect with the Ballerina GraphQL service.

In [ExpressJS GraphQL](https://graphql.org/graphql-js/running-an-express-graphql-server/), they use an input to check whether to start the GraphiQL server, and they serve it under the same URL. 

This is a nice to have feature, but for now, I think we can live with what we have. We can check the possibility of integrating a browser client later. WDYT?

**Comment by shafreenAnfar** [comment]
Yeah, this is a nice to have feature. Created an issue to track the task. If we can expose it under the same URL, it would be fine too. The goal here is to avoid the need to download the client.

**Comment by DimuthuMadushan** [comment]
The proposal:  [https://github.com/ballerina-platform/ballerina-standard-library#2755](https://github.com/ballerina-platform/ballerina-standard-library/issues/2755).
