### ISSUE TITLE
API docs are not updated

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#195]
**Description:**
Tried to use `reflect` module, using the examples in the [API docs](https://ballerina.io/swan-lake/learn/api-docs/ballerina/reflect/index.html). But it throws an error. It seems that the API docs are not updated with the latest syntax.

**Affected Product Version:**
SwanLake Preview 4

**Comment by daneshk** [comment]
Reflect module is no longer maintained from SL release. hence closing this issue
