### ISSUE TITLE
Append http:// when omitted in the http:client

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1986]
For example,

```ballerina
http:client foo = new("bar.com/zee");
``` 

should be the same as, 

```ballerina
http:client bar = new("http://bar.com/zee");
```

**Comment by ayeshLK** [comment]
@shafreenAnfar since there cub be service URL could be secured I do not think just prepending `http://` would not be enough. WDYT ?

**Comment by chamil321** [comment]
> @shafreenAnfar / @chamil321 since there cub be service URL could be secured I do not think just prepending `http://` would not be enough. WDYT ?

That's fine, let's add `http://` scheme as the default. User can anyway change it they expect it to be secured
