### ISSUE TITLE
Introduce GraphQL Interceptors

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#2001]
**Description:**
The requirement is to have something similar to the HTTP interceptors [1] for GraphQL. The advantage of having this is that the business logic can be completely abstracted out to the resolver level while having the common stuff like authentication, authorization, logging, observability, etc. in the middleware level.

A similar use case can be found at GraphQL official website [2].
A popular library can be found at npm [3].

This requirement is initiated with GraphQL security story completion [4].

[1] https://github.com/ballerina-platform/module-ballerina-http/blob/master/docs/proposals/interceptors.md
[2] https://graphql.org/graphql-js/authentication-and-express-middleware/
[3] https://www.npmjs.com/package/graphql-middleware
[4] https://github.com/ballerina-platform/ballerina-standard-library/issues/1771#issuecomment-932129846

Tasks:
- [x] Research
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/2977
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/2984
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/2986
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/2987

**Comment by DimuthuMadushan** [comment]
Tasks:
- [ ] Research
- [ ] Proposal
