### ISSUE TITLE
Generated Ballerina Code Follows Anti-Patterns

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#2016]
**Description:**
The Generated code from the gRPC tool follows some ballerina anti-patterns. 
For example, Ballerina does not recommend using parentheses around the condition statement of a if clause. But [according to this comment](https://github.com/wso2-enterprise/choreo-cp-graphql/pull/41#discussion_r723245430) it does. We should update the code generation to follow coding best practices.

**Comment by daneshk** [comment]
This is already fixed. @BuddhiWathsala @dilanSachi can you check and close

**Comment by dilanSachi** [comment]
Parentheses in if clauses are removed now. And unused variables in stubs are also removed [1].

[1] https://github.com/ballerina-platform/module-ballerina-grpc/pull/565

**Comment by BuddhiWathsala** [comment]
> according to this comment

Hence, closing this issue.
