### ISSUE TITLE
Enrich Ballerina.toml file in each standard library package with the keywords field

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-standard-library#2051]
See https://github.com/sameerajayasoma/jregex/blob/master/Ballerina.toml#L6

Ballerina central search is based on these keywords. The more relevant keywords, the better.

**Comment by niveathika** [comment]
Module List:

- [ ] io
- [ ] java.arrays
- [ ] random
- [ ] regex
- [ ] time
- [ ] url
- [ ] xmldata
- [ ] crypto
- [ ] log
- [ ] os
- [ ] protobuf
- [ ] task
- [ ] xslt
- [ ] cache
- [ ] file
- [ ] ftp
- [ ] mime
- [ ] nats
- [ ] stan
- [ ] tcp
- [ ] udp
- [ ] uuid
- [ ] auth
- [ ] email
- [ ] jwt
- [ ] oauth2
- [ ] http
- [ ] graphql
- [ ] grpc
- [ ] websocket
- [ ] websub
- [ ] websubhub
- [ ] kafka
- [ ] rabbitmq
- [ ] sql
- [ ] java.jdbc
- [ ] msssql
- [ ] mysql
- [ ] oracledb
- [ ] postgresql

**Comment by shafreenAnfar** [comment]
I think we can also add key words `listener` and `client` where necessary.

**Comment by kaneeldias** [comment]
Closing this issue as all modules have been updated.
