### ISSUE TITLE
Negative Test Report for SQL connectors

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#2059]
**Description:**
Negative Test Report will have common scenarios for SQL connectors as well as some different points for each connector,

 Connectors,
- [ ] Common Scenarios
- [ ] JDBC
- [ ] MySQL
- [ ] MSSQL
- [ ] Postgresql
- [ ] Oracle

**Comment by niveathika** [comment]
@kalaiyarasiganeshalingam Shall we include more on how the database type mismatching when querying? 
There are the following two scenarios to distinguish,
1. The type we send in the query does not match to the table -> Mismatch occurs when SQL query is constructed.
2. The return data from the result is a mismatch to the type expected. 

IMO we need to explore the second scenario bit more to include all different datatypes.

**Comment by kalaiyarasiganeshalingam** [comment]
Closing this issue as I have added test cases for the above negative scenarios in all the SQL modules now. I attached the sheet which contains all details with the MySQL module. Please refer this sheet to get more info. 

Sheet: https://docs.google.com/spreadsheets/d/1dqKgMJIgz9v72eiJb6Eg1cXpjt3PMWZRJECDZxdUnUo/edit?usp=sharing

OracleDb hasn't supported BFile and cache features. So I haven't tested those related test cases.
