### ISSUE TITLE
Couldn't create a response within a timeout time when loading the performance test for Kubernetes

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2109]
**Description:**
We had implemented the load performance test for MySQL operation with HTTP service for Kubernetes. When loading the test performance with a resource that returns a string or error[1], got the following error with a 100% error rate [3] due to a delay to create a response. But it is worked[4] when creating the response and sending it by the caller[2].

```Idle timeout triggered before initiating outbound response```

[1] https://github.com/ballerina-platform/ballerina-performance-cloud/pull/788/files#diff-f2b1eedfc554052e56f319ad7d62182e1d2e4d768b0b26420a8c9e5e9884ef2fR32
[2] https://github.com/ballerina-platform/ballerina-performance-cloud/pull/2293/files#diff-f2b1eedfc554052e56f319ad7d62182e1d2e4d768b0b26420a8c9e5e9884ef2fR48
**Open the Execute performance tag to get performance test result**
[3] https://github.com/ballerina-platform/ballerina-performance-cloud/runs/3801841708?check_suite_focus=true
[4] https://github.com/ballerina-platform/ballerina-performance-cloud/runs/3936720499?check_suite_focus=true

**Comment by ayeshLK** [comment]
We have done a load test for the above mentioned scenario with following sample:
```ballerina
import ballerina/http;
import ballerina/lang.runtime;
import ballerina/log;

service /db on new http:Listener(9090) {
    resource function put res1(int id) returns string|error {
        log:printInfo("[RETURN] Received request......", message = id.toString());
        runtime:sleep(0.1);
        if id == 1 {
            return "Hello, World..!";
        } else {
            return "Not Found..!";
        }
    }
}
```

Following is the configurations we used for the load test:
```
concurrency: 20
duration: 10 min
```
As per the test results, we have got 100% success rate.

**Comment by ayeshLK** [comment]
We have done another load test for above sample with following resource limitations:
```
max-cpu = 1
max-memory = 512mb
```
We used following test-suite configurations:
```
concurrency: 20
duration: 10 min
```
As per the test results we have got 100% success rate.

**Comment by chamil321** [comment]
> 

@ayeshLK The thread sleep will not replicate the issue IMO. The db client call is async IINM, and has scheduling process. Therefore let's use the same sample and try to reproduce. Later we can apply out potential fix and test it

**Comment by ayeshLK** [comment]
We have done a profiling for the load test for both return/respond scenarios with following code sample.
```ballerina
sql:ConnectionPool dbConnectionPool = {};

final string price = "1400";
final mysql:Client dbClient = check new (user = "user", password = "password", connectionPool = dbConnectionPool);

service /db on new http:Listener(9090) {
    // curl -X PUT 'localhost:9090/db?id=1'
    resource function put .(int id) returns string|error {
        int count = 0;
        sql:ParameterizedQuery updateQuery = `UPDATE petdb.pet SET Price = ${price} where id = ${id}`;

        sql:ExecutionResult|error result = dbClient->execute(updateQuery);
        if result is error {
            log:printError("Error at db_update", 'error = result);
            return result;
        } else {
            int? deleteRowCount = result?.affectedRowCount;
            if (deleteRowCount is int) {
                count = deleteRowCount;
            }
            return "Affected row:" + count.toString();
        }
    }

    // curl -X PUT 'localhost:9090/db/respond?id=1'
    resource function put respond(http:Caller caller, int id) returns error? {
        int count = 0;
        sql:ParameterizedQuery updateQuery = `UPDATE petdb.pet SET Price = ${price} where id = ${id}`;

        sql:ExecutionResult|error result = dbClient->execute(updateQuery);
        http:Response response = new;
        if result is error {
            log:printError("Error at db_update", 'error = result);
            response.statusCode = 500;
            response.setPayload(result.toString());
        } else {
            response.statusCode = 200;
            int? updateRowCount = result?.affectedRowCount;
            if (updateRowCount is int) {
                count = updateRowCount;
            }
            response.setPayload("Affected row:" + count.toString());
        }
        return caller->respond(response);
    }
}
```

As per the profiling results we observed that in return scenario application level `bal-sql-threads` are available only for a small time during the load test. 

Thread profiling results for Responding from a HTTP Resource:
![http-respond-result](https://user-images.githubusercontent.com/77491511/145526747-abfe2dc2-0f1b-4817-8c0f-31ffc317a9b9.png)

Thread profiling results for Returning from a HTTP Resource:
![http-return-result](https://user-images.githubusercontent.com/77491511/145526774-be79dde4-3357-4c0e-b66a-d253cc287cb4.png)

Complete profiling results could be found [here](https://drive.google.com/drive/folders/1GHQAOakjX2HqSz8iRpiUAgQMKQXMpsVY?usp=sharing).

**Comment by ayeshLK** [comment]
We have done a load test with above sample without limiting the `BALLERINA_MAX_POOL_SIZE`. It is observed that without this limitation both HTTP resource return and caller respond works fine. 

As per the analysis we did on HTTP codebase, when we are returning from a resource it creates a new strand. Hence drastically limiting the `BALLERINA_MAX_POOL_SIZE` will effect the execution of resource return.
