### ISSUE TITLE
Fix concurrent behavior of cache while preserving the performance

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#211]
**Description:**
Ballerina cache v2.0 introduced with the PR [1] by fixing all the concurrent issues that was captured in v1.0. The detailed discussion about that can be found at [1].

But in cache v2.0 also, we got a concurrent issue not because of the cache implementation, but because of the Ballerina `locks` syntax and Ballerina `map` implementation. Due to this there was a significant performance drop and quite high error rate introduced while checking with performance tests on Ballerina Swan Lake Preview 1 release. The detailed set of tests that were done to identify the root cause of this (which is Ballerina `locks` and Ballerina `map`) can be found at [2].

We were able to rectify the issue with following steps.
1. Remove Ballerina `map` usages with `java.util.ConcurrentHashMap` [3]
2. Remove Ballerina `locks` usages with Ballerina `boolean` [4]

The second step which was removing Ballerina `locks` with `boolean` was not a satisfactory solution. That was done as a quick fix to remove the error rate and improve the performance which was reduced because of `locks`.

But recently there were situations where this has introduced errors while accessing the `cache` even with a lower concurrency. Therefore, this need to be fixed properly and ASAP.
```
    error: {ballerina}TypeCastError message=incompatible types: '()' cannot be cast to 'cache:Node' 
	at ballerina.cache:remove(linked_list.bal:90) 
	ballerina.cache.LruEvictionPolicy:get(lru_eviction_policy.bal:28) 
	ballerina.Cache:get(cache.bal:187) 
	ballerina.jwt:validateFromCache(jwt_validator.bal:98) 
    ballerina.jwt:validateJwt(jwt_validator.bal:86) 
	ballerina.jwt.InboundJwtAuthProvider:authenticate(inbound_jwt_auth_provider.bal:63) 
	ballerina.http.BearerAuthHandler:process(auth/bearer_auth_handler.bal:58) 
	ballerina.http.auth.authn_filter:checkForAuthHandlers(auth/authn_filter.bal:80) 
	ballerina.http.auth.authn_filter:handleAuthRequest(auth/authn_filter.bal:59) 
	ballerina.http.AuthnFilter:filterRequest(auth/authn_filter.bal:46) 
    *****.postman.PostmanService__service_1:FindAllWorkspaces(svc_postman.bal:15) 
```

As suggested by @ramith the "Compare and Swap" technique [5] can be applied for this kind of situation. We need to revisit this and fix ASAP.

[1] https://github.com/ballerina-platform/ballerina-lang/issues/21051
[2] https://docs.google.com/spreadsheets/d/1Py4wZjK5Lnfzc3MYDkNUACEhV1zX6oI65NU6jJ0Qt6I/edit?usp=sharing
[3] https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html
[4] https://github.com/ballerina-platform/module-ballerina-cache/blob/v2.0.0/cache-ballerina/src/cache/linked_list.bal#L82
[5] http://tutorials.jenkov.com/java-concurrency/compare-and-swap.html

**Comment by lkokila** [comment]
Tagging https://github.com/ballerina-platform/ballerina-standard-library/issues/630
