### ISSUE TITLE
Kafka tooling check

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#2142]
For more information see the link below.

https://github.com/ballerina-platform/ballerina-standard-library/blob/main/docs/library-development-process.md#tooling-check

**Comment by dilanSachi** [comment]
Following cases were tested related to tooling tests.
 - [x] Code formatting 
 - [x] Code completion
 - [x] Symbol information on hover
 - [x] Go to definition

In hover case, found that function names are not visible for object hover beta6
![Screenshot from 2022-01-12 11-16-55](https://user-images.githubusercontent.com/35135122/149075337-bc5fedff-5451-4d9b-9906-56b6f221d357.png)
Issue - https://github.com/ballerina-platform/ballerina-lang/issues/33671
This is fixed now in the latest version as follows
![Screenshot from 2022-01-12 11-53-58](https://user-images.githubusercontent.com/35135122/149075369-ed66c210-69b3-4257-9820-fb66263a12f2.png)

 Do we need to add snippet generation for kafka:Service as well?
 ```ballerina
service kafka:Service on new kafka:Listener(kafka:DEFAULT_URL, consumerConfigs) {
    remote function onConsumerRecord(kafka:Caller caller, kafka:ConsumerRecord[] records) returns kafka:Error? {

    }
}
```
@shafreenAnfar @aashikam

**Comment by dilanSachi** [comment]
Do we need to add snippet generation for kafka:Service as well?
 ```ballerina
service kafka:Service on new kafka:Listener(kafka:DEFAULT_URL, consumerConfigs) {
    remote function onConsumerRecord(kafka:Caller caller, kafka:ConsumerRecord[] records) returns kafka:Error? {

    }
}
```
@shafreenAnfar @aashikam

**Comment by shafreenAnfar** [comment]
Yeah, we need to. @Bhashinee is the expert on that subject.
