### ISSUE TITLE
Kafka negative test report

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#2144]
For more information see the link below.

https://github.com/ballerina-platform/ballerina-standard-library/blob/main/docs/library-development-process.md#negative-test-report

**Comment by dilanSachi** [comment]
Following are the proposed negative test scenarios.

**Producer**
- [ ] Try to connect to a downed Kafka server.
- [ ] Initialize a transactional producer with invalid configuration
- [ ] Send a value with invalid key type
- [ ] Send message after the producer closed
* Security
  - [ ] Plaintext connection with SSL secured endpoint
  - [ ] Plaintext connection with SASL secured endpoint
  - [ ] SASL auth with incorrect credentials
  - [ ] SASL auth with a SSL secured port
  - [ ] SSL connection without SASL auth with a SSL secured SASL auth port
  - [ ] SSL connection with incorrect certs
  - [ ] SSL connection with incorrect passwords for cert/key
  - [ ] SSL connection with invalid cert/key filepaths

**Consumer**
- [ ] Try to connect to a downed Kafka server.
- [ ] Polling after the consumer closed
- [ ] Seek to negative values
- [ ] Get offsets of a non existing partition
- [ ] Poll from paused topic
- [ ] Pause/Resume from unassigned partitions
- [ ] Assign to null topic
- [ ] Subscribe to a topic via a closed consumer
- [ ] Subscribe to null topic
- [ ] Initialize consumer with no groupId
* Security
  - [ ] Plaintext connection with SSL secured endpoint
  - [ ] Plaintext connection with SASL secured endpoint
  - [ ] SASL auth with incorrect credentials
  - [ ] SASL auth with a SSL secured port
  - [ ] SSL connection without SASL auth with a SSL secured SASL auth port
  - [ ] SSL connection with incorrect certs
  - [ ] SSL connection with incorrect passwords for cert/key
  - [ ] SSL connection with invalid cert/key filepaths

**Listener**
- [ ] Try to connect to a downed Kafka server.
- [ ] Initialize listener with no groupId
* Security
  - [ ] Plaintext connection with SSL secured endpoint
  - [ ] Plaintext connection with SASL secured endpoint
  - [ ] SASL auth with incorrect credentials
  - [ ] SASL auth with a SSL secured port
  - [ ] SSL connection without SASL auth with a SSL secured SASL auth port
  - [ ] SSL connection with incorrect certs
  - [ ] SSL connection with incorrect passwords for cert/key
  - [ ] SSL connection with invalid cert/key filepaths

**Comment by aashikam** [comment]
- Stopping the Kafka server while the listener is up and listening. (not sure if i saw something like this)

**Comment by aashikam** [comment]
- Attaching and detaching from a closed listener. (also starting)
I think for listener, we can add more. Related to topics also, subscribing to invalid/non-existent topics etc. Also, if you check the code cov report you will see, some code snippets that cannot be covered by ballerina tests, we can try to reproduce those also.

**Comment by dilanSachi** [comment]
> * Stopping the Kafka server while the listener is up and listening. (not sure if i saw something like this)



> * Attaching and detaching from a closed listener. (also starting)
>   I think for listener, we can add more. Related to topics also, subscribing to invalid/non-existent topics etc. Also, if you check the code cov report you will see, some code snippets that cannot be covered by ballerina tests, we can try to reproduce those also.

Added

**Comment by dilanSachi** [comment]
`Stop the Kafka server while the listener is running` will be a complex scenario since the server cannot be stopped using a ballerina command

**Comment by aashikam** [comment]
> `Stop the Kafka server while the listener is running` will be a complex scenario since the server cannot be stopped using a ballerina command

Yeah, let's test this manually then, cause this can actually happen to someone 😅

**Comment by dilanSachi** [comment]
> Yeah, let's test this manually then, cause this can actually happen to someone sweat_smile

Will do and update here
