### ISSUE TITLE
Negative test plan for gRPC standard library

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2158]
**Description:**
$title

**Comment by BuddhiWathsala** [comment]
## Client
### Connect
- [ ] Connection timeout error
- [ ] Connection refused error
- [ ] SSL handshake errors
    - [ ] Connection closed while handshaking
    - [ ] Unknown HTTPS host
    - [ ] Connection timeout errorfor HTTPS endpoint
    - [ ] Connection refused error for HTTPS endpoint
    - [ ] Mutual SSL alerts

### Write
- [ ] Connection closed error
    - [ ] While writing messages
    - [ ] After writing messages
- [ ] Application errors
    - [ ] Connection timeout while writing messages
    - [ ] Connection timeout after writing messages

### Read
- [ ] Connection closed error
    - [ ] While reading messages
    - [ ] After writing messages
- [ ] Application errors
    - [x] Backend only sends headers without a response
    - [x] Invalid remote method

## Listener
### Write
- [ ] Connection closed error
    - [ ] While writing messages
    - [ ] After writing messages
- [ ] Application errors
    - [ ] Connection timeout while writing messages
    - [ ] Connection timeout after writing messages

### Read
- [ ] Connection closed error
    - [ ] While reading messages
    - [ ] After writing messages

Note that here the `messages` means all 4 types of the messages:
- Unary
- Server streaming
- Client streaming
- Bidirectional streaming

**Comment by dilanSachi** [comment]
We need to have tooling related negative tests too right?

**Comment by BuddhiWathsala** [comment]
Yes, +1.

**Comment by BuddhiWathsala** [comment]
> We need to have tooling related negative tests too right?

Updated.

**Comment by dilanSachi** [comment]
And also I think we already have enough negative tests in compiler plugin. Do we need more cases there @BuddhiWathsala ?

**Comment by BuddhiWathsala** [comment]
The negative scenarios covered in the compiler plugin can be marked as done. We only need to add the missing parts.

**Comment by BuddhiWathsala** [comment]
> Detailed error messages - https://docs.google.com/spreadsheets/d/1qST4Q-RwXmbvtWSGd4LkfwKTr3MuAIkv1EvHqCzR4-4/edit?usp=sharing

Closing this issue with this report of errors.
