### ISSUE TITLE
Add tooling support for MySQL

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2279]
**Description:**
Add Tooling support for the MySQL connector.

Following tooling support must be implemented,
- [ ] Diagnostics
- [ ] Code completions
- [ ] Code actions
- [ ] Formatting
- [ ] Hover

**Comment by niveathika** [comment]
Additional Diagnostics,

- [ ] connectTimeout, socketTimeout, failoverConfig.timeBeforeRetry and failoverConfig.queriesBeforeRetry validated for negative values
