### ISSUE TITLE
Add tooling support for JDBC

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2280]
**Description:**
Add Tooling support for the JDBC connector.

Following tooling support must be implemented,
- [ ] Diagnostics
- [ ] Code completions
- [ ] Code actions
- [ ] Formatting
- [ ] Hover

**Comment by niveathika** [comment]
Additional Diagnostics,

- [ ] connectTimeout, socketTimeout, failoverConfig.timeBeforeRetry and failoverConfig.queriesBeforeRetry validated for negative values

**Comment by niveathika** [comment]
This includes common scenarios mentioned in https://github.com/ballerina-platform/ballerina-standard-library/issues/2058
