### ISSUE TITLE
Tooling support for PostgreSQL

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2281]
**Description:**
Add Tooling support for the PostgreSQL connector.

Following tooling support must be implemented,
- [ ] Diagnostics
- [ ] Code completions
- [ ] Code actions
- [ ] Formatting
- [ ] Hover

**Comment by niveathika** [comment]
Diagnostics,

- [ ] int, decimal options in `Options` record needs to be validated for negative values.
