### ISSUE TITLE
Tooling support for MSSQL

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2282]
**Description:**
Add Tooling support for the MSSQL connector.

Following tooling support must be implemented,
- [ ] Diagnostics
- [ ] Code completions
- [ ] Code actions
- [ ] Formatting
- [ ] Hover

**Comment by niveathika** [comment]
- [ ] socketTimeout, queryTimeout and loginTimeout needs to be validated for negative values
