### ISSUE TITLE
Tooling support for OracleDB

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2283]
**Description:**
Add Tooling support for the OracleDB connector.

Following tooling support must be implemented,
- [ ] Diagnostics
- [ ] Code completions
- [ ] Code actions
- [ ] Formatting
- [ ] Hover

**Comment by niveathika** [comment]
Diagnostics,

loginTimeout, connectTimeout, connectTimeout needs to be validated for negative values.
