### ISSUE TITLE
Need package icons for each standard library

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#2295]
For all the standard libraries we need to have icons. These icons will be displayed when listing them in central as well as Choreo market place. These icons are part of the package. The below example is from central,

<img width="335" alt="Screen Shot 2021-10-29 at 11 18 09 AM" src="https://user-images.githubusercontent.com/6178058/139382622-e3b5d7a4-d947-4399-8fc9-83128fb3340d.png">

The below list is in two parts just to show that some will be listed in Choreo market place. But at the end of the day all we need is package icons for all of the libraries. 

# Libraries listed both in central and Choreo market place
Libraries which has a client will be listed in Choreo market place as connectors. For clients also we will be using the same icon which we have for packages.
- [x] email
- [x] [grpc](https://grpc.io/)
- [x] websub
- [x] tcp
- [x] udp

## Request/Response
- [x] http

## Streaming
- [x] websocket

## Remote File
- [x] ftp

## Messaging 
- [x] nats
- [x] stan
- [x] kafka
- [x] rabbitmq

## Database
- [x] sql
- [x] java.jdbc
- [x] mysql
- [x] mssql
- [x] oracledb
- [x] postgresql   

# Libraries only listed in central
- [x] io
- [x] url
- [x] java.arrays
- [x] random
- [x] regex
- [x] task
- [x] xmldata
- [x] os
- [x] xslt
- [x] uuid
- [x] log
- [x] cache
- [x] mime
- [x] websubhub
- [x] graphql
- [x] protobuf

## Time
- [x] time

## File
- [x] file

## Security
- [x] jwt
- [x] oauth2
- [x] crypto
- [x] auth

**Comment by tharindu-nw** [comment]
We decided to use package icon as the connector icon for connectors that do not have an icon declared in the display annotation. Therefore, it is not explicitly needed to set the icon in the display annotation for connectors in these libraries and the package level icon (set in `Ballerina.toml`) will be used.

**Comment by shafreenAnfar** [comment]
This task is completed. Hence closing the issue.
