### ISSUE TITLE
Task negative test report

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2320]
**Description:**
For more information see the link below.

https://github.com/ballerina-platform/ballerina-standard-library/blob/main/docs/library-development-process.md#negative-test-report

**Comment by kalaiyarasiganeshalingam** [comment]
These are the following test scenarios listed to test task package:

 - [ ] Invalid workerCount
 - [ ] Invalid interval
 - [ ] Invalid maxCount
 - [ ] Invalid startTime
 - [ ] Invalid endTime
 - [ ] Invalid job id

**Comment by daneshk** [comment]
Closing this task, as we have already done negative testing. Identified issue will address in issue #2497
