### ISSUE TITLE
Usability check for the XmlData library

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#2335]
**Description:**
$Subject

**Comment by kalaiyarasiganeshalingam** [comment]
The following improvement has in this module when checking a usability check.

- https://github.com/ballerina-platform/ballerina-standard-library/issues/2522
- https://github.com/ballerina-platform/ballerina-standard-library/issues/2513
- https://github.com/ballerina-platform/ballerina-standard-library/issues/2511
