### ISSUE TITLE
Skip Building Master when Non-Code Change is Merged

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#2362]
**Description:**
Currently, the master build workflow of each standard library repo runs for each commit (PR merge). This build will publish a timestamped version to the GitHub packages as well.

But ideally, some of these builds are redundant. For example, building and publishing the package when we do a change to README.md or when we add a new proposal is unnecessary. We can skip these builds.

Module List:
- [x] io
- [x] java.arrays
- [x] random
- [x] regex
- [x] time
- [x] url
- [x] xmldata
- [x] crypto
- [x] log
- [x] os
- [x] protobuf
- [x] task
- [x] xslt
- [x] cache
- [x] file
- [x] ftp
- [x] mime
- [x] nats
- [x] stan
- [x] tcp
- [x] udp
- [x] uuid
- [x] auth
- [x] email
- [x] jwt
- [x] oauth2
- [x] http
- [x] graphql
- [x] grpc
- [x] websocket
- [x] websub
- [x] websubhub
- [x] kafka
- [x] rabbitmq
- [x] sql
- [x] java.jdbc
- [x] mssql
- [x] mysql
- [x] oracledb
- [x] postgresql

**Comment by daneshk** [comment]
The task is done. Hense closing
