### ISSUE TITLE
Change init function parameters from optional to required

### ISSUE THREAD

**Issue by anukeshi** [ballerina-platform/ballerina-standard-library#2370]
**Description:**

Currently the init function parameters (host, port, username, password, database) are treated as optional. But the requirement is to have these fields in the Choreo low code editor generated form as mandatory, since we cannot establish a connection without setting these at the first step.

Current UI:
![Screenshot 2021-11-08 at 11 56 40](https://user-images.githubusercontent.com/30332391/140694168-fca8f4e6-5161-4125-ae69-9bb06c9857da.png)

Suggested UI:
![Screenshot 2021-11-08 at 09 44 45](https://user-images.githubusercontent.com/30332391/140693960-c1c421fe-39b9-434d-bc76-ad0a25c565e6.png)

**Comment by niveathika** [comment]
@anukeshi These were discussed during the initial design phase with James and we decided to make them optional.

Please refer https://docs.google.com/document/d/16dTRSNst_tUqdgJ09Ke0We87ivbHoonR1N86KbYV9TA/edit#

**Comment by anukeshi** [comment]
Will be addressed through https://github.com/wso2-enterprise/choreo/issues/9310, hence closing this.
