### ISSUE TITLE
Add Service Template code action for websocket service adds additional line spaces

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-standard-library#2374]
**Description:**
Consider the following capture.

![capture](https://user-images.githubusercontent.com/35211477/140880690-0888a860-d259-46c3-9676-85e2f6011dbc.gif)

Can we improve the resource function's text edit to not add the extra line spaces.

**Comment by Bhashinee** [comment]
This is fixed with https://github.com/ballerina-platform/module-ballerina-websocket/pull/440
