### ISSUE TITLE
DB connectors should support RawTemplate typeName 

### ISSUE THREAD

**Issue by anukeshi** [ballerina-platform/ballerina-standard-library#2381]
**Description:**

Currently the DB connector API, eg: MySQL (https://api.staging-central.ballerina.io/2.0/registry/connectors/156) has the typeName of `object {public string[] & readonly strings;public Value[] insertions;}` instead of the `RawTemplate` type (https://lib.ballerina.io/ballerina/sql/1.0.0/objectTypes/ParameterizedQuery). 

![Screenshot 2021-11-10 at 15 34 10](https://user-images.githubusercontent.com/30332391/141092834-1434331d-008f-477a-8b8a-e57d092f50f5.png)

Hence it is required to change all the DB Connector APIs to support `RawTemplate` typeName.
- MySQL https://api.staging-central.ballerina.io/2.0/registry/connectors/156
- MSSQL https://api.staging-central.ballerina.io/2.0/registry/connectors/154
- Postgre https://api.staging-central.ballerina.io/2.0/registry/connectors/157
- Oracle https://api.staging-central.ballerina.io/2.0/registry/connectors/171

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaneeldias** [comment]
This has been markedas `sql:ParameterizedQuery` (RawTemplate) [1][2] type name in MySQL and other SQL connectors.

[1] https://github.com/ballerina-platform/module-ballerinax-mysql/blob/f43b1dcb557e589acc79cc27a029dd537f7bc1e6/ballerina/client.bal#L57
[2] https://staging-lib.ballerina.io/ballerinax/mysql/1.0.0/clients/Client#query
