### ISSUE TITLE
Make queryRow() API accept anydata as the return-type instead of any

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2390]
**Description:**
The current implementation of the `queryRow()` [API](https://github.com/ballerina-platform/module-ballerina-sql/blob/97f00b34d696bd552b1db7bc6f71fb5a1c6bea8a/ballerina/client.bal#L32-L40) is as follows.
```
    remote isolated function queryRow(ParameterizedQuery sqlQuery, typedesc<any> returnType = <>)
    returns returnType|Error;
```

Here there is no purpose to have `any` as the return-type parameter as the API only supports `anydata` types.

**Comment by niveathika** [comment]
Closing this as the modules are updated
