### ISSUE TITLE
Add tests to identify compiler errors in gRPC tool generated stub files

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#2395]
**Description:**
Currently, the gRPC tool-generated stub files are tested using the Syntax tree (`syntaxTree.hasDiagnostics()`). These tests are able to identify syntax errors. However, these might fail to identify compiler errors as discussed in [[1]](https://github.com/ballerina-platform/ballerina-lang/issues/31448). Therefore, we need to add tests to identify the compiler errors (if any) of the stub files using the semantic-model or through Project API[[2]](https://docs.google.com/presentation/d/18cWKIjDKwcAOcn6DpRgna-RPt6YkvVNSAid6i6BU9XM/edit#slide=id.gaef8ddb39e_0_358).

[1] https://github.com/ballerina-platform/ballerina-lang/issues/31448
[2] https://docs.google.com/presentation/d/18cWKIjDKwcAOcn6DpRgna-RPt6YkvVNSAid6i6BU9XM/edit#slide=id.gaef8ddb39e_0_358

**Comment by BuddhiWathsala** [comment]
Testing semantic diagnostics using Testerina tests will be complicated since we have to add lots of transitive dependencies to the `Ballerina.toml` file. IMO, it is better to have a separate Java tests module to test CLI with semantics. Since we already have a separate module to test compiler plugin tests [1] in a similar manner, how about renaming that module and using it to add these CLI tests in Java?. A possible name would be `tooling-tests`.

[1] https://github.com/ballerina-platform/module-ballerina-grpc/tree/master/compiler-plugin-tests

@daneshk @shafreenAnfar @MadhukaHarith92 @dilanSachi WDYT?

**Comment by dilanSachi** [comment]
> Testing semantic diagnostics using Testerina tests will be complicated since we have to add lots of transitive dependencies to the `Ballerina.toml` file. IMO, it is better to have a separate Java tests module to test CLI with semantics. Since we already have a separate module to test compiler plugin tests [1] in a similar manner, how about renaming that module and using it to add these CLI tests in Java?. A possible name would be `tooling-tests`.
> 
> [1] https://github.com/ballerina-platform/module-ballerina-grpc/tree/master/compiler-plugin-tests
> 
> @daneshk @shafreenAnfar @MadhukaHarith92 @dilanSachi WDYT?

+ for the approach

**Comment by MadhukaHarith92** [comment]
@BuddhiWathsala +1 to move gRPC tooling tests to a separate directory. But will it be inconsistent to rename `compiler-plugin-tests` -> `tooling-tests` when we compare other modules such as graphql[[1]](https://github.com/ballerina-platform/module-ballerina-graphql/tree/master/compiler-plugin-tests) and http[[2]](https://github.com/ballerina-platform/module-ballerina-http/tree/master/compiler-plugin-tests) which have separate `compiler-plugin-tests` to test the compiler plugin?

How about a directory named `tooling-tests` with the sole purpose of testing gRPC tool?

[1] https://github.com/ballerina-platform/module-ballerina-graphql/tree/master/compiler-plugin-tests
[2] https://github.com/ballerina-platform/module-ballerina-http/tree/master/compiler-plugin-tests

**Comment by BuddhiWathsala** [comment]
> @BuddhiWathsala +1 to move gRPC tooling tests to a separate directory. But wouldn't it be inconsistent to rename `compiler-plugin-tests` -> `tooling-tests` when we compare other modules such as graphql[[1]](https://github.com/ballerina-platform/module-ballerina-graphql/tree/master/compiler-plugin-tests) and http[[2]](https://github.com/ballerina-platform/module-ballerina-http/tree/master/compiler-plugin-tests) which have separate `compiler-plugin-tests` to test the compiler plugin?
> 
> How about a directory named `tooling-tests` with the sole purpose of testing gRPC tool?
> 
> [1] https://github.com/ballerina-platform/module-ballerina-graphql/tree/master/compiler-plugin-tests [2] https://github.com/ballerina-platform/module-ballerina-http/tree/master/compiler-plugin-tests

That is also possible, my only concern here is when we add another submodule, it will slightly increase the build and release time. @MadhukaHarith92 I'm also +1 for your suggestion since that build time increase will be a small one and better to make it consistent.

**Comment by shafreenAnfar** [comment]
+1 for @MadhukaHarith92 suggestion. Maintainability is more important than a minor build performance improvement.
