### ISSUE TITLE
Unversioned Ballerina target directory is created after a successful build

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2396]
**Description:**
Recently I noticed that, after a module build, there is an additional directory created called `ballerinaTarget`. That directory contains an unversioned `bala` file and this unversioned file will fail our releases. This issue happens after the recent changes to the Gradle plugin (introduction of the target dir) [1]. The possible solutions to fix this:

1. Ignore the `bala` files in `gitignore`
2. Ignore the entire `ballerinaTarget` directory in `gitignore`
3. Create the `ballerinaTarget` inside the `build` directory (since build directory is already ignored, `ballerinaTarget`  will be automatically ignored)

[1] https://github.com/ballerina-platform/plugin-gradle/pull/65

@niveathika @ThisaruGuruge @shafreenAnfar @daneshk WDYT?.

**Comment by niveathika** [comment]
+1 for the third option. I already cleaned up the paths but did not send a PR since it has many other changes.

https://github.com/ballerina-platform/plugin-gradle/pull/68

**Comment by BuddhiWathsala** [comment]
Shall we merge this before the release since this will fail our releases?

> +1 for the third option. I already cleaned up the paths but did not send a PR since it has many other changes.
> 
> [ballerina-platform/plugin-gradle#68](https://github.com/ballerina-platform/plugin-gradle/pull/68)

**Comment by shafreenAnfar** [comment]
Yeah, +1 for the third option.

**Comment by kalaiyarasiganeshalingam** [comment]
To fix this issue, the following modules' plugin version needs to be updated to `0.14.1`. 

Please refer this PR to get more info: https://github.com/ballerina-platform/plugin-gradle/pull/68

- [ ] io
- [ ] url
- [ ] java.arrays
- [ ] random
- [ ] regex
- [ ] task
- [ ] time
- [ ] xmldata
- [ ] crypto
- [ ] os
- [ ] xslt
- [ ] uuid
- [ ] log
- [ ] cache
- [ ] file
- [ ] ftp
- [ ] mime
- [ ] nats
- [ ] stan
- [ ] tcp
- [ ] udp
- [ ] auth
- [ ] email
- [ ] http
- [ ] jwt
- [ ] oauth2
- [ ] graphql
- [ ] grpc
- [ ] websocket
- [ ] websub
- [ ] websubhub
- [ ] kafka
- [ ] rabbitmq
- [ ] sql
- [ ] java.jdbc
- [ ] mysql
- [ ] mssql
- [ ] oracledb
- [ ] postgresql
