### ISSUE TITLE
API Docs are not properly formatted for the new lines in the doc comments of the .bal files

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#2407]
**Description:**

$subject. Refer to [1]. The new lines are not properly rendered although they are there in the comment in [2] Also the VSCode rendering is not good due to this it seems. (Refer to the image 2)

[1] https://lib.ballerina.io/ballerina/sql/1.0.0/records/ExecutionResult
[2] https://github.com/ballerina-platform/module-ballerina-sql/blob/1ec005c29e5290babbfcf97c385013f64f8e251d/ballerina/types.bal#L628:L635

Image 1:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/16300038/141446938-ce0e592d-ede0-4005-a362-09e2fb284e09.png">

Image 2:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/16300038/141446819-908f471c-b3f0-450f-bb5e-ce0d1b49b5ee.png">

**Affected Versions:**

Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.6

**Comment by niveathika** [comment]
For now the above PR will fix this specific formatting, Full API doc review will be tracked in https://github.com/ballerina-platform/ballerina-standard-library/issues/2061
