### ISSUE TITLE
Standard libraries prune to fail during the releases due to multiple jBallerina packs

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2413]
**Description:**
Currently, we release stdlibs as follows:
1. Build the library without tests
2. Strip the timestamp version of the jBallerina pack and other dependencies
3. Build with tests and publish

In step 01, we download the timestamp jBallerina pack and keep it in the root-level `target/` directory. In step 03, we again download the released jBallerina pack and keep it also in the root-level `target/` directory. What actually happens is before step 03, in the root-level `target/` directory, there is a huge jBallerina pack which is a combination of timestamp jBallerina pack and the actual release pack like below.

```
➜  ballerina-runtime git:(release-2.0.1) ✗ tree target
.
├── bin
│   ├── bal
│   ├── bal.bat
│   └── version.txt
├── bre
│   ├── lib
│   │   ├── annotations-2.0.0-beta.4-20211117-173300-4b039e51.jar
│   │   ├── annotations-2.0.0-beta.4.jar
│   │   ├── antlr4-runtime-4.5.1.wso2v1.jar
│   │   ├── array-2.0.0-beta.4-20211117-173300-4b039e51.jar
│   │   ├── array-2.0.0-beta.4.jar
│   │   ├── asm-7.1.jar
│   │   ├── asm-analysis-7.1.jar
│   │   ├── asm-commons-7.2.jar
│   │   ├── asm-tree-7.2.jar
│   │   ├── asm-util-7.1.jar
│   │   ├── atomikos-util-5.0.8.jar
│   │   ├── axiom-api-1.2.22.jar
│   │   ├── axiom-impl-1.2.22.jar
│   │   ├── ballerina-bindgen-2.0.0-beta.4-20211117-173300-4b039e51.jar
│   │   ├── ballerina-bindgen-2.0.0-beta.4.jar
│   │   ├── ballerina-cli-2.0.0-beta.4-20211117-173300-4b039e51.jar
│   │   ├── ballerina-cli-2.0.0-beta.4.jar

...
    ├── lib
    │   ├── test.zip
    │   └── tools
    │       ├── debug-adapter
    │       │   └── lib
    │       │       ├── commons-io-2.7.jar
    │       │       ├── debug-adapter-cli-2.0.0-beta.4-20211117-173300-4b039e51.jar
    │       │       ├── debug-adapter-cli-2.0.0-beta.4.jar
    │       │       ├── debug-adapter-core-2.0.0-beta.4-20211117-173300-4b039e51.jar
    │       │       ├── debug-adapter-core-2.0.0-beta.4.jar
    │       │       ├── java-semver-0.9.0.jar
    │       │       ├── org.eclipse.lsp4j.debug-0.12.0.jar
    │       │       ├── org.eclipse.lsp4j.jsonrpc-0.12.0.jar
    │       │       └── org.eclipse.lsp4j.jsonrpc.debug-0.12.0.jar
...

    │   │   │   ├── http
    │   │   │   │   └── 2.0.1
    │   │   │   │       └── java11
    │   │   │   │           ├── bala.json
    │   │   │   │           ├── compiler-plugin
    │   │   │   │           │   ├── compiler-plugin.json
    │   │   │   │           │   └── libs
    │   │   │   │           │       ├── http-compiler-plugin-2.0.1-20211120-133000-7ed2577.jar
    │   │   │   │           │       └── http-compiler-plugin-2.0.1.jar
...
```

This release process theoretically works fine, but it is pruned to failures. For example, the log module failed due to that. 

#### Possible Solutions
1. To remove the initial build without test in step 01 since it seems unnecessary 
2. Add the cleaning step before the release like [here](https://github.com/ballerina-platform/module-ballerina-log/pull/372/commits/273472c972baf69015d359a5e6c57a41f59c457f)

@niveathika @ldclakmal @ThisaruGuruge @shafreenAnfar @daneshk WDYT?

**Comment by niveathika** [comment]
+1, can combine the release and clean tasks, This should work.
```
./gradlew clean release -Prelease.useAutomaticVersion=true
```

**Comment by BuddhiWathsala** [comment]
> +1, can combine the release and clean tasks, This should work.
> 
> ```
> ./gradlew clean release -Prelease.useAutomaticVersion=true
> ```

Yes +1 for that.

**Comment by niveathika** [comment]
Closing this issue as this is now addressed in all stdlibs
