### ISSUE TITLE
Cannot access dependent stub files inside a folder

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#2427]
**Description:**
Consider the following instance when a proto file depends on another proto file inside a folder.

---p1.proto
---lib
------p2.proto

p1.proto
```
syntax = "proto3";

import "lib/p2.proto";

service helloWorldWithDependency {
    rpc hello(HelloRequest) returns (HelloResponse);
}
```

p2.proto
```
syntax = "proto3";

message HelloRequest {
    string name = 1;
}
message HelloResponse {
    string message = 1;
}
```
Once the stub files are generated, `p1_pb.bal` file cannot find the `HelloRequest` and `HelloResponse` records which are in `lib/p2_pb.bal`.

**Comment by BuddhiWathsala** [comment]
I don't see any advantage of putting `p2_pb.bal` inside the `lib` directory since it is not usable in a Ballerina project. I think it is better to put it inside a Ballerina submodule, something like `modules/lib`.

@MadhukaHarith92 @dilanSachi @daneshk @shafreenAnfar WDYT?

**Comment by dilanSachi** [comment]
> I don't see any advantage of putting `p2_pb.bal` inside the `lib` directory since it is not usable in a Ballerina project. I think it is better to put it inside a Ballerina submodule, something like `modules/lib`.
> 
> @MadhukaHarith92 @dilanSachi @daneshk @shafreenAnfar WDYT?

+1. That way, `HelloRequest` can be imported as `lib:HelloRequest`.

**Comment by MadhukaHarith92** [comment]
Instead of creating submodules, shall we create the dependencies within the same directory as the root `_pb.bal` file? For example, consider the following proto file structure.
```
.
├── lib1
│   └── p1.proto
├── lib2
│   └── p2.proto
└── p0.proto
```

**p0.proto:**
```
syntax = "proto3";

import "lib1/p1.proto";
import "lib2/p2.proto";

service helloWorldWithDependency {
    rpc hello(HelloRequest) returns (HelloResponse);
}
```

The structure of the generated stub files would look like the following.
```
.
├── p0_pb.bal
├── lib1_p1_pb.bal
└── lib2_p2_pb.bal
```

The name of the dependencies will be in the format `<DIR1_DIR2....>_<PROTOFILENAME>_pb.bal`. This way the uniqueness of the dependent protobuf file names is guaranteed. WDYT?

**Comment by BuddhiWathsala** [comment]
> Instead of creating submodules, shall we create the dependencies within the same directory as the root `_pb.bal` file? For example, consider the following proto file structure.
> 
> ```
> .
> ├── lib1
> │   └── p1.proto
> ├── lib2
> │   └── p2.proto
> └── p0.proto
> ```
> 
> **p0.proto:**
> 
> ```
> syntax = "proto3";
> 
> import "lib1/p1.proto";
> import "lib2/p2.proto";
> 
> service helloWorldWithDependency {
>     rpc hello(HelloRequest) returns (HelloResponse);
> }
> ```
> 
> The structure of the generated stub files would look like the following.
> 
> ```
> .
> ├── p0_pb.bal
> ├── lib1_p1_pb.bal
> └── lib2_p2_pb.bal
> ```
> 
> The name of the dependencies will be in the format `<DIR1_DIR2....>_<PROTOFILENAME>_pb.bal`. This way the uniqueness of the dependent file names is also guaranteed. WDYT?

What would be the behaviour if `p1.proto` and `p2.proto` contain a similar message?. We need to check that. Let's check how Golang did this and we can follow the same since we already align with their approach.

**Comment by MadhukaHarith92** [comment]
> 

I think we discussed creating a common stub file with the name `<DIRECTORY_NAME>_grpc_pb.bal` to keep the common message types[[1]](https://github.com/ballerina-platform/ballerina-standard-library/issues/1635#issuecomment-880392543) when supporting multiple stub files in the same module. Can we follow that approach when creating multiple dependent stub files in the same directory?

[1] https://github.com/ballerina-platform/ballerina-standard-library/issues/1635#issuecomment-880392543

**Comment by BuddhiWathsala** [comment]
> > 
> 
> I think we discussed creating a common stub file with the name `<DIRECTORY_NAME>_grpc_pb.bal` to keep the common message types[[1]](https://github.com/ballerina-platform/ballerina-standard-library/issues/1635#issuecomment-880392543) when supporting multiple stub files in the same module. Can we follow that approach when creating multiple dependent stub files in the same directory?
> 
> [1] [#1635 (comment)](https://github.com/ballerina-platform/ballerina-standard-library/issues/1635#issuecomment-880392543)

So, this is a deviation from our initial design. I'm +1 to follow that approach. And let's check the behaviour when we have common messages too.
