### ISSUE TITLE
JDBC Module gives errors when running with beta4

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#2428]
**Description:**
$subject for BBE when running with Beta4 (After upgrading the b7a version from Beta3)

**Steps to reproduce:**

Copy the BBE to single .bal file and run.

It gives below errors.

```
Compiling source
        test2.bal
ERROR [ballerinax/java.jdbc/1.0.0::client.bal:(65:5,69:16)] mismatched function signatures: expected 'public function queryRow(ballerina/sql:1.1.0:ParameterizedQuery sqlQuery, typedesc<anydata> returnType) returns (returnType|ballerina/sql:1.1.0:Error)', found 'public function queryRow(ballerina/sql:1.1.0:ParameterizedQuery sqlQuery, typedesc returnType) returns (returnType|ballerina/sql:1.1.0:Error)'
WARNING [test2.bal:(37:5,39:8)] unused variable 'e'
WARNING [test2.bal:(57:5,57:39)] unused variable 'er'
WARNING [test2.bal:(77:5,81:41)] unused variable 'result'
WARNING [test2.bal:(95:5,96:63)] unused variable 'result'
error: compilation contains errors
```

**Affected Versions:**
SLBeta4

**Comment by niveathika** [comment]
As quoted here by @azinneera, hierarchical name resolution logic bug is fixed and this is waiting on central team fix.

> @niveathika there are two issues here:
> 
> 1. Some APIs in Ballerina Central has not implemented the restriction to avoid getting packages pushed from newer distribution
> 2. Bug is hierarchical name resolution logic
> 
> This issue will address the 2nd point and the first one will be fixed by the Ballerina Central team.

**Comment by niveathika** [comment]
The issue for central is tracked in
https://github.com/wso2-enterprise/ballerina-registry/issues/1190

**Comment by niveathika** [comment]
This is fixed in Swan Lake Beta6 rc2, https://github.com/ballerina-platform/ballerina-distribution/releases/tag/vswan-lake-beta6-rc2
