### ISSUE TITLE
Error defined in proto files must be escaped when generating Ballerina service 

### ISSUE THREAD

**Issue by AathmanT** [ballerina-platform/ballerina-standard-library#2475]
**Description:**
I have a proto file called types.proto. It has the following definition and it contains enum as one of the definitions.
```
message WebsocketMessage {
    enum Type {
        unknown = 0;
        control = 1;
        data = 2;
        error = 3;
    }
    Type type = 1;
    google.protobuf.Any message = 2;
}
```
When generating the Ballerina service from this proto file. We are getting `invalid token error`.
All the proto files can be found here.
https://drive.google.com/file/d/1j_jooAD2XSlbvzDsNKbLVg1SsSsls723/view?usp=sharing

**Affected Versions:**
Swan Lake Beta 3

**Comment by dilanSachi** [comment]
closing since fixed
