### ISSUE TITLE
Xmldata has gaps between implementation and spec

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2479]
**Description:**
The following gaps were found when writing a specification(https://github.com/ballerina-platform/module-ballerina-xmldata/pull/347):

- The following JSON returns an error:

```ballerina
     json data = {"#content":"text"};
    xml|Error? result = fromJson(data);
```
**error:**
```
 invalid xml qualified name: unsupported characters in '#content'
```
**Expected output:**
```
<root>text</root>
```

- The following JSON returns the wrong output:

```ballerina
xml x1 = xml `<e>
                    some
                    <a>textual</a>
                    content
                  </e>`;
json j = check toJson(x1);
```
**Output:**
```
{"e":{"#content":"content","a":"textual"}}
```

**Expected output:**
```
{e:{"#content":["some","content"],a:"textual"}}
```

- JSON[] is not working properly.

**Comment by kalaiyarasiganeshalingam** [comment]
The `fromJson` returns an error with the below XML when changing the `JsonOption` configuration `.

```ballerina
json data = {"Store": {
        "#id": "AST",
        "name": "Anne",
        "address": {
            "#id": "AST",
            "street": "Main",
            "city": "94"
        },
        "codes": ["4", "8"]
    }};
    xml?|error result = fromJson(data, {attributePrefix: "#"});
```

error: `invalid xml qualified name: unsupported characters in '#id'`

**Comment by kalaiyarasiganeshalingam** [comment]
Getting the following error when JSON is a single value (string, number, boolean, null).

```ballerinna
json data = 5;
xml?|error result = fromJson(data);
```

Error: `failed to convert json to xml`

**Comment by daneshk** [comment]
Closing this issue, as we already created issues for each spec deviation.
