### ISSUE TITLE
Intermittent test failure in websub release

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2490]
**Description:**
The following intermittent error occurred twice during the websub 2.1.0 release.

```sh
time = 2021-12-13T17:02:12.109Z level = INFO module = ballerina/websub message = "Unsubscribing from the hub..."
time = 2021-12-13T17:02:27.132Z level = ERROR module = ballerina/websub message = "[UNSUB_TEST] Error occurred while verifying unsubscription" error = "Something wrong with the connection"

		[fail] testUnsubscriptionOnGracefulStop:

		    Assertion Failed!

		    	at ballerina.test.0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0:assertTrue(assert.bal:64)
		    	ballerina.websub.2.tests.unsubscription_test:testUnsubscriptionOnGracefulStop(tests/unsubscription_test.bal:89)
```
**Steps to reproduce:**
- https://github.com/ballerina-platform/module-ballerina-websub/runs/4509635641?check_suite_focus=true
- https://github.com/ballerina-platform/module-ballerina-websub/runs/4509342990?check_suite_focus=true

**Affected Versions:**
Websub 2.1.0

**Comment by ayeshLK** [comment]
Fixed with [73da6a789c2e7c4339e6b975d88da15a2333054d](https://github.com/ballerina-platform/module-ballerina-websub/pull/468/commits/73da6a789c2e7c4339e6b975d88da15a2333054d)
