### ISSUE TITLE
gRPC Netty version bump to 4.1.71.Final fails 

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2492]
**Description:**
The Netty version bump of gRPC fails with the following error.

```sh
        grpc_tests
error: Test module initialization for test suite failed due to java.lang.UnsatisfiedLinkError {"message":"failed to load the required native library","cause":error("java.lang.IllegalArgumentException",message="Failed to load any of the given libraries: [netty_tcnative_osx_x86_64, netty_tcnative_x86_64, netty_tcnative]")}
        at ballerina.grpc.1:externInitEndpoint(service_endpoint.bal:132)
           ballerina.grpc.1.Listener:init(service_endpoint.bal:90)
error: there are test failures

```

**Affected Versions:**
- SL beta 06

**Related PRs**
- https://github.com/ballerina-platform/module-ballerina-grpc/pull/590
- https://github.com/ballerina-platform/module-ballerina-http/pull/783

**Comment by BuddhiWathsala** [comment]
Difference between HTTP and gRPC native libraries.
![Screenshot 2021-12-14 at 12 03 48](https://user-images.githubusercontent.com/18663444/145945658-9bbd4673-1034-43ba-8d46-543e93a62754.png)

**Comment by BuddhiWathsala** [comment]
Adding the missing JARs mime-native, mimepull, and testng won't fix the issue and gives the same issue.

**Comment by BuddhiWathsala** [comment]
Checked a sample with the intermediate pack(with boring SSL JAR) that we used to run gRPC tests, and the sample works fine even though the module tests fail. Seems we have to fix the module level tests and anyway need to pack the boring SSL JAR.

**Comment by BuddhiWathsala** [comment]
Similar to this issue: https://groups.google.com/g/netty/c/EbRR5_fN0RM?pli=1

It didn't pick the META-INF of boring SSL JAR correctly.

**Comment by BuddhiWathsala** [comment]
When there is [this HTTP service implementation](https://github.com/ballerina-platform/module-ballerina-grpc/blob/acc7493b4deaded695a40740a328180bb7530a21/ballerina-tests/tests/auth_test_commons.bal) with a gRPC SSL service, the gRPC tests fails. Otherwise, it will be fine to add the boring SSL JAR 2.0.46.Final version.

**Comment by daneshk** [comment]
> When there is [this HTTP service implementation](https://github.com/ballerina-platform/module-ballerina-grpc/blob/acc7493b4deaded695a40740a328180bb7530a21/ballerina-tests/tests/auth_test_commons.bal) with a gRPC SSL service, the gRPC tests fails. Otherwise, it will be fine to add the boring SSL JAR 2.0.46.Final version.

Good, we have narrowed the issue. So it may be because both HTTP and grpc packages pack the same jar. It should not fail though.

**Comment by BuddhiWathsala** [comment]
Yes, @daneshk issue happens since both HTTP and gRPC has the same JAR. 

According to the netty resource loading logic, when there are two JARs (default case), it returns an error. Since both HTTP and gRPC has the same JAR, we ended up getting this error.
![Screenshot 2021-12-14 at 19 07 53](https://user-images.githubusercontent.com/18663444/146008966-532cf6dc-1ea6-4efa-ad54-756ed7958663.png)

I can't see a straightforward way to solve this issue. If we remove packing it to HTTP, then HTTP will fail. If we didn’t pack to gRPC then gRPC will fail like right now.

**Comment by BuddhiWathsala** [comment]
Reason for the failure 
- https://github.com/netty/netty/issues/11921
- https://github.com/netty/netty/commit/ea2742b4f628dfae9523c49b22472df921d1386c

**Comment by BuddhiWathsala** [comment]
The only feasible solution would be to release both HTTP and gRPC again by downgrading the Netty versions.

**Comment by sameerajayasoma** [comment]
Looks like a bug in executable jar creation. We are copying the same Jar entry twice. @pramodya1994 @azinneera

**Comment by BuddhiWathsala** [comment]
As per an offline discussion with @azinneera and @hevayo, we discussed removing all the repetitive JARs from gRPC which already comes with HTTP. Then, import HTTP into gRPC and that import will give necessary JARs.

However, when I removed the `http-native` JAR from `Ballerina.toml` of gRPC, it gives class not found errors. Since gRPC is using `http-native` JAR for external calls, should I need to add `http-native` JAR to `Ballerina.toml` even though it comes with HTTP? @azinneera

**Comment by BuddhiWathsala** [comment]
HTTP native JAR cannot be removed from `Ballerina.toml` of gRPC due to [this issue](https://github.com/ballerina-platform/ballerina-standard-library/issues/2496).

@shafreenAnfar @daneshk FYI.

**Comment by sameerajayasoma** [comment]
I don't this think we have solved this issue properly. Apologies for reopening this issue.  

Here are the potential issues that I noticed:
- How do we explain "import ballerina/http as _" when someone look at the gRPC code? 
- Did you notice the list of new dependencies added to `Dependencies.toml` after this change? https://github.com/ballerina-platform/module-ballerina-grpc/pull/598/files

**Comment by BuddhiWathsala** [comment]
Closing since this has to be fixed on the Ballerina side and create an issue to keep track of the Ballerina level fix https://github.com/ballerina-platform/ballerina-lang/issues/34357.

In addition, created a task to revert these changes once the Ballerina level fix merged https://github.com/ballerina-platform/ballerina-standard-library/issues/2498.
