### ISSUE TITLE
Couldn't get an error when the scheduling time is invalid

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2497]
**Description:**
When scheduling tasks with time and that time already passed with the current time(invalid), it needs to return an error. In the current scenario, if time passed, the trigger will start at the scheduled time. 

Parent issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2320

**Comment by daneshk** [comment]
Fixed is already merged. Hence closing the issue
