### ISSUE TITLE
Improve fromJson() API for user to specify whether to include root tag in conversion

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2511]
**Description:**
`fromJson` creates root tag in the following situations:

- When JSON is a JSON array
  ```ballerina
     json data = [
        {
           "@writer": "Christopher",
           lname: "Nolan",
           age: 30,
           address: ["Uduvil"]
        },
        1
     ];
  ```

- When JSON data contains multiple key-value pairs
   ```ballerina
       json data = {
                      fname: "John",
                      lname: "Stallone"
             };
    ```
Better if we have an option to configure this parent tag because, in some scenarios, the user may want to add any other tag.

**Comment by daneshk** [comment]
@kalaiyarasiganeshalingam shall we come up with a proposal for this improvement
