### ISSUE TITLE
`websubhub:Service` will not complete the subscription verification process if `onSubscription` remote method is not implemented

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#2516]
**Description:**
When implementing a `websubhub:Service`, `onSubscription` is an optional remote method to be implemented. But, if the developer does not implement `onSubscription` method, `websubhub:Service` will not continue the subscription verification process. 

**Steps to reproduce:**
* Implement a `websubhub:Service` but do not implement `onSubscription` remote method.
* Try to subscribe to the hub

**Affected Versions:**
- SL Beta6

**Comment by ayeshLK** [comment]
There are two approaches which we could use to fix this:
- Mark `onSubscription` as mandatory method
- Implement the subscription verification flow for the scenario where `onSubscription` is not implemented 

@shafreenAnfar / @chamil321 WDYT ?

**Comment by shafreenAnfar** [comment]
I think in the original design also it is optional. Meaning subscription flow should work without it. Is there a problem in doing so ?

https://github.com/ballerina-platform/ballerina-standard-library/issues/786

**Comment by ayeshLK** [comment]
As per the inspection done this issue is already fixed with PR [#362](https://github.com/ballerina-platform/module-ballerina-websubhub/pull/362)

Commits:
https://github.com/ballerina-platform/module-ballerina-websubhub/pull/362/commits/9769294a720d87f0a6e853597500fa19096f2676
https://github.com/ballerina-platform/module-ballerina-websubhub/pull/362/commits/99499fe44cd828e5911fe320fab158baefde95a2
