### ISSUE TITLE
Improve sql:Client->query()` method documentation to reflect usage of parameterized queries

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-standard-library#2524]
**Description:**
When using the `sql:Client` to query (and other similar operations), users get a bit confused about the usage of `sql:ParameterizedQuery`. From an end user's perspective, what they see is a class, but in source we write parameterized queries as:
```ballerina
sql:ParameterizedQuery query = `select * from ${tableName} where id=${entityId}`;
```
We have to explicitly mention how to write `sql:ParameterizedQuery` in the method documentations. See the method documentation for `io:println()` for an example. Similarly, we should add some examples and mention about parameterized queries being converted to prepared statements in the docs.

**Describe your problem(s)**
See description

**Describe your solution(s)**
Improve lib docs to reflect the correct usage

**Related Issues (optional):**
#33669

**Comment by niveathika** [comment]
I am -1 on this because even though it is single line in the description, this needs to be repeated in all function description. There can be also issues where the give sample will not match all databases.

@daneshk WDYT?

**Comment by daneshk** [comment]
It is better if we can have a code snippet to explain the usage in API Docs. Shall we add a simple code snippet that matches the connector?
