### ISSUE TITLE
Write a tutorial on How to build a Data Service in Ballerina

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#2555]
**Description:**
Currently, we have a set of BBEs and API Docs. We don't have a tutorial about how to build a Data Service in Ballerina.

**Describe your task(s)**
We can get a simple scenario and explain step by step covering all the best practices.

Once we have the initial draft, we can decide where to put it on the website.

**Comment by kaneeldias** [comment]
Draft document
https://docs.google.com/document/d/1e34HU-2p4wYdTlzZWgg0TIIvWKTHZkVIGHiaEtwDYJ4/edit
