### ISSUE TITLE
Ballerina `table` implementation does not work properly for `decimal` values

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#2559]
**Description:**
In `ballerina-1.2.x` branch currently we have done a version update for `h2database` due to security vulnerability. In `ballerina-1.2.x`, ballerina `table` implementation is using an in-memory H2 database in runtime. But, with this version update it seems that the `table` implementation has been broken. 

As per the H2 documentation [1] `DECIMAL` data type will assume 0 as the default value for `scaleInt`. But, in ballerina table implementation when creating the in-memory db-table we do not specify the `scaleInt` when creating columns with `DECIMAL` value. Hence, the database would assume that the `scaleInt` is 0 and the decimal points will be lost. This will result in inconsistent outputs when storing ballerina records containing `decimal` fields in a ballerina table. Hence, following test case is broken [2]

[1] - [http://www.h2database.com/html/datatypes.html#numeric_type](http://www.h2database.com/html/datatypes.html#numeric_type)
[2] - [https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java#L66](https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java#L66)

**Affected Versions:**
- Ballerina 1.2.x

**OS, DB, other environment details and versions:**
- Related to PR [#34437](https://github.com/ballerina-platform/ballerina-lang/pull/34437)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
@ayeshLK Hope we can close this issue as, we are not upgrading.

**Comment by ldclakmal** [comment]
Yes. We can close this since we are not upgrading the H2 dependency version.
