### ISSUE TITLE
[gRPC][Tool] Generated Client/Service Sample File improvements

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#2587]
**Description:**
Following improvements identified in generated client/server sample files.

* Client sample code imports `ballerina/grpc` which is a redundant import in simple code. Remove adding this import to the client sample code.
* Client/Service sample file name starts with Capital letter. Since all the bal files are created with simple letters, better we change it to simple letters with _ separater

**Affected Versions:**
slbeta6

**Comment by BuddhiWathsala** [comment]
I wonder whether we need the term `sample` in the generated client or service skeleton files. @daneshk @MadhukaHarith92 @dilanSachi @shafreenAnfar WDYT?

**Comment by BuddhiWathsala** [comment]
> **Description:** Following improvements identified in generated client/server sample files.
> 
> * Client sample code imports `ballerina/grpc` which is a redundant import in simple code. Remove adding this import to the client sample code.
> * Client/Service sample file name starts with Capital letter. Since all the bal files are created with simple letters, better we change it to simple letters with _ separater
> 
> **Affected Versions:** slbeta6

I checked with the latest Ballerina distribution and couldn’t find the unnecessary `ballerina/grpc` import in the generated client skeleton files.

**Comment by daneshk** [comment]
> > **Description:** Following improvements identified in generated client/server sample files.
> > 
> > * Client sample code imports `ballerina/grpc` which is a redundant import in simple code. Remove adding this import to the client sample code.
> > * Client/Service sample file name starts with Capital letter. Since all the bal files are created with simple letters, better we change it to simple letters with _ separater
> > 
> > **Affected Versions:** slbeta6
> 
> I checked with the latest Ballerina distribution and couldn’t find the unnecessary `ballerina/grpc` import in the generated client skeleton files.

Then its okay. May be I am referring to older version.

**Comment by MadhukaHarith92** [comment]
> **Description:** Following improvements identified in generated client/server sample files.
> 
>     * Client sample code imports `ballerina/grpc` which is a redundant import in simple code. Remove adding this import to the client sample code.
> 
>     * Client/Service sample file name starts with Capital letter. Since all the bal files are created with simple letters, better we change it to simple letters with _ separater
> 
> 
> **Affected Versions:** slbeta6

Regarding the 2nd point, the name of the sample service bal file is derived from the service name (<SERVICE_NAME>_sample_service.bal). For instance, for the following proto definition,
```
syntax = "proto3";
import "google/protobuf/wrappers.proto";
service helloWorld {
	rpc hello(stream google.protobuf.StringValue) returns (stream google.protobuf.StringValue);
}
```

The generated sample service file name is `helloWorld_sample_service.bal`.

@daneshk shall we change this to make the starting letter of the sample service file name simple when the starting letter of the service is capital as well?

**Comment by daneshk** [comment]
> I wonder whether we need the term `sample` in the generated client or service skeleton files. @daneshk @MadhukaHarith92 @dilanSachi @shafreenAnfar WDYT?

yes, the world `sample` not looks good. These files are not complete ones. it is code snippets to startwith. Is there any other  word we can use to imply these are template files

**Comment by daneshk** [comment]
> > **Description:** Following improvements identified in generated client/server sample files.
> > ```
> > * Client sample code imports `ballerina/grpc` which is a redundant import in simple code. Remove adding this import to the client sample code.
> > 
> > * Client/Service sample file name starts with Capital letter. Since all the bal files are created with simple letters, better we change it to simple letters with _ separater
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Affected Versions:** slbeta6
> 
> Regarding the 2nd point, the name of the sample service bal file is derived from the service name (<SERVICE_NAME>_sample_service.bal). For instance, for the following proto definition,
> 
> ```
> syntax = "proto3";
> import "google/protobuf/wrappers.proto";
> service helloWorld {
> 	rpc hello(stream google.protobuf.StringValue) returns (stream google.protobuf.StringValue);
> }
> ```
> 
> The generated sample service file name is `helloWorld_sample_service.bal`.
> 
> @daneshk shall we change this to make the starting letter of the sample service file name simple when the starting letter of the service is capital as well?

Yes, let's make filename starts with simple letter in both cases.

**Comment by BuddhiWathsala** [comment]
> > I wonder whether we need the term `sample` in the generated client or service skeleton files. @daneshk @MadhukaHarith92 @dilanSachi @shafreenAnfar WDYT?
> 
> yes, the world `sample` not looks good. These files are not complete ones. it is code snippets to startwith. Is there any other word we can use to imply these are template files

How about `template` or `skeleton`?

**Comment by MadhukaHarith92** [comment]
> > I wonder whether we need the term `sample` in the generated client or service skeleton files. @daneshk @MadhukaHarith92 @dilanSachi @shafreenAnfar WDYT?
> 
> yes, the world `sample` not looks good. These files are not complete ones. it is code snippets to startwith. Is there any other word we can use to imply these are template files

+1 to remove the `sample` from the generated sample service file (`helloWorld_sample_service.bal` -> `helloWorld_service.bal`). Instead of the file name, shall we add a comment to the sample code to indicate these are template files. eg:
```
import ballerina/grpc;

listener grpc:Listener ep = new (9090);

@grpc:ServiceDescriptor {descriptor: ROOT_DESCRIPTOR_HELLOWORLDSTRING, descMap: getDescriptorMapHelloWorldString()}
service "helloWorld" on ep {

    remote function hello(stream<string, grpc:Error?> clientStream) returns stream<string, error?>|error {
        // Implementation goes here.
    }
}
```

Users can remove the comment when implementing.

**Comment by BuddhiWathsala** [comment]
> > > **Description:** Following improvements identified in generated client/server sample files.
> > > ```
> > > * Client sample code imports `ballerina/grpc` which is a redundant import in simple code. Remove adding this import to the client sample code.
> > > 
> > > * Client/Service sample file name starts with Capital letter. Since all the bal files are created with simple letters, better we change it to simple letters with _ separater
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Affected Versions:** slbeta6
> > 
> > 
> > Regarding the 2nd point, the name of the sample service bal file is derived from the service name (<SERVICE_NAME>_sample_service.bal). For instance, for the following proto definition,
> > ```
> > syntax = "proto3";
> > import "google/protobuf/wrappers.proto";
> > service helloWorld {
> > 	rpc hello(stream google.protobuf.StringValue) returns (stream google.protobuf.StringValue);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The generated sample service file name is `helloWorld_sample_service.bal`.
> > @daneshk shall we change this to make the starting letter of the sample service file name simple when the starting letter of the service is capital as well?
> 
> Yes, let's make filename starts with simple letter in both cases.

Let say we have a service name as `HelloWorld`?. What would be the correct name for service and client files?

1. Option 01: `helloWorld_X_service.bal` & `helloWorld_X_client.bal`
2. Option 02: `helloworld_X_service.bal` & `helloworld_X_client.bal`
3. Option 03: `hello_world_X_service.bal` & `hello_world_X_client.bal`

Here `X` means some term to indicate this is a template or nothing as @MadhukaHarith92 suggested.

**Comment by dilanSachi** [comment]
I think `helloworld_service.bal` and `helloworld_client.bal` would be good

**Comment by BuddhiWathsala** [comment]
> Let say we have a service name as `HelloWorld`?. What would be the correct name for service and client files?
> 
> 1. Option 01: `helloWorld_X_service.bal` & `helloWorld_X_client.bal`
> 2. Option 02: `helloworld_X_service.bal` & `helloworld_X_client.bal`
> 3. Option 03: `hello_world_X_service.bal` & `hello_world_X_client.bal`
> 
> Here `X` means some term to indicate this is a template or nothing as @MadhukaHarith92 suggested.

I'm +1 for option 02 since we don’t know how users will name their services, for example option 01 and 03 becomes weird when we have services like `ABCService`.

**Comment by daneshk** [comment]
+1 for option 02

**Comment by daneshk** [comment]
> > > I wonder whether we need the term `sample` in the generated client or service skeleton files. @daneshk @MadhukaHarith92 @dilanSachi @shafreenAnfar WDYT?
> > 
> > 
> > yes, the world `sample` not looks good. These files are not complete ones. it is code snippets to startwith. Is there any other word we can use to imply these are template files
> 
> How about `template` or `skeleton`?

What is the filename of the service generated by openapi tool?

**Comment by BuddhiWathsala** [comment]
They don’t use such a term. When they generate Ballerina files from the spec, the names are as follows.
- `client.bal`
- `<given_openapi_spec>_service.bal`
- `util.bal ` & `types.bal`

**Comment by MadhukaHarith92** [comment]
> > > > I wonder whether we need the term `sample` in the generated client or service skeleton files. @daneshk @MadhukaHarith92 @dilanSachi @shafreenAnfar WDYT?
> > > 
> > > 
> > > yes, the world `sample` not looks good. These files are not complete ones. it is code snippets to startwith. Is there any other word we can use to imply these are template files
> > 
> > 
> > How about `template` or `skeleton`?
> 
> What is the filename of the service generated by openapi tool?

`petstore_service.bal` and `types.bal` was generated when executing `bal openapi -i petstore.yaml --mode service`

**Comment by daneshk** [comment]
Okay. Let's use the same and remove the word `sample` from the filename. @shafreenAnfar your thoughts?

**Comment by shafreenAnfar** [comment]
> Okay. Let's use the same and remove the word sample from the filename. @shafreenAnfar your thoughts?

Yeah, +1.

As @MadhukaHarith92 mentioned, to indicate this is a skeleton we can use a comment if needed.

**Comment by BuddhiWathsala** [comment]
ATM, our stub file name is `<PROTO_FILE_NAME>_pb.bal`. Should we make the `<PROTO_FILE_NAME>` also to the simple case to make is consistent with service and client file names. 

Normally, users name their the proto file name and the service name using a similar name. So to make the experience consistent, better to make it simple as well. For example, let say a user has a proto file named `helloWorld.proto` and the service name is `HelloWorld`, then (after the suggested changes) the generated files are like below.
1. `helloworld_service.bal`
2. `helloworld_client.bal`
3. `helloWorld_pb.bal` // Inconsistent

@daneshk @shafreenAnfar @MadhukaHarith92 @dilanSachi WDYT?

**Comment by daneshk** [comment]
Yes, this is a breaking change. Normally filenames are simple letters. Shall we not do that change now?
