### ISSUE TITLE
[gRPC][Tool] proto_path options is missing in cli help description.

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#2588]
**Description:**
The newly introduced --proto_path option is missing in cli help description. Shall we add it?

**Describe your task(s)**
`$ bal grpc --help` command

**Comment by BuddhiWathsala** [comment]
@daneshk, how about removing the `proxy` information from the `--mode` details since we don’t support it anymore?

**Comment by daneshk** [comment]
> @daneshk, how about removing the `proxy` information from the `--mode` details since we don’t support it anymore?

+1. Yes please remove it

**Comment by BuddhiWathsala** [comment]
Fixed with this https://github.com/ballerina-platform/ballerina-lang/pull/34686
