### ISSUE TITLE
Change the proto_path option of gRPC CLI to proto-path

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2590]
**Description:**
$title

Replace the term with a hyphen instead of the underscore.

Refer to the comment - https://github.com/ballerina-platform/ballerina-lang/pull/34686#discussion_r786455774

This will be a breaking change, @daneshk @shafreenAnfar @MadhukaHarith92 @dilanSachi

**Comment by daneshk** [comment]
@praminda Do you use this grpc command option in your application

**Comment by daneshk** [comment]
+1 to correct it now as we are not add this new option in public documents yet

**Comment by praminda** [comment]
No we are ok with the change

**Comment by BuddhiWathsala** [comment]
@daneshk I think we should change the `--protocVersion` option also to `--protoc-version`. I think it rarely has usages ATM.

**Comment by daneshk** [comment]
> @daneshk I think we should change the `--protocVersion` option also to `--protoc-version`. I think it rarely has usages ATM.

This is a hidden option ATM

**Comment by BuddhiWathsala** [comment]
Shouldn’t we need to change it to make it consistent with others?

**Comment by daneshk** [comment]
> Shouldn’t we need to change it to make it consistent with others?

Let's change it.
