### ISSUE TITLE
In `ballerina/time` in `time:utcFromString` the example is wrong

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-standard-library#2593]
**Description:**
$title

Given example is `2007-12-0310:15:30.00Z` and it must be corrected as `2007-12-03T10:15:30.00Z`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
I think we fixed this recently. @BuddhiWathsala can you check

**Comment by BuddhiWathsala** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/2494

Fixed in https://github.com/ballerina-platform/module-ballerina-time/pull/362
