### ISSUE TITLE
[Ballerina/sql] : Getting error while upgrading from slbeta3 to slbetat6

### ISSUE THREAD

**Issue by Shehanir** [ballerina-platform/ballerina-standard-library#2616]
**Description:**
I tried to upgrade the ballerina distribution from slbeta3 to slbeta6. While building the project I'm getting following error.

> error: compilation failed: The compiler extension in package 'ballerina:sql:1.2.0' failed to complete. class io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode cannot be cast to class io.ballerina.compiler.syntax.tree.UnaryExpressionNode (io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode and io.ballerina.compiler.syntax.tree.UnaryExpressionNode are in unnamed module of loader 'app')

I tried to built by removing cache and dependencies.toml as well

**Steps to reproduce:**
Upgrade projects which uses ballerina/sql module from slbeta3 to slbeta6

**Affected Versions:**
slbeta6

**Comment by niveathika** [comment]
This is already fixed for 2201.0.0 GA, tracked in https://github.com/ballerina-platform/ballerina-standard-library/issues/2536

If this cannot be migrated to 2201.0.0, you can use configurables to customize connection pool. https://lib.ballerina.io/ballerina/sql/1.2.0/records/ConnectionPool
