### ISSUE TITLE
Allow init function in gRPC services by the compiler plugin

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2617]
**Description:**
$title

**Comment by BuddhiWathsala** [comment]
Should we allow all the functions including `init` or only allow the `init` function? @daneshk @shafreenAnfar @dilanSachi WDYT?

**Comment by BuddhiWathsala** [comment]
> Should we allow all the functions including `init` or only allow the `init` function? @daneshk @shafreenAnfar @dilanSachi WDYT?

**Comment by shafreenAnfar** [comment]
AFAIU, services can have any type of functions ? @rdhananjaya any thoughts ?

**Comment by BuddhiWathsala** [comment]
Yes, normal functions are allowed in services. Then, I think it is better to allow all the normal functions and remote methods. We can disallow only the resource methods since those are not usable in the gRPC context.

**Comment by rdhananjaya** [comment]
If we disallow regular member functions, we are forcing the programmers to write large methods. I don't think that's a good thing to do.
