### ISSUE TITLE
Implement ftgo microservice application in Ballerina

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2651]
**Description:**
$subject

**Comment by daneshk** [comment]
Initial implementation can be found in https://github.com/kaneeldias/ballerina-microservices-example

Following Tasks need to complete,

[ ] Add test cases for each microservice(partially completed) #2736
[ ] Redo Readme file align with the other samples in https://github.com/ballerina-guides
[ ] Create a repository in the ballerina-guide organization and move the code there(Possible repo name: ftgo-microservices-application)

**Comment by daneshk** [comment]
This task is currently on hold due to other priorities. We will resume work soon.
