### ISSUE TITLE
[WebSub] Revisit/clean up BBEs

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-standard-library#266]
**Description:**
$title.

With the service integration sample, we should be able to restructure the other WebSub BBEs.

**Comment by ayeshLK** [comment]
We have done a full revamp of `websub module` for **Swan Lake Beta**  and this support is no longer available. Due to that reason, this BBE is outdated and removed already.

Hence we will close this issue.

**Comment by praneesha** [comment]
Closing as per the above comment.
