### ISSUE TITLE
gRPC load test shows an error rate

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#2663]
**Description:**
Previously all the 4 load tests in gRPC had around 0.5% error rates. After changing, concurrency options unary test and client streaming test are now passing with 0% error rate. But still the bidirectional streaming test shows around 0.2% error rate and server streaming test shows an error rate of 96%. Need to evaluate on this.

**Comment by dilanSachi** [comment]
Tested the scenario locally. Noticed that the pod gets killed after some time due to `OOMKilled` error. Apparently the pod goes out of memory for some reason. This only happened for server streaming scenario. After removing the query expressions [1] in the server streaming remote function, no errors were observed.

Btw did not notice this at the time of load test addition(noticed only around 0.5% error rate). Maybe the latest lang builds requires more memory for query expression evaluation.

@BuddhiWathsala any thoughts on this?

[1] https://github.com/ballerina-platform/module-ballerina-grpc/blob/6ef1fc3b8b0cd99b9c460d01b42f9c52f42ee931/load-tests/route_guide_server_streaming/src/routeguide_service.bal#L40

**Comment by dilanSachi** [comment]
And also, changed the query expression to a foreach.
```ballerina
//Feature[] selectedFeatures = from var feature in FEATURES
//    where feature.name != ""
//    where feature.location.longitude >= left
//    where feature.location.longitude <= right
//    where feature.location.latitude >= bottom
//    where feature.location.latitude <= top
//    select feature;
Feature[] selectedFeatures = [];
foreach Feature feature in FEATURES {
    if feature.name != "" && feature.location.longitude >= left && feature.location.longitude <= right
    && feature.location.latitude >= bottom && feature.location.latitude <= top {
        selectedFeatures.push(feature);
    }
}
```
Didnt see any error rate either

**Comment by shafreenAnfar** [comment]
@pcnfernando @gimantha FYI.

**Comment by BuddhiWathsala** [comment]
I reported this sometimes back, https://github.com/ballerina-platform/ballerina-lang/issues/34869
