### ISSUE TITLE
Proposal: OS Environment Variables related Operations

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#2666]
## Summary
At the moment, the Ballerina OS module only has APIs to retrieve environment variable information. However, it’s not possible to perform other operations such as setting new environment variables, listing them, and unsettling particular environment variables. In this proposal, we describe how these requirements can be fascilitated.

## Goals
To support setting, unsettling, and listing environment variables.

## Motivation

To allow users to manipulate environment variables programmatically.

## Description

```ballerina
# Represents OS module related errors.
public type Error distinct error;
```

- The `setEnv` function can be used to set any environment variable programmatically.

```ballerina
# Sets the value of the environment variable named by the key. 
# ```ballerina
# os:Error err = os:setEnv("BALCONFIGFILE", "/path/to/Config.toml");
# ```
#
# + key - Key of the environment variable
# + value - Value of the environment variable
# + return - error if setting the environment variable fails
public isolated function setEnv(string key, string value) returns Error
```

- Users can remove any particular environment variable from the system using the `unsetEnv` function.

```ballerina
# Removes a single environment variable from the system if it exists.
# ```ballerina
# var env = os:unsetEnv("BALCONFIGFILE");
# ```
#
# + name - Name of the environment variable
public isolated function unsetEnv(string key)
```

- To list the existing environment variables of the system, the `listEnv` function can be used. This would return the environment variables as a map.

```ballerina
# Returns a map of environment variables.
# ```ballerina
# map<string> envs = os:listEnv();
# ```
#
# + return - map of environment variables
public isolated function listEnv() returns map<string>
```

## Testing

- Set an environment variable using the `setEnv` function and validate if it was set correctly.
- Remove the previously created environment variable using the `unsetEnv` function can check whether it had been removed from the system correctly.
- Retrieve the list of environment variables by calling the `listEnv` function and check whether this returns a valid `map<string>`.

**Comment by BuddhiWathsala** [comment]
@MadhukaHarith92, what is the behaviour when someone passes a name of an existing env to the `setEnv` API?. Does it override or return an error?

**Comment by MadhukaHarith92** [comment]
> @MadhukaHarith92, what is the behaviour when someone passes a name of an existing env to the `setEnv` API?. Does it override or return an error?

Yes, it will be overridden and the environment variable will be set to the new value passed.

**Comment by daneshk** [comment]
what are the scenarios we can get errors when setting and unsettling env

**Comment by MadhukaHarith92** [comment]
> what are the scenarios we can get errors when setting and unsettling env

For `unsetEnv` an error will be returned if the given environment variable does not exist in the system. For the `setEnv` function there is no need of returning an error, hence updating the proposal.

**Comment by daneshk** [comment]
> 

for `unsetEnv`, shall we just remove if it exists and ignore if it is not. without giving an error. At the end, removed property should not be in the environment.

**Comment by BuddhiWathsala** [comment]
Just a heads up, C# follows a different approach to set and unset variables. Just curious why the proposed approach is better than this one [1] since we can support `string?` easily in Ballerina.

[1] https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-6.0

**Comment by MadhukaHarith92** [comment]
> > 
> 
> for `unsetEnv`, shall we just remove if it exists and ignore if it is not. without giving an error. At the end, removed property should not be in the environment.

+1, Updated the proposal.

**Comment by daneshk** [comment]
> Just a heads up, C# follows a different approach to set and unset variables. Just curious why the proposed approach is better than this one [1] since we can support `string?` easily in Ballerina.
> 
> [1] https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-6.0

check the exception they handled in `setEnv`, I think we need them. Regarding having one API, I think it is clean to have a separate API to `unset`, otherwise we have clearly mention in the doc

**Comment by daneshk** [comment]
@sameerajayasoma can you please review and give your input

**Comment by sameerajayasoma** [comment]
The `setEnv` function returns an `Error`. Is it `Error` or `error`? `Error` is not defined anywhere.

**Comment by sameerajayasoma** [comment]
An implementation-related question: Java does not have set or unset environment variable methods. How are we going to implement it in jBallerina?

**Comment by MadhukaHarith92** [comment]
> An implementation-related question: Java does not have set or unset environment variable methods. How are we going to implement it in jBallerina?

In both golang and python, the environment variable which is set is limited for the current application, i.e the variable gets applied for all the code subsequent to the API call but gets removed once the application is terminated.

Similar behavior can be implemented in jBallerina using `java.lang.reflect` as in this sample[[1]](http://www.java2s.com/example/java-api/java/lang/reflect/field/setaccessible-1-39.html).

[1] http://www.java2s.com/example/java-api/java/lang/reflect/field/setaccessible-1-39.html

**Comment by MadhukaHarith92** [comment]
> The `setEnv` function returns an `Error`. Is it `Error` or `error`? `Error` is not defined anywhere.

It is `os:Error`, updated the proposal with the `os:Error` definition.
> 
> What are the cases where `setEnv` returns errors?

The jBallerina function which updates the environment variables map may throw an exception. We thought of returning an `os:Error` in such situations.

**Comment by sameerajayasoma** [comment]
LGTM
