### ISSUE TITLE
Proposal: Error Handling

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#2669]
## Summary
Error handling is an integral part of any network program. Errors can be returned by many components such as interceptors, dispatcher, data-binder, security handlers, etc. This proposal is to discuss how to capture those errors and deal with them. 

## Goals
- Allow users to catch errors and deal with it

## Motivation

As mentioned in the summary section. In any network program, there can be errors returned by different components. These errors are often handled by a default handler and sent back as `500 Internal Server Error` with an entity-body. However, this often causes problems because when designing any API consistency matters. Therefore, all the responses must have a consistent format.

As a result, almost all the real API requires overriding the default error handler and replacing it with their own error handlers. At the moment HTTP library doesn't have a solid way of doing this.

## Description

Error handlers were briefly discussed in #692. Error handlers can be placed in the interceptor pipeline. These error handlers can catch any errors returned by the main service, interceptors, dispatcher, data-binder, security handlers, etc.  Whenever one of these components returns an error the execution jumps to the closest error handler in the interceptor pipeline. 

For instance, say the data-binder returned an error. In this case, because data binding happens just before dispatching to the service resource, the first error handler at the service level catches the error. If there is no error handler at the service level, the first error handler at the listener level catches the error.

There are two types of error handlers.
1. RequestErrorInterceptor
2. ResponseErrorInterceptor

### RequestErrorInterceptor
As the name says this type of error interceptor is only engaged in the request path. Following is how you can define one.

```ballerina
# The HTTP request error interceptor service object  
public type RequestErrorInterceptor distinct service object {};

service class RequestErrorInterceptor {
   *http:RequestErrorInterceptor;
 
   resouce function 'default [string… path](http:RequestContext ctx, http:Caller caller,
                       http:Request req, error err) returns http:RequestInterceptor|error? {
       // deal with the error
       return ctx.next();
   }
}
```
The only mandatory argument is `error` the rest are optional. Just like in the main service, it is possible to return values to send back HTTP responses. This terminates the request path and results in triggering the response path of the interceptor pipeline. Following is such an example.

```ballerina
service class RequestErrorInterceptor {
   *http:RequestErrorInterceptor;
 
   resouce function 'default [string… path](error err) returns http:NotFound  {
       http:NotFound nf = { body: { msg: err.message()} };
       return nf;
   }
}
```

### ResponseErrorInterceptor
As the name says this type of error interceptor is only engaged in the response path. Following is how you can define one.
```ballerina
# The HTTP response error interceptor service object  
public type ResponseErrorInterceptor distinct service object {};

service class ResponseErrorInterceptor {
   *http:ResponseErrorInterceptor;
 
   remote function interceptResponseError(http:RequestContext ctx,
                       http:Response res, error err) returns http:ResponseInterceptor|error? {
       // deal with the error
       return ctx.next();
   }
}
```
The only mandatory argument is `error` the rest are optional. Just like in the main service, it is possible to return values to send back HTTP responses. This overrides the current response and results in triggering the next immediate response interceptor. Following is such an example.

```ballerina
service class ResponseErrorInterceptor {
   *http:ResponseErrorInterceptor;
 
   remote function interceptResponseError(error err) returns http:NotFound {
       http:NotFound nf = { body: { msg: err.message()} };
       return nf;
   }
}
```
It is possible to get hold of the original response using the argument `http:Response res` and then alter the response headers and the body. However, in that case, the OpenAPI tool will not be able to capture those changes. 

**Note**: The best way to catch all the errors is by having a `ResponseErrorInterceptor` at the `Listener` level.

**Comment by shafreenAnfar** [comment]
Originally there was a proposal to allow something similar to the below function in `http:Services` to handle errors.

```ballerina
remote function handleError(error err) returns anydata {}
```
However, cons of this approach are,

- When the actual service is not available there is no way to intercept 404 response from the listener
- Inconsistent with interceptor error handling which means user needs to learn more
- Service gets polluted with error handing logic. Mainly because service is mostly about implementing resources and its logic.

**Comment by shafreenAnfar** [comment]
@sameerajayasoma do comment if you have any feedback.

**Comment by sameerajayasoma** [comment]
Looks good as per the offline chat last week with @shafreenAnfar.  I missed updating the issue.

Btw, can we always have the default `ResponseErrorInterceptor ` at the listener level no matter what? It'll help us to catch errors raised at other error interceptors.

**Comment by chamil321** [comment]
> Originally there was a proposal to allow something similar to the below function in `http:Services` to handle errors.
> 
> ```ballerina
> remote function handleError(error err) returns anydata {}
> ```
> 
> However, cons of this approach are,
> 
> * When the actual service is not available there is no way to intercept 404 response from the listener
> * Inconsistent with interceptor error handling which means user needs to learn more
> * Service gets polluted with error handing logic. Mainly because service is mostly about implementing resources and its business logic.

+1 for this approach rather having separate function in each service. The interceptor can handle it properly with our current implementation.

**Comment by TharmiganK** [comment]
Errors returned from HTTP module : 

<table>
<thead>
  <tr>
    <th></th>
    <th>Error</th>
    <th>Level</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="5">Executing Interceptors</td>
    <td>500 - no next service to be returned</td>
    <td rowspan="5">Interceptor</td>
  </tr>
  <tr>
    <td>500 - request context object does not contain the configured interceptors</td>
  </tr>
  <tr>
    <td>500 - next interceptor service did not match with the configuration</td>
  </tr>
  <tr>
    <td>500 - target service did not match with the configuration</td>
  </tr>
  <tr>
    <td>Other internal errors when executing resource/remote functions</td>
  </tr>
  <tr>
    <td rowspan="3">Finding Service</td>
    <td>404 - no service has registered for listener</td>
    <td rowspan="3">Listener</td>
  </tr>
  <tr>
    <td>404 - no matching service found for path</td>
  </tr>
  <tr>
    <td>500 - Found non-matrix parameter in path</td>
  </tr>
  <tr>
    <td rowspan="2">Finding Resource</td>
    <td>404 - no matching resource found for path</td>
    <td rowspan="2">Service</td>
  </tr>
  <tr>
    <td>405 - Method not allowed</td>
  </tr>
  <tr>
    <td rowspan="5">Databinding</td>
    <td>500 - Error in casting path param</td>
    <td rowspan="5">Service</td>
  </tr>
  <tr>
    <td>400 - no query param value found</td>
  </tr>
  <tr>
    <td>500 - Error in casting query param </td>
  </tr>
  <tr>
    <td>400 - no header value found</td>
  </tr>
  <tr>
    <td>400 - data binding failed</td>
  </tr>
  <tr>
    <td rowspan="2">Security</td>
    <td>401 - Unauthorized errors</td>
    <td rowspan="2">Resource</td>
  </tr>
  <tr>
    <td>403 - Forbidden errors</td>
  </tr>
  <tr>
    <td>Resource execution</td>
    <td>500 - Internal errors</td>
    <td>Resource</td>
  </tr>
  <tr>
    <td rowspan="15">Transport</td>
    <td>500 - Remote client closed the connection</td>
    <td rowspan="15">Transport</td>
  </tr>
  <tr>
    <td>500 - Remote host closed the connection</td>
  </tr>
  <tr>
    <td>500 - Connection between remote client and host is closed</td>
  </tr>
  <tr>
    <td>500 - Connection between client and remote host is closed</td>
  </tr>
  <tr>
    <td>500 - Promised stream is already rejected or stream is no longer valid</td>
  </tr>
  <tr>
    <td>500 - Could not obtain a connection within maximum wait time</td>
  </tr>
  <tr>
    <td>500 - Inbound response message already received</td>
  </tr>
  <tr>
    <td>502 - Could not resolve host</td>
  </tr>
  <tr>
    <td>502 - SSL connection failed</td>
  </tr>
  <tr>
    <td>502 - Remote host closed the connection while SSL handshake</td>
  </tr>
  <tr>
    <td>413 - Request entity too large</td>
  </tr>
  <tr>
    <td>414 - Request uri too large</td>
  </tr>
  <tr>
    <td>431 - Request Header Fields Too Large</td>
  </tr>
  <tr>
    <td>Idle timeout triggerred errors</td>
  </tr>
  <tr>
    <td>505 - HTTP version not supported</td>
  </tr>
</tbody>
</table>

**Comment by TharmiganK** [comment]
```ballerina
service class DefaultErrorInterceptor {
    *http:ResponseErrorInterceptor;

    remote function interceptResponseError(error err) returns http:Response {
        http:Response res = new;
        res.setTextPayload(err.message());
        // By default, the error response is set to 500 - Internal Server Error
        // However, if the error is an internal error which has a different error
        // status code (4XX or 5XX) then this 500 status code will be overwritten 
        // by the original status code.
        res.statusCode = 500;
        return res;
    }
}
```

The above error interceptor can be added as the default response error interceptor to the pipeline and this will be placed as the first interceptor i.e. this will be executed at last if the injected error is not handled by any other error interceptors.

@shafreenAnfar @chamil321 Please add thoughts if you think otherwise

**Comment by shafreenAnfar** [comment]
I have some questions with regard to transport level errors. Because those errors should/could not end up being HTTP status codes errors.

**Comment by TharmiganK** [comment]
With this proposal the following are implemented:
- [Introduced error interceptors and incorporated proposed error handling logic](https://github.com/ballerina-platform/module-ballerina-http/pull/924)
- [Introduced the default interceptor](https://github.com/ballerina-platform/module-ballerina-http/pull/964)
- [Added an `Error Handling` BBE](https://github.com/ballerina-platform/ballerina-distribution/pull/2677)

With this implementation, all of the errors **except the transport level errors** can be intercepted and handled by error interceptors placed in the pipeline and when there is no user defined error interceptors, then the **default error interceptor** will get invoked.

**Comment by shafreenAnfar** [comment]
I think we can close all the respective issues and create a new issue to track the transport level errors. I think we need to start working on it and complete the task. Let's go through the priority list and decide.

**Comment by TharmiganK** [comment]
Created an issue to track the transport level error handling, hence closing this issue
