### ISSUE TITLE
Enum with a Ballerina keyword has incorrect record generation in gRPC CLI

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2678]
**Description:**
#### Case 01
Let's say I have an enum in a proto as below.

```proto
message CallState {
  enum State {
    UNDEFINED = 0;
    NEW = 1;
  }
  State state = 2;
}
```

The relevant Ballerina enum the gRPC CLI generates is,

```ballerina
public enum CallState_State {
    UNDEFINED,
    'NEW
}
```

#### Case 02
Let's say I have an enum in a proto as below.

```proto
message CallState {
  enum State {
    undefined = 0;
    new = 1;
  }
  State state = 2;
}
```
Then, the relevant Ballerina enum the gRPC CLI generates is,

```ballerina
public enum CallState_State {
    undefined,
    'new
}
```

Both cases 01 and 02 will fail at the runtime. The workaround to fix this issue is to set values for enums as follows.

```ballerina
public enum CallState_State {
    UNDEFINED,
    'NEW = "NEW"
}
// OR
public enum CallState_State {
    undefined,
    'new = "new"
}
```

I think, in case 01, we shouldn’t escape the `NEW` since it is not exactly a keyword, and having `NEW` instead of `'NEW` won’t break the code.

But the case 02 can be fixed by changing CLI to generate the workarounds I previously suggested or even it has to be fixed at the language level. IMO, the language fix would be more effective.
https://github.com/ballerina-platform/ballerina-lang/issues/35035

**Steps to reproduce:**
Try to run a gRPC sample using the following proto.
```proto
syntax = "proto3";

message CallInfo {
  string session = 1;
  string new = 2;
}

message CallState {
  enum State {
    UNDEFINED = 0;
    NEW = 1;
  }
  State state = 2;
}

service Phone {
  rpc UnaryCall(CallInfo) returns (CallState);
}
```

**Affected Versions:**
- SL GA
- Ballerina gRPC 1.2.0

**OS, DB, other environment details and versions:**
- macOS

**Comment by BuddhiWathsala** [comment]
@daneshk @shafreenAnfar @MadhukaHarith92 @dilanSachi WDYT?.

**Comment by dilanSachi** [comment]
If we change the CLI to work with the workaround, we will have to change it again once the lang level fix is completed right?

**Comment by BuddhiWathsala** [comment]
> I think, in case 01, we shouldn’t escape the `NEW` since it is not exactly a keyword, and having `NEW` instead of `'NEW` won’t break the code.

I thought not to address that part, but to change the following,

> I think, in case 01, we shouldn’t escape the NEW since it is not exactly a keyword, and having NEW instead of 'NEW won’t break the code.

**Comment by BuddhiWathsala** [comment]
The much better workaround for this is the following code which removes the apostrophe. That workaround won’t break after the fix, the workaround I mentioned above will break for `'NEW` cases.

The correct workaround.

Current code,
```ballerina
public enum CallState_State {
    UNDEFINED,
    'NEW
}
```

Using the following as a workaround is not a good solution for this case.
```ballerina
public enum CallState_State {
    UNDEFINED,
    'NEW = "NEW"
}
```

Instead, it is better to use the following workaround,
```ballerina
public enum CallState_State {
    UNDEFINED,
    NEW
}
```
