### ISSUE TITLE
Easy way to add liveness and readiness probs in k8s

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#2682]
At the moment, Ballerina services do not have anything inbuilt to support this. I think doing something similar to Spring Boot Actuator might be useful.

**Comment by xlight05** [comment]
Currently, In Cloud.toml we have a property for specifying readiness and liveness probe and we generate k8s probes based on that. https://github.com/ballerina-platform/module-ballerina-c2c/tree/master/samples/sample6

Additionally, we have tooling support to generate a Cloud.toml entry from code and the other way around. 

Are we thinking of a different approach here?
