### ISSUE TITLE
Empty record is not being generated from proto

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-standard-library#2685]
**Description:**
Consider the following sample. 
```proto
message Empty {}
```
This does not get converted to ballerina record with the grpc tool. 

I think this is needed as its being used in few scenarios. 
https://github.com/GoogleCloudPlatform/microservices-demo
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/empty.proto

https://stackoverflow.com/questions/31768665/can-i-define-a-grpc-call-with-a-null-request-or-response

**Affected Versions:**
SL GA
**OS, DB, other environment details and versions:**

**Comment by daneshk** [comment]
@xlight05 can you explain the steps you follow. Normally this proto file is a dependent proto for another service proto file, as this contains only message definition. Can you try generating the source code for the service proto file which contains the `Empty` message?

**Comment by daneshk** [comment]
FYI, we have written a couple of services in the `Online Boutique` in Ballerina [1].  Please check it out

1. https://github.com/ballerina-platform/module-ballerina-grpc/tree/master/examples/online-boutique-microservice

**Comment by xlight05** [comment]
@daneshk  I've simply downloaded [this](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/pb/demo.proto) proto files and generated ballerina services required, using,
`bal grpc --mode service --input demo.proto --output demo_service/`

**Comment by BuddhiWathsala** [comment]
@xlight05, I tried your sample and I encountered the same issue. We'll look into that.

**Comment by BuddhiWathsala** [comment]
Creating the following record in the stub (i.e., `*_pb.bal`) file would be the workaround to fix this issue. 

```ballerina
public type Empty record {|
|};
```

**Comment by BuddhiWathsala** [comment]
Sample to reproduce the issue,
```proto
syntax = "proto3";

import "google/protobuf/wrappers.proto";

service ServiceWithEmpty {
    rpc UnaryCall(google.protobuf.StringValue) returns (Empty) {}
}

message Empty {}
```
