### ISSUE TITLE
Proposal: Introduce APIs to extract a substring/s from the given string

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2689]
## Summary
The Ballerina Regex module doesn't have any API to extract a substring/s from the given string by using regex. So, this proposal introduces new APIs to extract a substring/s from the given string using regex.

## Goals

- Provide a way to extract a substring/s using regex.

## Motivation
As mentioned in the summary, at the moment, users have no way to extract a substring/s from the given string. But this is an important feature in string manipulation. So, this allows users to extract a substring/s easily by using Ballerina. 

## Description
```ballerina
# Match record contains the information of an extracted sub-string.
#
# + value - the actual value of the match
# + startIndex - the start index of the match
# + endIndex - the last index of the match
public type Match record{|
    string value; // Do we need this??
    int startIndex;
    int endIndex;
|};
```

- The `find` function can be used to extract the first sub-string from a given string that is only matched with the given regex.

```ballerina
# Extracts the first sub-string from a given string that is only matched with the given regex.
# ```ballerina
# regex:Match? result = regex:find("\"\"Hello my Number is 123456789 and my friend's number is 987654321\"\"", "\\d+");
# ```
#
# + str - The string to match the regex
# + regex - The regex to match the string
# + return - The `Matcher` if the provided string matches the regex or else nil
public isolated function find(string str, string regex) returns Match? {}
```

- The `findAll` function can be used to extract all sub-strings from a given string that are only matched with a given regex.
```ballerina
# Extracts all sub-strings from a given string that are only matched with a given regex.
# ```ballerina
# regex:Match[] res = regex:findAll("\"\"Hello my Number is 123456789 and my friend's number is 987654321\"\"", "\\d+");
# ```
#
# + str - The string to match the regex
# + regex - The regex to match the string
# + return - The array of `Matcher` if the provided string matches the regex or else nil
public isolated function findAll(string str, string regex) returns Match[] {}
```

**Comment by daneshk** [comment]
Few suggestions: 

* Shall we rename the `find` function to `findFirst`, as we are returning only the first substring
* Shall we rename the first input param to `originalString` instead of `stringToFind`
* Shall we just return the string value without start and end index. If the user needs the starting index, he/she can use the `indexOf` function in strings.

**Comment by kalaiyarasiganeshalingam** [comment]
> Few suggestions:
> 
> * Shall we rename the `find` function to `findFirst`, as we are returning only the first substring
> * Shall we rename the first input param to `originalString` instead of `stringToFind`
> * Shall we just return the string value without start and end index. If the user needs the starting index, he/she can use the `indexOf` function in strings.

Updated the proposal now.

**Comment by jclark** [comment]
Better would be:

```
public type Match record {|
    string value; // XXX not great
    int startIndex;
    int endIndex;
|};

public isolated function find(string str, string regex) returns Match? {}
public isolated function findAll(string str, string regex) returns Match[] {}
```

**Comment by kalaiyarasiganeshalingam** [comment]
> Better would be:
> 
> ```
> public type Match record {|
>     string value; // XXX not great
>     int startIndex;
>     int endIndex;
> |};
> 
> public isolated function find(string str, string regex) returns Match? {}
> public isolated function findAll(string str, string regex) returns Match[] {}
> ```

Updated the proposal.

**Comment by daneshk** [comment]
@sameerajayasoma can you please review the proposal and give your input.

**Comment by sameerajayasoma** [comment]
Did we consider the option of compiling the regex first and then performing these operations against that compiled representation?  Why did we decide to go with separate module-level methods?

**Comment by daneshk** [comment]
I like to categorize this as two levels of support. one is the simplified version of full-featured functions like we have now and what we proposed in the regex module. The other one is the complied version, where the user needs to compile the regex pattern and do operations on top of it. We are thinking of supporting both like in python[1].

We have a plan of supporting to compile the regex pattern first and perform the operations. We will create a separate design proposal for it. Considering the requirement and level we support already, we consider adding these two new method level methods.

WDYT?  

1. https://docs.python.org/3/library/re.html#module-contents

**Comment by buehlefs** [comment]
If possible the `Match` record should also contain information about matched regex groups. This is especially useful when using named groups to extract multiple substrings out of a single match where one is not interested in the complete match.

Example (using python syntax):
```python
input = "http://localhost/user/2/order/5"
regex = r"^http://localhost/user/(?P<userId>\d+)/order/(?P<orderNr>\d+)$"
match = re.match(regex, input)
match[0] # "http://localhost/user/2/order/5"
match["userId"] # "2"
match.groupdict() # {"userId": "2"}, {"orderNr": "5"})
```

**Comment by jclark** [comment]
@buehlfs That is a very useful feature. My only concern is that if we support groups plus the `\N` syntax to refer to groups, then the language described by the regular expression is no longer regular, and it is no longer possible to decide whether the set of strings matched by one subexpression is a subset of the set of strings matched by a regular expression. This would limit the extent to which we could integrate regular expressions into the type system.

**Comment by buehlefs** [comment]
@jclark I believe that everything that will be matched would be a string from the type system viewpoint. Groups are already supported by the replace function of the regex module, as well as references to matched groups in the replaced string. Just exposing that information in a map like structure should work for named groups, for unnamed groups an array should work as well. As I have never needed to use the `\N` syntax to refer to a group match in the same match I would not mind if it was not supported. This kind of use case could be left to external regular expression libraries.
For the regular expressions themselves python uses raw string literals `r""` that are normal strings but need less escaping characters to write. In the javascript world we have the `/regex/` syntax that directly creates a regex object (similar to pythons `re.compile(r"regex")`).

Also I don't think that there is much use in the compiler knowing if a regular expression matches a strict subset of the matches of another regular expression. Testing if a string can be parsed as a number could use dedicated methods. Testing if a string is a specific string literal could just use equality tests (or something like the `"someString" in {"a", "b", "c"}` syntax from python). Using regex for these kind of tests would be using the wrong tool in my opinion.

**Comment by sameerajayasoma** [comment]
@jclark Agreed. Let's add the proposed functions for now.

**Comment by sameerajayasoma** [comment]
Here are the function definitions with updated documentation.

```ballerina
#  A Match holds the matched substring and its position in the input string.
#
# + value - matched substring
# + startIndex - the start index of the match
# + endIndex - the last index of the match
public type Match record{|
    string value; 
    int startIndex;
    int endIndex;
|};

# Returns the leftmost substring in str that matches the regex. 
# ```ballerina
# regex:Match? result = regex:find("Betty Botter bought some butter but she said the butter’s bitter.", "\\b[bB].tt[a-z]*");
# ```
#
# + str - the string to be matched
# + regex - the regex
# + return - a `Match` record which holds the matched substring, or nil if there is no match
public isolated function find(string str, string regex) returns Match? {}

# Returns all substrings in str that match the regex. 
# ```ballerina
# regex:Match[] result = regex:findAll(""Betty Botter bought some butter but she said the butter’s bitter.", "\\b[bB].tt[a-z]*");
# ```
#
# + str - The string to be matched
# + regex - The regex
# + return - an array of `Match` records
# Each member holds a matched substring
public isolated function findAll(string str, string regex) returns Match[] {}
```

**Comment by jclark** [comment]
> Also I don't think that there is much use in the compiler knowing if a regular expression matches a strict subset of the matches of another regular expression.

@buehlefs It's useful because that is what is needed to allow the regular expression to be used as a type.

**Comment by daneshk** [comment]
I changed the function definition based on the Jame's input and function names are also changed to `search` and `searchAll` to align with the proposed design. (We are planning to add these functions to the existing module till we move it to the language level)

```
#  Holds the matched substring and its position in the input string.
#
# + matched - Matched substring
# + startIndex - The start index of the match
# + endIndex - The last index of the match
type PartMatch record {|
   string matched;
   int startIndex;
   int endIndex;
|};

# Holds information about matched regex groups
public type Groups readonly & object {
   int count;
   // Capture groups are indexed from 1
   // Group 0 means whole regex
   // Panics if i < 0 or > count
   isolated function get(int i) returns PartMatch?;
};

# Holds the results of a match against a regular expression. 
# It contains the match boundaries, groups and group boundaries.
#
# + groups - Information about matched regex groups
public type Match record {|
    // The match for the whole regex
   *PartMatch;
   Groups groups;
|};

# Returns the first substring in str that matches the regex.
# ```ballerina
# regex:Match? result = regex:search("Betty Botter bought some butter but she said the butter’s bitter.", "\\b[bB].tt[a-z]*");
# ```
#
# + str - The string to be matched
# + regex - The regex value
# + startIndex - The starting index for the search
# + return - a `Match` record which holds the matched substring, or nil if there is no match
public isolated function search(string str, string regex, int startIndex = 0) returns Match? {
}

# Returns all substrings in str that match the regex. 
# ```ballerina
# regex:Match[] result = regex:searchAll(""Betty Botter bought some butter but she said the butter’s bitter.", "\\b[bB].tt[a-z]*");
# ```
#
# + str - The string to be matched
# + regex - The regex value
# + return - An array of `Match` records
# Each member holds a matched substring
public isolated function searchAll(string str, string regex) returns Match[] {}
```

and the existing replace functions will change like below,

```
# A function to be invoked to create the new substring to be used to replace the matches.
type ReplacerFunction function(Match 'match) returns string;

# A function to be invoked to create the new substring or string value to be used to replace the matches.
public type Replacement ReplacerFunction|string;

public isolated function replaceAll(string originalString, string regex, Replacement replacement) returns string {}

public isolated function replaceFirst(string originalString, string regex, Replacement replacement) returns string {}
```

@jclark @sameerajayasoma Shall we proceed with these changes

**Comment by jclark** [comment]
I think we want a replace function that takes the index to start from. Maybe replace or replaceFrom (should be consistent with search).

We should call the parameter in the ReplacerFunction something other than `match` (I had forgotten it was a keyword): maybe `matched`.

ECMAScript has a matchAll function that seems pretty similar to our searchAll, so I am wondering whether searchAll is the right name.

We need to be clear about anchoring semantics.  Does `match` mean look for a match anywhere? Or does `match` mean the whole string matches the regular expression?

**Comment by daneshk** [comment]
> I think we want a replace function that takes the index to start from. Maybe replace or replaceFrom (should be consistent with search).

To be consistent with the search function, Shall we make it `replace`. We will deprecate the existing `replaceFirst` function and introduce a new `replace` function with starting index.

>  
> We should call the parameter in the ReplacerFunction something other than `match` (I had forgotten it was a keyword): maybe `matched`.

+1 for matched. I will do the change.

> 
> ECMAScript has a matchAll function that seems pretty similar to our searchAll, so I am wondering whether searchAll is the right name.
> 
> We need to be clear about anchoring semantics. Does `match` mean look for a match anywhere? Or does `match` mean the whole string matches the regular expression?

We will check on this further and get back.

**Comment by jclark** [comment]
The way it seems to work in most languages is that the regex isn't anchored.

So a string `hello` matches a regex `hell`.  In other words, `matches` means "matches anywhere".  This is the same as what happens with traditional Unix tools. If I use a regex `/foo/` in e.g. sed, it will search for `foo` anywhere on the line.

To require the whole input to match the regex, you have to use anchoring `^hell$`.

Normally, `^` and `$` will match only the beginning and end of the input string.  But there's a `m` flag (for multiline), that causes them to match also at the beginning and end of a line respectively.

Related is `s` flag (for single-line). By default `.` matches anything other than a line-terminator: the `s` flag changes it so that it matches anything.

**Comment by kalaiyarasiganeshalingam** [comment]
Following are my observations regarding the match,

According to the [Wiki page](https://en.wikipedia.org/wiki/Regular_expression) `A match is made, not when all the atoms of the string are matched, but rather when all the pattern atoms in the regex have matched.`. AFAIU, Which means `match` refers to testing whether there is an occurrence of the regular expression anywhere within the text.

We also checked different other languages. Following are the observations,

- [Golang](https://pkg.go.dev/regexp#Regexp.Match) has `find`, `findAll`, `findAllIndex`, `findAllString` etc functions to look for a match anywhere in the text.
- [Python](https://docs.python.org/3/library/re.html#regular-expression-objects) has the following functions to look for a match
    - `match`: It looks for a match only at the beginning of the text. Same as `^` regex syntax
    - `search` and `findAll`: Those look for a match anywhere in the text.
    - `fullMatch`: It looks for a whole string match. 
- [ECMAScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) has `match` and `matchAll` functions to look for a match anywhere in the text and `search` is used to get the index of the match anywhere in the string.

For the `search` and `searchAll` functions, I suggest going with the `find` and `findAll` functions like Golang to match anywhere. We do have `replace` and `replaceAll` functions. Find and Replace are commonly used in most places like IDEs, text editors, etc.

**Comment by jclark** [comment]
The go names are for methods on the RegExp. These names work for that. What you are doing to the RegExp is finding it in the string.

However, that's not the case here. The string is the first argument.  We are doing something to the string.  What we are doing to the string is searching it for the RegExp.

So I don't think find and findAll are a good choice.

**Comment by daneshk** [comment]
Understood. Thanks, James

Shall we then use `match` and `matchAll` functions to extract the first occurrence and all occurrences that match the regex anywhere in the input string?

We currently have a `matches` function that returns a boolean value to check whether the whole input string matches the regex. Shall we rename it to `fullMatch`?

Appreciate your input

**Comment by daneshk** [comment]
@jclark @sameerajayasoma Can you help us finalize the names of the functions, please.

**Comment by jclark** [comment]
We don't want a function called `match` because it's a keyword.

I think `search` works well as the name of a function that looks for matches anywhere in the string. You are searching a string for a regex. It is clear that it is not anchored. (In English, the object of `search` is where you are searching, whereas the object of `find` is what you are searching for.) 

I would leave `matches` as is. This does an anchored match, right? In other words, `s.matches("xyz")` is true if `s.search("^xyz$")` is non-nil.

You can't rename `matches` to `fullMatch` without a major version change. We don't want to do that do we?

**Comment by daneshk** [comment]
Thanks a lot, James.

We will proceed as suggested.

> 
> I would leave `matches` as is. This does an anchored match, right? In other words, `s.matches("xyz")` is true if `s.search("^xyz$")` is non-nil.

Yes, it is an anchored match.

> 
> You can't rename `matches` to `fullMatch` without a major version change. We don't want to do that do we?

Yes, we only can depreciate the current one. introduce the new function now. Remove it completely in the next major version.

**Comment by kalaiyarasiganeshalingam** [comment]
This proposal is implemented with this [PR ](https://github.com/ballerina-platform/module-ballerina-regex/pull/377)
