### ISSUE TITLE
Invalid First parameter must be caller type diagnostic

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-standard-library#2695]
**Description:**
I'm not sure if this is a bug, or not sure if i should place these methods here, so correct me if i'm wrong.

When I create a normal function inside grpc service, with two parameters I get a diagnostic like saying `when there are two parameters to a remote function, the first one must be a caller type`. This function is not marked as remote (see the getUserCart method). 
![Screenshot from 2022-02-15 19-23-11](https://user-images.githubusercontent.com/23274047/154076791-bddc2a83-077c-4791-8b70-371efeaef43c.png)

**Steps to reproduce:**
```bal
service "CheckoutService" on ep {

    remote function PlaceOrder(PlaceOrderRequest value) returns PlaceOrderResponse|error {
         .....
          self.getUserCart("hello","USD");
    }

    function getUserCart (string userId, string userCurrency) returns CartItem[]|error {
           ....
    }
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
Seems like a bug. compiler validation should only run for remote functions, not normal functions. @BuddhiWathsala please check.
In the meantime, can you write the logic inside the remote function?
