### ISSUE TITLE
Improve data binding

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#2700]
Data binding needs to be improved as in https://github.com/ballerina-platform/ballerina-standard-library/issues/2530#issuecomment-1011271021

**Comment by chamil321** [comment]
Following types are supported with the introduction of `anydata`

Ballerina Type | Basic Type | Array Type | Map Type | Table Type | 
-- | -- | -- | -- | --
boolean | ✅ | ✅ | ✅|✅
int | ✅ | ✅ | ✅|✅
float | ✅ | ✅ | ✅|✅
decimal | ✅ | ✅ | ✅|✅
byte[] | ✅ | ✅ | ✅|✅
string|✅|✅|✅|✅
xml|✅|✅|✅|✅
json|✅|✅|✅|✅
map|✅|✅|✅|✅
record|✅|✅|✅|✅
array|✅|✅|✅|❌
table|✅|✅|✅|❌
