### ISSUE TITLE
Add ORM support in Ballerina 

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#2702]
**Description:**
Create a new library to support ORM on top of Ballerina SQL connectors

**Comment by niveathika** [comment]
The following subtasks needs to be completed,
- [ ] Research on existing ORM modules
    - [ ] GORM
    - [ ] sqlx
    - [ ] Hibernate
    - [ ] JPA
    - [ ] Castor
    - [ ] sequalize
    - [ ] jHipster
- [ ] Research on existing Low Code Editors using database connectivity
- [ ] Proposing the design
- [ ] Implementation

**Comment by daneshk** [comment]
Please find the updated design document https://docs.google.com/document/d/1hDa9pTZYmT3GbGdUrFZCaOenGIsTc5P9/edit#heading=h.gjdgxs

**Comment by niveathika** [comment]
Closing this as basic persist support is implemented in https://github.com/ballerina-platform/module-ballerina-persist
