### ISSUE TITLE
Panic inside a resource function does not kill the application

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-standard-library#2714]
**Description:**
Came up during a code review session, Consider the following sample.

```bal
service / on new http:Listener(8900) {
    resource function get greeting() returns string {
        panic error("test panic");
    }
}
```
When the following resource function is invoked the application is not killed. It simply prints an error in the log. 
Is this intended? Platforms like Kubernetes automatically restart the pod if it is killed.

@shafreenAnfar

**Comment by shafreenAnfar** [comment]
I think when the code panics it is better to crash the service. As @xlight05 mentioned it will result in a crash loop, crash loop results in alerts (in proper deployment). Alerts results in human attention. I think that is what we need for services that panics. 

@sameerajayasoma @chamil321 any thoughts.

**Comment by sameerajayasoma** [comment]
Panics are abnormal errors. It makes sense to kill the instance when a panic happens.

**Comment by chamil321** [comment]
Since the panic is an unrecoverable error, Shall we call `System.exit()` rather stopping listeners individually. 
@warunalakshitha Do we have such function which is provided by the lang runtime?

**Comment by shafreenAnfar** [comment]
I think what you explained above falls under normal errors but panics are abnormal errors. Here is what James' slide deck says "Abnormal errors should typically result in immediate program termination". 

> we call System.exit() rather stopping listeners individually.

Even if you stop the listeners, eventually you need to immediately terminate the program. Therefore, we can start with terminating.

**Comment by warunalakshitha** [comment]
IMO calling System.exit is wrong since that will skip properly shutdown of the ballerina program including scheduler, module stops and any other cleanup etc. Panics are abnormal errors but if main strand does not have impact ATM we do not terminate the program.

As an example we do not terminate the program if name worker panic unless you wait on the worker.

Shall we creare a spec issue and discuss there?

**Comment by warunalakshitha** [comment]
May be it should be a internal server response (5XX)

**Comment by chamil321** [comment]
@jclark Could you please shade some light here. 

The question is, should the application (A service in this context) be terminated when a panic occurs from a resource function?

```ballerina
service / on new http:Listener(8900) {
    resource function get greeting() returns string {
        panic error("test panic");
    }
}
```
Current behaviour is similar to error return and does stop the listener.

**Comment by jclark** [comment]
A panic means either an application bug or resource exhaustion. If there's an application bug, then the application state may be in an inconsistent state and it is not safe to continue executing. I would expect `panic` to terminate the application.  If the user doesn't want this they should explicitly trap the panic. 

If a resource function returns an error, then the HTTP listener should report an error to the client, but continue to handle other requests.

**Comment by chamil321** [comment]
> A panic means either an application bug or resource exhaustion. If there's an application bug, then the application state may be in an inconsistent state and it is not safe to continue executing. I would expect `panic` to terminate the application. If the user doesn't want this they should explicitly trap the panic.
> 
> If a resource function returns an error, then the HTTP listener should report an error to the client, but continue to handle other requests.

Appreciate the input and it aligns with initial suggestion. We can proceed accordingly.
