### ISSUE TITLE
Introduce Dataloader for GraphQL Package 

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#2731]
**Description:**

When a GraphQL resolver has to call a database, there can be occasions where an initial query returns a set of keys to retrieve data from an additional query. Usually, a GraphQL resolver does not have access to other information except for their own parent. Therefore, this will cause another `n` calls to the DB. (The `n + 1` problem). 

To resolve this, the *__dataloader__* concept is introduced. In Ballerina too, we should introduce this. 

References:

* [N + 1 Problem](https://medium.com/the-marcy-lab-school/what-is-the-n-1-problem-in-graphql-dd4921cb3c1a)
* [Data Loader](https://github.com/graphql/dataloader)
* [Solving the n + 1 Problem Using Batching](https://shopify.engineering/solving-the-n-1-problem-for-graphql-through-batching)

**Comment by ThisaruGuruge** [comment]
Proposal: https://github.com/ballerina-platform/ballerina-standard-library/issues/3391

**Comment by MohamedSabthar** [comment]
After making improvement https://github.com/ballerina-platform/ballerina-standard-library/issues/4122, we plan to proceed with the implementation.

**Comment by MohamedSabthar** [comment]
New design proposal available here: https://github.com/ballerina-platform/ballerina-standard-library/issues/4569

**Comment by ThisaruGuruge** [comment]
Closing as per the above.
