### ISSUE TITLE
Function name `matches` in `ballerina/regex` package does not follow function naming guidelines

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-standard-library#2734]
It should have been named as `match` IMO. Can you please explain the rationale behind this function name? 

Here is the current function signature.
```ballerina
function matches(string stringToMatch, string regex) returns boolean
```

**Comment by sameerajayasoma** [comment]
Related to #2689

**Comment by daneshk** [comment]
Honestly, I can't recall how we came up with the function name as `matches`. These functions came from the `stringutils` package[1] we had before. I think we referred to Java APIs when designing.  So, as you said, it should be the `match` function.

We will look into this. Maybe we can depreciate this API introduces a new API by correcting the name.
Thanks for pointing this out.

1. https://github.com/ballerina-attic/module-ballerina-stringutils/blob/master/stringutils-ballerina/natives.bal

**Comment by sameerajayasoma** [comment]
Let's deprecate this method in Swan Lake Update 1

**Comment by daneshk** [comment]
@kalaiyarasiganeshalingam Please look into this

**Comment by daneshk** [comment]
As per comment[1], we are going to leave `matches` as is. Hence closing this issue.

1. https://github.com/ballerina-platform/ballerina-standard-library/issues/2689#issuecomment-1062545173
