### ISSUE TITLE
Change Titles of the Standard Library Module Docs to Sentence Case

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-standard-library#2748]
**Description:**
Need to change the titles of API Docs to sentence case. Need to update the `Package.md`, `Module.md` and `README.md` files of all the modules. For example, in [1],

1. `gRPC Communication Patterns` should be -> `gRPC communication patterns` 
2. `Creating the Server` should be -> `Creating the server`

[1] https://lib.ballerina.io/ballerina/grpc/1.2.0

Module List:
- [x] io
- [x] java.arrays
- [x] random
- [x] regex
- [x] time
- [x] url
- [x] xmldata
- [x] crypto
- [x] log
- [x] os
- [x] protobuf
- [x] task
- [x] xslt
- [x] cache
- [x] file
- [x] ftp
- [x] mime
- [x] nats
- [x] stan
- [x] tcp
- [x] udp
- [x] uuid
- [x] auth
- [x] email
- [x] jwt
- [x] oauth2
- [x] http
- [x] graphql
- [x] grpc
- [x] websocket
- [x] websub
- [x] websubhub
- [x] kafka
- [x] rabbitmq
- [x] sql
- [x] java.jdbc
- [x] mssql
- [x] mysql
- [x] oracledb
- [x] postgresql

**Comment by daneshk** [comment]
This task is already completed. Hence closing the issue.
