### ISSUE TITLE
Incorrect stub generated for message with Any type field in gRPC tool

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#2750]
**Description:**
Try to build the stub file for the following proto definition.
```proto
syntax = "proto3";

import "google/protobuf/any.proto";

message AnyTypeRequest {
    string name = 1;
    google.protobuf.Any details = 2;
};
```

The following is the generated stub file.
```ballerina
public type AnyTypeRequest record {|
    string name = "";
    'any:Any details = ();
|};

const string ROOT_DESCRIPTOR_ANY2 = "0A0A616E79322E70726F746F1A19676F6F676C652F70726F746F6275662F616E792E70726F746F22540A0E416E79547970655265717565737412120A046E616D6518012001280952046E616D65122E0A0764657461696C7318022001280B32142E676F6F676C652E70726F746F6275662E416E79520764657461696C73620670726F746F33";

public isolated function getDescriptorMapAny2() returns map<string> {
    return {"any2.proto": "0A0A616E79322E70726F746F1A19676F6F676C652F70726F746F6275662F616E792E70726F746F22540A0E416E79547970655265717565737412120A046E616D6518012001280952046E616D65122E0A0764657461696C7318022001280B32142E676F6F676C652E70726F746F6275662E416E79520764657461696C73620670726F746F33", "google/protobuf/any.proto": "0A19676F6F676C652F70726F746F6275662F616E792E70726F746F120F676F6F676C652E70726F746F62756622360A03416E7912190A08747970655F75726C18012001280952077479706555726C12140A0576616C756518022001280C520576616C7565424F0A13636F6D2E676F6F676C652E70726F746F6275664208416E7950726F746F50015A057479706573A20203475042AA021E476F6F676C652E50726F746F6275662E57656C6C4B6E6F776E5479706573620670726F746F33"};
}
```

There are 2 issues here.
1. The `ballerina/protobuf.types.'any` import is missing.
2. The `AnyTypeRequest` record definition throws a compilation error: `ERROR [sample.bal:(9:24,9:26)] incompatible types: expected 'ballerina/protobuf.types.any:1.2.0:Any', found '()'`

**Affected Versions:**
SLGA

**Comment by MadhukaHarith92** [comment]
IMO, the default value in the record should be changed as follows according to the `Any` type definition[[1]](https://github.com/ballerina-platform/module-ballerina-protobuf/blob/main/ballerina/modules/types.any/any.bal#L37).
```ballerina
public type AnyTypeArrayRequest record {|
    string name = "";
    'any:Any details = {typeUrl: "", value: ()};
|};
```

[1] https://github.com/ballerina-platform/module-ballerina-protobuf/blob/main/ballerina/modules/types.any/any.bal#L37

@BuddhiWathsala @daneshk WDYT

**Comment by daneshk** [comment]
Just thinking, if we can set default values when defining the `Any` type record in the protobuf module. Here we can just say
```
public type Any record {|
    string typeUrl = "";
    ValueType value = ();
|};
```

```
public type AnyTypeArrayRequest record {|
    string name = "";
    'any:Any details = {};
|};
```

**Comment by MadhukaHarith92** [comment]
> Just thinking, if we can set default values when defining the `Any` type record in the protobuf module. Here we can just say
> 
> ```
> public type Any record {|
>     string typeUrl = "";
>     ValueType value = ();
> |};
> ```
> 
> ```
> public type AnyTypeArrayRequest record {|
>     string name = "";
>     'any:Any details = {};
> |};
> ```

+1, That would be better.

**Comment by BuddhiWathsala** [comment]
Yes, that approach is much cleaner.

**Comment by MadhukaHarith92** [comment]
Closing since this task is completed in https://github.com/ballerina-platform/module-ballerina-grpc/pull/739
