### ISSUE TITLE
Proposal: Integrate GraphiQL into GraphQL Services

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#2755]
## Summary
This proposal is to integrate GraphiQL into Ballerina GraphQL services on demand. GraphiQL is the official reference implementation of GraphQL Integrated Development Environment(IDE) that provides a graphical view and querying facility for the service.

## Goals
- Integrate GraphiQL into Ballerina GraphQL Services.
- Provide an easy way to test the Ballerina GraphQL APIs locally.

## Non-Goals
- Use a none CDN based approach for the GraphiQL client implementation.

## Motivation

GraphQL has several tools that can be integrated into a GraphQL library. To give a better development experience for the GraphQL users, most of the GraphQL libraries integrate GraphiQL which is a very popular tool among the GraphQL community. GraphiQL provides a graphical user interface to execute the GraphQL queries. Users will be able to use any kind of complex GraphQL queries with GraphiQL. This can be used for testing purposes and to learn and understand the GraphQL query language as well. GraphiQL displays the schema of the service in Schema Definition Language(SDL) which is an important feature, especially for code first approach libraries like Ballerina GraphQL. Also, this can be used as a debugging tool for GraphQL APIs.

## Description

GraphQL Foundation provides multiple ways to implement a GraphiQL client. This proposal proposes to include the GraphiQL client as a single-page web application served from the Ballerina server using the existing CDN assets. An example implementation of the web app can be found in GraphiQL [examples](https://github.com/graphql/graphiql/tree/main/examples/graphiql-cdn). The web app can be saved as a single HTML file inside the Ballerina GraphQL package. Developers can enable/disable the GraphiQL client and configure the path where the GraphiQL is served.

### GraphiQL Configurations
Even though GraphiQL is an essential tool, it will be disabled in the production level APIs due to security concerns. Hence, the GraphQL service accepts a separate set of configurations for the GraphiQL client. With these configurations, the user will be able to enable the client easily. Configurations can be sent via Ballerina GraphQL [service configuration](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/docs/spec/spec.md#81-service-configuration). It has a separate optional field for GraphiQL configurations. It accepts a record as the input and it consists of a mandatory field and an optional field. 

```bal
type graphiql record {
    boolean enable;
    string path = "/graphiql";
};
```
In this GraphiQL configuration record, the field `enable` accepts a boolean that denotes whether the client is enabled or not. The optional field `path` accepts a valid string path for the GraphiQL service. The path can be any valid string. If the path is not provided in the configuration, the `/graphiql` is set as the default path. If the GraphiQL client is configured to the same path as the GraphQL path, an error will be thrown.
If the configurations are provided correctly, the web app will be served at the given path when the service is started. The developer will be able to access the web application via a web browser.

**Comment by ThisaruGuruge** [comment]
I think the second approach is better since compiler warning does not *force* it completely. This can lead to misunderstandings and some new/inexperienced users may find it hard.

It also enables us to configure CORS specifically for the resource that serves the GraphiQL, not the entire GraphQL service, which is a plus point.

**Comment by shafreenAnfar** [comment]
Yeah, I also prefer the second approach.

**Comment by DimuthuMadushan** [comment]
Updated the proposal as per the discussions.

**Comment by shafreenAnfar** [comment]
@DimuthuMadushan I guess none CDN approach is a Non-Goal of this proposal ?

**Comment by DimuthuMadushan** [comment]
@shafreenAnfar yes. added to the proposal.

**Comment by shafreenAnfar** [comment]
@sameerajayasoma FYI.

**Comment by sameerajayasoma** [comment]
Apologies for the late reply. 

I would prefer to enable the GraphiQL endpoint using a configurable variable. Hardcoding GraphiQL config in the code is a bad idea, especially since it should not be exposed in production. Here is how I would design this. 

Define configurable variables in `ballerina/graphql` package. **I just came up with the following variable names. Need to figure out better names if we are going ahead with this design.**
```
// Option 1
configurable boolean graphiqlEnable = false;
configurable string graphiqlPath = "graphiql"; 

// Option 2
type Graphiql record {
    boolean enable = false;
    string path = "/graphiql";
};

configurable Graphiql graphiql = {};
```

The advantage of option 1 is that the configurable values can be specified in the command line. 
```
java -jar gqlsvc.jar -CgraphiqlEnable=true
```

**Comment by DimuthuMadushan** [comment]
Thank you @sameerajayasoma for the suggestion. I have tried `option 1` locally and found no issues with that design.

Configurable variables:
```ballerina
public configurable boolean graphiql = false;
public configurable string graphiqlPath = "graphiql";
```
Execution commands:
```curl
bal run -- -Cballerina.graphql.graphiql=true -Cballerina.graphql.graphiqlPath=graphical

java -jar gqlsvc.jar -Cballerina.graphql.graphiql=true -Cballerina.graphql.graphiqlPath=graphical
```
Would like to know suggestions on this and whether we proceed with this design. @sameerajayasoma @shafreenAnfar @ThisaruGuruge

**Comment by sameerajayasoma** [comment]
Looks good. 

How about the following variable names?

```ballerina
public configurable boolean enableGraphiql = false;
public configurable string graphiqlPath = "graphiql";
```

The most commonly used configurable variable would be the first one. 

```sh
java -jar gqlsvc.jar -Cballerina.graphql.enableGraphiql=true

```

**Comment by shafreenAnfar** [comment]
+1 for the above two variable names. I guess the same would work for `bal run` as well.

**Comment by DimuthuMadushan** [comment]
When it comes to testing, currently we have these [test services](https://github.com/ballerina-platform/module-ballerina-graphql/blob/b527978d600e178d8c92c0c804298bea58858107/ballerina/tests/test_services.bal#L50) with different forms of GraphiQL configurations. With the new design, It seems like we don't have a way to provide configurations like earlier. @ThisaruGuruge any idea on this?

**Comment by ThisaruGuruge** [comment]
> When it comes to testing, currently we have these [test services](https://github.com/ballerina-platform/module-ballerina-graphql/blob/b527978d600e178d8c92c0c804298bea58858107/ballerina/tests/test_services.bal#L50) with different forms of GraphiQL configurations. With the new design, It seems like we don't have a way to provide configurations like earlier. @ThisaruGuruge any idea on this?

In that case, will it be okay to keep it as it is @sameerajayasoma? Otherwise we might have to test this manually for each release and it might leave a window for human error? WDYT?

**Comment by sameerajayasoma** [comment]
Looping @azinneera and @warunalakshitha. Do we have a way to provide different configurable values in test cases?

**Comment by azinneera** [comment]
> We can provide different values for configurable variables for tests by adding a Config.toml inside tests directory. That will apply for all the tests in that module.
> 
> But if we cannot provide separate configurable values for different test cases in same test module.

Adding on to the @warunalakshitha 's comment, this requirement was raised sometime ago for an Observability use case as well. There is an open spec issue to track this. I think we should check the feasibility of implementing @manuranga 's suggestion to address this: https://github.com/ballerina-platform/ballerina-spec/issues/762#issuecomment-785274601

**Comment by shafreenAnfar** [comment]
@sameerajayasoma Given that we don't have a proper way to add test-cases. Shall we revert back to the original proposal as @ThisaruGuruge mentioned in https://github.com/ballerina-platform/ballerina-standard-library/issues/2755#issuecomment-1115732188 ?

It is true that there is a slight inconsistency between the two types of configuration. However, IMO, when it comes to user experience both types of approaches have pros and cons.

**Comment by sameerajayasoma** [comment]
I think we are mixing two different things: design and implementability, and we have to adjust the design to make it implementable in some situations.  The proposal is to change the design because we can't write unit tests :) 

Anyway, I see two options here:
1) Delay this feature until we can pass different configurable values to test functions
2) Go with the original proposal. 

As I've explained in https://github.com/ballerina-platform/ballerina-standard-library/issues/2755#issuecomment-1105710198, we are mixing two kinds of configuration elements into `graphql:ServiceConfig` record. 

I prefer option #1, but given the circumstances, let's go with option 2.

**Comment by DimuthuMadushan** [comment]
Closed since agreed to go with the original proposal.
