### ISSUE TITLE
gRPC CLI unable to generate all the necessary messages

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2766]
**Description:**
When we develop gRPC applications with `google.protobuf.Any` type, we have to generate records for all the messages in a specified proto directory (i.e, `--proto-path` or a director as an `--input`).

Here is an example, 
[proto.zip](https://github.com/ballerina-platform/ballerina-standard-library/files/8206950/proto.zip)

When I generate the relevant stubs for the above proto directory as below, it won't generate the `Message2` definition, which I need to pass as a `google.protobuf.Any` type.

```sh
$ bal grpc --input=proto/foo/bar/service.proto --output=ballerina --mode service --proto-path=proto
```

In addition, neither the `protoc` command did not generate it. The `protoc` command even didn't generate the `Message1`. 
```sh
$ protoc --go_out=go --go-grpc_out=go proto/foo/bar/service.proto --proto_path=proto
```

AFAIU, we can generate them separately and include them in a project. But in Ballerina, we cannot do that since we only have one descriptor for a given service. And that service definition cannot include descriptors other than the ones we generated. As they have mentioned [here](https://developers.google.com/protocol-buffers/docs/reference/go-generated#package), the protoc compiler won't handle such cases. Only the gen tools do that.

However, when I use Java `io.grpc:protoc-gen-grpc-java` generation tool, it generates all the necessary messages, including `Message1` and `Message2`. That is the behaviour we should implement in Ballerina CLI.

[Sample Java code](https://github.com/ballerina-platform/ballerina-standard-library/files/8207028/test-grpc-gen-project.zip)

**Affected Versions:**
- Ballerina 2201.0.1

**OS, DB, other environment details and versions:**
- macOS

**Comment by BuddhiWathsala** [comment]
@shafreenAnfar @daneshk @MadhukaHarith92 @dilanSachi any input for this issue.

**Comment by dilanSachi** [comment]
Currently, When we give a directory path instead of a proto file path to the input path, it generates the stub files for all the proto files. But it does not check inside the nested directories.

**Comment by daneshk** [comment]
Shall we use solution 02 in the proposal to support nested directories, in [1]
```
Solution 02
Allow users to use wild cards as Go did.
bal grpc –input proto/**.proto –output ballerina-out
```

1. https://github.com/ballerina-platform/ballerina-standard-library/issues/2794#issue-1174569163
