### ISSUE TITLE
Introduce gRPC runtime-level support for record annotations

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2796]
**Description:**
$title

**Comment by BuddhiWathsala** [comment]
This is a blocker for this task - https://github.com/ballerina-platform/ballerina-lang/issues/35711

**Comment by BuddhiWathsala** [comment]
Due to this (https://github.com/ballerina-platform/ballerina-lang/issues/35711) restriction, we cannot directly use Java byte array representation in Ballerina. IMO, there are two ways to solve this issue.

### Option 01
Represent descriptors as previously done, using a hexadecimal string.

### Option 02
- Get the Java byte array and shift it to the Ballerina range (0 to 255)
- Move the shifted array to Ballerina
- Ballerina sends the shifted array back to Java
- Shift the Ballerina range back to the Java range (-128 to +127)
- Use it

Option 02 will be a time-consuming task, therefore +1 to option 01. 

@daneshk @shafreenAnfar @MadhukaHarith92 @dilanSachi  WDYT?

**Comment by MadhukaHarith92** [comment]
+1 for option 1.
