### ISSUE TITLE
Introduce gRPC packaging support 

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2798]
**Description:**
$title

**Comment by dilanSachi** [comment]
Taken from the CLI improvements proposal [1],

**The Ballerina CLI cannot create packages according to the protobuf definition. In protobuf, there is a way to specify Java and Go packages. However, for Ballerina, we do not have such an option.**

**Go Packages**

`option go_package = "example.com/messages1";`

**Java Packages**

`option java_package = "com.example.tutorial.protos";`

To do this we have to use a custom file option by contributing to [2]. This way, we can define a proto file as follows,

```proto
extend FileOptions {
   optional string ballerina_package = 1147;
}
```
Then the user can import this proto file in their respective proto file and define the ballerina package.

[1] https://github.com/ballerina-platform/ballerina-standard-library/issues/2794
[2] https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md
