### ISSUE TITLE
gRPC CLI Improvements

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2799]
**Description:**
Tasks related to the proposal - https://github.com/ballerina-platform/ballerina-standard-library/issues/2794

Sub-tasks
- [Problem 01 - Support for Nested Directories](https://github.com/ballerina-platform/ballerina-standard-library/issues/2766)
- [Problem 02 - Centralized Proto Descriptor - Runtime-Level Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/2796)
- [Problem 02 - Centralized Proto Descriptor - CLI-Level Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/2797)
- [Problem 03 - Packaging Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/2798)

**Comment by dilanSachi** [comment]
Closing since the subtasks are completed now.
