### ISSUE TITLE
Remove ballerina-core dependency and any usages

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-standard-library#2802]
**Description:**
ballerina-core (https://github.com/ballerina-platform/ballerina-lang/tree/master/bvm/ballerina-core)  java package contains old bvm types and values. This has been used only by several jballerina-unit-tests. We have migrated those to new java runtime and now there are no usages in the ballerina-lang.

But still some of standard libraries use ballerina-core and we need to remove them.

Using old implementation will cause unexpected bugs.

**Comment by warunalakshitha** [comment]
Most of the usages are only unused dependencies in gradle files.

https://github.com/ballerina-platform/module-ballerina-io/blob/f7d13698a2ef15c9f48077a6effa23e8e9f251c9/native/build.gradle#L28

**Comment by niveathika** [comment]
The module list:

- [ ]  io
- [ ]  java.arrays
- [ ]  random
- [ ]  regex
- [ ]  time
- [ ]  url
- [ ]  xmldata
- [ ]  crypto
- [ ]  log
- [ ]  os
- [ ]  protobuf
- [ ]  task
- [ ]  xslt
- [ ]  cache
- [ ]  file
- [ ]  ftp
- [ ]  mime
- [ ]  nats
- [ ]  stan
- [ ]  tcp
- [ ]  udp
- [ ]  uuid
- [ ]  auth
- [ ]  email
- [ ]  jwt
- [ ]  oauth2
- [ ]  http
- [ ]  graphql
- [ ]  grpc
- [ ]  transaction
- [ ]  websocket
- [ ]  websub
- [ ]  websubhub
- [ ]  kafka
- [ ]  rabbitmq
- [ ]  sql
- [ ]  java.jdbc
- [ ]  mssql
- [ ]  mysql
- [ ]  oracledb
- [ ]  postgresql

**Comment by BuddhiWathsala** [comment]
`time` and `grpc` packages do not have the `ballerina-core` dependency.

**Comment by ldclakmal** [comment]
`url`, `crypto`, `auth`, `jwt`, `oauth2` packages do not have the `ballerina-core` dependency.

**Comment by niveathika** [comment]
`sql`, `mysql` and `oracledb` does not have ballerina-core dependency

**Comment by dilanSachi** [comment]
Found core usage in `ftp`. removed in the above tagged PR.

**Comment by ThisaruGuruge** [comment]
GraphQL does not have `ballerina-core` dependency.

**Comment by kaneeldias** [comment]
mssql and java.jdbc does not have the `ballerina-core` dependency.

**Comment by kalaiyarasiganeshalingam** [comment]
`xmldata`, `task`, `cache`, `file`, regex, and postgresql packages do not have ballerina-core dependency.

**Comment by xlight05** [comment]
It was unused in a test module. 
https://github.com/ballerina-platform/module-ballerinax-aws.lambda/pull/630

**Comment by chamil321** [comment]
Dependency is remove from HTTP and MIME

**Comment by MohamedSabthar** [comment]
`serdes` does not have ballerina-core dependency.

**Comment by ThisaruGuruge** [comment]
Closing since the `ballerina-core` is now removed from the lang via https://github.com/ballerina-platform/ballerina-lang/pull/37685.
