### ISSUE TITLE
Release all Ballerina drivers on top of Ballerina GA version

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-standard-library#2804]
**Description:**

**Describe your problem(s)**

Choreo marketplace does not list the drivers. 
Reason is the way it is designed to pull the packages from central .

>   If Choreo is on X major version it will receive latest patch version of the lib released on X.
>   Now Choreo is on GA. If there's no version released on GA, Choreo marketplace shows nothing (in fact, ballerina central API returns nothing)

**Describe your solution(s)**

Release all drivers on top of GA. Until next major version release of Ballerina we will be able to use those drivers. 

**Related Issues (optional):**
N/A

**Comment by kaneeldias** [comment]
Closing issue as al 4 SQL DB drivers have been published in Central
