### ISSUE TITLE
Proposal creation for gRPC CLI improvement

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2811]
**Description:**
Need to create a proposal for these gRPC CLI improvements https://github.com/ballerina-platform/ballerina-standard-library/issues/2799

**Comment by BuddhiWathsala** [comment]
Created the initial draft - https://github.com/ballerina-platform/ballerina-standard-library/issues/2794

**Comment by dilanSachi** [comment]
This is completed
