### ISSUE TITLE
Proposal: Introduce API to convert the Ballerina record to XML

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2819]
## Summary
The Ballerina Xmldata module doesn't have any API to convert the Ballerina record to XML directly. So, this proposal introduces a new `fromRecord` API to convert the Ballerina record to XML.

## Goals
Provide a way to directly convert the Ballerina record to XML.

## Motivation
When we are writing a connector for the SOAP backend service(e.g Netsuite Connector), we need to convert the Ballerina record value to XML payload. As mentioned in the summary, We don't have a way to convert the Ballerina record to XML. At the moment, users have to write their own custom implementation to convert Ballerina records to XML and it would be easy for them If we provide an API to convert.

Note: This feature is also required by the connector team and they are planning to remove their custom implementation and use `xmldata` module, once we have this feature.

## Description
The API definition of this:

```ballerina
# Converts a Ballerina record to an XML representation.
# ```ballerina
# Employee data = {
#   name: "Asha"
# };
# xml? xmlValue = check xmldata:fromRecord(data);
# ```
#
# + recordValue - The Ballerina record to be converted to XML
# + arrayEntryTag - The name of the XML elements that represent 
#                   a converted JSON array entry when the JSON 
#                   array entry key is not present during the conversion
# + return - An XML representation of the given Ballerina record if the record is
#            successfully converted or else an `xmldata:Error`
public isolated function fromRecord(record {} recordValue, string arrayEntryTag = "item") returns xml|Error;
```
### Rules for Record to XML Conversion
The following rules are used during the conversion process:

- A default root element will be created When data contains multiple key-value pairs
   ```ballerina
   Person data = {
        fname: "John",
        lname: "Stallone"
    };
   ```
- If JSON properties' keys have the prefix as `_`, those will be handled as attributes or namespaces in the XML.
- If optional values in the Ballerina record are nil, those will be converted to empty XML elements in the XML.
   ```ballerina
   Person data = {
        fname: "John",
        lname: ()
    };
   ```
-  If optional fields are in the Ballerina record, those will be skipped.

The following table shows a mapping between the different forms of XML, to a corresponding matching Ballerina record representation by considering the above rules.

|Record Type  | Record Sample | XML Representation Type | XML Representation of XML |
|---|---|---|---|
|Record has single <br> key-value | `{name:"Asha"}` | Empty element | `<name>Asha</name>`<br> | 
|Record has single <br> key-value and value is "" | `{name:""}` | Empty element | `<name/>`<br> | 
|Record has  optional values | `{name: ()}` | Empty element | `<name/>`<br> | 
|Empty record | `{}` | Empty Sequence  | `` <br>|
|Record with <br> single key-value | `{`<br>&emsp;&emsp;`"store": {`<br>&emsp;&emsp;&emsp;&emsp;`"name": "Anne",`<br>&emsp;&emsp;&emsp;&emsp;`"address": {`<br>&emsp;&emsp;&emsp;&emsp;&emsp;`"street": "Main",`<br>&emsp;&emsp;&emsp;&emsp;&emsp;`"city": "94"`<br>&emsp;&emsp;&emsp;&emsp;`}`<br>&emsp;&emsp;`}`<br>} |XML sequence | `<store>`<br>&emsp;&emsp;`<name>Anne</name>`<br>&emsp;&emsp;`<address>`<br>&emsp;&emsp;&emsp;&emsp;`<street>Main</street>`<br>&emsp;&emsp;&emsp;&emsp;`<city>94</city>`<br>&emsp;&emsp;`</address>`<br>`</store>` <br>|
|Record with <br> multiple key-value pairs | `{`<br> &emsp; &emsp;`"key1":"value1",`<br> &emsp; &emsp;`"key2":"value2"`<br>`}` |XML sequence with `root` tag  | `<root>`<br>&emsp;&emsp;`<key1>value1</key1>`<br>&emsp;&emsp;`<key2>value2</key2>`<br>`</root>` |
|Record with key <br> as "\\#content" | `{"\#content":"value1"}` | XML text | `value1` |
|Record with key <br> prefix as ‘_’ | `{`<br>&emsp;&emsp;`"foo": {`<br>&emsp;&emsp;&emsp;&emsp;`"_key": "value",`<br>&emsp;&emsp;&emsp;&emsp;`"_xmlns\:ns0":"<http://sample.com>"`<br>&emsp;&emsp;`}`<br>} | XML element with attribute and namespace | `<foo key="value"` <br> `xmlns:ns0="<http://sample.com>"/>`<br> |

**Comment by daneshk** [comment]
@kalaiyarasiganeshalingam How are we handling optional values in the Ballerina record. are we skipping those fields. And also shall we mention, how XML namespaces are handled. other special scenarios in the proposal

**Comment by kalaiyarasiganeshalingam** [comment]
> @kalaiyarasiganeshalingam How are we handling optional values in the Ballerina record. are we skipping those fields.

We have to keep the consistency between `toRecord` and `fromRecord`. Hence, in the `toRecord`, Only if XML has that optional field's value, then the record optional field in the Ballerina record has a value. Otherwise, nil. So, I'm going to follow the same. If the optional field has a value, that field will be added to the XML. Otherwise, skip those.

 > And also shall we mention, how XML namespaces are handled. other special scenarios in the proposal

The Ballerina's record field's name does not allow some symbols and a colon. So we have some restrictions in the created record by using `toRecord`. Hence, `fromRecord` will also keep them.

- In the `toRecord`, if the ballerina record has fields and those are indicates namespaces or attributes of the XML, those fields are started with only `_`. Hence, if the users have to add the namespaces or attributes when using `fromRecord`, they have to create a fields' name with a prefix as `_` in the record.

- The name prefixes are divided by `:` in the XML.
Eg:
    -  xmlns:prefix="URI"
    - <h:table/>
   
    These colons are also converted to `_` in the record when using `toRecord`. So, in the `fromRecord`, if the record fields' name will cantain a name prefix, those fields should also use `_` to separate the prefixes.

**Comment by daneshk** [comment]
@sameerajayasoma would you please have a look and give your feedback.

**Comment by jclark** [comment]
This should work consistently with OpenAPI

https://swagger.io/docs/specification/data-models/representing-xml/

If I have a value of type json (including records) that belongs to some Ballerina type T that we map to some OpenAPI spec S, and there is a value V that belongs to T, then the mapping of V to X being done in this issue should be the valid XML according to S.

**Comment by sameerajayasoma** [comment]
The default attribute prefix in `xmldata:fromJson()` method is `@`, but as per this proposal the attribute prefix of `xmldata:fromRecord` is `_`. Can you explain why? 

In Ballerina `json` is a subtype of `record {|anydata...;|}`. Why do we need two functions `fromJson()` and `fromRecord`. Can't we have a single function for this? 

Can we introduce annotations to change the default behavior of this record to XML mapping and vice versa? OpenAPI spec allow adding fields to change the behaviour.

**Comment by sameerajayasoma** [comment]
The proposal does not cover records values having fields of type `table` and `xml`.  A `table` value can be mapped to an array of corresponding xml elements.

**Comment by kalaiyarasiganeshalingam** [comment]
Please find the mapping rules of the ballerina record to XML with OpenAPI definition.

**Basic Conversion**

The following ballerina record definitions are consistent with the OpenAPI definition to map records to XML without any additional configurations.

|Ballerina Record Definition  | OpenAPI Definition | XML format |
|---|---|---|
|**Record with single field** <br><br> type Root record { <br> &emsp;string key?; <br>}| components:<br>&emsp;schemas:<br>&emsp;&emsp;Root:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;key:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string| `<Root>`<br>&emsp;`<key>string</key>`<br>`</Root>`<br> |
|**Record with multiple key** <br><br>type Root record {  <br> &emsp;string key1?; <br> &emsp;string key2?; <br>}|components:<br>&emsp;schemas:<br>&emsp;&emsp;Root:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;key1:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string <br>&emsp;&emsp;&emsp;&emsp;key2:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string|`<Root>`<br>&emsp;`<key1>string</key1>`<br>&emsp;`<key2>string</key2>`<br>`</Root>`<br>|
|**Nested Record**<br><br>type Root record {  <br> &emsp;Store store?;  <br>}<br><br>type Store record { <br>&emsp;string name?;<br> &emsp;Address address?;<br>}<br><br>type Address record {  <br> &emsp;string street?;<br> &emsp;int city?;<br>}|components:<br>&emsp;schemas:<br>&emsp;&emsp;Root:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;store<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;name<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;address:<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;properties<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;street:<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;city<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; type: integer|`<Root>`<br>&emsp;`<store>`<br>&emsp;&emsp;`<name>string</name>`<br>&emsp;&emsp;`<address>`<br>&emsp;&emsp;&emsp;`<street>string</street>`<br>&emsp;&emsp;&emsp;`<city>0</city>`<br>&emsp;&emsp;`/address>`<br>&emsp;`</store>`<br>`</Root>`|
|**Array**<br><br>type Root record {<br> &emsp; string[] key?; <br>}|Root:<br>&emsp;type: object<br>&emsp;properties<br>&emsp;&emsp;key:<br>&emsp;&emsp;&emsp;type: array<br>&emsp;&emsp;items<br>&emsp;&emsp;&emsp;type: string|`<Root>`<br>&emsp;`<key>string</key>`<br>&emsp;`<key>string</key>`<br>`</Root>`<br>|
|**Record field type as XML** <br><br>type Root record {  <br>&emsp;xml key?; <br>}|components:<br>&emsp;schemas<br>&emsp;&emsp;Root:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties<br>&emsp;&emsp;&emsp;&emsp;key:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: object|`<Root>`<br>&emsp;&emsp;&emsp;`<key>`<br>&emsp;&emsp;&emsp;&emsp;`xml object`<br>&emsp;&emsp;&emsp;`</key>`<br>`</Root>`<br>|
|**Record field type as table** <br><br>table<map<string>> t = table [{key:"value"}]; <br><br> type Root record { <br>&emsp;table key?; <br>}|components:<br>&emsp;schemas:<br>&emsp;&emsp;Root:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;key:<br>&emsp;&emsp;&emsp;&emsp;type: array<br>&emsp;&emsp;&emsp;items<br>&emsp;&emsp;&emsp;&emsp;type: object|`<Root>`<br>&emsp;`<key>xml object</key>`<br>&emsp;`<key>xml object</key>`<br>`</Root>`|
|**Required Field**<br><br>type Root record {  <br>&emsp;int id; <br>&emsp;string uname; <br>&emsp;string name?; <br>}|components:<br>&emsp;schemas:<br>&emsp;&emsp;root:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;id<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: integer<br>&emsp;&emsp;&emsp;&emsp;uname:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;name:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;required:<br>&emsp;&emsp;&emsp;&emsp;&emsp;- id<br>&emsp;&emsp;&emsp;&emsp;&emsp;- uname|`<Root>`<br>&emsp;`<id>0</id>`<br>&emsp;`<uname>string</uname>`<br>&emsp;`<name>string</name>`<br>`</Root>`|
|**Close record**<br><br> type Person record {\|<br>&emsp;string name;<br>\|};|components:<br>&emsp;schemas<br>&emsp;&emsp; Person:<br>&emsp; &emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;&emsp;properties<br>&emsp;&emsp;&emsp; name:<br>&emsp;&emsp;&emsp;&emsp; type: string<br>&emsp;&emsp;&emsp;required<br>&emsp;&emsp;&emsp;&emsp; - name<br>&emsp;&emsp;&emsp;additionalProperties: false|`<Preson>`<br>&emsp;`<name>string</name>`<br>`</Person>`|
|**open record** <br><br>type Person record {<br>&emsp;string name;<br>};|components:<br>&emsp;schemas<br>&emsp;&emsp; Person:<br>&emsp; &emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;&emsp;properties<br>&emsp;&emsp;&emsp; name:<br>&emsp;&emsp;&emsp;&emsp; type: string<br>&emsp;&emsp;&emsp;required<br>&emsp;&emsp;&emsp;&emsp; - name<br>&emsp;&emsp;&emsp;additionalProperties: true|`<Preson>`<br>&emsp;`<name>string</name>`<br>&emsp;`<id>string</id>`<br>`</Person>`|
|**Union Type Field**<br><br>type Location record { <br>&emsp; string\|Address address?; <br>}<br><br>type Address record { <br>&emsp;int id;<br>&emsp;string uname;<br>&emsp;string name?; <br>}|components:<br>&emsp;schemas<br>&emsp;&emsp;Location:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;key<br>&emsp;&emsp;&emsp;&emsp;&emsp;oneOf<br>&emsp;&emsp;&emsp;&emsp;&emsp; - $ref: '#/components/schemas/Address'<br>&emsp;&emsp;&emsp;&emsp;&emsp;- type: string     <br>&emsp;&emsp;Address:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp; id:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: integer<br>&emsp;&emsp;&emsp;&emsp;username:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;name:<br>&emsp;&emsp;&emsp;&emsp;&emsp; type: string<br>&emsp;&emsp;&emsp;&emsp;required:<br>&emsp;&emsp;&emsp;&emsp;&emsp; - id<br>&emsp;&emsp;&emsp;&emsp;&emsp;- uname|`<Location>`<br>&emsp;`<address>`<br>&emsp;&emsp;`<id>0</id>`<br>&emsp;&emsp;`<uname>string</uname>`<br>&emsp;&emsp;`<name>string</name>`<br>&emsp;`</address>`<br>`</Location>` <br><br>OR<br><br>`<Location>`<br>&emsp;`<address>string</address>`<br>`</Location>`|

**Conversion with Attributes and Namespaces**

OpenAPI definition has metadata objects that allow for more fine-tuned XML model definitions. You can find those here.  https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-22

So, In Ballerina, we are going to introduce some annotations to support these metadata.

|OpenAPI metadata | OpenAPI Definition | Ballerina Record Definition <br> with annotation | XML format|
|---|---|---|---|
|XML Name <br> Replacement|components:<br>&emsp; schemas:<br>&emsp;&emsp; animals:<br>&emsp;&emsp; &emsp;  type: object<br>&emsp;&emsp; &emsp; properties:<br>&emsp;&emsp; &emsp; &emsp;  id:<br>&emsp;&emsp; &emsp; &emsp; &emsp;  type: integer<br>&emsp; &emsp;&emsp; &emsp;  **xml:**<br>&emsp;&emsp;&emsp; &emsp;&emsp;  **name: ID**<br>&emsp; &emsp; &emsp; **xml:**<br>&emsp;&emsp;&emsp;  &emsp;**name: animal**|**@xmldata:name {**<br>&emsp;**value: animal**<br>**}** <br>type animals record {<br>&emsp;**@xmldata:name{**<br>&emsp;&emsp;**value: ID**<br>&emsp;**}**<br>&emsp; string id?;<br>};|`<animal>`<br>&emsp;`<ID>0</ID>`<br>`</animal>`|
|XML Attribute|components:<br>&emsp;schemas:<br>&emsp;&emsp;Pline:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;discount:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;&emsp;**xml:**<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;**attribute: true**|type Pline record {<br>&emsp;**@xmldata:attribute**<br>&emsp;int discount?;<br>};| `<Pline discount= "string">`<br>`</Pline>`|
|XML Namespace|components:<br>&emsp;schemas:<br>&emsp;&emsp;Root<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;**xml:**<br>&emsp;&emsp;&emsp;**prefix: ns0**<br>&emsp;&emsp;&emsp;**namespace: 'http://www.w3.org/'**|**@xmldata:namespace {**<br>&emsp;**prefix:”nso”,**<br> &emsp;**uri = ”http://www.w3.org/”**<br>**}**<br>type Root record {};|`<ns0:Root xmlns:ns0 = "http://www.w3.org/">`<br>`</ns0:Root>`|
|XML Namespace <br> and Prefix|components:<br>&emsp;schemas:<br>&emsp;&emsp;Pline:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;**xml:**<br>&emsp;&emsp;&emsp;&emsp;**prefix: 'nso'**<br>&emsp;&emsp;&emsp;&emsp;**namespace: 'http://www.w3.org/'**<br>&emsp;&emsp;&emsp;properties<br>&emsp;&emsp;&emsp;&emsp;foo:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;&emsp;**xml:**<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;**prefix: 'nso'**|**@xmldata:namespace {**<br>&emsp;**prefix: “nso”,**        <br>&emsp;**uri = ”'http://www.w3.org/”**<br>**}** <br>type Pline record {<br>&emsp;**@xmldata:namespae{**<br>&emsp;&emsp;**prefix: “nso”**<br>&emsp;**}** <br>&emsp;string foo;<br>};|`<nso:Pline xmlns:ns0="http://www.w3.org/">`<br>&emsp;`<nso:foo></nso:foo>`<br>`</nso:Pline>`|
|XML Prefix with Namespaces <br><br>**Noted:** OpenAPI <br> Specification <br>[does not support](https://github.com/OAI/OpenAPI-Specification/issues/1456) <br> multiple XML <br> namespaces <br> within a single element. <br>As a workaround, <br>we can define additional <br>namespaces as <br>regular attributes <br>(that is, schema <br>properties with xml.attribute=true)|components:<br>&emsp;schemas:<br>&emsp;&emsp;Root<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties<br>&emsp;&emsp;&emsp;&emsp;key:<br>&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;&emsp;&emsp;**xmlns:asd**<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;enum<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;**- 'http://www.w3.org/'**<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;**xml**<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;**attribute: true**<br>&emsp;&emsp;&emsp;&emsp;&emsp;**xml:**<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;**prefix: ns0** &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;**namespace: 'http://www.w3.org/'**|**@xmldata:namespace {**<br>&emsp;**prefix:”nso”**, <br>&emsp;**uri = ”http://www.w3.org/”**<br>**}**<br>type Root record {<br>&emsp;string key?;<br>&emsp;**@xmldata:attribute**<br>&emsp;**string xmlns\:asd =  "http://www.w3.org/"**;<br>};|`<ns0:root xmlns:ns0="http://www.w3.org/" xmlns:asd="http://www.w3.org/">`<br>&emsp;`<key>string</key>`<br>`</ns0:root>`|
|Signifies whether <br>the array is wrapped or not.|One of the below open <br> API definitions can be used to <br>define the ballerina record array field definition. <br>So, we don’t need to introduce <br>new annotations for wrapped metadata.<br><br>1. Unwrap array definition<br>components:<br>&emsp;schemas:<br>&emsp;&emsp;root:<br>&emsp;&emsp;&emsp;type: object<br>&emsp;&emsp;&emsp;properties:<br>&emsp;&emsp;&emsp;&emsp;root<br>&emsp;&emsp;&emsp;&emsp;&emsp;type:array<br>&emsp; &emsp;&emsp;&emsp;&emsp;&emsp;items: <br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;type: string<br><br>2. Wrap array definition.<br>components:<br>&emsp;schemas:<br>&emsp;&emsp;root:<br>&emsp;&emsp;&emsp;type: array<br>&emsp; &emsp;&emsp;&emsp;items:<br>&emsp; &emsp;&emsp;&emsp;&emsp;type: string<br>&emsp;&emsp;&emsp;xml:<br>&emsp;&emsp;&emsp;wrapped: true|type root record {  <br>&emsp;string[] root?; <br>}|`<root>`<br>&emsp;`<root>string</root>`<br>`</root>`|

**Convert XML element with attributes(Unsupported in OpenAPI)**

OpenAPI does not support xml which has elements with attributes. 
For more info, please see this issue: [https://github.com/OAI/OpenAPI-Specification/issues/630](https://github.com/OAI/OpenAPI-Specification/issues/630)

But this usecase is commonly used in XML. Therefore, In Ballerina, we support through special field name `#content` like below.

|Ballerina Record Definition | XML Sample | 
|---|---|
|type PLine record {<br>&emsp; ItemCode itemCode?;<br>}<br><br>type ItemCode record { <br>&emsp; string discount?;<br>&emsp;&emsp;int \#content?;// If the value doesn't have a key, <br> can initialize that value with the default ey name`#content`<br>}|`<PLine>`<br>&emsp;`<itemCode discount=22%>`<br>&emsp;&emsp;`200777`<br>&emsp;`</itemCode>`<br>`</PLine>`|

**API Definition**
```ballerina
# Converts a Ballerina record to an XML representation by following the OpenAPI 
# definition.
# ```ballerina
# Employee data = {
#   name: "Asha"
# };
# xml? xmlValue = check xmldata:fromRecord(data);
# ```
#
# + recordType - The `typedesc` of the given Ballerina record
# + recordValue - The Ballerina record to be converted to XML
# + return - An XML representation of the given Ballerina record if the record is
#            successfully converted or else an `xmldata:Error`
public isolated function fromRecord(typedesc<record {}> recordType, record {|anydata...;|} recordValue) returns xml|Error;
```
**Annotation Definitions**

```ballerina
# Defines the new name of the name.
#
# + value - The value of the new name 
public type NameConfig record {|
    string value;
|};

# The annotation is used to specify the new name of the existing record name or field name according to the XML format.
public annotation NameConfig Name on record field;
```

```ballerina
# Defines the namespace of the XML element
#
# + prefix - The value of the prefix of the namespace
# + uri - The value of the URI of the namespace  
public type NamespaceConfig record {|
    string prefix;
    string uri?;
|};

# The annotation is used to specify the namespace's prefix and URI of the XML element.
public annotation NamespaceConfig Namespace on record field;
```

```ballerina
# The annotation is used to denote the field that is considered an attribute.
public annotation Attribute;
```

**Comment by jclark** [comment]
Do we have actual users requesting this functionality?

**Comment by kalaiyarasiganeshalingam** [comment]
No, we don't have actual users requesting this functionality.

**Comment by daneshk** [comment]
> No, we don't have actual users requesting this functionality.

But, the Ballerina connector team is building a WSDL tool that builds client connectors to connect to the SOAP backends. This feature is useful for them to convert Ballerina records to XML payload easily. Currently, they are building the XML payload from the record in each connector manually.

**Comment by daneshk** [comment]
@jclark @sameerajayasoma Could you please give your feedback on the updated changes.

**Comment by jclark** [comment]
I guess I don't really understand what problem you are trying to solve: fromRecord doesn't make much sense to me.  There are lots of different ways of converting between Ballerina and XML: there's no one right way; it depends what problem you are trying to solve.

I would see OpenAPI-style XML as an alternative way of serializing the json and anydata types. So I would expect a

```
function toXml(map<anydata)>) returns xml;
function fromXml(xml, typedesc<map<anydata>> t  = <>) returns error|t;
```

**Comment by daneshk** [comment]
The problem is, We are building a connector to connect with the SOAP backend where the request payload is XML type. The connector APIs accept Ballerina record values, and inside the connector, we need to convert the Ballerina record value to XML value and construct a request payload.

We are planning to give an API from the `xmldata` module to convert Ballerina value to XML To be used in those connectors. We went through OpenAPI-style and amended our design by introducing a few annotations to mark XML attributes and namespaces.

As we already have `xmldata:fromJson` and `xmldata:toJson` functions which are specific to JSON <> XML conversion. So we thought of calling the functions of Ballerina record value conversions like `xmldata:fromRecord` and `xmldata:ToRecord`. since JSON is also a subtype of `record {|anydata...;|}`, we don't need two APIs.

+1 for suggested APIs. They can use to convert both JSON and anydata types—the only doubt is whether the function names are aligned with our convention. `xmldata:toXML` and `xmldata:fromXML`

**Comment by kalaiyarasiganeshalingam** [comment]
Please find the following APIs definitions according to the latest suggestion.

```ballerina
# Converts an XML to its `Map` or `Record` representation.
# The namespaces and attributes will not be considered a special case.
#
# + xmlValue - The XML source to be converted to a given target type
# + returnType - The `typedesc` of the `map<anydata>` that should be returned as a result
# + return - The given target type representation of the given XML on success,
# else returns an `xmldata:Error`
public isolated function fromXml(xml xmlValue, typedesc<(map<anydata>|json)> returnType = <>)
returns returnType|Error;
```

```ballerina
# Converts a `Map` or `Record` representation to its XML representation.
# The record has annotations to configure namespaces and attributes,  but others don't have these.
#
# + mapValue - The `Map` or `Record` representation source to be converted to XML
# + return - XML representation of the given source if the source is
# successfully converted or else an `xmldata:Error`
public isolated function toXml(map<anydata> mapValue) returns xml|Error;
```

**Comment by daneshk** [comment]
This is not implemented yet, Hence reopening the issue
