### ISSUE TITLE
Html content sends as raw text if content type is not provided

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-standard-library#2820]
**Description:**
$title

**Describe your problem(s)**
```
email:Message message = {
        to: metadata.to,
        'from: sender_mail,
        subject: subject,
        htmlBody: emailContent
    };
```
With the above code, `emailContent` send as raw text

```
email:Message message = {
        to: metadata.to,
        'from: sender_mail,
        subject: subject,
        htmlBody: emailContent,
        contentType: "text/html"
    };
```
This works as expected.

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayeshLK** [comment]
Fixed with [#480](https://github.com/ballerina-platform/module-ballerina-email/pull/480)
