### ISSUE TITLE
Add support to respond `error` type using `http:Caller`

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#2832]
**Description:**
We supports resource functions to return `error` types which will be converted to an error response with the error message. Similarly, we will allow `http:Caller` to respond with `error` type.

```ballerina
service on new http:Listener(9090) {
    resource function get returnedError() returns error {
        return error("return new error");
    }

    resource function get respondedError(http:Caller caller) returns error? {
        check caller->respond(error("respond with new error"));
    }
}
```

**Related Issues:**
Part of [`Move security error reporting to a default error interceptor #2823`](https://github.com/ballerina-platform/ballerina-standard-library/issues/2823)

**Comment by TharmiganK** [comment]
We also have a `http:CallerInfo` annotation which is used to specify the respond type of the `caller->respond()` method.
Since there is a limitation in specifying the `typedesc` as generic `error` (types of `error` is allowed), at the moment we only support `respondType` to be `http:ResponseMessage|http:Error`. So we are using the annotation and respond with the error, we can only use an error of type `http:Error`

**Comment by chamil321** [comment]
> We also have a `http:CallerInfo` annotation which is used to specify the respond type of the `caller->respond()` method. Since there is a limitation in specifying the `typedesc` as generic `error` (types of `error` is allowed), at the moment we only support `respondType` to be `http:ResponseMessage|http:Error`. So we are using the annotation and respond with the error, we can only use an error of type `http:Error`

Related lang bug https://github.com/ballerina-platform/ballerina-spec/issues/797
