### ISSUE TITLE
Proposal: Introduce the constants for path and path list separators

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2834]
## Summary

The following two separators are widely used in the file system, and these values depend on the OS in the system as well. 
-  Path separator: It is a character used to separate the parent directories that make up the path to a specific location. For windows, it’s ‘\’ and for UNIX it’s ‘/’
-  Path list separator: It is a character commonly used by the operating system to separate paths in the path list. For windows, it’s ‘;‘ and for UNIX it’s ‘:’

The file module has these constants for internal use. Now, this proposal is going to introduce these constants to be accessed by the user.

## Goals

Provide a way to get the separators according to the OS system.

## Motivation

When users use file APIs, they have to initialize the separator as a file path can't be created without these. If we introduce this in the file module, users can easily use it without initialization.

Note: This feature is also required by the Choreo team

## Description

The constants initialization is as follows:

```ballerina
final boolean isWindows = os:getEnv("OS") != "";
// OS-specific path separator.
public final string pathSeparator = isWindows ? "\\" : "/";
// OS-specific path list separator.
public final string pathListSeparator = isWindows ? ";" : ":";
````

**Comment by daneshk** [comment]
It should be `Path Separator` and `Path List Separator` not `file separator` and `path separator`. For the public variables, shall we name it like below,

```
public final string pathSeparator = isWindows ? "\\" : "/";
public final string pathListSeparator = isWindows ? ";" : ":";
```

Refer: https://pkg.go.dev/os#PathSeparator

**Comment by daneshk** [comment]
Looks good to me

**Comment by daneshk** [comment]
@kalaiyarasiganeshalingam we need to add descriptions to those two variables. shall we add like below?

```
// OS-specific path separator.
public final string pathSeparator = isWindows ? "\\" : "/";
// OS-specific path list separator.
public final string pathListSeparator = isWindows ? ";" : ":";
```

**Comment by niveathika** [comment]
Looks good to me.
