### ISSUE TITLE
Directory copy do not replace existing files

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-standard-library#2837]
**Description:**

Tried following sample code to copy and replace all the content in `f1/test` direcotry into `f2/test` and it does not replace. Only workaround was to delete the `f2/test` and copy

```
import ballerina/file;

public function main() returns error? {
    string s1 = check file:joinPath("f1", "test");
    string dest = check file:joinPath("f2", "test");
    check file:copy(s1, dest, file:REPLACE_EXISTING);
}
```

**Steps to reproduce:**

**Affected Versions:**
2201.0.2

**Comment by kalaiyarasiganeshalingam** [comment]
Fixed the issue and released the file package https://central.ballerina.io/ballerina/file
