### ISSUE TITLE
Introduce OS command execution support in Ballerina

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#2852]
**Description:**
We need to reintroduce the OS command execution feature in the OS module. We had this feature in 1.x.x versions, but removed it due to security concerns and to rewrite it in the correct way using new Ballerina language support.

We may need to avoid executing certain commands to prevent security vulnerabilities, especially running them in Choreo environments.

Old API Docs: https://ballerina.io/1.1/learn/api-docs/ballerina/system/index.html
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/435

**Comment by MadhukaHarith92** [comment]
Proposal: https://github.com/ballerina-platform/ballerina-standard-library/issues/2963
