### ISSUE TITLE
Change Titles of the BallerinaX Module Docs to Sentence Case

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-standard-library#2872]
**Description:**
Need to change the titles of API Docs to sentence case. Need to update the `package.md`, `module.md`, and `README.md` files of all the modules. For example, in [1],

1. `Consumer and Producer` should be -> `Consumer and producer`
2. `Data Serialization
` should be -> `Data serialization`

The module list can be found in [2].

[1] https://lib.ballerina.io/ballerinax/kafka/latest
[2] https://lib.ballerina.io/ballerinax

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
We did the change in all standard libraries including ballerinax modules. Some of the modules are still not released with this change, that is the reason, it is not reflected in API Docs. check https://github.com/ballerina-platform/module-ballerinax-kafka/blob/master/ballerina/Module.md

**Comment by niveathika** [comment]
Closing this as all stdlibs are now released with this fix.
