### ISSUE TITLE
WebSub subscriber service results in panic with `service path not found`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-standard-library#2882]
**Description:**
$title. If the attach point is not specified or is `/`.

```cmd
error: Error retrieving Service Information: service path not found
        at ballerina.websub.2.Listener:retrieveGeneratedServicePath(sub_listener.bal:114)
           ballerina.websub.2.Listener:executeAttach(sub_listener.bal:104)
           ballerina.websub.2.Listener:attach(sub_listener.bal:72)
```

Why do these panic at runtime? If these aren't valid, shouldn't we disallow them at compile-time?

Removing `()` from the type of the `name` param of `Listener.attach` will disallow the no path scenario. For `/`, may need a compiler plugin validation.

**Steps to reproduce:**
```ballerina
import ballerina/websub;

configurable string hub = ?;
configurable string topic = ?;

@websub:SubscriberServiceConfig {
    target: [
        hub, 
        topic
    ]
}
service / on new websub:Listener(8080) {

    remote function onEventNotification(websub:ContentDistributionMessage event) returns error? {
    }
}
```

```ballerina
import ballerina/websub;

configurable string hub = ?;
configurable string topic = ?;

@websub:SubscriberServiceConfig {
    target: [
        hub, 
        topic
    ]
}
service on new websub:Listener(8080) {

    remote function onEventNotification(websub:ContentDistributionMessage event) returns error? {
    }
}
```

**Affected Versions:**
2.2.1

**Comment by ayeshLK** [comment]
Tested this issue against WebSub version `2.4.0` (Ballerina distribution `2201.2.2`). 

Following are the findings:
- When the attach point is not specified or `()`, then the attach point will be auto-generated and there will be no error. This issue has been fixed in this [1] PR.
- When the attach point is specified as `/`, at compile time this information is visible and hence will not generate the attach point automatically. But, at runtime this attach point information is not visible to the service and it tries to retrieve the auto-generated attach-point details which is not available and hence result in an error.

[1] - https://github.com/ballerina-platform/module-ballerina-websub/pull/510

**Comment by MaryamZi** [comment]
> But, at runtime this attach point information is not visible to the service and it tries to retrieve the auto-generated attach-point details which is not available and hence result in an error.

Can you point to how/where you check this at runtime?

**Comment by ayeshLK** [comment]
@MaryamZi just added a test case to the module [1] and added a log line at here [2].

[1] - https://github.com/ayeshLK/module-ballerina-websub/blob/46a295fc6de909715f2244b922e6720d17997692/ballerina-tests/tests/service_path_generation_test.bal#L41
[2] - https://github.com/ayeshLK/module-ballerina-websub/blob/46a295fc6de909715f2244b922e6720d17997692/ballerina/sub_listener.bal#L98

**Comment by MaryamZi** [comment]
When the path is `/`, the argument to `attach` is an empty array. 

See https://ballerina.io/spec/lang/master/#service-decl

> The attach-point determines the second argument passed to the attach method: if the attach-point is absent, then the argument is nil; if it is a string-literal, then the argument is a string; otherwise, it is an absolute-resource-path and the argument is an array of strings, with one string for each resource-path-segment-name.  

Also see https://github.com/ballerina-platform/ballerina-lang/issues/29960.

So the problem seems to be with the `isEmptyServicePath` check, where an empty array is also considered [as an empty service path](https://github.com/ayeshLK/module-ballerina-websub/blob/46a295fc6de909715f2244b922e6720d17997692/ballerina/sub_listener.bal#L291) which would result in `shouldUseGeneratedServicePath` evaluating to true.

**Comment by ayeshLK** [comment]
@MaryamZi thanks for the clarification. This should work fine.
