### ISSUE TITLE
Provide support for converting string to parameterizedQuery

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-standard-library#2894]
**Description:**
$title

**Describe your problem(s)**
There is a requirement to execute the sql script with JDBC client. Script can be read as a string and that needs to be converted to a parameterizedQuery. Currently we don't have this support.

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
This should be a util function. 

For now, you can use the following workaround.
```ballerina
string queryStr = "SELECT * FROM Teachers;";

sql:ParameterizedQuery query = ``;
query.strings = [queryStr];

```

**Comment by daneshk** [comment]
Closing the issue as we provided a workaround for the case. Please reopen if you have any questions
