### ISSUE TITLE
Improve WebSocket Service Implementation in GraphQL Subscription

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#2899]
**Description:**
In order to add the `subscription` query support in the GraphiQL client, the GraphQL subscription Websocket service should follow the [`graphql-ws`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#graphql-over-websocket-protocol) protocol. According to the [GraphiQL docs](https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/docs/create-fetcher.md#create-fetcher), the `graphql-ws` spec act as a reference implementation of [GraphQL over HTTP](https://github.com/graphql/graphql-over-http) specification. Also, this protocol is considered one of the most popular transport specs and it is used in GraphQL packages like [apollo](https://github.com/apollographql/subscriptions-transport-ws#subscriptions-transport-ws-is-no-longer-maintained).

**Comment by Nuvindu** [comment]
Expecting a fix for [#2534](https://github.com/graphql/graphiql/issues/2534)
