### ISSUE TITLE
Make resource function code snippet more  user  friendly

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#2923]
**Description:**
Resource function code snippet in VScode currently generates 

```ballerina
resource function name . () {
}
```
But mostly used format is `resource function <httpMethod> <ResourceName () ` can we change the  snippet  to something like below? Then it is easy to map and change without looking into the documentation.

```ballerina
resource function httpmethod name () {
}
```

Or is  there any specific  reason to  have current one, which I don't  see ? 
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shafreenAnfar** [comment]
Closing this as per https://github.com/ballerina-platform/ballerina-lang/issues/35490
