### ISSUE TITLE
Builtin sub-types not considered in validating HTTP resource method return types

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#2924]
Consider the following resource function in an HTTP service.
```ballerina
resource function post orderTShirt() returns xml:Element {
        return xml `<placeOrder>
                              <order-status>PLACED</order-status>
                              <order-id>ORD-1234</order-id>
                          </placeOrder>`;
}
```
The compiler plugin complains with the following:
```
invalid resource method return type: expected anydata|http:Response|http:StatusCodeRecord|error, but found xml:Element
```
This issue is there for other builtin sub-types as well.

**Comment by chamil321** [comment]
Need to address https://ballerina.io/spec/lang/master/#built-in_subtypes

**Comment by pubudu91** [comment]
Also, another issue. In the error message it says `anydata|http:Response|http:StatusCodeRecord|error`. But there doesn't seem to be any type named `StatusCodeRecord` in the HTTP package. Is this meant to be `StatusCodeResponse`?

**Comment by pubudu91** [comment]
And also slight formatting issue in the error message. Typically in error messages such as the above, we enclose the types within quotes. e.g., `'anydata'`

**Comment by chamil321** [comment]
> http:StatusCodeRecord

This is how we have set the error internally, and asserted tests cases even[1]
```ballerina
"invalid resource method return type: expected 'anydata|http:Response|http:StatusCodeResponse|error', but found 'http:Client'"
```
                
[1] https://github.com/ballerina-platform/module-ballerina-http/blob/8b8cbe3e8b8762dce681d124bdc3098b300d6f01/compiler-plugin-tests/src/test/java/io/ballerina/stdlib/http/compiler/CompilerPluginTest.java#L120

**Comment by pubudu91** [comment]
Is this in 2201.1.0? I was using 2201.0.3
