### ISSUE TITLE
Enable Trivy scans for Database driver modules

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#2927]
**Description:**
$subject for following modules,

- [x] [module-ballerinax-mysql.driver](https://github.com/ballerina-platform/module-ballerinax-mysql.driver)
- [x] [module-ballerinax-mssql.driver](https://github.com/ballerina-platform/module-ballerinax-mssql.driver)
- [x] [module-ballerinax-postgresql.driver](https://github.com/ballerina-platform/module-ballerinax-postgresql.driver)
- [ ] [module-ballerinax-oracledb.driver](https://github.com/ballerina-platform/module-ballerinax-oracledb.driver)

**Comment by niveathika** [comment]
@ldclakmal The above modules are build through Ballerina action. Is it possible to enable Trivy scans for these?

**Comment by ldclakmal** [comment]
@niveathika Yes. It should be possible. We can integrate the same Trivy action which we have in stdlibs. But we may need to customize the directory path for the scan. And we should add the same for the `central-publish` and `release` actions as well.

**Comment by niveathika** [comment]
This is now complete
