### ISSUE TITLE
[http] Returning 500 when the upstream server is unavailable

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#2929]
Consider the following:
```ballerina
import ballerina/http;

service /foo on new http:Listener(9090) {
    resource function get . () returns json|error {
        http:Client ep = checkpanic new("http://localhost:8080");
        return ep->get("/bar");
    }
}
```
Suppose the service we are trying to connect to at `localhost:8080` is unavailable. Shouldn't this resource be returning a 502 in such cases? Currently it's returning a 500.

**Comment by shafreenAnfar** [comment]
Yeah, maybe in this case we can improve the implementation. If the returned error is an http:ClientError, we can send back `502`. 

@chamil321 @TharmiganK @ayeshLK any thoughts.

**Comment by ayeshLK** [comment]
I think even though this returns an `http:ClientError` we do not have any idea of what is the particular error (there can be multiple error cases in above scenario data-binding error, service not found, bad request etc.). I think we could use following approach to solve this:
```ballerina
import ballerina/http;

service /foo on new http:Listener(9090) {
    resource function get . () returns http:Response|error {
        http:Client ep = check new("http://localhost:8080");
        return ep->get("/bar");
    }
}
```

In this way client will receive the original response from backend server and it should contain the relevant information.

**Comment by chamil321** [comment]
Followings are the initial observations:

- The client connection related are properly fetched at HTTP transport level with 502 status code. (https://github.com/ballerina-platform/module-ballerina-http/blob/v2.6.0/native/src/main/java/io/ballerina/stdlib/http/transport/contractimpl/sender/ConnectionAvailabilityFuture.java#L137)
- At the listener level, those status codes are not consider when creating BError (https://github.com/ballerina-platform/module-ballerina-http/blob/v2.6.0/native/src/main/java/io/ballerina/stdlib/http/api/client/actions/AbstractHTTPAction.java#L498)

Solution
- Create error subtype with `Detail` record, populate status code and return from the client actions
- So when it is returned from the resource, properly the given status code will be set. (https://github.com/ballerina-platform/module-ballerina-http/blob/v2.6.0/ballerina/http_connection.bal#L204)

**Comment by MadhukaHarith92** [comment]
Closing since completed.
