### ISSUE TITLE
GraphQL Support for Custom Directives

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#2937]
In addition to standard ones we need to allow custom ones too.

**Comment by ThisaruGuruge** [comment]
Now we have interceptors implemented, we can implement the custom directives using a special set of interceptors. 

We can introduce an annotation that can be used on graphql Interceptors that indicate a given interceptor is a directive. The usage could be something like this:

```ballerina
@graphql:Directive {
    name: "Uppercase"
    appliedOn: "FIELD", // This can be provided as an enum with possible values
}
public distinct service class Uppercase {
    isolated remote function execute(graphql:Context context, graphql:Field 'field) {
        string fieldValue = context.resolve('field);
        if 'field.getDirectives().contains("Uppercase") {
            return fieldValue.toUpperAscii();
        }
        return fieldValue;
    }
}
```

We need to identify these at the compile-time and add these as directives to the schema. Then at the runtime, we can validate them using the existing validation logic.

**Comment by MohamedSabthar** [comment]
Proposal: https://github.com/ballerina-platform/ballerina-standard-library/issues/4327
