### ISSUE TITLE
Migrate HTTP resource use case to use newly introduced code modifier compiler plugins

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-standard-library#2944]
**Description:**
Need to check current HTTP resource use cases and migrate them to use newly introduced code modifier compiler plugins.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayeshLK** [comment]
We are using compiler plugin code-modifiers in following places:
- HTTP/OpenAPI
  - [https://github.com/ballerina-platform/openapi-tools/pull/955](https://github.com/ballerina-platform/openapi-tools/pull/955) 
- WebSub
  - [https://github.com/ballerina-platform/module-ballerina-websub/pull/510](https://github.com/ballerina-platform/module-ballerina-websub/pull/510)

**Comment by pramodya1994** [comment]
@ayeshLK  If we don't have more use-cases we can close this issue now.

**Comment by ThisaruGuruge** [comment]
GraphQL used code modifiers to add the generated schema to the service. Related PR: https://github.com/ballerina-platform/module-ballerina-graphql/pull/709
