### ISSUE TITLE
Proposal: gRPC Packaging Support

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#2948]
## Summary
The Ballerina CLI doesn't have a way of creating modules according to the protobuf definition. For languages like `go`, `java` there is a way to define packages in the proto definition.
```protobuf
option go_package = "example.com/message";
option java_package = "com.example.message";
```
Here, we are going to introduce a way to define Ballerina modules in the proto definition and how the Ballerina CLI will handle the module structure generation.
## Goals
To support Ballerina modules via the proto definition and Ballerina CLI.

## Motivation
For now, all the Ballerina files are generated in the root directory. With the support for Ballerina modules, the package structure and readability can be improved. 

## Description
To support the option `option ballerina_module` in protobuf, we need to contribute to [google.protobuf.descriptor.proto](https://github.com/protocolbuffers/protobuf/blob/bbcc459aa0c2d5796725f5cb66718acda1ee38f8/src/google/protobuf/descriptor.proto#L341).
This option is not possible according to the response from the `protobuf` community [1]. Therefore, we need to introduce a custom file option as below.
There are two ways for this.
1. We can define a protobuf file in the Ballerina `protobuf` repo containing the content,
```protobuf
import "google/protobuf/descriptor.proto";

extend google.protobuf.FileOptions {
	optional string ballerina_module = 1147;
}
```
and share publicly so that a user can import the file and use as follows.
```protobuf
import "ballerina/protobuf/descriptor.proto";

option (ballerina_module) = "message";
```
2. Or else, user can directly use the following in their protobuf definition.
```protobuf
import "google/protobuf/descriptor.proto";

extend google.protobuf.FileOptions {
	optional string ballerina_module = 1147;
}
option (ballerina_module) = "message";
```
For both these, we need to contribute to the doc [here](https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md) to allocate a number.

When defining the `ballerina_module`, it should start with the package name and follow with the sub module name.

eg - `sample_service.message`

#### Case 01
When the protobuf file is inside a ballerina project, `ballerina_module` should start with the relevant package name.

*sample_service.proto*
```protobuf
import "message1.proto";
import "message2.proto";
import "message3.proto";

option (ballerina_module) = "sample_service";
```
*message1.proto*
```protobuf
option (ballerina_module) = "sample_service.message1";
```
*message2.proto*
```protobuf
option (ballerina_module) = "sample_service.message2";
```
*message3.proto*
```protobuf
option (ballerina_module) = "sample_service";
```
With these module definitions, the generated module structure will be as follows.
```
sample_service
├── modules
│   │── message1
│   │   └─ message1_pb.bal
│   └── message2
│       └─ message2_pb.bal
├── sample_service_pb.bal
├── message3_pb.bal
└── Ballerina.toml
```
#### Case 02
When the protobuf file is not inside a ballerina project, a ballerina package will be generated according to the defined `ballerina_module`. If the imported protobuf files have different package names, it will result in an error.

#### Case 03
In a case like,
*response_msg.proto*
```protobuf
option (ballerina_module) = "sample_service.messages.response_message";
```
*request_msg.proto*
```protobuf
option (ballerina_module) = "sample_service.messages.request_message";
```
Since, Ballerina does not have nested modules, structure will be as follows,
```
sample_service
├── modules
│   │── messages.response_message
│   │   └─ response_msg_pb.bal
│   └── messages.request_message
│       └─ request_msg_pb.bal
├── sample_service_pb.bal
└── Ballerina.toml
```
#### Case 04
In a case where a component in a sub-module is referred in another sub-module, it will result in an error.

## Testing
1. Test the CLI with the module generation.
2. Test the runtime with the module generation change.

## References
[1] https://github.com/protocolbuffers/protobuf/issues/9656
[2] https://developers.google.com/protocol-buffers/docs/proto#customoptions

**Comment by daneshk** [comment]
Let's name our custom proto descriptor file as `ballerina/protobuf/descriptor.proto`. When executing the CLI tool, we can copy this to the temp directory as other well-known protobuf descriptors. So user only need to import our descriptor in their proto files, like

```
import ballerina/protobuf/descriptor.proto
```

**Comment by dilanSachi** [comment]
> import ballerina/protobuf/descriptor.proto

Wont this result in an error if a user try to generate go stubs using protoc?

**Comment by daneshk** [comment]
yes, we need to put this proto file someway in a git repo and point it in an MD file for other language users. For Ballerina users, we can support like above.

**Comment by dilanSachi** [comment]
> Let's name our custom proto descriptor file as `ballerina/protobuf/descriptor.proto`. When executing the CLI tool, we can copy this to the temp directory as other well-known protobuf descriptors. So users only need to import our descriptor in their proto files, like
> 
> ```
> import ballerina/protobuf/descriptor.proto
> ```

Updated

**Comment by daneshk** [comment]
I am not sure, how we handle case 02 is correct when generating the stubs. If the imported protobuf files have different package names, we have to create new Ballerina packages for them inside the output directory. In this case, there will be multiple packages created. @BuddhiWathsala WDYT?

**Comment by dilanSachi** [comment]
Closing since this is completed now
