### ISSUE TITLE
Format the generated functions for oneof type

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2952]
**Description:**
Need to apply these changes https://github.com/ballerina-platform/module-ballerina-protobuf/pull/176#discussion_r884670782

**Comment by dilanSachi** [comment]
Here what we have to do is try and avoid ballerina anti-patterns which are generated by the protoc tool

**Comment by pedaars** [comment]
i would like to pick this up please

**Comment by dilanSachi** [comment]
Hi @pedaars  🚀

We value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

- Understanding Ballerina Platform: Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)
- How to Contribute: Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- Learn Ballerina: If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)
- Get Help and Connect: Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!

Happy coding! 🎉

**Comment by dilanSachi** [comment]
@pedaars  
Let me give you some context regarding this specific issue.

In Ballerina gRPC, we use the `protoc-tool`[1] to generate the ballerina files needed for the gRPC client and service. In the current generated files, there are some ballerina anti-patterns followed. You can see some samples in the generated test case files [2], [3]. What you have to do is update the protoc-tool to remove these redundant usages. List of Ballerina anti-patterns can be found here [4].

This fix needs to be done in the [protoc-tool](https://github.com/ballerina-platform/protoc-tools/tree/main).
* The tool starts execution from [here](https://github.com/ballerina-platform/protoc-tools/blob/main/protoc-cli/src/main/java/io/ballerina/protoc/protobuf/cmd/GrpcCmd.java#L128)
* To generate the `bal` files, we invoke the [`generateSyntaxTree`](https://github.com/ballerina-platform/protoc-tools/blob/main/protoc-cli/src/main/java/io/ballerina/protoc/builder/syntaxtree/SyntaxTreeGenerator.java#L113) method.
* You can go through these and get yourself familiarized with the code.
* Once you have added the fix, you can update the [existing test cases](https://github.com/ballerina-platform/protoc-tools/tree/main/tooling-tests) to match the new changes.

Also, if you want learn about gRPC and the protoc-tool you can follow these.
* https://ballerina.io/learn/by-example/grpc-service-simple/
* https://ballerina.io/learn/grpc-tool/

[1] https://github.com/ballerina-platform/protoc-tools
[2] https://github.com/ballerina-platform/protoc-tools/blob/98f45aecd6e43c0e5d0e982a9cc300336c8e660a/tooling-tests/src/test/resources/test-src/generated-sources/tool_test_data_type_11/oneof_field_service_pb.bal#L169
[3] https://github.com/ballerina-platform/protoc-tools/blob/98f45aecd6e43c0e5d0e982a9cc300336c8e660a/tooling-tests/src/test/resources/test-src/generated-sources/tool_test_data_type_9/helloWorldWithReservedNames_pb.bal#L164
[4] https://docs.google.com/document/d/1y6QVqaZzZt9jMpYV4jP5WRS_W_KoC4y40Uuoh1ALu8E/edit#heading=h.kel062m2vr8k

**Comment by pedaars** [comment]
Sorry I will have to leave this for someone with java experience

**Comment by Ishad-M-I-M** [comment]
Hi @dilanSachi can I get this assigned to me.

**Comment by Ishad-M-I-M** [comment]
Is this only the anti-pattern that needs to be fixed in the generated code for this issue?
```ballerina
 !(r?.doubleData is ())
```
to 
```ballerina
r?.doubleData !is ()
```
