### ISSUE TITLE
Proposal: OS Command Execution

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#2963]
## Summary

At the moment, the Ballerina OS module does not have an API to execute OS commands. In this proposal, we describe how this requirement can be facilitated.

## Goals

To support OS command execution.

## Motivation

To allow users to execute operating system commands programmatically.

## Description

```ballerina
# Represents a command.
#
# + value - The value of the command
# + arguments - The arguments of the command
public type Command record {
    string value;
    string[] arguments;
};

# Executes an operating system command as a subprocess of the current process.
# ```ballerina
# os:Process|os:Error result = os:exec({value: "bal", arguments: ["run", filepath]}, dir = "/User/MyProject", BAL_CONFIG_FILE = "/abc/Config.toml");
# ```
#
# + command - The command to be executed
# + dir - The current working directory to be set to the process
# + envProperties - The environment properties
#
# + return - Process object in success, or an Error if a failure occurs
public isolated function  exec(Command command, string? dir = (), *EnvProperties envProperties) returns Process | Error;
```

- The `exec` function can be used to execute OS commands programmatically. Users can pass the command as a raw template. Additionally, users can pass any number of environment properties as key-value pairs that need to be set when executing the command.

```ballerina
# Environment properties that need to be set when executing the command.
#
# + command - command which cannot be a key
public type EnvProperties record {|
    never command?;
|};
```

- Represents an environment property as an included record type.

```ballerina
# This object contains information on a process being created from Ballerina.
# This is returned from the `exec` function.
public class Process {

    # Waits for the process to finish its work and exit.
    # ```ballerina
    # int|os:Error exitCode = process.waitForExit();
    # ```
    #
    # + return - Returns the exit code for the process, or else an `Error` if a failure occurs
    public isolated function waitForExit() returns int|Error;

    # Provides a stream (to read from), which is made available as the 'standard error', or the 'standard out' of the process.
    # ```ballerina
    # stream<string, os:Error?>|os:Error err = process.fread(io:stderr);
    # ```
    #
    # + return - The `stream<string, Error?>`, which represents the process's 'standard error', or the 'standard out', or an Error
    public isolated function fread(io:FileOutputStream fileOutputStream) returns stream<string, Error?>|Error;

    # Terminates the process.
    # ```ballerina
    # var result = process.exit();
    # ```
    #
    public isolated function exit();
}
```

## Testing

- Execute an OS command using the `exec` function and validate whether it was successful.
- Pass an environment property to the `exec` function and validate if it was set correctly.

**Comment by daneshk** [comment]
Do we need two APIs as `waitForExit` and `exitCode`. Can't we have only one? 

For `stdout` and `stderr`, can't we have one API like in the IO module[1]

1. https://github.com/ballerina-platform/module-ballerina-io/blob/master/ballerina/print.bal#L75

**Comment by daneshk** [comment]
IMO, process `exit()` is more suit than `destroy()`

**Comment by MadhukaHarith92** [comment]
> Do we need two APIs as `waitForExit` and `exitCode`. Can't we have only one?

+1, removed `exitCode()` since it is redundant.
> 
> For `stdout` and `stderr`, can't we have one API like in the IO module[1]
> 
>     1. https://github.com/ballerina-platform/module-ballerina-io/blob/master/ballerina/print.bal#L75

Merged the 2 APIs to a single API `fprint()`.

**Comment by MadhukaHarith92** [comment]
> IMO, process `exit()` is more suit than `destroy()`

Renamed the API to `exit()`

**Comment by daneshk** [comment]
> > Do we need two APIs as `waitForExit` and `exitCode`. Can't we have only one?
> 
> +1, removed `exitCode()` since it is redundant.
> 
> > For `stdout` and `stderr`, can't we have one API like in the IO module[1]
> > ```
> > 1. https://github.com/ballerina-platform/module-ballerina-io/blob/master/ballerina/print.bal#L75
> > ```
> 
> Merged the 2 APIs to a single API `fprint()`.

Here we are reading from the file descriptor? should be `fread()`

**Comment by daneshk** [comment]
@MadhukaHarith92 why do we need `any` type for the command?

**Comment by MadhukaHarith92** [comment]
> @MadhukaHarith92 why do we need `any` type for the command?

Removed `any` type from the union. The insertions will be of `any` type.

**Comment by daneshk** [comment]
@sameerajayasoma Can you please review

**Comment by sameerajayasoma** [comment]
I am a little bit confused about the `fread` method. What does it return? The stdout or stderr. 

Concern on the implementability: Don't we need the command and the arguments as separate strings?

**Comment by MadhukaHarith92** [comment]
> I am a little bit confused about the `fread` method. What does it return? The stdout or stderr.

The return type will vary based on the `fileOutputStream` input (of type `io:FileOutputStream`) passed to the `fread()` function. For instance, `process.fread(io:stderr)` will return an `STDERR` stream where as `process.fread(io:stdout)` will return an `STDOUT` stream.
> 
> Concern on the implementability: Don't we need the command and the arguments as separate strings?

We thought of accepting a single raw template as the input to improve user experience. From the implementation perspective, the input will be delimited by spaces, and the first item in the array will be the command and the rest will be the arguments.

**Comment by sameerajayasoma** [comment]
> The return type will vary based on the `fileOutputStream` input (of type `io:FileOutputStream` which is an enum[[1]](https://github.com/ballerina-platform/module-ballerina-io/blob/00ccc1c49c518a5d7e11be5ff45c7e94f751fa6d/ballerina/print.bal#L28)) passed to the `fread()` function. For instance, `process.fread(io:stderr)` will return an `STDERR` stream where as `process.fread(io:stdout)` will return an `STDOUT` stream.

Ack. Thanks.
> 
> > Concern on the implementability: Don't we need the command and the arguments as separate strings?
> 
> We thought of accepting a single raw template as the input to improve user experience. From the implementation perspective, the input will be delimited by spaces, and the first item in the array will be the command and the rest will be the arguments.

Are we planning to parse the complete command to figure out the command and its arguments? E.g. `$> foo bar "some input" "another input"`.

Don't we need to way to write to the stdin of the process?

**Comment by MadhukaHarith92** [comment]
> Are we planning to parse the complete command to figure out the command and its arguments? E.g. `$> foo bar "some input" "another input"`.

Updated the `os:exec()` API. Users will pass the command as a record with value and arguments as separate fields.

```ballerina
public type Command record {
    string value;
    string[] arguments;
};
public isolated function  exec(Command command, string? dir = (), *EnvProperties envProperties) returns Process | Error;
```

eg:
```ballerina
os:Process|os:Error process = os:exec({value: "bal", arguments: ["run", filepath]}, dir = "/User/MyProject", BAL_CONFIG_FILE = "/abc/Config.toml");
```
> 
> Don't we need to way to write to the stdin of the process?

Suggested API:
```ballerina
public isolated function write() returns io:WritableChannel|Error;
```

We thought of exposing the channel APIs of the io module[[1]](https://github.com/ballerina-platform/module-ballerina-io/blob/master/ballerina/channel_string_io.bal) so that users can write to the `io:WritableChannel` returned in `write()` function.

eg:
```ballerina
os:Process|os:Error process = os:exec({value: "bal", arguments: ["run", filepath]}, dir = "/User/MyProject", BAL_CONFIG_FILE = "/abc/Config.toml");

check io:WritableChannel input = process.write();
check channelWriteString(input, "success");
```

Similarly, `fread()` function will return `io:ReadableChannel`.
```ballerina
public isolated function fread(io:FileOutputStream fileOutputStream) returns io:ReadableChannel|Error;
```

WDYT?

[1] https://github.com/ballerina-platform/module-ballerina-io/blob/master/ballerina/channel_string_io.bal

**Comment by daneshk** [comment]
Based on the discussion we(Madhuka and me) had, decided to go with the below design for the initial phase, without write operation and working directory, etc.

Provide the `os:exec` function that executes the command and returns the` os:Process` class

```
# Executes an operating system command as a subprocess of the current process.
# ```ballerina
# os:Process|os:Error result = os:exec({value: "bal", arguments: ["run", filepath]}, BAL_CONFIG_FILE = "/abc/Config.toml");
# ```
#
# + command - The command to be executed
# + envProperties - The environment properties
#
# + return - Process object in success, or an Error if a failure occurs
public isolated function  exec(Command command, *EnvProperties envProperties) returns Process | Error;
```
where the Command consists of command and arguments as follows,

```
public type Command record {|
    string value;
    string[] arguments = [];
|};
```
Users can pass any number of environment properties as key-value pairs that need to be set when executing the command.

```
public type EnvProperties record {|
    never command?;
|};
```

The `os:Process` object definition looks like below,

```
# This object contains information on a process being created from Ballerina.
# This is returned from the `exec` function.
public class Process {

    # Waits for the process to finish its work and exit.
    # ```ballerina
    # int|os:Error exitCode = process.waitForExit();
    # ```
    #
    # + return - Returns the exit code for the process, or else an `Error` if a failure occurs
    public isolated function waitForExit() returns int|Error;

    # Returns the standard output as default. Option provided to return standard error by providing file descriptor.
    # ```ballerina
    # byte[]|os:Error err = process.output(io:stderr);
    # ```
    #
    # + return - The `stream<string, Error?>`, which represents the process's 'standard error', or the 'standard out', or an Error
    public isolated function output(io:FileOutputStream fileOutputStream = io:stdout) returns byte[]|Error;

    # Terminates the process.
    # ```ballerina
    # var result = process.exit();
    # ```
    #
    public isolated function exit();
}
```

**Comment by daneshk** [comment]
For the next phase, we need to provide the following options,
* Change the working directory of the subprocess
* Provide support to read and write from stdin, stdout, and stderr using channel support (Need to support Channels from IO module).
