### ISSUE TITLE
Proposal: Ballerina SerDes module

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#2964]
## Summary
Proposing an effective way to serialize/deserialize Ballerina `anydata` type to send them efficiently over the wire.

## Goals
- Come up with a package to serialize/deserialize Ballerina anydata that requires minimal user input.
- Protocol modules such as HTTP, WS, Kafka, NATS, RabbitMQ should be able to seamlessly integrate with this package.
- Protocol buffers could be used to serialize data in a compact binary format.

## Motivation

Ballerina language supports the concept of anydata, which can be sent across the network. In order to do so, it is required to serialize/deserialize anydata in some form. Converting anydata to JSON and sending it over the wire is the current approach. Even though this approach is appropriate in certain use cases, there are more efficient ways to serialize/deserialize data such as proto3 (by Google) or avro (by Hadoop).

## Description

As mentioned in the Goals section, the primary goal of this proposal is to come up with a standard library package to serialize and deserialize anydata type. Initially `proto3` will be used as the main underlying technology to implement the package. The package will include other technologies such as `Avro` in future.

### Proto3
Protocol Buffers is a method of serializing structured data developed by Google, and proto3 is the latest version of Protocol Buffers. Protocol Buffers use `.proto` files to define messages (similar to a Ballerina record type) in proto3 syntax and the messages are used to generate the proto schema that can later be populated with data. These generated messages can be serialized/deserialized more efficiently compared to JSON. More information related to proto3 can be found in the official [documentation](https://developers.google.com/protocol-buffers/docs/overview).

Ballerina type | proto3 type
---------------------- | ----------------------
int | sint64
byte | bytes
float | double
decimal | message
boolean | bool
string | string
array | repeated `type`
tuple | message
map | message
table | message
record | message
Union | message
enum | message

Following are the example of ballerina type to proto message

#### Primitvie

1. int, byte, string, boolean and float uses the flowing message format

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
string package = "serdes";
</pre>
</td>
<td>
<pre>
message StringValue {
    string atomicField = 1;
}
</pre>
</td>
</tr>

<tr></tr>

<tr>
<td>
<pre>
int age = 24;
</pre>
</td>
<td>
<pre>
message IntValue {
  sint64 atomicField = 1;
}
</pre>
</td>
</tr>
<table>

2. decimal type uses the following message format
 <table>

<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
decimal salary = 2e5;
</pre>
</td>
<td>
BigDecimal
<pre>
message DecimalValue {
    uint32 scale = 1;
    uint32 precision = 2;
    bytes value = 3;
}
</pre>
</td>
</tr>
</table>

#### Array

1. Simple arrays
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type IntArray int[];
</pre>
</td>
<td>
<pre>
message ArrayBuilder {
    repeated sint64 arrayField = 1;
}
</pre>
</td>
</tr>

<tr></tr>

<tr>
<td>
<pre>
type FloatArray float[];
</pre>
</td>
<td>
<pre>
message ArrayBuilder {
    repeated double arrayField = 1;
}
</pre>
</td>
</tr>

<tr></tr>

<tr>
<td>
<pre>
type DecimalArray decimal[];
</pre>
</td>
<td>
<pre>
message ArrayBuilder {
  message DecimalValue {
     uint32 scale  = 1;
     uint32 precision  = 2;
     bytes value  = 3;
  }
  repeated DecimalValue arrayField  = 1;
}
</pre>
</td>
</tr>
<table>

2. Multidimensional arrays

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type String2DArray string[][];
</pre>
</td>
<td>
<pre>
message ArrayBuilder {
  message ArrayBuilder {
     repeated string arrayField  = 1;
  }
  repeated ArrayBuilder arrayField  = 1;
}
</pre>
</td>
</tr>

<tr></tr>

<tr>
<td>
<pre>
type Decimal3DArray decimal[][][];
</pre>
</td>
<td>
<pre>
message ArrayBuilder {
  message ArrayBuilder {
    message ArrayBuilder {
      message DecimalValue {
         uint32 scale  = 1;
         uint32 precision  = 2;
         bytes value  = 3;
      }
      repeated DecimalValue arrayField  = 1;
    }
    repeated ArrayBuilder arrayField  = 1;
  }
  repeated ArrayBuilder arrayField  = 1;
}
</pre>
</td>
</tr>
<table>

#### Union

1. Union with primitive types

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type PrimitiveUnion  int|byte|float|decimal|string?; 
</pre>
</td>
<td>
<pre>
message UnionBuilder {
  message DecimalValue {
     uint32 scale  = 1;
     uint32 precision  = 2;
     bytes value  = 3;
  }
  sint64 int___unionField  = 1;
  bytes byte___unionField  = 2;
  double float___unionField  = 3;
  DecimalValue decimal___unionField  = 4;
  string string___unionField  = 5;
  bool nullField  = 6;
}

</pre>
</td>
</tr>
<tr><td colspan="2">`&lttype>___` prefix added to avoid name collision in protobuf schema generation</td></tr>
<table>

2. Union of multidimensional arrays

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type UnionWithArray int[][]|float[]|string[][][];
</pre>
</td>
<td>
<pre>
message UnionBuilder {
  message int___ArrayBuilder_1 {
     repeated sint64 arrayField  = 1;
  }
  message string___ArrayBuilder_2 {
    message ArrayBuilder {
       repeated string arrayField  = 1;
    }
    repeated ArrayBuilder arrayField  = 1;
  }
  repeated int___ArrayBuilder_1 int___arrayField_2___unionField  = 1;
  repeated double float___arrayField_1___unionField  = 2;
  repeated string___ArrayBuilder_2 string___arrayField_3___unionField  = 3;
}
</pre>
</td>
</tr>
<tr><td colspan="2">
A (union) member array has the following name format for message field name and nested message name:
<ul>
<li>Field name format: `&lttype>___arrayField_&ltdimension>_unionField`</li>
<li>Nested message name format: `&lttype>_ArrayBuilder_&ltdimension>`</li>
</ul>
Here `&lttype>`, `&ltdimension>` used to avoid name collision in protobuf schema generation.
</td></tr>
<table>

3. Union of union-arrays

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type IntOrString int|string;
</pre>
<pre >
type FloatOrNill float?;
</pre>
<pre >
type <b>UnionArray</b> IntOrString[]|FloatOrNill[];
</pre>
</td>
<td>
<pre>
message UnionBuilder {
  message IntOrString___UnionBuilder {
     sint64 int___unionField  = 1;
     string string___unionField  = 2;
  }
  message FloatOrNill___UnionBuilder {
     double float___unionField  = 1;
     bool nullField  = 2;
  }
  repeated IntOrString___UnionBuilder IntOrString___arrayField_1___unionField  = 1;
  repeated FloatOrNill___UnionBuilder FloatOrNill___arrayField_1___unionField  = 2;
}
</pre>
</td>
</tr>
<table>

#### Record

1. Simple record with primitive types
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type Employee record {
    string name;
    byte age;
    int weight;
    float height;
    boolean isMarried;
    decimal salary;
};
</pre>
</td>
<td>
<pre>
message Employee {
  message DecimalValue {
     uint32 scale  = 1;
     uint32 precision  = 2;
     bytes value  = 3;
  }
  string name  = 1;
  bytes age  = 2;
  sint64 weight  = 3;
  double height  = 4;
  bool isMarried  = 5;
  DecimalValue salary  = 6;
}
</pre>
</td>
</tr>
<tr><td colspan="2">Proto message name and field names are the same as the ballerina record type name and field names.</td></tr>
<table>

2. Record with arrays fields

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type RecordWithSimpleArrays record {
    string[] stringArray;
    int[] intArray;
    float[] floatArray;
    boolean[] boolArray;
    byte[] byteArray;
};
</pre>
</td>
<td>
<pre>
message RecordWithSimpleArrays {
   repeated string stringArray  = 1;
   repeated sint64 intArray  = 2;
   repeated double floatArray  = 3;
   repeated bool boolArray  = 4;
   bytes byteArray  = 5;
}
</pre>
</td>
</tr>
<tr></tr>
<tr>
<td>
<pre >
type RecordWithMultidimentionalArrays record {
    string[][][] string3DArray;
    decimal[][] decimal2DArray;
};
</pre>
</td>
<td>
<pre>
message RecordWithMultidimentionalArrays {
  message decimal2DArray___ArrayBuilder {
    message DecimalValue {
       uint32 scale  = 1;
       uint32 precision  = 2;
       bytes value  = 3;
    }
    repeated DecimalValue arrayField  = 1;
  }
  message string___ArrayBuilder_3 {
    message ArrayBuilder {
       repeated string arrayField  = 1;
    }
    repeated ArrayBuilder arrayField  = 1;
  }
  repeated string3DArray___ArrayBuilder string3DArray  = 1;
  repeated decimal2DArray___ArrayBuilder decimal2DArray  = 2;
}

</pre>
</td>
</tr>
<table>

3. Record with union fields

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type RecordWithUnion record {
    int|string? data;
};
</pre>
</td>
<td>
<pre>
message RecordWithUnion {
  message data___UnionBuilder {
     bool nullField  = 1;
     sint64 int___unionField  = 2;
     string string___unionField  = 3;
  }
  data___UnionBuilder data  = 1;
}
</pre>
</td>
</tr>
<tr><td colspan="2">Nested message names of union messages are prefixed with ballerina record field name to avoid name collision, generally the union message name follows the form of `&ltrecordFieldName>__UnionBuilder`
</td></tr>
<table>

4. Record with cyclic references

<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type <b>Node1</b> record {
    string name;
    Nested2? nested;
};
</pre>
<pre >
type Node2 record {
    string name;
    Nested3? nested;
};
</pre>
<pre >
type Node3 record {
    string name;
    Nested1? nested;
};
</pre>
</td>
<td>
<pre>
message <b>Node1</b> {
  message nested___UnionBuilder {
    message Node2 {
      message nested___UnionBuilder {
        message Node3 {
          message nested___UnionBuilder {
             Nested1 Nested1___unionField  = 1;
             bool nullField  = 2;
          }
          string name  = 1;
          nested___UnionBuilder nested  = 2;
        }
        Nested3 Nested3___unionField  = 1;
        bool nullField  = 2;
      }
      string name  = 1;
      nested___UnionBuilder nested  = 2;
    }
    Nested2 Nested2___unionField  = 1;
    bool nullField  = 2;
  }
  string name  = 1;
  nested___UnionBuilder nested  = 2;
}
</pre>
</td>
</tr>
<table>

#### Map

1. Map with primitive types
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type MapInt map&lt;int>;
</pre>
</td>
<td>
<pre>
message MapBuilder {
  message MapFieldEntry {
     string key  = 1;
     sint64 value  = 2;
  }
  repeated MapFieldEntry mapField  = 1;
}
</pre>
</td>
</tr>

<tr></tr>

<tr>
<td>
<pre >
type MapDecimal map&lt;decimal>;
</pre>
</td>
<td>
<pre>
message MapBuilder {
  message MapFieldEntry {
    message DecimalValue {
       uint32 scale  = 1;
       uint32 precision  = 2;
       bytes value  = 3;
    }
    string key  = 1;
    DecimalValue value  = 2;
  }
  repeated MapFieldEntry mapField  = 1;
}
</pre>
</td>
</tr>
<table>

2. Map with records
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type Status record {
    int code;
    string message?;
};
</pre>
<pre >
type <b>MapRecord</b> map&lt;Status>;
</pre>
</td>
<td>
<pre>
message <b>MapBuilder</b> {
  message MapFieldEntry {
    message Status {
       sint64 code  = 1;
       string message  = 2;
    }
    string key  = 1;
    Status value  = 2;
  }
  repeated MapFieldEntry mapField  = 1;
}
</pre>
</td>
</tr>
<table>

3. Map with arrays
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type IntMatrix int[][];
</pre>
<pre >
type <b>MapArray</b> map&lt;IntMatrix>;
</pre>
</td>
<td>
<pre>
message <b>MapBuilder</b> {
  message MapFieldEntry {
    message ArrayBuilder {
       repeated sint64 arrayField  = 1;
    }
    string key  = 1;
    repeated ArrayBuilder value  = 2;
  }
  repeated MapFieldEntry mapField  = 1;
}
</pre>
</td>
</tr>
<table>

4. Map with unions
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type Status record {
    int code;
    string message?;
};
</pre>
<pre >
type IntMatrix int[][];
</pre>
<pre >
type <b>MapUnion</b> map&lt;Status|IntMatrix>;
</pre>
</td>
<td>
<pre>
message <b>MapBuilder</b> {
  message MapFieldEntry {
    message value___UnionBuilder {
      message Status {
         sint64 code  = 1;
         string message  = 2;
      }
     message int___ArrayBuilder_1 {
        repeated sint64 arrayField  = 1;
      }
      Status Status___unionField  = 1;
      repeated int___ArrayBuilder_1 int___arrayField_2___unionField  = 2;
    }
    string key  = 1;
    value___UnionBuilder value  = 2;
  }
  repeated MapFieldEntry mapField  = 1;
}
</pre>
</td>
</tr>
<table>

5. Map with maps
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type Status record {
    int code;
    string message?;
};
</pre>
<pre >
type IntMatrix int[][];
</pre>
<pre >
type MapUnion map&lt;Status|IntMatrix>;
</pre>
<pre>
type <b>MapOfMaps</b> map&lt;MapUnion>;
</pre>
</td>
<td>
<pre>
message <b>MapBuilder</b> {
  message MapFieldEntry {
    message MapBuilder {
      message MapFieldEntry {
        message value___UnionBuilder {
          message Status {
             sint64 code  = 1;
             string message  = 2;
          }
         message int___ArrayBuilder_1 {
            repeated sint64 arrayField  = 1;
          }
          Status Status___unionField  = 1;
          repeated int___ArrayBuilder_1 int___arrayField_2___unionField  = 2;
        }
        string key  = 1;
        value___UnionBuilder value  = 2;
      }
      repeated MapFieldEntry mapField  = 1;
    }
    string key  = 1;
    MapBuilder value  = 2;
  }
  repeated MapFieldEntry mapField  = 1;
}

</pre>
</td>
</tr>
<table>

#### Table

1. Table with Map constraint
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre >
type Score map<int>;
</pre>
<pre>
type <b>ScoreTable</b> table&lt;Score>;
</pre>
</td>
<td>
<pre>
message <b>TableBuilder</b> {
  message MapBuilder {
    message MapFieldEntry {
       string key  = 1;
       sint64 value  = 2;
    }
    repeated MapFieldEntry mapField  = 1;
  }
  repeated MapBuilder tableEntry  = 1;
}
</pre>
</td>
</tr>
<table>
2. Table with record constraint
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>

<pre >
type Row record {
    int id;
    string name;
};
</pre>
<pre>
type <b>RecordTable</b> table&lt;Row>;
</pre>
</td>
<td>
<pre>
message <b>TableBuilder</b> {
  message Row {
     sint64 id  = 1;
     string name  = 2;
  }
  repeated Row tableEntry  = 1;
}
</pre>
</td>
</tr>
<table>

#### Tuple
1. Tuple with primitive type elements
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre>
type PrimitiveTuple [byte, int, float, boolean, string ,decimal];
</pre>
</td>
<td>
<pre>
message TupleBuilder {
  message DecimalValue {
     uint32 scale  = 1;
     uint32 precision  = 2;
     bytes value  = 3;
  }
  bytes element_1  = 1;
  sint64 element_2  = 2;
  double element_3  = 3;
  bool element_4  = 4;
  string element_5  = 5;
  DecimalValue element_6  = 6;
}
</pre>
</td>
</tr>
<table>

 2. Tuple with Union elements 
<table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre>
type TupleWithUnion [byte|string, decimal|boolean];
</pre>
</td>
<td>
<pre>
message TupleBuilder {
  message element_1___UnionBuilder {
     bytes byte___unionField  = 1;
     string string___unionField  = 2;
  }
  message element_2___UnionBuilder {
   message DecimalValue {
      uint32 scale  = 1;
      uint32 precision  = 2;
      bytes value  = 3;
    }
    bool boolean___unionField  = 1;
    DecimalValue decimal___unionField  = 2;
  }
  element_1___UnionBuilder element_1  = 1;
  element_2___UnionBuilder element_2  = 2;
}
</pre>
</td>
</tr>
<table>

 3. Tuple with array elements
 <table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre>
type UnionTupleElement byte|string;
</pre>
<pre>
type <b>TupleWithArray</b> [string[], boolean[][], int[][][], UnionTupleElement[]];
</pre>
</td>
<td>
<pre>
message TupleBuilder {
  message int___ArrayBuilder_2 {
    message ArrayBuilder {
       repeated sint64 arrayField  = 1;
    }
    repeated ArrayBuilder arrayField  = 1;
  }
 message UnionTupleElement___UnionBuilder {
    bytes byte___unionField  = 1;
    string string___unionField  = 2;
  }
 message boolean___ArrayBuilder_1 {
    repeated bool arrayField  = 1;
  }
  repeated string element_1  = 1;
  repeated boolean___ArrayBuilder_1 element_2  = 2;
  repeated int___ArrayBuilder_2 element_3  = 3;
  repeated UnionTupleElement___UnionBuilder element_4  = 4;
}

</pre>
</td>
</tr>
<table>

 4. Tuple with record elements
   <table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre>
type Student record {
    string name;
    int courseId;
    decimal fees;
};
</pre>
<pre>
type Teacher record {
    string name;
    int courseId;
    decimal salary;
};
</pre>
<pre>
type <b>TupleWithRecord</b> [Student, Teacher];
</pre>
</td>
<td>
<pre>
message <b>TupleBuilder</b> {
  message Teacher {
    message DecimalValue {
       uint32 scale  = 1;
       uint32 precision  = 2;
       bytes value  = 3;
    }
    sint64 courseId  = 1;
    string name  = 2;
    DecimalValue salary  = 3;
  }
  message Student {
    message DecimalValue {
      uint32 scale  = 1;
      uint32 precision  = 2;
      bytes value  = 3;
    }
    sint64 courseId  = 1;
    DecimalValue fees  = 2;
    string name  = 3;
  }
  Student element_1  = 1;
  Teacher element_2  = 2;
}
</pre>
</td>
</tr>
<table>

 5. Tuple with tuple elements
    <table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre>
type PrimitiveTuple [byte, int, float, boolean, string ,decimal];
</pre>
<pre>
type TupleWithUnion [byte|string, decimal|boolean];
</pre>
<pre>
type <b>TupleOfTuples</b> [PrimitiveTuple, TupleWithUnion];
</pre>
</td>
<td>
<pre>
message TupleBuilder {
  message element_2___TupleBuilder {
    message element_1___UnionBuilder {
       bytes byte___unionField  = 1;
       string string___unionField  = 2;
    }
    message element_2___UnionBuilder {
     message DecimalValue {
        uint32 scale  = 1;
        uint32 precision  = 2;
        bytes value  = 3;
      }
      bool boolean___unionField  = 1;
      DecimalValue decimal___unionField  = 2;
    }
    element_1___UnionBuilder element_1  = 1;
    element_2___UnionBuilder element_2  = 2;
  }
  message element_1___TupleBuilder {
    message DecimalValue {
       uint32 scale  = 1;
       uint32 precision  = 2;
       bytes value  = 3;
    }
    bytes element_1  = 1;
    sint64 element_2  = 2;
    double element_3  = 3;
    bool element_4  = 4;
    string element_5  = 5;
    DecimalValue element_6  = 6;
  }
  element_1___TupleBuilder element_1  = 1;
  element_2___TupleBuilder element_2  = 2;
}
</pre>
</td>
</tr>
<table>

#### Enum
Ballerina enum is a syntactic sugar of union of constant strings thus enum is handled as union in protobuf level
     <table >
<tr>
<th> Ballerina </th>
<th> Proto message </th>
 </tr>

<tr></tr>

<tr>
<td>
<pre>
enum Color {
    RED=”red”,
    GREEN,
    BLUE
}
</pre>
</td>
<td>
<pre>
message UnionBuilder {
   string string___unionField  = 1;
}
</pre>
</td>
</tr>
<tr></tr>

<tr>
<td>
<pre>
const OPEN = "open";
const CLOSE = "close";
type <b>STATE</b> OPEN|CLOSE;
</pre>
</td>
<td>
<pre>
message <b>UnionBuilder</b> {
   string string___unionField  = 1;
}
</pre>
</td>
</tr>
<table>

### SerDes API

```ballerina
// serdes Error
public type Error distinct error; 

// Abstract object
public type Schema object {

  public isolated function serialize(anydata data) returns byte[]|Error;

  public isolated function deserialize(byte[] encodedMessage, typedesc<anydata> T = <>) returns T|Error;
}
```

Ex: Implementing Proto3 version of serialization & deserialization
```ballerina
public class Proto3Schema {
  *Schema;

   // Implement serialize(), deserialize() methods here

   public isolated function deserialize(byte[] encodedMessage,  typedesc<anydata> T = <>) returns T|Error = 
   @java:Method {
      'class: "io.ballerina.stdlib.serdes...."
   }  external;
}
```

Similar to the above `Proto3Schema` implementation other versions of serialization & deserialization can be implemented in future (Ex: `AvroSchema`)

#### Serialize
```ballerina
import ballerina/serdes;

type Person record {
   string name;
   string age;
}

public function main() returns error? {
  
   Person president = { name: "Joe",  age:70 };

   // This should be able to generate the required schema and then the classes
   serdes:Schema schema = check new Proto3Schema(Person);

   // Serialize president value into a byte array
   byte[] encoded = check schema.serialize(president);
}
```

#### Deserialize
```ballerina
import ballerina/serdes;

type Person record {
   string name;
   string age;
}

public function main() returns error {

    byte[] encoded = <bytes>;

    // This should be able to generate the required schema and then the classes
    serdes:Schema schema = check new Proto3Schema(Person);

    // deserialize president value into Person type
    Person president = check schema.deserialize(encoded);
}
```

### Design Considerations 

The design of the Standard Library SerDes package can be divided into following 2 phases,

1. Implement dynamic schema & message generation using the proto3 Java API.

Dynamic Schema creation could be implemented as a separate Java package with the help of Protocol Buffers' [Java API](https://developers.google.com/protocol-buffers/docs/reference/java). Making this implementation independent of the rest of the code will make it easier to move between different serialization/deserialization technologies such as [Avro](https://avro.apache.org/docs/current/) in the future.

2. Creating a mapping between Ballerina anydata types and Proto3 message.

A parser should be implemented to convert Ballerina anydata to proto3 message and vice versa. The parser should be able to map Ballerina anydata types to proto3 [field types](https://developers.google.com/protocol-buffers/docs/proto3#specifying_field_types).

## Alternatives

[Thrift](https://thrift.apache.org/), [Avro](https://avro.apache.org/docs/current/) are some alternative serialization technologies but proto3 has the fastest performance. Comparison between Avro and Protocol buffer can be found [here](https://dataforgeeks.com/data-serialisation-avro-vs-protocol-buffers/2015/).

**Comment by MohamedSabthar** [comment]
Related Issue:[ #780](https://github.com/ballerina-platform/ballerina-standard-library/issues/780)

**Comment by shafreenAnfar** [comment]
@MohamedSabthar Shall we update description section of the proposal with the mapping between proto schema and Ballerina types.
