### ISSUE TITLE
Proposal: Metadata retrieval support for SQL connectors

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#2965]
## Summary
Introduce a metadata client, APIs and corresponding record types to retrieve and represent metadata relating to tables,
columns and constraints of relational databases.

## History
In 1.4.x versions and below of SQL packages, there was no specific support to retrieve metadata. Instead, the SQL
`query()` method  could have been used to query the tables specific to the RDBMS containing metadata, and then retrieve
and parse the required information.

This requires the user to have in-depth knowledge of the RDBMS being used in order to understand the schema which
is used to store the metadata.

## Goals
- Support to retrieve and map metadata relating to tables, columns and constraints in a relational database.
- Provide an extensible design which can be implemented by the SQL connectors (`MySQL`, `MSSQL`, `PostgreSQL`, `OracleDB`, and any other future connectors).

## Non-goals
- This would only provide support to retrieve metadata from one database per client. If there is a requirement to retrieve metadata regarding multiple databases, then multiple databases would have to be created.

## Motivation
With this support, the user would not need to write specific queries, nor have in-depth knowledge of the RDBMS being used.
Instead, they may make simple API calls to retrieve the necessary information.

### Schema client
A new client would be introduced which is used to query the database to retrieve the relevant metadata. On initialization,
the user would have to provide credentials to access the relevant metadata tables. It is also required to provide the name of the database regarding which the metadata should be retrieved.

#### Example client initialization (for MySQL)
```ballerina
# Represents a Mock database schema client.
isolated client class MockSchemaClient {
    *SchemaClient;

    public function init(string host, int port, string user, string password, string database) returns Error? {
        // Use the connector's underlying `client` to establish the connection.
    }
}
```

> **_NOTE:_**  The parameter `database` in the example above refers to the database for which the metadata retrieved is
> about. It does not indicate that the client connects to that database.

This client can be extended by each SQL connector to customize the implementation as necessary.

### Types
New record-types would be introduced to represent the metadata which may be retrieved.
- `TableDefinition`
- `ColumnDefinition`
- `CheckConstraintDefinition`
- `ReferentialConstraintDefinition`
- `RoutineDefinition`
- `ParameterDefinition`

These record types contain only fields which are common to relational databases. However, they may be inherited and then
extended by each SQL connector to provide support for additional database-specific fields.

#### Table Definition
```ballerina
# Represents a table in the database.
#
# + name - The name of the table
# + 'type - Whether the table is a base table or a view
# + columns - The columns included in the table
public type TableDefinition record {
    string name;
    TableType 'type;
    ColumnDefinition[] columns?;
};
```

The `columns` field is optional as there are use cases where the user would not want to retrieve information regarding
the columns of a table.

The `TableType` type is an enum, which can take one of two values:
- `BASE_TABLE`
- `VIEW`

#### Column Definition
```ballerina
# Represents a column in a table.
#
# + name - The name of the column  
# + 'type - The SQL data-type associated with the column
# + defaultValue - The default value of the column  
# + nullable - Whether the column is nullable  
# + referentialConstraints - Referential constraints (foreign key relationships) associated with the column
# + checkConstraints - Check constraints associated with the column
public type ColumnDefinition record {
    string name;
    string 'type;
    anydata? defaultValue;
    boolean nullable;
    ReferentialConstraint[] referentialConstraints?;
    CheckConstraint[] checkConstraints?;
};
```

The `referentialConstraints` and `checkConstraints` fields are optional as there may be use cases where the user does not
want to retrieve this information.

#### Referential Constraint
```ballerina
# Represents a referential constraint (foriegn key constraint).
# 
# + name - The name of the constraint
# + tableName - The name of the table which contains the referenced column
# + columnName - The name of the referenced column
# + updateRule - The action taken when an update statement violates the constraint
# + deleteRule - The action taken when a delete statement violates the constraint
public type ReferentialConstraint record {
    string name;
    string tableName;
    string columnName;
    ReferentialRule updateRule;
    ReferentialRule deleteRule; 
};
```

The `ReferentialRule` type is an enum with four possible values:
- `NO_ACTION`
- `RESTRICT`
- `CASCADE`
- `SET_NULL`
- `SET_DEFAULT`

#### Check Constraint
```ballerina
# Represents a check constraint.
# 
# + name - The name of the constraint
# + clause - The actual text of the SQL definition statement
public type CheckConstraint record {
    string name;
    string clause;
};
```

#### Routine Definition
```ballerina
# Represents a routine.
# 
# + name - The name of the routine
# + 'type - The type of the routine (procedure or function)
# + returnType - If the routine returns a value, the return data-type. Else ()
# + parameters - The parameters associated with the routine
public type RoutineDefinition record {
    string name;
    RoutineType 'type;
    string? returnType;
    ParameterDefinition[] parameters;
};
```

The `RoutineType` type is an enum which can take one of two values
- `PROCEDURE`
- `FUNCTION`

#### Parameter Definition
```ballerina
# Represents a routine parameter.
# 
# + mode - The mode of the parameter (IN, OUT, INOUT)
# + name - The name of the parameter
# + type - The data-type of the parameter
public type ParameterDefinition record {
    ParameterMode mode;
    string name;
    string type;
};
```

The `ParameterMode` type is an enum which can take one of three values
- `IN`
- `OUT`
- `INOUT`

### Methods
The `SchemaClient` will contain six methods which may be used to retrieve metadata.
- `listTables()`
- `getTableInfo()`
- `listRoutines()`
- `getRoutineInfo()`

All of these methods will be implemented by each SQL connector.

#### Retrieve all tables
```ballerina
remote isolated function listTables() returns string[]|Error;
```
This would fetch the names of all the tables in the database.

#### Retrieve a single table
```ballerina
remote isolated function getTableInfo(string tableName, ColumnRetrievalOptions include = COLUMNS_ONLY) returns TableDefinition|Error;

public enum ColumnRetrievalOptions {
    NO_COLUMNS,
    COLUMNS_ONLY,
    COLUMNS_WITH_CONSTRAINTS
}
```
This would fetch all relevant information from a given table from the database. Based on the option provided for the `include` parameter, relevant column information would also be retrieved.

#### Retrieve all routines
```ballerina
remote isolated function listRoutines() returns string[]|Error;
```
This would fetch the names of all the routines created in the database.

#### Retrieve a single routine
```ballerina
remote isolated function getRoutineInfo(string name) returns RoutineDefinition|Error;
```
This would fetch all relevant information regarding the provided routine (including the parameter data).

## References
[1] https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/system-information-schema-views-transact-sql?view=sql-server-ver16
[2] https://www.postgresql.org/docs/current/information-schema.html
[3] https://dev.mysql.com/doc/mysql-infoschema-excerpt/8.0/en/information-schema-table-reference.html
[4] https://docs.oracle.com/cd/E19078-01/mysql/mysql-refman-5.0/information-schema.html

**Comment by daneshk** [comment]
Few Suggestions:

* Instead of `MetadataClient`, shall we name the client as `SchemaClient`. As this client provides DB schema information.
* Shall we have the following APIs,

**List Tables in the Database**
```ballerina
remote isolated function listTables() returns string[]|Error;
```

**Get Table Info**
```ballerina
remote isolated function getTableInfo(string name, XYZ include = COLUMNS) returns TableDefinition|Error;

type enum XYZ(proper name) {
  COLUMNS;
  COLUMNS_WITH_CONSTRAINS;
}
```
We don't APIs to fetch column details. we can fetch them with Table definition.

**List Routines in the Database**
```ballerina
remote isolated function listRoutines() returns string[]|Error;
```

**Get Routine Info**
```ballerina
remote isolated function getRoutineInfo(string name) returns RoutineDefinition|Error;
```

@kaneeldias WDYT?

**Comment by daneshk** [comment]
For the client init function parameter, shall we keep the order the same as other SQL clients and make database a required param

**Comment by kaneeldias** [comment]
> For the client init function parameter, shall we keep the order the same as other SQL clients and make database a required param

This would be idea, but in that case the compilation fails with `required parameter after the defaultable parameter` since the username, password etc. would be defaultable. Any better solutions for this?

**Comment by kaneeldias** [comment]
@daneshk the proposal has been updated with the feedbackl

**Comment by daneshk** [comment]
> > For the client init function parameter, shall we keep the order the same as other SQL clients and make database a required param
> 
> This would be ideal, but in that case the compilation fails with `required parameter after the defaultable parameter` since the username, password etc. would be defaultable. Any better solutions for this?
> 
> ```ballerina
> public function init(string url, string? user = (), string? password = (), string? datasourceName = (),
>     string database) returns Error?
> ```

Shall we make `user` and `password` required?. Here we need an admin user right, there should have a user and password in this case.

**Comment by kaneeldias** [comment]
> > > For the client init function parameter, shall we keep the order the same as other SQL clients and make database a required param
> > 
> > 
> > This would be ideal, but in that case the compilation fails with `required parameter after the defaultable parameter` since the username, password etc. would be defaultable. Any better solutions for this?
> > ```ballerina
> > public function init(string url, string? user = (), string? password = (), string? datasourceName = (),
> >     string database) returns Error?
> > ```
> 
> Shall we make `user` and `password` required?. Here we need an admin user right, there should have a user and password in this case.

Updated the proposal with the suggestion

**Comment by daneshk** [comment]
@sameerajayasoma Can you check this proposal for database schema retrieval support for SQL connectors? This support will be helpful for our persist layer to compare the generated schema with the underline database schema and create migration scripts.

**Comment by niveathika** [comment]
@kaneeldias A small suggestions, shall we rename the authorisation error as below?
```
# Represents an error that occurs when the user does not have the required privileges to execute an action.
public type InsufficientPrivilegesError distinct ApplicationError;
```

I feel this would be more descriptive.

**Comment by kaneeldias** [comment]
> @kaneeldias A small suggestions, shall we rename the authorisation error as below?
> 
> ```ballerina
> # Represents an error that occurs when the user does not have the required privileges to execute an action.
> public type InsufficientPrivilegesError distinct ApplicationError;
> ```
> 
> I feel this would be more descriptive.

+1 amended the proposal

**Comment by daneshk** [comment]
Let's do the implementation for the SQL module initially in update 02. Then let's planned to support this in other connectors in future updates

**Comment by kaneeldias** [comment]
Removed `InsufficientPrivilegesError` error type as is it not possible for a user to not have read access to the `INFORMATION_SCHEMA` tables [1].

[1] https://stackoverflow.com/questions/68758308/deny-access-to-information-schema-in-mariadb
