### ISSUE TITLE
Convert time to email string returns value doesn't contain leading zero for date.

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#2971]
**Description:**
Based on the RFC 5322[1] specification, the email string value of the date 03 Jun 2015, can be represented in both ways,

`Fri, 03 Jun 2015 23:39:12 GMT` and `Fri, 3 Jun 2015 23:39:12 GMT`

In the time module, `utcToEmailString` and `civilToEmailString` function returns the string value as `Fri, 3 Jun 2015 23:39:12 GMT`.

We need to find a way of providing both on request as different APIs follow one of these formats.

1. https://datatracker.ietf.org/doc/html/rfc5322#section-3.3

Related issue: https://github.com/ballerina-platform/ballerina-extended-library/issues/401

**Comment by sahanHe** [comment]
+ There is a inconsistency between two APIs as `utcToEmailString` provides the string without leading zero while 'civilToEmailString' provides the string with leading zero. As an example following test pass without an issue.
```ballerina
isolated function test() returns Error? {
    Utc utc = check utcFromString("2007-12-03T10:15:30.00Z");
    Civil civil = check civilFromString("2007-12-03T10:15:30.00+05:30");
    
    test:assertEquals(utcToEmailString(utc, "Z"), "Mon, 3 Dec 2007 10:15:30 Z");
    test:assertEquals(civilToEmailString(civil, PREFER_TIME_ABBREV), "Mon, 03 Dec 2007 10:15:30 +0000 (Z)");
}
```

**Comment by sahanHe** [comment]
Changed both APIs to have same API signature without leading zero in date as [specifications](https://www.rfc-editor.org/rfc/rfc5322) in PR [#422](https://github.com/ballerina-platform/module-ballerina-time/pull/442)
