### ISSUE TITLE
Provide JetStream support instead of STAN

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#2980]
STAN - https://docs.nats.io/legacy/stan
JetStream - https://docs.nats.io/nats-concepts/jetstream

Ballerina needs to do the same. This issue is to track the requirement.

**Comment by shafreenAnfar** [comment]
@indikasampath2000 @HasithaAthukorala since this is a `ballerinax` package, do you all think you can take up this ?

**Comment by aashikam** [comment]
Proposal: https://github.com/ballerina-platform/ballerina-standard-library/issues/3550
