### ISSUE TITLE
[HTTP2] Manual testing the application level errors

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#2989]
**Description:**

#### Idle timeout error
- Idle timeout triggered before initiating inbound request
- Idle timeout triggered while reading inbound request headers
- Idle timeout triggered while reading inbound request entity body
- Idle timeout triggered before initiating outbound response
- Idle timeout triggered while writing outbound response headers
- Idle timeout triggered while writing outbound response entity body
- Idle timeout triggered before initiating 100 continue response
- Idle timeout triggered while writing 100 continue response
- Idle timeout triggered before initiating outbound request
- Idle timeout triggered while writing outbound request headers
- Idle timeout triggered while writing outbound request entity body
- Idle timeout triggered before initiating inbound response
- Idle timeout triggered before initiating push response
- Idle timeout triggered while reading inbound response headers
- Idle timeout triggered while reading inbound response entity body
- Idle timeout triggered while reading push response entity body

#### Client connection closure error scenarios
- Remote client closed the connection before initiating inbound request
- Remote client closed the connection while reading inbound request headers
- Remote client closed the connection while reading inbound request entity body
- Remote client closed the connection before initiating outbound response
- Remote client closed the connection while writing outbound response headers
- Remote client closed the connection while writing outbound response entity body
- Remote client closed the connection before initiating 100 continue response
- Remote client closed the connection while writing 100 continue response

#### Server connection closure error scenarios
- Remote host closed the connection before initiating outbound request
- Remote host closed the connection while writing outbound request headers
- Remote host closed the connection while writing outbound request entity body
- Remote host closed the connection before initiating inbound response
- Remote host closed the connection while reading inbound response headers
- Remote host closed the connection while reading inbound response body
- Remote host closed the connection before reading 100 continue response

**Describe your task(s)**
Slow clients and optimised netty servers can be used to test these cases
Eg : https://github.com/shafreenAnfar/netty-servers

![image](https://user-images.githubusercontent.com/8381003/174227793-e31afedd-d0c5-4288-bd59-ae48a71f3933.png)

- ### Client
   - connect
      - [x] SSL handshake alerts
         - [x] Connection closed error while SSL handshake
         - [x] Unknown Host error for HTTPS endpoint
         - [x] Connection time out error for HTTPS endpoint
         - [x] Connection refused error for HTTPS endpoint
         - [x] Cipher suite alerts 
         - [x] TLS protocol alerts 
         - [x] SNI alerts 
         - [x] Mutual SSL alerts 
      - [x] Connection timeout error 
      - [x] Connection refused error
   - write 
      - Headers
         - I/O errors  
            - [ ] Send Socket buffer filled scenario 
            - Connection closed error 
               - [ ] Before writing headers 
               - [x] While/After writing headers 
         - Application Errors 
            - [ ] Response comes back before writing entity body request
      - Body
         - I/O errors 
            - [ ] Send Socket buffer filled scenario
            - Connection closed error  
               - [x] While writing body 
               - [x] After writing body 
         - Application Errors
            - [ ] Connection timeout while writing entity body
            - [ ] Connection timeout after writing entity body
   - read
      - Headers
         - I/O errors  
            - Connection closed error  
               - [ ] While reading headers 
               - [x] After reading headers 
         - Application Errors 
            - [x] Connection timeout before reading the headers
            - [x] Connection timeout after reading the headers
      - Body
         - I/O errors  
            - Connection closed error  
               - [x] While reading body 
               - [ ] After reading body 
         - Application Errors 
            - [x] Connection timeout while reading the body 
            - [ ] Response comes back but closing header of chunk comes a bit later
- ### Listener
   - accept
      - I/O errors 
         - [ ] SSL handshake alerts
            - [ ] Connection closed error while SSL handshake
            - [ ] Unknown Host error for HTTPS endpoint
            - [ ] Connection time out error for HTTPS endpoint
            - [x] Connection refused error for HTTPS endpoint
           - [x] Cipher suite alerts 
           - [x] TLS protocol alerts 
           - [ ] SNI alerts 
           - [ ] Mutual SSL alerts 
   - read 
      - Headers
         - IO Errors
            - Connection closed error 
               - [x] While reading headers 
               - [x] After reading headers
         - Application Errors
            - [x] Connection timeout while reading headers
            - [ ] Client sends the request with invalid headers
      - Body
         - IO Errors
            - Connection closed error 
               - [x] While reading body
               - [ ] After reading body
         - Application Errors
            - [x] Connection timeout while reading entity body
   - write
      - Header
         - IO Errors
            - Connection closed error 
               - [x] While writing headers
               - [x] After writing headers
         - Application Errors
            - [x] Connection timeout before writing headers
      - Body
         - IO Errors
            - Connection closed error 
               - [x] While writing body
               - [ ] After writing body
         - Application Errors
            - [x] Connection timeout while writing entity body

**Comment by TharmiganK** [comment]
Tested above scenarios and gathered respective error log in this [doc](https://docs.google.com/spreadsheets/d/1IK3fbVchDSS88CRu6lYCBGTp-wxIZU7tdyjYk9Psupg/edit?usp=sharing)
