### ISSUE TITLE
Proposal: Support Data Mapping in CSV read/write operations 

### ISSUE THREAD

**Issue by sahanHe** [ballerina-platform/ballerina-standard-library#3004]
## Summary

Current CSV read/write APIs supports reading and writing as string[][] values. In this proposal we propose to add data mapping to return an array of particular record defined by the user.

## Goals

* Add data mapping feature to CSV READ/Write operations to return an array of particular record defined by the user.

* Change ```fileReadCsv, fileWriteCsv, fileReadCsvAsStream, fileWriteCsvFromStream``` to support data mapping.

* Carry out data mapping by inferring the return type automatically as a dependently-typed function.

## Motivation

Until now, user doesn't have a direct data mapping method to get an array of user defined records from CSVs.  

## Description

```fileReadCsv(), fileWriteCsv(), fileReadCsvAsStream(), fileWriteCsvFromStream()```  APIs are modified to support data mapping in CSV read/write operations. 
* The ```fileReadCsv()``` API currently returns String[][] and it will be modified to return either String[][] or record[] depending on the return type. 
* The ```fileWriteCsv()``` API currently accepts String[][] inputs and it will be modified to accept both String[][] and record[].

* The ```fileReadCsvAsStream()``` currently returns ```stream<string[], Error?>|Error``` and it will be modified to return ```stream<string[]|record{}, Error?>|Error```.  
* The ```fileWriteCsvFromStream()``` currently accepts ```stream<string[], Error?>```  as the input and it will be modified to accept ```stream<string[]|record{}, Error?>```.

modified APIs
```ballerina
# Read file content as a CSV.
# + path - The CSV file path
# + skipHeaders - Number of headers, which should be skipped prior to reading records
# + returnType - The type of the return value (string[] or map<anydata>)
# + return - The entire CSV content in the channel as an array of string arrays, an array of records or an `io:Error`

public isolated function fileReadCsv(string path, int skipHeaders = 0, typedesc<record{}|string[]> returnType = <>) returns returnType[]|Error = @java:Method ;
```

``` ballerina
# Write CSV content to a file.
# + path - The CSV file path
# + content - CSV content as an array of string arrays or an array of records
# + option - To indicate whether to overwrite or append the given content
# + return - `()` when the writing was successful or an `io:Error`
public isolated function fileWriteCsv(string path, string[][]|map<anydata>[] content, FileWriteOption option = OVERWRITE) returns Error? ;
```

```ballerina
# Read file content as a CSV.
# + path - The CSV file path
# + returnType - The type of the return value (string[] or map<anydata>)
# + return - The entire CSV content in the channel a stream of string arrays, an stream of records or an `io:Error`
public isolated function fileReadCsvAsStream(string path, typedesc<string[]|record{}>  returnType = <>) returns  stream<returnType, Error?>|Error  = @java:Method ;
```

```ballerina
# Write CSV record stream to a file.
# + path - The CSV file path
# + content - A CSV record stream to be written
# + option - To indicate whether to overwrite or append the given content
# + return - `()` when the writing was successful or an `io:Error`
public isolated function fileWriteCsvFromStream(string path, stream<string[]|map<anydata>, Error?> content, FileWriteOption option = OVERWRITE) returns Error? ;
```

Example of a data mapping in to array of records.

CSV file
```
id, name, salary
User1, WSO2, 10000.50
User2, WSO2, 20000.50
User3, WSO2, 30000.00
```

Code

```ballerina
type Employee record {
    string id;
    string name;
    float salary;
};


@test:Config {}
isolated function testCsvContent() returns error? {
    float expectedValue = 60001.00;
    float total = 0;

    Employee[] result = check fileReadCSV(filePath);
    foreach Employee x in result {
        total = total + x.salary;
    }
    test:assertEquals(total, expectedValue);
    check fileWriteCsv(filePath, result);
}


@test:Config {}
isolated function testCsvStreamContent() returns error? {
    float expectedValue = 60001.00;
    float total = 0;
    stream<Employee, io:Error?> csvStream = check io:fileReadCsvAsStream(filePath);
    check csvStream.forEach(function(Employee x) {
                              total = total + x.salary;
                          });
    test:assertEquals(total, expectedValue);
    check fileWriteCsvFromStream(filePath, csvStream);
}
```

## Risks and Assumptions

1. Headers of the record is provided in the first row of CSV, and they are equal to the headers in record type, otherwise data gets mapped in the order of fields in the record..
2. Number of fields in defined record and the number of headers in the CSV file are equal.

**Comment by daneshk** [comment]
In the description, mention what the new API definition looks like and how it is improved from the existing API. Mention all the APIs that are going to change with this improvement.

in the example, we don't need the below lines.
```
check csvChannel
check csvChannel.close();
```

**Comment by sahanHe** [comment]
> In the description, mention what the new API definition looks like and how it is improved from the existing API. Mention all the APIs that are going to change with this improvement.
> 
> in the example, we don't need the below lines.
> 
> ```
> check csvChannel
> check csvChannel.close();
> ```

made the necessary changes.

**Comment by daneshk** [comment]
Shall we mention all four APIs[1] that are going to change in the description?

1. https://github.com/ballerina-platform/module-ballerina-io/blob/master/ballerina/file_csv_io.bal

**Comment by MadhukaHarith92** [comment]
@sahanHe method body is not needed for proposals. The method signature followed by a semicolon is enough. eg:
```ballerina
public isolated function fileReadCsv(string path, int skipHeaders = 0, ReturnType returnType = <>) returns returnType = @java:Method;
```

Also, better if you can add the doc comments.

**Comment by daneshk** [comment]
@sameerajayasoma Can you please check and share your thoughts on this data binding support
