### ISSUE TITLE
Add sufficient HTTP2 ballerina tests

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#3024]
**Description:**
$subject

Related to #454 

**Describe your task(s)**
- [x] Initially identify the failing test cases when listener version is 2.0
- [x] Fix failing cases and add HTTP2 tests

**Comment by ayeshLK** [comment]
Following test cases were disabled due to missing features:
- testHttp25XXHandleError
- testHttp2InvalidUrlLength
- testHttp2InvalidPayloadSize
- testHttp2HateoasLinks1
- testHttp2HateoasLinks2
- testHttp2HateoasLinksInBody
