### ISSUE TITLE
Invalid local address is generated from the `http:Caller`

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-standard-library#3030]
**Description:**

Here, I'm trying to get the local address of a `http:Caller`
```ballerina
string graphqlURL = string `http://${caller.localAddress.host}:${caller.localAddress.port}/`;
io:println("url: ", graphqlURL);
```
But it returns the following invalid address.
```
url: http://0:0:0:0:0:0:0:1:9000/
```

- OS Version : Windows 10 Pro

**Comment by chamil321** [comment]
@Nuvindu It looks like the literal IPv6 address. What is the response when the address is enclosed with brackets?
```
http://[0:0:0:0:0:0:0:1]:9000/
```

**Comment by Nuvindu** [comment]
The address link with brackets is identical to the  `http://localhost:9000/`. 
A curl request without brackets returns an error. `(3) URL using bad/illegal format or missing URL`

**Comment by Nuvindu** [comment]
Tried the code with a Ubuntu 20.04.4 LTS version. It produces a different local address as `http://ip6-localhost:9000/graphiql`. Therefore manually adding brackets will not solve the issue in this case. @chamil321 is there a better way to fix this?

**Comment by chamil321** [comment]
From the PR https://github.com/ballerina-platform/module-ballerina-http/pull/1126, the IP is provided to be used instead of the host name. Hence closing the issue
