### ISSUE TITLE
Http client fails to handle load and throws GenericClientError

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-standard-library#3042]
**Description:**
When sending a high load of requests to external endpoints, the HTTP client fails to handle this load and throws the below error. For this particular scenario reproduced with this code, it is only reproduced once, but in a multi-container environment, the number of errors is high.

`{ballerina/http}GenericClientError message=Remote host closed the connection before initiating inbound response`

**Steps to reproduce:**
A sample client similar to [mytest.txt](https://github.com/ballerina-platform/ballerina-standard-library/files/9002543/mytest.txt) can be used to reproduce.

**Affected Versions:**

Ballerina SwanLake 2201.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
A retry can be used as a temporary workaround.
But we need to identify possible reasons for this error and ways to fix it.

**Comment by shafreenAnfar** [comment]
This is most probably because of the load and the pod limits. Please try with GraalVM, it might give better performance. Closing this issue as this not the 80% case. 

Do feel free to re-open the issue if you come across the same problem with the latest version.
