### ISSUE TITLE
Intermittent HTTP test failure

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#305]
**Description:**
<s>

```
	[fail] testBasicHttp2CircuitBreaker:
	    Found unexpected output type: Idle timeout triggered before initiating inbound response
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertFail(assert.bal:126)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.resiliency.00-commons:invokeApiAndVerifyResponse(tests/integration-tests/service/resiliency/00-commons.bal:48)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.resiliency.16-http2-circuit-breaker-test:testBasicHttp2CircuitBreaker(tests/integration-tests/service/resiliency/16-http2-circuit-breaker-test.bal:115)

```
</s>

**Comment by chamil321** [comment]
Disable http-ballerina-tests/tests/resiliency_http_circuit_breaker_test_3.bal:109 test case due to intermittent failure

**Comment by chamil321** [comment]
```ballerina
	[fail] testHTTP2303Status:
	    Found unexpected output type: Idle timeout triggered before initiating inbound response
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
	    	ballerina.test.0_0_0:assertFail(assert.bal:127)
	    	ballerina.http_tests.1_0_2.tests.http2_redirect:testHTTP2303Status(tests/http2_redirect.bal:410)

```

**Comment by chamil321** [comment]
[fail] testWithStrongClientWithWeakService:
	    Assertion Failed!
	    	
	    	expected: 'SSL connection failed:Received fatal alert: handshake_failure localhost/127.0.0....'
	    	actual	: 'SSL connection failed:Received fatal alert: handshake_failure null'
	    	
	    	Diff	:
	    	
	    	--- expected
	    	+++ actual
	    	
	    	@@ -1,2 +1,1 @@
	    	
	    	-SSL connection failed:Received fatal alert: handshake_failure localhost/127.0.0.
	    	-1:9227
	    	+SSL connection failed:Received fatal alert: handshake_failure null
	    	
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:76)
	    	ballerina.http_tests.1_0_2.tests.ssl_cipher_strength_test:testWithStrongClientWithWeakService(tests/ssl_cipher_strength_test.bal:104)

**Comment by chamil321** [comment]
Windows failure

	[fail] testTypicalBackendTimeout:
	    Found unexpected output
	    	
	    	expected: '500'
	    	actual	: '200'
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:76)
	    	ballerina.http_tests.1_0_2.tests.resiliency_commons:invokeApiAndVerifyResponse(tests/resiliency_commons.bal:44)
	    	ballerina.http_tests.1_0_2.tests.resiliency_http_circuit_breaker_test_1:testTypicalBackendTimeout(tests/resiliency_http_circuit_breaker_test_1.bal:105)

**Comment by chamil321** [comment]
[fail] testHTTP2303Status:
	    Found unexpected output type: Idle timeout triggered before initiating inbound response
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
	    	ballerina.test.0_0_0:assertFail(assert.bal:127)
	    	ballerina.http_tests.1_0_2.tests.http2_redirect:testHTTP2303Status(tests/http2_redirect.bal:410)

**Comment by chamil321** [comment]
```
[fail] testDirtyResponse:

		    Assertion Failed!
		    	
		    	expected: 'Couldn't complete the respond operation as the response has been already used.'
		    	actual	: ''
		    	
		    	Diff	:
		    	
		    	--- expected
		    	+++ actual
		    	
		    	@@ -1,1 +1,1 @@
		    	
		    	-Couldn't complete the respond operation as the response has been already used.
		    	+
		    	

		    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
		    	ballerina.http_tests.1_1_0-alpha8.tests.http_dirty_response_test:testDirtyResponse(tests/http_dirty_response_test.bal:58)
```

**Comment by chamil321** [comment]
```
		[fail] testHttp2RetryWithServerPush:

		    Found unexpected output type: Idle timeout triggered before initiating inbound response

		    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_0_0:assertFail(assert.bal:125)
		    	ballerina.http_tests.1_1_0-beta_1.tests.http2_retry_test:testHttp2RetryWithServerPush(tests/http2_retry_test.bal:237)

```

**Comment by chamil321** [comment]
```
		[fail] testHttp2SimpleRetry:

		    Found unexpected output type: Idle timeout triggered before initiating inbound response

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertFail(assert.bal:125)
		    	ballerina.http_tests.1_1_0-beta_1.tests.http2_retry_test:testHttp2SimpleRetry(tests/http2_retry_test.bal:221)
		    	```

**Comment by chamil321** [comment]
```
		[fail] testBasicHttp2Failover:

		    Found unexpected output type: Idle timeout triggered before initiating inbound response

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertFail(assert.bal:236)
		    	ballerina.http_tests.1_1_0-beta_2.tests.resiliency_http2_failover_test:testBasicHttp2Failover(tests/resiliency_http2_failover_test.bal:131)
```

**Comment by TharmiganK** [comment]
```
               [fail] testCircuitBreakerWithoutStatusCodes2#1:

		    Found unexpected output

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertTrue(assert.bal:64)
		    	ballerina.http_tests.1_1_0-beta_2.tests.test_commons:assertTrueTextPayload(tests/test_commons.bal:103)
		    	ballerina.http_tests.1_1_0-beta_2.tests.resiliency_commons:invokeApiAndVerifyResponseWithHttpGet(tests/resiliency_commons.bal:64)
		    	ballerina.http_tests.1_1_0-beta_2.tests.resiliency_http_circuit_breaker_without_status_codes_test:testCircuitBreakerWithoutStatusCodes2(tests/resiliency_http_circuit_breaker_without_status_codes_test.bal:82)

**Comment by chamil321** [comment]
```
[fail] testInvokingStoppedService:

		    Found unexpected output
		    	
		    	expected: 'Something wrong with the connection'
		    	actual	: 'Connection between client and remote host is closed'
		    	
		    	Diff	:
		    	
		    	--- actual
		    	+++ expected
		    	
		    	@@ -1,1 +1,1 @@
		    	
		    	-Connection between client and remote host is closed
		    	+Something wrong with the connection
		    	

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertEquals(assert.bal:112)
		    	ballerina.http_tests.1_1_0-beta_3.tests.http_listener_method_service_test:testInvokingStoppedService(tests/http_listener_method_service_test.bal:116)
		    	```

**Comment by chamil321** [comment]
> ```
> [fail] testInvokingStoppedService:
> 
> 		    Found unexpected output
> 		    	
> 		    	expected: 'Something wrong with the connection'
> 		    	actual	: 'Connection between client and remote host is closed'
> 		    	
> 		    	Diff	:
> 		    	
> 		    	--- actual
> 		    	+++ expected
> 		    	
> 		    	@@ -1,1 +1,1 @@
> 		    	
> 		    	-Connection between client and remote host is closed
> 		    	+Something wrong with the connection
> 		    	
> 
> 		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
> 		    	ballerina.test.0_8_0:assertEquals(assert.bal:112)
> 		    	ballerina.http_tests.1_1_0-beta_3.tests.http_listener_method_service_test:testInvokingStoppedService(tests/http_listener_method_service_test.bal:116)
> 		    	```
> ```

Fixed via ballerina-platform/module-ballerina-http#532

**Comment by chamil321** [comment]
```
		[fail] testClientUpgradewithLargePayload:

		    Found unexpected output: Duplicate handler name: idleStateHandler

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertFail(assert.bal:236)
		    	ballerina.http_tests.1_1_0-beta_3.tests.http2_client_upgrade_with_large_payload_test:testClientUpgradewithLargePayload(tests/http2_client_upgrade_with_large_payload_test.bal:193)
```

**Comment by chamil321** [comment]
```
		[fail] testHttp2SimpleRetry:

		    Found unexpected output type: Idle timeout triggered before initiating inbound response

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertFail(assert.bal:236)
		    	ballerina.http_tests.1_1_0-beta_3.tests.http2_retry_test:testHttp2SimpleRetry(tests/http2_retry_test.bal:221)
```

**Comment by TharmiganK** [comment]
>                [fail] testCircuitBreakerWithoutStatusCodes2#1:
> 
> 		    Found unexpected output
> 
> 		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
> 		    	ballerina.test.0_8_0:assertTrue(assert.bal:64)
> 		    	ballerina.http_tests.1_1_0-beta_2.tests.test_commons:assertTrueTextPayload(tests/test_commons.bal:103)
> 		    	ballerina.http_tests.1_1_0-beta_2.tests.resiliency_commons:invokeApiAndVerifyResponseWithHttpGet(tests/resiliency_commons.bal:64)
> 		    	ballerina.http_tests.1_1_0-beta_2.tests.resiliency_http_circuit_breaker_without_status_codes_test:testCircuitBreakerWithoutStatusCodes2(tests/resiliency_http_circuit_breaker_without_status_codes_test.bal:82)

**Possible reason for the intermittent failure :** 
The expected behaviour is, the circuit should switch to `OPEN` state after first request due to an error and then should give an `upstream unavailable` error for the second request. But intermittently when the timeout is reached the state is switched to `HALF-OPEN` and return the error from backend service.

Fixed via [ballerina-platform/module-ballerina-http/pull/641](https://github.com/ballerina-platform/module-ballerina-http/pull/641)

**Comment by TharmiganK** [comment]
> Windows test failure
> 
> [fail] testWithStrongClientWithWeakService:
> Assertion Failed!
> 
> ```
>     	expected: 'SSL connection failed:Received fatal alert: handshake_failure localhost/127.0.0....'
>     	actual	: 'SSL connection failed:Received fatal alert: handshake_failure null'
>     	
>     	Diff	:
>     	
>     	--- expected
>     	+++ actual
>     	
>     	@@ -1,2 +1,1 @@
>     	
>     	-SSL connection failed:Received fatal alert: handshake_failure localhost/127.0.0.
>     	-1:9227
>     	+SSL connection failed:Received fatal alert: handshake_failure null
>     	
>     	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
>     	ballerina.test.0_0_0:assertEquals(assert.bal:76)
>     	ballerina.http_tests.1_0_2.tests.ssl_cipher_strength_test:testWithStrongClientWithWeakService(tests/ssl_cipher_strength_test.bal:104)
> ```

**Possible reason for the intermittent failure :** 

The test can fail intermittently due to the issue [`SSL test failure after jdk 11 migration`](https://github.com/ballerina-platform/ballerina-standard-library/issues/315) : remote address may be set to `null` before creating the error.

Fixed via [ballerina-platform/module-ballerina-http/pull/622](https://github.com/ballerina-platform/module-ballerina-http/pull/622)

Also checked the behaviour multiple times in windows and linux - No intermittent failures occurred.

**Comment by TharmiganK** [comment]
> Disabled `http-ballerina-tests/tests/resiliency_http_circuit_breaker_test_3.bal:109` test case due to intermittent failure

This is an intermittent test failure when calling `forceClose()` function. 

**Possible reason for the intermittent failure :**

`forceClose()` is called before the circuit breaks (or switched to OPEN stage). So the circuit switched to OPEN stage after calling `forceClose()` and the test was passing intermittently since the circuit switched to HALF-OPEN or the next request made after reset time (which was set to 1s)

Fixed via [ballerina-platform/module-ballerina-http/pull/643](https://github.com/ballerina-platform/module-ballerina-http/pull/643)

**Comment by TharmiganK** [comment]
> 		[fail] testClientUpgradewithLargePayload:
> 
> 		    Found unexpected output: Duplicate handler name: idleStateHandler
> 
> 		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
> 		    	ballerina.test.0_8_0:assertFail(assert.bal:236)
> 		    	ballerina.http_tests.1_1_0-beta_3.tests.http2_client_upgrade_with_large_payload_test:testClientUpgradewithLargePayload(tests/http2_client_upgrade_with_large_payload_test.bal:193)

Similarly,

```
[fail] testSmallPayloadForNonChunkedResponse:

   Found unexpected output type: Duplicate handler name: idleStateHandler

     at ballerina.test.0:createBallerinaError(assert.bal:43)
     ballerina.test.0:assertFail(assert.bal:236)
     ballerina.http_tests.2.tests.http_trailing_header_test:testSmallPayloadForNonChunkedResponse(tests/http_trailing_header_test.bal:173)
```

**Comment by ayeshLK** [comment]
It was observed that one `websub` test case failed intermittently due to an issue in HTTP Client.
```
		[fail] testOnIntentVerificationSuccessDefaultImpl:

		    Duplicate handler name: idleStateHandler

		    	at ballerina.http.2:externExecuteClientAction(http_client.bal:224)
		    	ballerina.http.2.HttpClient:get(http_client.bal:96)
		    	ballerina.http.2:sendNewRequest(caching_http_caching_client.bal:362)
		    	ballerina.http.2:getCachedResponse(caching_http_caching_client.bal:320)
		    	ballerina.http.2.HttpCachingClient:get(caching_http_caching_client.bal:162)
		    	ballerina.http.2.Client:processGet(http_client_endpoint.bal:194)
```

**Comment by TharmiganK** [comment]
> Windows failure
> 
> ```
> [fail] testTypicalBackendTimeout:
>     Found unexpected output
>     	
>     	expected: '500'
>     	actual	: '200'
>     	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
>     	ballerina.test.0_0_0:assertEquals(assert.bal:76)
>     	ballerina.http_tests.1_0_2.tests.resiliency_commons:invokeApiAndVerifyResponse(tests/resiliency_commons.bal:44)
>     	ballerina.http_tests.1_0_2.tests.resiliency_http_circuit_breaker_test_1:testTypicalBackendTimeout(tests/resiliency_http_circuit_breaker_test_1.bal:105)
> ```

Fixed via [ballerina-platform/module-ballerina-http/pull/661/files](https://github.com/ballerina-platform/module-ballerina-http/pull/661/files)

**Comment by TharmiganK** [comment]
> [fail] testDirtyResponse:
> 
> 		    Assertion Failed!
> 		    	
> 		    	expected: 'Couldn't complete the respond operation as the response has been already used.'
> 		    	actual	: ''
> 		    	
> 		    	Diff	:
> 		    	
> 		    	--- expected
> 		    	+++ actual
> 		    	
> 		    	@@ -1,1 +1,1 @@
> 		    	
> 		    	-Couldn't complete the respond operation as the response has been already used.
> 		    	+
> 		    	
> 
> 		    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
> 		    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
> 		    	ballerina.http_tests.1_1_0-alpha8.tests.http_dirty_response_test:testDirtyResponse(tests/http_dirty_response_test.bal:58)

Fixed via [ballerina-platform/module-ballerina-http/pull/663/files](https://github.com/ballerina-platform/module-ballerina-http/pull/663/files)

**Comment by TharmiganK** [comment]
> ```
> 	[fail] testHTTP2303Status:
> 	    Found unexpected output type: Idle timeout triggered before initiating inbound response
> 	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
> 	    	ballerina.test.0_0_0:assertFail(assert.bal:127)
> 	    	ballerina.http_tests.1_0_2.tests.http2_redirect:testHTTP2303Status(tests/http2_redirect.bal:410)
> ```


> 		[fail] testHttp2RetryWithServerPush:
> 
> 		    Found unexpected output type: Idle timeout triggered before initiating inbound response
> 
> 		    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:43)
> 		    	ballerina.test.0_0_0:assertFail(assert.bal:125)
> 		    	ballerina.http_tests.1_1_0-beta_1.tests.http2_retry_test:testHttp2RetryWithServerPush(tests/http2_retry_test.bal:237)



> **Description:**
> 
> ```
> 	[fail] testBasicHttp2CircuitBreaker:
> 	    Found unexpected output type: Idle timeout triggered before initiating inbound response
> 	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
> 	    	ballerina.test.0_0_0:assertFail(assert.bal:126)
> 	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.resiliency.00-commons:invokeApiAndVerifyResponse(tests/integration-tests/service/resiliency/00-commons.bal:48)
> 	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.resiliency.16-http2-circuit-breaker-test:testBasicHttp2CircuitBreaker(tests/integration-tests/service/resiliency/16-http2-circuit-breaker-test.bal:115)
> ```

Fixed via [ballerina-platform/module-ballerina-http/pull/666](https://github.com/ballerina-platform/module-ballerina-http/pull/666)

**Comment by chamil321** [comment]
Closing as all the issues has been addressed
