### ISSUE TITLE
Write how to article for parsing date/time from string

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3071]
**Description:**
Currently we only support for two string formats. others we need to parse manually using string manipulation. We need to have a. guide which explain the steps to do.

**Comment by daneshk** [comment]
Like https://stackoverflow.com/collectives/wso2/articles/72564747/building-ballerina-from-sources

**Comment by MadhukaHarith92** [comment]
Closing since the task is completed.
