### ISSUE TITLE
Support for allowing tuple type in the resource return type

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-standard-library#3091]
**Description:**
The current resource doesn't allow to have tuple as a return type. but there can be scenarios we have to return a tuple as output.
```ballerina
public type ReturnTypes readonly & [int, decimal];

service / on new http:Listener(9090) {
    resource function post . (@http:Payload Pet payload) returns ReturnTypes {
        return [20, 28.0];
    }
}
```
Version : Ballerina 2201.1.0 (Swan Lake)

**Comment by TharmiganK** [comment]
Implementation vice we have the support from `2.4.x`. But these types are not allowed by the compiler plugin.

**Comment by TharmiganK** [comment]
Closing this issue since this is fixed with the compiler plugin rewrite
