### ISSUE TITLE
XSLT version supported by XSLT module is undocumented

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-standard-library#3092]
**Description:**
Documentation of XSLT module doesn't tell the supported XSLT version. Please update the documentation to tell the supported version.

https://lib.ballerina.io/ballerina/xslt/2.2.1

**Comment by daneshk** [comment]
@sahanHe Let's check on this.

**Comment by sahanHe** [comment]
@janihur Currently Ballerina XSLT library supports XSL Transformations (XSLT) Version 1.0
