### ISSUE TITLE
Fails with SSL error during handshake between secure http listener in SwanLake and secure http client in 1.2.x version

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-standard-library#3095]
**Description:**
$title

**Steps to reproduce:**
Write a secure http listener in ballerina version `2022.0.2`
Write a secure http client for the above listener in `1.2.x`
It fails with `SslError message=SSL connection failed`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Bhashinee** [comment]
Tried with `Ballerina 2201.3.0 (Swan Lake Update 3)` listener and `Ballerina 1.2.35` versions. This was not reproducible. Tried code samples are as below,

Service(Running on Ballerina 2201.3.0 (Swan Lake Update 3))

```
import ballerina/http;

type Album readonly & record {|
    string title;
    string artist;
|};

listener http:Listener securedEP = new (9090,
    secureSocket = {
        key: {
            path: "path/to/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }
);

service / on securedEP {

    resource function get albums() returns Album[] {
        return [
            {title: "Blue Train", artist: "John Coltrane"},
            {title: "Jeru", artist: "Gerry Mulligan"}
        ];
    }
}
```

Client running on `Ballerina 1.2.35`

```
import ballerina/http;
import ballerina/log;

http:ClientConfiguration clientEPConfig = {
    secureSocket: {
        trustStore: {
            path: "path/to/ballerinaTruststore.p12",
            password: "ballerina"
        }
    }
};

public function main() {
    http:Client clientEP = new("https://localhost:9090", clientEPConfig);

    var resp = clientEP->get("/albums/");
    if (resp is http:Response) {

        var payload = resp.getTextPayload();
        if (payload is string) {

            log:printInfo(payload);
        } else {

            log:printError(<string>payload.detail()["message"]);
        }
    } else {

        log:printError(<string>resp.detail()["message"]);
    }
}
```
Apart from the keystores, tried with certs and keys too.

**Comment by Bhashinee** [comment]
Closing the issue as per the above comment. If this is still occurring please reopen the issue with code samples.
