### ISSUE TITLE
Context is Initialized per Service in GraphQL Subscriptions

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#3115]
**Description:**
In GraphQL subscriptions, the `Context` object is initialized when the `WsService` object is initialized. This is wrong. The context should be created per request.

**Comment by DimuthuMadushan** [comment]
This currently blocked due to [ballerina-standard-library/#3145](https://github.com/ballerina-platform/ballerina-standard-library/issues/3145)

**Comment by DimuthuMadushan** [comment]
Continue with dummy `http:RequestContext` until the [ballerina-standard-library/#3145](https://github.com/ballerina-platform/ballerina-standard-library/issues/3145) get resolved.
