### ISSUE TITLE
Perf test - HTTP1.1 Vs HTTP2

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#3122]
**Description:**
$subject (before update 2 release)

Related Docs: 
https://docs.google.com/spreadsheets/d/1mB1eYwu4s219_p3XjBmhEBAqtg7-UVsBGhTJ9Y8t_80/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1KfMXPbXbWIGbRNY4gtljRRIRqabhdUs8DHRLVaCM52k/edit#gid=0

Sample back-end and payload:
- [ldclakmal/ballerina-http-test-suite](https://github.com/ldclakmal/ballerina-http-test-suite)

Performance Test Environment:
- Concurrency: 100
- Duration: 30 min
- Memory: 350MB

**Comment by ayeshLK** [comment]
### HTTP Pass-through Tests
#### Sample Code
```ballerina
// `httpListener` can be HTTP 1.1/HTTP 2.0 (with/without SSL)
service /passthrough on httpListener {
    resource function post .(http:Caller caller, http:Request clientRequest) returns error? {
        // `backendClient` can be HTTP 1.1/HTTP 2.0 client (with/without SSL)
        http:Response response = check backendClient->forward("/service/EchoService", clientRequest);
        return caller->respond(response);
    }
}
```

#### Results

**Comment by shafreenAnfar** [comment]
The above doesn't have number of users.

**Comment by chamil321** [comment]
Please find the load test comparison did before/after HTTP2 target channel improvement
https://github.com/ballerina-platform/ballerina-standard-library/issues/494#issuecomment-1196453207

**Comment by ayeshLK** [comment]
Did a retest on `h1c-h1c` passthrough. Please find the result below (same limitations applied as above tests):

|Label      |# Samples|Average|Median|90% Line|95% Line|99% Line|Min|Max|Error %|Throughput|Received KB/sec|Std. Dev.|# Users|
|-----------|---------|-------|------|--------|--------|--------|---|---|-------|----------|---------------|---------|------|
|H1C-H1C|17529130 |10     |9     |17      |20      |26      |0  |315|0.00%  |9738.4    |1711.8         |5.19     |100|

**Comment by ayeshLK** [comment]
Did a re-test on `h1c-h1c` passthrough with SL Update 2 RC1 pack. Following is the results:
|Label      |# Samples|Average|Median|90% Line|95% Line|99% Line|Min|Max|Error %|Throughput|Received KB/sec|Std. Dev.|# Users|
|-----------|---------|-------|------|--------|--------|--------|---|---|-------|----------|---------------|---------|--|
|50B Payload|17758921 |9      |9     |17      |19      |26      |0  |325|0.00%  |9866.2    |1734.3         |5.08     |100|

**Comment by ayeshLK** [comment]
Did a re-test on `h2-h2` passthrough to validate the underlying tcp-connections. It seems like the HTTP client is using one channel to send the requests.
![tcp-con-1](https://user-images.githubusercontent.com/77491511/182191065-5579f9b4-f52b-44e7-9cfc-63ada5ff5ac2.png)

@chamil321 / @shafreenAnfar any thoughts ?

**Comment by ayeshLK** [comment]
Did a re-test for `h1c-h1c` and `h2c-h2c` with following configurations:
- Memory : 350MB
- Concurrency : 100
- Payload : 1KB
- Duration : 30 min

|Label     |# Samples|Average|Median|90% Line|95% Line|99% Line|Min|Max|Error %|Throughput|Received KB/sec|Std. Dev.|# Users|
|----------|---------|-------|------|--------|--------|--------|---|---|-------|----------|---------------|---------|-------|
|H1C-H1C   |15804058 |11     |10    |19      |22      |31      |0  |312|0.00%  |8780.1    |9997.7         |6.04     |100    |
|H2C-H2C   |7083843  |24     |23    |37      |43      |61      |1  |1801|0.00%  |3935.2    |4673.1         |19.52    |100   |

**Comment by ayeshLK** [comment]
Did a re-test on `h2c-h2c` and verified that there were 100 tcp-connections created from the perf-test client to the passthrough service.

 Also did a periodical JFR recordings throughout the perf-test duration. JFR recordings could be found [here](https://drive.google.com/file/d/1GT6OtUrMh1E8PyCPJi_PeA-4KaJNlVCA/view?usp=sharing).

**Comment by ayeshLK** [comment]
Did a re-test on `h2c-h2c` after removing the log entry. Following are the results:

|Label     |# Samples|Average|Median|90% Line|95% Line|99% Line|Min|Max|Error %|Throughput|Received KB/sec|Std. Dev.|# Users|
|----------|---------|-------|------|--------|--------|--------|---|---|-------|----------|---------------|---------|---------|
|H2C-H2C|9083313  |19     |18    |31      |35      |49      |0  |445|0.00%  |5046.5    |5992.7         |9.39     |100|

**Comment by ayeshLK** [comment]
JFR for `h2c-h2c` after removing the log entry could be found [here](https://drive.google.com/file/d/13oOx5_B3AEjtv7POZhJSsAyFXbd1b3xK/view?usp=sharing).

**Comment by ayeshLK** [comment]
Did re-test for `h1c-h1c` and `h2c-h2c` with [h2load](https://nghttp2.org/documentation/h2load-howto.html) bench-marking tool. Following is the results:

### H1C-H1C

Configurations:
- Payload - 50B
- Concurrency - 10
- Number of pipe-lining requests - 10
- Memory Limit - 350MB

Command:
```sh
h2load http://localhost:9090/passthrough -d 50B.json --header 'Content-Type: application/json' -n100000 -c10 -m10
```

Results:
```sh
starting benchmark...
spawning thread #0: 10 total client(s). 100000 total requests
Application protocol: http/1.1
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done

finished in 6.29s, 14317.36 req/s, 2.43MB/s
requests: 100000 total, 90001 started, 90000 done, 90000 succeeded, 10000 failed, 10000 errored, 0 timeout
status codes: 90000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 15.28MB (16020000) total, 7.98MB (8370000) headers (space savings 0.00%), 4.29MB (4500000) data
                     min         max         mean         sd        +/- sd
time for request:      268us     25.42ms       625us       347us    94.10%
time for connect:       67us       532us       282us       142us    60.00%
time to 1st byte:     1.80ms      2.49ms      2.19ms       229us    66.67%
req/s           :       0.00     1606.03     1438.04      505.29    90.00%
```

### H2C-H2C

Configurations:
- Payload - 50B
- Concurrency - 10
- Number of concurrent streams - 10
- Memory Limit - 350MB


Command:
```sh
h2load http://localhost:9090/passthrough -d 50B.json --header 'Content-Type: application/json' -n100000 -c10 -m10
```

Results:
```sh
starting benchmark...
spawning thread #0: 10 total client(s). 100000 total requests
Application protocol: h2c
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 12.29s, 8137.07 req/s, 564.69KB/s
requests: 100000 total, 100000 started, 100000 done, 100000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 100000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 6.78MB (7106289) total, 296.97KB (304099) headers (space savings 94.85%), 4.77MB (5000000) data
                     min         max         mean         sd        +/- sd
time for request:      307us    656.37ms     12.00ms     22.27ms    96.31%
time for connect:      263us      1.46ms       801us       379us    60.00%
time to 1st byte:   516.62ms    568.40ms    528.96ms     16.25ms    90.00%
req/s           :     813.78      841.84      832.05        9.23    70.00%
```

** Note: When we run the same test again on the H2C-H2C the results were improved **

Resutls:
```sh
starting benchmark...
spawning thread #0: 10 total client(s). 100000 total requests
Application protocol: h2c
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 5.34s, 18728.32 req/s, 1.27MB/s
requests: 100000 total, 100000 started, 100000 done, 100000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 100000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 6.78MB (7104150) total, 294.88KB (301960) headers (space savings 94.88%), 4.77MB (5000000) data
                     min         max         mean         sd        +/- sd
time for request:      271us     58.77ms      5.31ms      2.70ms    80.41%
time for connect:      105us       576us       308us       145us    70.00%
time to 1st byte:    39.14ms     59.37ms     45.71ms      7.11ms    70.00%
req/s           :    1872.94     1892.54     1880.25        6.27    70.00%
```

### Other Observations
- When running the test multiple times it was observed that the `h2load` tool freezes for both `H1C-H1C` and `H2C-H2C`.

**Comment by chamil321** [comment]
As per the [latest load test results](https://github.com/ballerina-platform/ballerina-standard-library/issues/494#issuecomment-1196453207), HTTP2 outperforms by a significant margin.
