### ISSUE TITLE
Migrate all publish to central workflow to include multiple central environments

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3136]
**Description:**
$subject

Module List:

Level 1
- [x] io
- [x] java.arrays
- [x] regex
- [x] time
- [x] url
- [x] xmldata
- [x] constraint

Level 2
- [x] crypto
- [x] log
- [x] os
- [x] random
- [x] task
- [x] xslt
- [x] serdes
- [x] protobuf

Level 3
- [x] cache
- [x] file
- [x] ftp
- [ ] mime
- [x] nats
- [x] stan
- [x] tcp
- [x] udp
- [x] uuid

Level 4
- [x] auth
- [x] email
- [x] jwt
- [x] oauth2

Level 5
- [x] http

Level 6
- [x] grpc
- [x] websocket
- [x] websub
- [x] websubhub

Level 7
- [x] graphql
- [x] kafka
- [x] rabbitmq
- [x] sql

Level 8
- [x] java.jdbc
- [x] mysql 
- [x] postgresql
- [x] mssql
- [x] oracledb

**Comment by Bhashinee** [comment]
https://github.com/ballerina-platform/module-ballerina-websocket/pull/630
https://github.com/ballerina-platform/module-ballerina-tcp/pull/634
https://github.com/ballerina-platform/module-ballerina-udp/pull/538

**Comment by ayeshLK** [comment]
[https://github.com/ballerina-platform/module-ballerina-jwt/pull/636](https://github.com/ballerina-platform/module-ballerina-jwt/pull/636)
