### ISSUE TITLE
Need to Access the `http:RequestContext` within WebSocket Upgrade Service

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#3145]
**Description:**
To add the GraphQL [Context](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/docs/spec/spec.md#8-context) support for `subscription` operations, the `graphql:Context` object is needed to be initialized per each request. Since the GraphQL module uses WebSocket as the underline protocol of subscription operations, the context object initialization is needed to be done within the WebSocket [upgrade service](https://github.com/ballerina-platform/module-ballerina-websocket/blob/main/docs/spec/spec.md#31-upgradeservice). To initialized the context object, `http:RequestContext` and `http:Request` are required. Currently, `http:RequestContext` cannot be accessed within the WebSocket upgrade service.

**Comment by Bhashinee** [comment]
WebSocket does not have a concept of interceptors(at least for now) for which HTTP uses this RequestContext. We can provide it as a parameter for the initial upgrade request if we can get an API from the HTTP package. But need to think about whether this is necessary from the WebSocket point of view. From what I understood interceptors are important when you have multiple resources in your service(to execute common logic across all the resources) and when you need to modify requests/responses. These are not common things in WebSocket as we don't even let the users create requests/responses. They are created internally as those should be sent in a specific format. And also there is only a single resource in the WebSocket upgrade service.  

So we need to discuss before adding this.

**Comment by Bhashinee** [comment]
Had a discussion about this with Thisaru, Shafreen, and Dimuthu. The final decision was to continue with setting the RequestContext to null and continue.
