### ISSUE TITLE
GraphQL build failed on Windows due to an intermittent error

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-standard-library#3172]
**Description:**

When building the graphql package, a test case was failed due to an intermittent error. It occurred while a WebSocket client is initiating.
https://github.com/ballerina-platform/module-ballerina-graphql/runs/7545316864?check_suite_focus=true#step:4:222

This happened only on Windows.

**Comment by ThisaruGuruge** [comment]
This is the excerpt from the error log:

```shell
Error: null

    at ballerina.websocket.2.Client:initEndpoint(websocket_sync_client.bal:62)
    ballerina.websocket.2.Client:init(websocket_sync_client.bal:59)
    ballerina.graphql_tests$test.1.tests.36_subscriptions:testInvalidSubscription(tests/36_subscriptions.bal:190)
```
