### ISSUE TITLE
Introduce an API to generate the proto3 file in serdes module

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#3177]
**Description:**
Currently serdes module uses protocol buffers to perform serialization and desirialization.
It does so by generating a dynamic `proto3 schema` for the given ballerina typedesc.
This underlying schema is not yet exposed to the user.
We should introduce an API to generate a `proto3` file from the underlying generated schema

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Closing as we deprecated SerDes package.
