### ISSUE TITLE
Implement generated client code for the entity record with associations (Persist Module)

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3193]
**Description:**
This task is to implement client code for the single entity record with associations. This client code will get auto-generated by looking at the entities in the Ballerina project. each entity will have a Ballerina client.

- [x] one-to-one associations
- [x] one-to-many associations
- [x] many-to-many associations

**Comment by kaneeldias** [comment]
Support for many-to-many associations added in https://github.com/ballerina-platform/module-ballerina-persist/pull/82
