### ISSUE TITLE
Change the colour of lables of Constraint package

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#3198]
**Description:**
<img width="834" alt="Screenshot 2022-08-02 at 15 20 03" src="https://user-images.githubusercontent.com/8381003/182346286-cca106a0-36df-49e4-9fae-82ba4671bd5c.png">

**Comment by TharmiganK** [comment]
This is fixed now :
See the [badge](https://codecov.io/gh/ballerina-platform/module-ballerina-constraint/branch/main/graph/badge.svg)
See the [std lib dashboard](https://github.com/ballerina-platform/ballerina-standard-library)
