### ISSUE TITLE
HTTP Perf tests failing for days

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#3199]
**Description:**
$subject

**Comment by ayeshLK** [comment]
It seems like even though the load-tests are passing, results have not been updated to `load-test-result` branch was not properly deleted when updating a previous load-test results. 

Will be fixed with [#1164](https://github.com/ballerina-platform/module-ballerina-http/pull/1164)

**Comment by chamil321** [comment]
Results have successfully updated. https://github.com/ballerina-platform/module-ballerina-http/actions/runs/2795950476

**Comment by ayeshLK** [comment]
Even though the workflow was successful, the error rate for load-tests are 100%. Hence, re-opening the issue.

**Comment by chamil321** [comment]
> Even though the workflow was successful, the error rate for load-tests are 100%. Hence, re-opening the issue.

Ack

**Comment by ayeshLK** [comment]
This was verified as fixed with following PR [#1183](https://github.com/ballerina-platform/module-ballerina-http/pull/1183)

There was an issue with `snowpeak` load test and it will be captured in issue [#3070](https://github.com/ballerina-platform/ballerina-standard-library/issues/3070)
