### ISSUE TITLE
Write the Generated GraphQL Schema to a File

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#3205]
**Description:**
Currently, the GraphQL schema generated from the Ballerina service is kept in memory. But it is better to write the generated schema to a file so that users can use/share it.

This file can be used to transfer the schema from compile-time to runtime, instead of adding it as an annotation for the service.

**Comment by DimuthuMadushan** [comment]
Proposal: [ballerina-standard-library/#3286](https://github.com/ballerina-platform/ballerina-standard-library/issues/3286)
