### ISSUE TITLE
Support advanced queries in persist module

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3219]
**Description:**
The current `ballerina/persist` module design[1], doesn't have a way of specifying advanced queries and selecting the columns the user needs to fetch, instead it returns the entire record value. This issue caters to the requirement of allowing users to specify advanced queries using Ballerina Query Syntax.

e.g: The user has the following `Employee` entity defined,

```ballerina
@persist:Entity { key: [“id”]}
public type Employee record {|
    readonly int id;
    string fname;
    string lname;
    string department;
    int age;
    string email;
    decimal salary;
|};
```
and the user needs to fetch the `fname`, `lname`, and `salary` from employees whose age exceeds 30.

* Proposed Solution

In the generated client for this `Employee` entity, there will be a `stream API` like below, which returns stream of record values,

```ballerina
public isolated client class EmployeeClient {
   public remote function query() returns stream<Employee, error?>|error {}
   ...
}
```

So the user can use this API to write the advanced query like below,

```ballerina
stream<record {string fname; string lname; decimal salary}, error?> users = from var {fname, lname, age, salary} in eClient->query() 
                 where age > 30 
                 select {fname, lname, salary};
```

Using code modifier at compile time, we will modify the code like below,

```ballerina
stream<record {string fname; string lname; decimal salary}, error?> users = eClient->execute(`SELECT fname, lname, salary from Employee where age > 30`);
```
and execute against the DB.

At the initial step, we will support a few sets of query operations. We can improve in the future.

1. https://docs.google.com/document/d/1hDa9pTZYmT3GbGdUrFZCaOenGIsTc5P9/edit#

**Comment by niveathika** [comment]
SubTask for the feasibility study,
- [x] Identify when `query()` remote function is called in Query Expression
- [x] Identify the use of where clause and process expressions. (Expressions are available in tree format, visitor can be used to construct where clause)
- [ ] Databinding and retrieving only specific columns  from the database


Blockers identified when trying a feasibility study for the above proposal,
1. Identify when `query()` remote function is called in Query Expression
    - [x] Action cannot be invoked in from clause (Fixed from Update 2)
    - [x] Even though, we can identify a remote call invocation, there is no way to validate that the client is the generated client to be used for persistence. (Proposal: Attach annotation `@persist:runInDB` to the query )
    - [ ] Annotation cannot be attached to queries

**Comment by niveathika** [comment]
Feasibly study has the following conclusions,

1. Identify persistance query usages
    - Import of persist module to any of the modules ensures that code modifier is engaged
    - A limitation is that if the persist client is bundled in separate package, the  query improvement will not be applied.
    - One workaround would be to require users to attach an annotation `persist:RunInDB` to the query. This ensures code modifier is engaged (Blocker as annotation cannot be attached to a query). 
    - It also has another advantage, the user specifically mentions to run the filter clause in the DB. Without this, if the code modifier runs into any errors, user would be confused since they are not aware of code modifier change, the error reported will be different to what they have written.
    
2. Supporting `where`, `limit` and `order by`
    - The filter clauses can be suppprted
    - SQL condition 'LIKE', 'BETWEEN', 'IN' cannot be supported for now
    - `limit` and `order by` needs to be done with static variables, i.e use of ballerina variables in the clause cannot be supported
    
3. Supporting `select` clause with or without use of data binding
    - This cannot be supported atm, as semantic information is not available for the code modifier to work.
    - Currently ballerina does not support non external dependently typed functions.
       ```ballerina
       remote function execute(sql:ParameterizedQuery filterClause, typedesc<record {}> t) returns stream<t, error?> {
       ```
    - Since query use the return type of the action to infer the type, we cannot use infer type for the API. Type description needs to be explicitly defined
    - ```ballerina
       record{int id; string period; int quantity;}[]? mns =
            check from entity:MedicalNeed medicalNeed in mnClient->read()
               where medicalNeed.quantity > 5
               limit 5
               order by medicalNeed.quantity descending
               select {
                    id: medicalNeed.needId,
                    period: medicalNeed.period,
                    quantity: medicalNeed.quantity
               };
       ```
       In the above example, code modifier is unaware of the types of id, period, quantity fields in the returned record. As such the type desc cannot be constructed as at code modifier level.
    - Even if we were to identify from the variable assigned this will be difficult if the user has defined a custom Typed Record
    - Since, type description cannot be defined inline, even if type is inferred to make the code work, we need to modify the code at module level with a custom Typed record.

Considering the above implication and per the offline discussions, I will proceed with a proposal to support only improving filter clause for the time being.

**Comment by niveathika** [comment]
Proposal: https://github.com/ballerina-platform/ballerina-standard-library/issues/3303
Implementation: https://github.com/ballerina-platform/ballerina-standard-library/issues/3304 

The above issues will be used to track the tasks.
