### ISSUE TITLE
Returning http:StatusCodeResponse throwing a compiler error

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/ballerina-standard-library#3224]
**Description:**
> $Subject 

**Steps to reproduce:**
```ballerina
service on new http:Listener(9090) {
    resource function get test() returns @http:Payload http:StatusCodeResponse{
        http:Ok Ok = {};
        return Ok;
    }
}
```
Error message :
```
invalid resource method return type: expected anydata|http:Response|http:StatusCodeRecord|error, but found http:StatusCodeResponse(HTTP_102)
```

**Affected Versions:**
Ballerina Swan Lake 2201.1.1

**Comment by chamil321** [comment]
The issue has been fixed in https://github.com/ballerina-platform/module-ballerina-http/pull/1054 and will be release with 2201.2.0. 
@Thevakumar-Luheerathan Do you need a patch release with this fix?

**Comment by Thevakumar-Luheerathan** [comment]
No thank you
