### ISSUE TITLE
[gRPC] Blocking client hangs when backend golang server returns an Error

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#327]
When Ballerina gRPC client does a blocking RPC with Golang service and Golang service sends an error. Ballerina gRPC Client hangs waiting for client response. 

RCA: when the Golang server sends as an error, the error sends with the initial header frames, it doesn't send any data frames. but Ballerina transport implementation always looks for the data frame. hence client hangs.

**Comment by daneshk** [comment]
We debug the issue further, Following are the findings
* Response headers come from the backend server(Golang server) are `:status`, `content-type`, `grpc-status`, and `grpc-message`.
* To verify, whether this is an initial header frame, we checked the existence of `:method` header, but it is not coming in the response headers. refer https://github.com/wso2/transport-http/pull/197/files#diff-a8c2a73a70ce052bd20e0fb23d542afe2ae5e828f9c097be186e75d6ca0484fbR320
* So we ignore the response message.

Possible solution,
* instead of checking `:method` header, check `content-type` header to verify it is initial header.

**Comment by chamil321** [comment]
I checked both `pushPromisedResponse` and `Response` tracelog to check the header availability. In the following log, the First header and data pair belong to a `Response`, and the second pair belong to `pushPromisedResponse`. The aforementioned condition has been used for both types of responses. The `: status` header seems more appropriate to check as there can be situations where there is no data sent along with the response. In that case `:content-type` header may not be present IINM. WDYT?

```
[L:/127.0.0.1:7090 - R:/127.0.0.1:41318] OUTBOUND HEADERS: streamId=1 headers=DefaultHttp2Headers[:status: 200, content-type: application/json, server: ballerina, date: Mon, 26 Oct 2020 11:08:38 +0530] padding=0 endStream=false  
[L:/127.0.0.1:7090 - R:/127.0.0.1:41318] OUTBOUND DATA: streamId=1 padding=0 endStream=true length=37 data=37B
{"response":{"name":"main resource"}}  
[L:/127.0.0.1:7090 - R:/127.0.0.1:41318] OUTBOUND HEADERS: streamId=2 headers=DefaultHttp2Headers[:status: 200, content-type: application/json, server: ballerina, date: Mon, 26 Oct 2020 11:08:38 +0530] padding=0 endStream=false  
[L:/127.0.0.1:7090 - R:/127.0.0.1:41318] OUTBOUND DATA: streamId=2 padding=0 endStream=true length=29 data=29B
{"push":{"name":"resource1"}} 
```
