### ISSUE TITLE
`graphql:Client` should include graphql errors as the cause of data binding error

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3281]
This is especially useful for the scenario where the data field is either null or not available.

**Comment by MohamedSabthar** [comment]
As for the current implementation, if the data field is either null or not available we return the graphql errors as `ServerError` and we do not perform data binding. In a partial response case, user can get the data as json from the returned `ServerError`.

**Comment by ThisaruGuruge** [comment]
@shafreenAnfar Looks like this already works as expected. Do we have anything else to improve this?

**Comment by MohamedSabthar** [comment]
Had a chat on this issue. The `executeWithType()` API handles the error as mentioned above, but this need to be handled for the `execute()` API. 
2 cases need to be considered in the `execute()` API

Case 1: The server returns a response with no data field but returns an error field
This case could happen on GraphQL validation.
Currently, we are catching this error as http:ApplicationResponseError and returning a graphql:RequestError and we are not performing any data binding here.
This case will be improved by setting the GraphQL response errors as errorDetails of graphql:RequestError

Case 2: The server returns a response with the data field set to null along with an error
This case will be improved by introducing a new PayloadBindingError in the graphql module. The graphql error response will be set as errorDetails of this newly introduced error
