### ISSUE TITLE
User-Agent header is set to a default value or empty in http post request

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-standard-library#3283]
**Description:**

**Case 01**
When calling a service's post resource function with `user-agent` header, the value gets overridden with the default value.

sample service
```
import ballerina/http;
import ballerina/log;

service / on new http:Listener(9090) {
    resource function post hello(@http:Header {name: "user-agent"} string? userAgent = ())
            returns json {

        log:printInfo("Received header value: " + (userAgent ?: ""));
        return {"hello": "world"};
    }
}
```

sample test invoking the service using an http client
```
import ballerina/test;
import ballerina/http;
import ballerina/io;

final http:Client clientEndpoint = check new ("http://localhost:9090");

@test:Config {}
function mytest() returns error? {
    io:println("\nGET request with Headers:");
    http:Response resp = check clientEndpoint->post("/hello", {"user-agent": "slbeta3"});
    io:println((check resp.getJsonPayload()).toJsonString());
}
```

**case 02**
When the above service accepts a payload as well, the user-agent header gets set to empty.

sample service
```
import ballerina/http;
import ballerina/log;

type MyRecord record {|
    string id;
    string name;
|};

service / on new http:Listener(9090) {

    resource function post hello(@http:Payload MyRecord payloadVal, @http:Header {name: "user-agent"} string? userAgent = ())
            returns json {

        log:printInfo("Received header value: " + (userAgent ?: ""));
        return {"hello": "world"};
    }
}
```

sample client
```
import ballerina/test;
import ballerina/http;
import ballerina/io;

final http:Client clientEndpoint = check new ("http://localhost:9090");

@test:Config {}
function mytest() returns error? {
    http:Response resp = check clientEndpoint->post("/hello", {"id": "dil", "name": "Ballerina"}, {"user-agent": "slbeta3"});
    io:println((check resp.getJsonPayload()).toJsonString());
}
```
**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
This is a blocker for https://github.com/wso2-enterprise/ballerina-registry/issues/1601

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
Case 1:

The second param of Entity body(POST, PUT, ...) client remote functions is Payload. The user agent being a header, it needs to be send as the third param. 
```ballerina
http:Response resp = check clientEndpoint->post("/hello", (), {"user-agent": "slbeta3"});
```

Case 2:

There is a bug as the user agent header is removed from the request and when doing the payload binding, this flow is invoked. Hence when header binding happens the header is not present in the header map as it is being removed and populated to request. Same happen when `http:Request` is present. Workaround would be to access userAgent via `http:Request`

```
log:printInfo("UA: " + req.userAgent);
```
