### ISSUE TITLE
Service definition without "/" and "on" throws compilation error

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/ballerina-standard-library#3285]
**Description:**
A service definition given in specs (https://github.com/ballerina-platform/module-ballerina-http/blob/master/docs/spec/spec.md#222-service-base-path) throws error without `/` and `on` keywords.
```ballerina
service hello\-world new http:Listener(9090) {
   resource function get foo() {

   }
}
```
Error messages
```
ERROR [main.bal:(20:1,24:2)] service declaration does not implement all required constructs of type: 'other'
ERROR [main.bal:(20:9,20:21)] unknown type 'hello\-world'
ERROR [main.bal:(20:22,20:22)] missing on keyword
ERROR [main.bal:(20:22,20:45)] service type is not supported by the listener
error: compilation contains errors
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
@Thevakumar-Luheerathan Thanks for pointing out it
