### ISSUE TITLE
`time:utcNow` API returns invalid results

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#3292]
**Description:**
When trying to retrieve the current UTC time using `time:utcNow` API, returned milliseconds from epoch time is invalid. 

Tried following code sample:
```ballerina
import ballerina/time;
import ballerina/io;

public function main() {
    [int, decimal] currentTime = time:utcNow();
    io:println("Received time values", currentTime);
}
```

Results:
```sh
Received time values[1661813273,0.120306000]
```

As per the retrieved results current time is `1661813273 milliseconds` from epoch time. When convert the milliseconds from epoch value to the date and time format it seems like the time is `Tue Jan 20 1970 05:36:53 UTC`. 

**OS, DB, other environment details and versions:**
- Ballerina 2201.1.0+

**Comment by sahanHe** [comment]
As you can see in the [API documention](https://lib.ballerina.io/ballerina/time/2.2.2/types#Utc:~:text=Utc%20readonly%20%26,positive%20leap%20second) first member of the tuple is number of seconds from epoch time, not milliseconds.  if the value is used correctly, you'll get the time `Tuesday, 30 August 2022 04:17:53 [GMT+05:30]`.
