### ISSUE TITLE
GraphQL dynamic listener is not working

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3294]
**Description:**

GraphQL dynamic listener is giving an error

**Steps to reproduce:**

Run the following code :

```ballerina
import ballerina/lang.runtime;
import ballerina/graphql;

public function main() returns error? {
    graphql:Listener serverEP = check new(4000);
    check serverEP.attach(backendService, "graphql");
    check serverEP.'start();
    runtime:registerListener(serverEP);
}

graphql:Service backendService = service object {

    resource function get greeting() returns string {
        return "Hello, World";
    }
};
```

Output : 

```console
Compiling source
        user/graphql_backend_server:0.1.0

Running executable

error: Error occurred while creating the schema
```

**Affected Versions:**

Ballerina SwanLake 2201.2.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MohamedSabthar** [comment]
Related issue: [#3317](https://github.com/ballerina-platform/ballerina-standard-library/issues/3317)

**Comment by ThisaruGuruge** [comment]
This is not a bug, but a limitation. We knew this was a limitation when we moved to compile-time schema generation. Hence changing the label as an improvement.
