### ISSUE TITLE
[Bug]: Support date-time formatting features like JS, JAVA

### ISSUE THREAD

**Issue by sarindaSenevirathne** [ballerina-platform/ballerina-standard-library#3311]
### Description

In ballerina, we have some data formatting capability, but we could not provide a format like yyyy-mm-dd and get the formatted output like JS and JAVA. In ballerina we have to take year month and date separately using civil date format and do the string concatination to achieve this requirement.

It would be better if we have this format support in ballerina time module

### Affected Version(s)

Ballerina 2201.1.1 (Swan Lake Update 1)

### Labels

LanguageServer, jBallerina, StandardLibs

**Comment by sahanHe** [comment]
Hi @sarindaSenevirathne, 

Thank you for your valuable feedback. Currently time module doesn't provide any specific API for custom time formats like mentioned above. But using simple string manipulations, many time/date formats can be obtained including the mentioned format. You can find more details and code snippets related to the conversion here: [A guide for Date/Time conversion in Ballerina Language](https://stackoverflow.com/collectives/wso2/articles/73277351/a-guide-for-date-time-conversion-in-ballerina-language).
Regards,
Sahan

**Comment by sahanHe** [comment]
Closing the issue as completed. Please reopen the issue if there are more related questions.
