### ISSUE TITLE
Ballerina vs Quarkus vs Micronaut comparsion

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3312]
Let's write this in Ballerina and do  a comparison in terms of image size, RSS, start-up time, perf, etc.

https://github.com/MichelSchudel/conference-service-quarkus

**Comment by TharmiganK** [comment]
Created a repository with all the sample applications : https://github.com/TharmiganK/conference-service/tree/main

**Comment by TharmiganK** [comment]
Created a document for the comparison : https://docs.google.com/document/d/1BsQtmxtfiY7D_Ikm9odpTt6bYK5phyEGtbvZcC-0U7M/edit?usp=sharing
