### ISSUE TITLE
Add setting max length value for persist entity fields through constraint module

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3313]
**Description:**
$subject, please. Check the possibility of using the Ballerina constraint package to add max length value for Persist entity fields.

```ballerina
@persist:Entity{}
type User record {|
    @constraint:String {
        maxLength: 100
    }
    string name;
|};
```

**Comment by kalaiyarasiganeshalingam** [comment]
This issue is reopened because the value must be validated against the maximum constraint annotation.
