### ISSUE TITLE
Incorporate GraalVM native-image test build to Std Libs daily build 

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3316]
**Description:**

> $Subject

**Comment by TharmiganK** [comment]
Follow the following steps to add `Build with bal test native` workflow to the standard library repos : 
1. Update the `ballerinaGradlePluginVersion` in `gradle.properties` to `1.0.0`
2. If your repo has a separate sub-project to run ballerina tests, then these [changes](https://github.com/ballerina-platform/module-ballerina-http/pull/1322/commits/0c6c601d0f62ffa0292c06f00915f5eab81a7103) should be done to the `build.gradle` file in the sub-project.
3. Add the [`Build with bal test native` workflow](url) to your repo and change the additional arguments to skip any native java tests and compiler plugin tests associated with your module.

**Comment by TharmiganK** [comment]
Task Status t:

- [ ] constraint
- [ ] io
- [ ] java.arrays
- [ ] regex
- [ ] time
- [ ] url
- [ ] xmldata
- [ ] crypto
- [ ] log
- [ ] os
- [ ] protobuf
- [ ] random
- [ ] serdes
- [ ] task
- [ ] xslt
- [ ] cache
- [ ] file
- [ ] ftp
- [ ] mime
- [ ] tcp
- [ ] udp
- [ ] uuid
- [ ] auth
- [ ] email
- [ ] jwt
- [ ] oauth2
- [ ] http
- [ ] grpc
- [ ] websocket
- [ ] websub
- [ ] websubhub
- [ ] graphql
- [ ] sql
- [ ] nats
- [ ] kafka
- [ ] rabbitmq
- [ ] java.jdbc
- [ ] mssql
- [ ] mysql
- [ ] oracledb
- [ ] postgresql

**Comment by niveathika** [comment]
As per this discussion, we have decided to go ahead with adding the workflow with daily build disabled, 
https://github.com/ballerina-platform/module-ballerina-sql/pull/593#issuecomment-1333980539

**Comment by TharmiganK** [comment]
Closing this issue here as all the std libs has deployed the workflows. The failures are tracked via https://github.com/ballerina-platform/ballerina-standard-library/issues/3755
