### ISSUE TITLE
Oauth2 client treats `201-Created` response as a failure

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3334]
**Description:**

Recently the default status code of the HTTP post resource response is changed to `201-Created`. Because of this the following oauth2 token endpoint : https://github.com/ldclakmal/ballerina-security/blob/master/scenarios/sts/ballerina-sts.bal returns a `201-Created` response rather than `200-Created`.

But the[ oauth2 client only considers `200-Ok` as a success response](https://github.com/ballerina-platform/module-ballerina-oauth2/blob/master/native/src/main/java/io/ballerina/stdlib/oauth2/OAuth2Client.java#L300) and gives the following error for `201-created` response :

```console
error: Failed to call the token endpoint 'https://localhost:9445/oauth2/token'.
        at ballerina.oauth2.2:prepareError(oauth2_errors.bal:27)
           ballerina.oauth2.2:sendRequest(client_oauth2_provider.bal:540)
           ballerina.oauth2.2:getAccessTokenFromTokenRequestForPasswordGrant(client_oauth2_provider.bal:364)
           ballerina.oauth2.2:getOAuth2TokenForPasswordGrant(client_oauth2_provider.bal:250)
           ballerina.oauth2.2:generateOAuth2Token(client_oauth2_provider.bal:217)
           ballerina.oauth2.2.ClientOAuth2Provider:init(client_oauth2_provider.bal:190)
           ballerina.http.2.ClientOAuth2Handler:init(auth_client_oauth2_handler.bal:28)
           ballerina.http.2:initClientAuthHandler(http_secure_client.bal:240)
           ballerina.http.2.HttpSecureClient:init(http_secure_client.bal:32)
           ballerina.http.2:createHttpSecureClient(http_secure_client.bal:202)
           ballerina.http.2.HttpCachingClient:init(caching_http_caching_client.bal:40)
           ballerina.http.2:createHttpCachingClient(caching_http_caching_client.bal:262)
           ballerina.http.2:createDefaultClient(http_client_endpoint.bal:760)
           ballerina.http.2:createCookieClient(http_client_endpoint.bal:755)
           ballerina.http.2:checkForRetry(http_client_endpoint.bal:662)
           ballerina.http.2:initialize(http_client_endpoint.bal:634)
           ballerina.http.2.Client:init(http_client_endpoint.bal:55)
cause: Failed to get a success response from the endpoint. Response code: '201'. Response body: '{"access_token":"b52f440a-3224-4651-8464-c1d92c224b76", "refresh_token":"ef43ba88-5456-4495-bca8-fd968993d8ab", "token_type":"example", "expires_in":2, "example_parameter":"example_value", "scope":"admin"}'
        at ballerina.oauth2.2:doHttpRequest(oauth2_commons.bal:72)
           ballerina.oauth2.2:sendRequest(client_oauth2_provider.bal:531)
           ... 15 more
```

**Steps to reproduce:**

1. Download the necessary code and resources [here](https://drive.google.com/file/d/1pLK5zfGtTMDpy7YnAxCsJk1ZnsY0Pwwt/view?usp=sharing).
2. Run the mock oauth2 token endpoint
3. Run the main server
4. Run the client

**Affected Versions:**

Ballerina SwanLake 2201.2.0

**Comment by MohamedSabthar** [comment]
According to [RFC6749](https://www.rfc-editor.org/rfc/rfc6749#section-5.1) status code should be 200. But we could improve the error message instead of returning an error like `Failed to get a success response from the endpoint. Response code: '201'. Response body:` ( 201 error could be interpreted as success code for creation)

@shafreenAnfar WTYD ?
