### ISSUE TITLE
OAuth refresh token grant type token initiation fails

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-standard-library#3388]
**Description:**
While initiating token request following error is prompted 

error: Dependant module initialization for test suite failed due to Failed to call the token endpoint 'https://localhost:9445/oauth2/token'.
        at ballerina.oauth2.2:prepareError(oauth2_errors.bal:27)
           ballerina.oauth2.2:sendRequest(client_oauth2_provider.bal:540)
           ballerina.oauth2.2:getAccessTokenFromRefreshRequestForRefreshTokenGrant(client_oauth2_provider.bal:482)
           ballerina.oauth2.2:getOAuth2TokenForRefreshTokenGrantType(client_oauth2_provider.bal:270)
           ballerina.oauth2.2:generateOAuth2Token(client_oauth2_provider.bal:219)
           ballerina.oauth2.2.ClientOAuth2Provider:init(client_oauth2_provider.bal:190)
           ballerina.http.2.ClientOAuth2Handler:init(auth_client_oauth2_handler.bal:28)
cause: Failed to get a success response from the endpoint. Response code: '201'. Response body: '{"access_token":"1676c2b7-759c-4909-9e59-ead2800207c0", "refresh_token":"56486157-f651-45de-833a-97eaa1152a58", "token_type":"example", "expires_in":3600, "example_parameter":"example_value"}'
        at ballerina.oauth2.2:doHttpRequest(oauth2_commons.bal:72)
           ballerina.oauth2.2:sendRequest(client_oauth2_provider.bal:531)
           ... 5 more

Notice on the response it's a 201 with a proper access token in its body. However the message states  Failed to get a success response from the endpoint.

**Steps to reproduce:**

- Start STS Backend 
- Initiate a token request with following configuration and request structure 

`http:OAuth2RefreshTokenGrantConfig config = {
    refreshUrl: tokenEndpoint,
    refreshToken: refreshToken,
    clientId: clientId,
    clientSecret: clientSecret,
    clientConfig: {
        secureSocket: {
            cert: "./resources/public.crt"
        }
    }
};`

`  final http:Client clientEndpoint = check new (activitiesEp, auth = config, secureSocket = {cert: "./resources/public.crt"});
    json userActivitiesResponse = check clientEndpoint->get(activitiesUri);`

**Affected Versions:**

Ballerina 2201.2.0 (Swan Lake Update 2)
Language specification 2022R3
Update Tool 1.3.10

**OS, DB, other environment details and versions:**

MAC OS

**Comment by TharmiganK** [comment]
This is because of the recent change in http to default post resource response to 201-Created rather than 200-OK

This is already addressed and fixed

See the following issue : https://github.com/ballerina-platform/ballerina-standard-library/issues/3334

**Comment by pamod** [comment]
Thanks @TharmiganK. So I can expect a patch release for this ?

**Comment by MohamedSabthar** [comment]
@pamod are you using STS written in ballerina? what STS backend are you using ?

**Comment by pamod** [comment]
@MohamedSabthar I am using STS which came with hackthon exercises, written in ballerina
