### ISSUE TITLE
Improve the sql script generation to support associations

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#3398]
**Description:**
Db has support  following associations:
- one to one
- one to Many
- Many to Many

Therefore, Need to improve the sql script that has contains all the related tables according to the associations.

**Comment by daneshk** [comment]
We have already added support for 1:1 and 1:M associations and decided not to support N: M associations for phase 01. So, I am closing the issue. Let's create a new issue when we have a design for the N: M associations
