### ISSUE TITLE
io:filewriteCSV produces incorrect order when structurally equivalent different order record types

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3399]
**Description:**

Consider the below example,
```ballerina
import ballerina/io;

type Base record {|
    int base1;
    int base2;
|};

type Derived1 record {|
    int derived1;
    int derived2;
    int base1;
    int base2;
|};

type Derived2 record {|
    *Base;
    int derived1;
    int derived2;
|};

public function main() returns error? {
    Derived1 d1 = {base1: 1, base2: 2, derived1: 3, derived2: 4};
    Derived2 d2 = {derived1: 3, derived2: 4, base1: 1, base2: 2};
    Derived2 d3 = {base1: 1,  derived1: 3, derived2: 4, base2: 2};
    record {|
        int base1;
        int derived1;
        int derived2;
        int base2;
    |} d4 = {base1: 1, derived1: 3, derived2: 4, base2: 2};
    Derived1[] arr = [d1, d2, d3, d4];

    check io:fileWriteCsv("derived1.csv", arr);
}
```
The order of the CSV output file is not correct. we need to consider filenames/keys of the record/map to preserve the correct order.

**Comment by sahanHe** [comment]
This is caused as we cannot guarantee the order of fields inside a record unlike `string[]`. This bug can be solved by maintaining the same order of fields in the first element while writing the other elements  of the array. As the field order can be changed from the input, the headers has to be written by default when the record[] is used as the input.

**Comment by sahanHe** [comment]
For the case of appending to a existing CSV file, we can check if there is a existing file and read the headers. If the headers match, it will append the new records according to the existing order. If there is no such a CSV file, it will create a new csv file to append the data.

**Comment by niveathika** [comment]
In case of overwrite, I dont think there is a need to check for headers,

1. Overwrite:
     Do not consider existing records or not. Headers based on the field names are added by default.

2 Append. 
    File does not exist or does not consist of any rows, it is similar to an overwrite scenario.

   If records exist, the first row is considered as headers and processed to see if the field name matches.
   If it does not match, returns error
   If it matches, follow the order to append records.

I think this covers all use cases. @daneshk WDYT?

**Comment by sahanHe** [comment]
For the `fileWriteCsvFromStream()` we will use the same behavior as above to write the CSV stream.

1. Overwrite:
    Do not consider existing data records or not. Headers based on the field names are added by default.

2.Append
    File does not exist or does not consist of any rows, it is similar to an overwrite scenario.
    If records exist, the first row is considered as headers and processed to see if the field name matches.
    If it does not match, returns error
    If it matches, follow the order to append records.
