### ISSUE TITLE
Populate HATEOAS link's `types` field based on the resource return type

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3404]
**Description:**

> $Subject

**Describe your problem(s)**

According to the current implementation, the `types` field in a static HATEOAS link is populated using the `mediaType` specified in the `@http:Payload` annotation.

See the following example : 

```ballerina
import ballerina/http;

service /restbucks on new http:Listener(9090) {

    @http:ResourceConfig {
        name: "order",
        linkedTo: [
            {name: "orders", relation: "update"},
            {name: "payment", relation: "payment"}
        ]
    }
    resource function post 'order(@http:Payload json 'order) returns json {
        return {id: "001", 'order: 'order, cost: 49.30};
    }

    @http:ResourceConfig {
        name: "orders",
        linkedTo: [
            {name: "orders", relation: "update"},
            {name: "payment", relation: "payment"}
        ]
    }
    resource function put orders/[string id](@http:Payload json 'order) returns 'order {
        return 'order;
    }

    @http:ResourceConfig {
        name: "payment"
    }
    resource function put payment/[string id](@http:Payload json payment)
           returns @http:Payload{mediaType: "application/restbucks.payment+json"} http:Accepted {
        return http:ACCEPTED;
    }
}
```

Request : 
```
curl http://localhost:9090/restbucks/order -d '{"name":"latte", "quantity":2}' 
-H "Content-Type: application/json" -X POST
```
Current output : 
```json
{
   "id":"001",
   "order":{"name":"latte", "quantity":2},
   "cost":49.3,
   "_links":{
      "update":{
         "rel":"update",
         "href":"/restBucks/orders/{id}",
         "methods":["PUT"]
      },
      "payment":{
         "rel":"payment",
         "href":"/restBucks/payment/{id}",
         "types":["application/restbucks.payment+json"],
         "methods":["PUT"]
      }
   }
}
```

Expected output :
```json
{
   "id":"001",
   "order":{"name":"latte", "quantity":2},
   "cost":49.3,
   "_links":{
      "update":{
         "rel":"update",
         "href":"/restBucks/orders/{id}",
         "types":["application/json"],
         "methods":["PUT"]
      },
      "payment":{
         "rel":"payment",
         "href":"/restBucks/payment/{id}",
         "types":["application/restbucks.payment+json"],
         "methods":["PUT"]
      }
   }
}
```

**Describe your solution(s)**

So in order to get the `types` the user need to explicitly add this annotation to the resource method which is not necessary since the return media-type can be resolved using the return type of the resource function.

**Comment by TharmiganK** [comment]
| Basic Return Type | Content Type                    |
| ------------------ | ------------------------- |
| ()                             | -                                          |
| Response               | -                                          |
| error                       | -                                          |
| string                     | text/plain                             |
| xml                         | application/xml                   |
| byte[]                     | application/octet-stream  |
| other                      | application/json                 |

When a resource returns a union of the above basic types then the `types` field will be populated with an array of content-types which are of the members of the union.

For example :

```ballerina
public type ReturnType string|xml|map<string>;

service /hateoas on new http:Listener(9091) {

    @http:ResourceConfig {
        linkedTo: [
            {name:"link1", relation: "link1"},
            {name:"link2", relation: "link2"},
            {name:"link3", relation: "link3"},
            {name:"link4", relation: "link4"},
            {name:"link5", relation: "link5"},
            {name:"link6", relation: "link6"},
            {name:"link7", relation: "link7"},
            {name:"link8", relation: "link8"},
            {name:"link9", relation: "link9"}
        ]
    }
    resource function get links() returns http:Ok {
        return {body: {message: "Links returned"}};
    }

    @http:ResourceConfig {
        name: "link1"
    }
    resource function get link1() returns string {
        return "Hello, from resource link1";
    }

    @http:ResourceConfig {
        name: "link2"
    }
    resource function get link2() returns xml {
        return xml`<message>Hello, from resource link2</message>`;
    }

    @http:ResourceConfig {
        name: "link3"
    }
    resource function get link3() returns byte[] {
        return "Hello, from resource link3".toBytes();
    }

    @http:ResourceConfig {
        name: "link4"
    }
    resource function get link4() returns @http:Payload{mediaType: "application/json"} http:Response {
        http:Response res = new;
        res.setTextPayload("Hello, from resource link4");
        return res;
    }

    @http:ResourceConfig {
        name: "link5"
    }
    resource function get link5() returns http:Ok {
        return {body: "Hello, from resource lin5"};
    }

    @http:ResourceConfig {
        name: "link6"
    }
    resource function get lin6() returns string|xml {
        return "Hello, from resource link6";
    }

    @http:ResourceConfig {
        name: "link7"
    }
    resource function get link7() returns ReturnType {
        return "Hello, from resource link7";
    }

    @http:ResourceConfig {
        name: "link8"
    }
    resource function get link8() returns http:Response|error? {
        return;
    }

    @http:ResourceConfig {
        name: "link9"
    }
    resource function get link9() returns @http:Payload{mediaType: "application/json"} string|xml {
        return xml`<message>Hello, from resource link9</message>`;
    }
}
```

cURL request : `curl http://localhost:9091/hateoas/links`

Response payload :
```json
{
    "message": "Links returned",
    "_links": {
        "link1": {
            "href": "/hateoas/link1",
            "types": [ "text/plain" ],
            "methods": [ "GET" ]
        },
        "link2": {
            "href": "/hateoas/link2",
            "types": [ "application/xml" ],
            "methods": [ "GET" ]
        },
        "link3": {
            "href": "/hateoas/link3",
            "types": [ "application/octet-stream" ],
            "methods": [ "GET" ]
        },
        "link4": {
            "href": "/hateoas/link4",
            "types": [ "application/json" ],
            "methods": [ "GET" ]
        },
        "link5": {
            "href": "/hateoas/link5",
            "types": [ "application/json" ],
            "methods": [ "GET" ]
        },
        "link6": {
            "href": "/hateoas/lin6",
            "types": [
                "application/xml",
                "text/plain"
            ],
            "methods": [ "GET" ]
        },
        "link7": {
            "href": "/hateoas/link7",
            "types": [
                "application/xml",
                "application/json",
                "text/plain"
            ],
            "methods": [ "GET" ]
        },
        "link8": {
            "href": "/hateoas/link8",
            "methods": [ "GET" ]
        },
        "link9": {
            "href": "/hateoas/link9",
            "types": [ "application/json" ],
            "methods": [ "GET" ]
        }
    }
}
```

**Comment by chamil321** [comment]
> `types` for basic returned types :
> 
> Basic Return Type	Content Type
> ()	-
> Response	-
> error	-
> string	text/plain
> xml	application/xml
> byte[]	application/octet-stream
> other	application/json
> When a resource returns a union of the above basic types then the `types` field will be populated with an array of content-types which are of the members of the union.
> 
> If the `Payload` annotation is used to overwrite the `mediaType` then the `types` field will be only populated with the configured value.
> 
> For example :
> 
> ```ballerina
> public type ReturnType string|xml|map<string>;
> 
> service /hateoas on new http:Listener(9091) {
> 
>     @http:ResourceConfig {
>         linkedTo: [
>             {name:"link1", relation: "link1"},
>             {name:"link2", relation: "link2"},
>             {name:"link3", relation: "link3"},
>             {name:"link4", relation: "link4"},
>             {name:"link5", relation: "link5"},
>             {name:"link6", relation: "link6"},
>             {name:"link7", relation: "link7"},
>             {name:"link8", relation: "link8"},
>             {name:"link9", relation: "link9"}
>         ]
>     }
>     resource function get links() returns http:Ok {
>         return {body: {message: "Links returned"}};
>     }
> 
>     @http:ResourceConfig {
>         name: "link1"
>     }
>     resource function get link1() returns string {
>         return "Hello, from resource link1";
>     }
> 
>     @http:ResourceConfig {
>         name: "link2"
>     }
>     resource function get link2() returns xml {
>         return xml`<message>Hello, from resource link2</message>`;
>     }
> 
>     @http:ResourceConfig {
>         name: "link3"
>     }
>     resource function get link3() returns byte[] {
>         return "Hello, from resource link3".toBytes();
>     }
> 
>     @http:ResourceConfig {
>         name: "link4"
>     }
>     resource function get link4() returns @http:Payload{mediaType: "application/json"} http:Response {
>         http:Response res = new;
>         res.setTextPayload("Hello, from resource link4");
>         return res;
>     }
> 
>     @http:ResourceConfig {
>         name: "link5"
>     }
>     resource function get link5() returns http:Ok {
>         return {body: "Hello, from resource lin5"};
>     }
> 
>     @http:ResourceConfig {
>         name: "link6"
>     }
>     resource function get lin6() returns string|xml {
>         return "Hello, from resource link6";
>     }
> 
>     @http:ResourceConfig {
>         name: "link7"
>     }
>     resource function get link7() returns ReturnType {
>         return "Hello, from resource link7";
>     }
> 
>     @http:ResourceConfig {
>         name: "link8"
>     }
>     resource function get link8() returns http:Response|error? {
>         return;
>     }
> 
>     @http:ResourceConfig {
>         name: "link9"
>     }
>     resource function get link9() returns @http:Payload{mediaType: "application/json"} string|xml {
>         return xml`<message>Hello, from resource link9</message>`;
>     }
> }
> ```
> 
> cURL request : `curl http://localhost:9091/hateoas/links`
> 
> Response payload :
> 
> ```json
> {
>     "message": "Links returned",
>     "_links": {
>         "link1": {
>             "href": "/hateoas/link1",
>             "types": [ "text/plain" ],
>             "methods": [ "GET" ]
>         },
>         "link2": {
>             "href": "/hateoas/link2",
>             "types": [ "application/xml" ],
>             "methods": [ "GET" ]
>         },
>         "link3": {
>             "href": "/hateoas/link3",
>             "types": [ "application/octet-stream" ],
>             "methods": [ "GET" ]
>         },
>         "link4": {
>             "href": "/hateoas/link4",
>             "types": [ "application/json" ],
>             "methods": [ "GET" ]
>         },
>         "link5": {
>             "href": "/hateoas/link5",
>             "types": [ "application/json" ],
>             "methods": [ "GET" ]
>         },
>         "link6": {
>             "href": "/hateoas/lin6",
>             "types": [
>                 "application/xml",
>                 "text/plain"
>             ],
>             "methods": [ "GET" ]
>         },
>         "link7": {
>             "href": "/hateoas/link7",
>             "types": [
>                 "application/xml",
>                 "application/json",
>                 "text/plain"
>             ],
>             "methods": [ "GET" ]
>         },
>         "link8": {
>             "href": "/hateoas/link8",
>             "methods": [ "GET" ]
>         },
>         "link9": {
>             "href": "/hateoas/link9",
>             "types": [ "application/json" ],
>             "methods": [ "GET" ]
>         }
>     }
> }
> ```

Some of the return types does not directly map to the correct media type. For example, Link 5, Link 8.. etc. I think its better to not to mention types field unless it is 100% accurate. 
In Link5, if user had mentioned a content type, it is not reflected in the links right. In such cases we can skip the types field

**Comment by TharmiganK** [comment]
> Some of the return types does not directly map to the correct media type. For example, Link 5, Link 8.. etc. I think its better to not to mention types field unless it is 100% accurate. In Link5, if user had mentioned a content type, it is not reflected in the links right. In such cases we can skip the types field

+1
will fix this by handling the StatusCodeResponses separately from records. And will add the `types` only when the media-type is resolvable from the body type

**Comment by TharmiganK** [comment]
The `types` field will be populated from the following ways :

1. Payload annotation on return type will get the highest priority. And if the user specified the return media-type(s) then those will be directly used to populate `types` filed. In this case, return type of the resource will not be considered.

```ballerina 
// `types` of this link resource will be `[application/json]`
resource function get link1() returns @http:Payload{mediaType: "application/json"}  Result {
    ...
}

// `types` of this link resource will be `[application/json, application/json+id]`
resource function get link2() returns @http:Payload{mediaType: ["application/json", "application/json+id"]}  Result {
    ...
}
```

2. If the resource returns the response using the caller and respond type is specified in `CallerInfo` annotation that type will be used as the return type and the returned media-type(s) will be resolved base on that type (See point 3)

```ballerina
// `types` of this link resource will be `[text/plain]`
resource function get link(@http:CallerInfo{respondType: string} http:Caller caller) returns error? {
    ...
}
```

3. The returned media-types will be resolved from the resource return type as shown in the following table :

| Return Type                  | Media Type                                                                                    |
| ---------------------- | ------------------------------------------------------------ |
| ()                                    | -                                                                                                      |
| Response                      | -                                                                                                      |
| error                              | -                                                                                                       |
| anydata                         | -                                                                                                       |
| string                             | `text/plain`                                                                                     |
| xml                                | `application/xml`                                                                            |
| byte[]                            | `application/octet-stream`                                                           |
| other basic types         | `application/json`                                                                          |
| StatusCodeResponse  | resolved from the `body` type                                                   |
| Union types                  | list of all the media-types resolved from each member types |
