### ISSUE TITLE
HTTP/2 calls sent to a HTTPS based REST API backend fails within in K8s cluster

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-standard-library#3440]
**Description:**

After upgrading to the latest version of ballerina, the HTTP calls sent to a HTTPS based (signed by a well known cert - no secure socket config) REST API backend fails. Reverting back to the previous version fixes the issue as well and no other changes were done along with this.

**Steps to reproduce:**
This was only reproduced in a K8s environment.

**Affected Versions:**
2201.2.0 (Previously 2201.1.0)
ballerina/http 2.4.0 (Previously 2.2.2)

**OS, DB, other environment details and versions:**
K8s Cluster with Service Mesh installed

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
This should be fixed via https://github.com/ballerina-platform/module-ballerina-http/pull/1286.
