### ISSUE TITLE
Update Slack channel occurrences with Discord

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-standard-library#3463]
**Description:**

$subject from repo readme.md , package.md, module.md. Check all the places in all modules.

**Comment by kalaiyarasiganeshalingam** [comment]
Module List for stdLibs :

- [ ] io
- [ ] java.arrays
- [ ] regex
- [ ] time
- [ ] url
- [ ] xmldata
- [ ] constraint
- [ ] crypto
- [ ] random
- [ ] log
- [ ] os
- [ ] task
- [ ] xslt
- [ ] serdes
- [ ] protobuf
- [ ] cache
- [ ] file
- [ ] ftp
- [ ] mime
- [ ] nats
- [ ] tcp
- [ ] udp
- [ ] uuid
- [ ] auth
- [ ] email
- [ ] jwt
- [ ] oauth2
- [ ] http
- [ ] grpc
- [ ] websocket
- [ ] websub
- [ ] websubhub
- [ ] graphql
- [ ] kafka
- [ ] rabbitmq
- [ ] sql
- [ ] java.jdbc
- [ ] mysql 
- [ ] postgresql
- [ ] mssql
- [ ] oracledb
