### ISSUE TITLE
Fix WebSub test failure after testerina migration

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#3464]
**Description:**
Test cases in following test file has failed after testerina migration:
- subscription_initiation_test.bal

**Comment by ayeshLK** [comment]
Tested the issue locally using a ballerina-lang build from `testerina-migration` branch [1] and found that this issue is no longer there. Hence, closing the GitHub issue.

[1] - https://github.com/ballerina-platform/ballerina-lang/tree/testerina-migration

**Comment by gayaldassanayake** [comment]
The hackathon Qs 7_1, 7_2 are hanging in a similar manner when running tests with the latest daily build.

**Comment by ayeshLK** [comment]
@gayaldassanayake created a separate issue to track this behavior. Hence closing this issue.
- https://github.com/ballerina-platform/ballerina-standard-library/issues/4019
