### ISSUE TITLE
Resolver returns null when a record has a service object as its field

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#3466]
**Description:**
$Subject

**Steps to reproduce:**
```ballerina
import ballerina/graphql;
public service class Product {
    private final string id;

    function init(string id) {
        self.id = id;
    }

    resource function get id() returns string {
        return self.id;
    }
}

public type Review record {
  Product product; // this is not allowed in ballerina graphql. should return a compilation error
  int score;
  string description;
};

@graphql:ServiceConfig {
    cors: {
        allowOrigins: ["*"]
    }
}
service /graphql on new graphql:Listener(5001) {
    resource function get latestReviews () returns Review[] {
        return [{product: new ("1"), score: 20, description: "this is a product"}];
    }
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Ideally, we should allow this, as service types are valid field types. @MohamedSabthar What is the current functionality of this? If it works, that's the expected behaviour. If it does not work, that is the actual bug and we should fix it.

**Comment by MohamedSabthar** [comment]
> Ideally, we should allow this, as service types are valid field types. @MohamedSabthar What is the current functionality of this? If it works, that's the expected behaviour. If it does not work, that is the actual bug and we should fix it.

@ThisaruGuruge Yes, we need to allow this. 

For the above service and for below query
```graphql
{
  latestReviews {
    description
    score
  }
}
```

The server should send the below **expected response**
```json
{
  "data": {
    "latestReviews": [
      {
        "description": "this is a product",
        "score": 20
      }
    ]
  }
```
But this produces following response **(actual response)**
```json
{
  "data": null
}
```
However removing `Product` from the service giving the correct response.

**Comment by ThisaruGuruge** [comment]
This is indeed a bug. We should fix this to return a proper response.
