### ISSUE TITLE
Add code actions to execute persist tool actions

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3471]
**Description:**
At the moment, persist tool provides CLI commands to initialize the project, generate client code, and push DB changes. Add code actions as well. So the user gets a better development experience rather than switching between VSCode editor and terminal.

**Describe your task(s)**
The suggested Development flow would be like the below,

1. The user creates a Ballerina project and defines entities.
2. A code action appears suggesting adding database configs and database driver dependency params
3. Once the user clicks on the code action, update the `Configs.toml` with required configuration entries and the `Ballerina.toml` file with database driver params.
4. Use a compiler plugin the generate SQL scripts for defined entities and add a code action to push database schema changes to the database. If the database is not configured properly give an error. if not execute the generated SQL scripts against the database.
5. Use compiler plugin to generate client code for the defined entities and add it to the target directory which can access and be visible to the default package(This needs a few project API support as well).

**Comment by daneshk** [comment]
Depriotize due to change in the design

**Comment by niveathika** [comment]
With the latest design change and considering following,
1. Usability
    Code actions are listed under a yellow bulb. This is hardly noticeable if the model file is valid. On the other hand plugin commands have more visibility
    <img width="242" alt="Screenshot 2023-03-10 at 21 16 37" src="https://user-images.githubusercontent.com/27669465/224361481-3d36932d-4006-4edf-887a-78a02c45e8e4.png">

2. Implementation
    Code actions can only contain text edits. In this sense we have to duplicate all changes we do in tooling in the code action itself. This will lead to duplication of code and unnecessary overhead going forward
    With plugin commands we can invoke the commands in terminal
<img width="1434" alt="Screenshot 2023-03-10 at 21 26 04" src="https://user-images.githubusercontent.com/27669465/224362737-c869f14e-3f63-4f81-b5bc-af777319f56f.png">

Due to the above reason we decided go ahead with Plugin commands rather than code actions

**Comment by niveathika** [comment]
New issue which details the plugin command improvement https://github.com/ballerina-platform/ballerina-standard-library/issues/4188
