### ISSUE TITLE
Clean up of persist-tools code to remove redundant modules

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3474]
**Description:**
$subject

**Comment by MadhukaHarith92** [comment]
Currently, the empty `ballerina` project is used to create a Ballerina distribution inside the `target` directory by applying the Ballerina gradle plugin[[1]](https://github.com/ballerina-platform/plugin-gradle). The registered `build` task in the plugin uses `bal` command so there has to be a Ballerina project to create the `target` directory.

This distribution is used in tooling tests including:
1. Generate the SQL scripts to be used in `bal persist db push` command.
2. Check for semantic and syntax errors in the generated clients using `bal persist generate`.
3. In negative test cases validate if the error message is returned when commands are executed outside a Ballerina project.

If we are to remove the `ballerina` sub-dir we have to remove the above usages.

[1] https://github.com/ballerina-platform/plugin-gradle

**Comment by niveathika** [comment]
Ballerina plugin to used to build and publish ballerina packages(This is specifically for standard libraries as external users can use the published distribution). 

All the above uses you have indicated is to get a pack to test the `tools` usage. That is not the task of ballerina plugin. Our build needs to be refactored to create this intermediate pack w/o the plugin.

We have similar code in in other `tools` modules such as [graphql-tools](https://github.com/ballerina-platform/graphql-tools/blob/main/graphql-cli/build.gradle)

Lets' look through the code and refactor the build.
