### ISSUE TITLE
[Compiler Validator] Compiler doesn't validate equality of entities between submodules 

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3492]
**Description:**
If we copy the same entity to the sub-module. the compiler doesn't give an error for duplicated table names, instead updates the SQL scripts with duplicating table create scripts

**Comment by daneshk** [comment]
Shall we avoid creating an entity with the same name inside sub-modules of the same project?
This kind of a limitation, but if there are entities with the same name, there is an issue with clients.

**Comment by niveathika** [comment]
However, if the user the has overridden the table name, table name should be taken into consideration not record name.

Improvements,
1. Improve error message to indicate where the other duplicated entry is
2. The line indicated in the error message must be specific to either tableName field/ record name. No need to indicate the entire entity.

**Comment by niveathika** [comment]
Closing this as the tableName field in annotations is removed in V2
