### ISSUE TITLE
Proposal for supporting subscription in graphql:Client

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#3540]
**Description:**
sub task of [#3400](https://github.com/ballerina-platform/ballerina-standard-library/issues/3400)

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MohamedSabthar** [comment]
Proposal : [#3560](https://github.com/ballerina-platform/ballerina-standard-library/issues/3560)

**Comment by anupama-pathirage** [comment]
Since this is moved to done in https://github.com/ballerina-platform/ballerina-standard-library/projects/139 can we close this issue? Pls create a different issue or update the title/description accordingly if there are remaining parts.

@shafreenAnfar / @MohamedSabthar
