### ISSUE TITLE
Socket connection gets closed when the operation is complete or if there is an error

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#3548]
**Description:**
The graphql-transport-ws/graphql-ws subprotocol allows multiplexing a single WebSocket between multiple subscription operations. Each subscription operation is uniquely identified by a unique id generated by the client.

The subscription operation in ballerina graphql doesn't handle this multiplexing operation properly. In the current implementation, 
the socket connection is closed whenever there is a websocket_complete message (to stop specific subscription) recived or when there is an error while executing the subscription operation. Closing the socket will terminate all the other subscription operations requested by the client. 
According to [this spec](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md), the socket should not be closed But no further messages should be sent to that specific(completed/error-occurred) subscription operation.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
We need to fix this and port the fix to the 1.4.x versions (2201.2.x branch) as well.
