### ISSUE TITLE
[Bug]: Complex passwords from Config.toml  are not working with the http client auth

### ISSUE THREAD

**Issue by jdchathuranga** [ballerina-platform/ballerina-standard-library#3549]
### Description

We are getting some configs from the Config.toml as configurable, but if we add a complex password, (example `Ef2%I1^@Nd8>WTtcn+3=QL?M!{gG198h=lH4<ukg`), seems that OAuth client doesn't get it correctly.

At the receiving(in this case, ServiceNow) end we can't pinpoint whether it is missing the full password or part of it, but receiving end clearly says the issue is with the password.

### Steps to Reproduce

We have the following HTTP client definition,

Following implementation is in a module in the ballerina project.

```
configurable ApiConfiguration apiConfig = ?;

 final http:Client serviceNowClient = check new(apiConfig.snBaseUrl, auth = {
    username: apiConfig.username,
    password: apiConfig.password,
    clientId: apiConfig.clientId,
    clientSecret: apiConfig.clientSecret,
    tokenUrl: apiConfig.tokenUrl,
    refreshConfig: {
            refreshUrl: apiConfig.tokenUrl
    }
 });
```

configurable definition,

```
public type ApiConfiguration record {|
 string tokenUrl;
 string username;
 string password;
 string clientId;
 string clientSecret;
 string snBaseUrl;
 string snApiPath;
|};
```
Config.toml sample,
```
[org.name.module]
[org.name.module.apiConfig]
 tokenUrl = "token_url"
 username = "user"
 password = "Ef2%I1^@Nd8>WTtcn+3=QL?M!{gG198h=lH4<ukg"
 clientId = "client_id"
 clientSecret = "client_secret"
 snBaseUrl = "base_url"
 snApiPath = "path_to_resource"
```

### Affected Version(s)

2201.1.1

### Related area

-> Standard Library

**Comment by dilanSachi** [comment]
Tested this with WSO2 IS docker and looks like the special characters are not encoded correctly when sending the request.
When the above password is encoded using `URLEncoder`, it connects successfully to the server.

**Comment by dilanSachi** [comment]
Could not exactly find anything in a spec related to encoding the passwords. However, found a discussion similar to this [1].
@MohamedSabthar what do you think about this?

[1] https://github.com/jhipster/generator-jhipster/pull/1835

**Comment by MohamedSabthar** [comment]
@jdchathuranga are you using WSO2 identity server as you STS ?

**Comment by jdchathuranga** [comment]
We found this particular issue when trying to make an authenticated API call to service now. I have included a sample code in the as well.

**Comment by dilanSachi** [comment]
Had a discussion on this with @MohamedSabthar. We think this is because we don't encode password and username separately when sending the reqeust in oauth2. Hence this will need to be fixed in oauth2 module. Ill attach the relevant oauth2 issue here.

Issue - https://github.com/ballerina-platform/ballerina-standard-library/issues/4110

**Comment by chamil321** [comment]
@MohamedSabthar Can you link the PR of the fix and close the issue?

**Comment by MohamedSabthar** [comment]
Fixed with: https://github.com/ballerina-platform/module-ballerina-oauth2/pull/915
