### ISSUE TITLE
Update load-test workflows

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#3555]
**Description:**
1. GitHub is deprecating set-output commands from GitHub actions (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). The alternative is to use environment files (https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files)

2. Change the time of each load-test to reduce the queuing of load-tests

**Comment by niveathika** [comment]
@dilanSachi Lets also verify if the load test results folder is ignored in build workflow

**Comment by dilanSachi** [comment]
This task is completed now
