### ISSUE TITLE
[persist] Improve advanced filter query support

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3566]
**Description:**
The following improvements can be done for the above feature

Diagnostics that can be added,
- [x] Add error diagnostics when users use `execute` function
- [x] Add warning diagnostics when `read` function is used outside the scope of query clause
- [x] Add validations for unsupported scenarios in the  query syntax
       - Using variables in limit clause
       - Using variables in order by clause
       - Unsupported expressions in where clause

Validations for query modification
- [x] Validate the `read()` function is called from persist clients before modification

Debugging experience 
- [ ] Improve debugging experience with modifiers
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/3678

**Comment by niveathika** [comment]
The current status of this task is,

**Validations for query modification**
This is done for clients with assigned types. This will not work if the client is assigned to a Type Reference type.

**Diagnostics**
Currently the diagnostics are applied blindly. i.e. `read()` function not optimised warning will be given to any remote `read()` function. This cannot be isolated to only generated persist clients due to,
1. Analysis is done on syntax level, thus the invocation of read() function is just a token at this point. There is no way to identify the client type
2. Even if variables of persist clients can be identified through modifier analysis. This cannot be applied in a final analysis task due to restriction in modifier - Analysis task order is not guaranteed(https://github.com/ballerina-platform/ballerina-lang/issues/38731). Thus it is impossible to add this custom validations

**Debugging experience**
There is no support for debugging for code modifiers. (https://github.com/ballerina-platform/ballerina-lang/issues/38678)

There is more confusion for persist read() query usage, as we need to remove nodes,
<img width="732" alt="Screenshot 2022-11-17 at 15 30 56" src="https://user-images.githubusercontent.com/27669465/202918595-a827abf4-d16a-4b18-a3d2-4a125259b3af.png">

<img width="943" alt="Screenshot 2022-11-17 at 15 31 15" src="https://user-images.githubusercontent.com/27669465/202918601-55c94227-9c53-4882-9c6a-591d1b05b7ca.png">

As seen in the above screen shots when user tries to debug the order by clause, select is stepped into. This can be further complicated if there are multiple queries. As a temporary workaround we can stop removing the filter nodes(where, limit, order by). Though this will reduce throughput of the query.

**Comment by niveathika** [comment]
This is deprioritised and this feature will be removed from phase 1.

**Comment by kalaiyarasiganeshalingam** [comment]
The summary of this task of phase 1 is,

This task is implemented to perform a query in the following format. If any clauses are missing in the `from' clause, those clauses are also omitted from the SQL query.

```
SELECT {COLOUMs’ NAME} FROM {TABLES} WHERE {CONDITIONS} GROUP BY {COLOUMS' NAME} ORDER BY {COLOUM NAME ASC/DESC, ... } LIMIT {VARIABLES} 
```

**Ballerina Query**
```ballerina 
entities:Product[] output = check from entities:Product e in mcClient->/products(targetType = entities:Product)
                order by e.name ascending, e.age descending
                limit 4
                where e.id == value || e.id == 6 || e.id == 7 || e.id != 1  && e.id >= 1 && e.id <= 20 && e.name == "Person2"
                group by var id3 = getValue(4), var name = e.name, var age = e.age
                select {id: id3, name: name , age: age};
```

**Equivalent SQL Query**

```
SELECT `Product`.`id` AS `id`,`Product`.`name` AS `name`,`Product`.`age` AS `age` FROM `Product` AS `Product` WHERE  id = 5  OR id = 6 OR id = 7 OR id <> 1 AND id >= 1 AND id <= 20 AND name = Person2 GROUP BY  id, name, age ORDER BY  name ASC , age DESC  LIMIT   4
```

**Ballerina query only has where clause**

```
entities:Product[] products4 = check from var e in mcClient->/products(targetType = entities:Product)
                where (e.id == value || e.id == 5) && e.id != 6
                select e;
```

**Equivalent SQL Query**

```
SELECT `Product`.`id` AS `id`,`Product`.`name` AS `name`,`Product`.`age` AS `age` FROM `Product` AS `Product` WHERE  ( id = 5  OR id = 5)  AND id <> 6
```

Here, the signature of the persist remote method call of the `from` clause will be modified to perform the above translation with the following parameter by the code modifier.

**Modified code for the above samples**

```ballerina
entities:Product[] output = check from entities:Product e in mcClient->/products(targetType = entities:Product, whereClause = ` id = ${value}  OR id = 6 OR id = 7 OR id <> 1 AND id >= 1 AND id <= 20 AND name = "Person2"`, orderByClause = ` name ASC , age DESC `, groupByClause = ` ${getValue(4)}, name, age`, limitClause = `  4`)
                        order by e.name ascending, e.age descending
                        limit 4
                        where e.id == value || e.id == 6 || e.id == 7 || e.id != 1  && e.id >= 1 && e.id <= 20 && e.name == "Person2"
                        group by var id3 = getValue(4), var name = e.name, var age = e.age
                        select {id: id3, name: name , age: age};

```

```ballerina
entities:Product[] products4 = check from var e in mcClient->/products(targetType = entities:Product, whereClause = ` ( id = ${value}  OR id = 5)  AND id <> 6`)
                        where (e.id == value || e.id == 5) && e.id != 6
                        select e;


```

Before the source modification, the following validations are used to find the appropriate query. 

- Validate whether the expression of the query is a client resource access node or not.
- Validate whether the expression of the query is a client resource access node or not.
- Validate whether the client is the persist client or not.
- Validate whether the resource path is valid or not with the model type name.
- Validate whether the method name is `get` or not.
- Validate whether the arguments present or not.
- If arguments are presented, validate the type and size of the arguments.
- Additionally, add the validation to make sure the `group by` clause is after the `where` and `order` clauses. Otherwise, the query will become complex.

The following situation returns diagnostic: 

- When a client resource access call has more than one argument such as `whereClause`, `limitClause`, `orderByClause` or `groupByClauses`.
- When `group by` clause is before the `where` clause or `order by` clause.

This implementation is also supported the function pointer in the clauses too. 

**Ballerina query**
```ballerina
entities:Product[] output = check from entities:Product e in mcClient->/products(targetType = entities:Product)
                order by getStringValue("name") ascending, e.age descending
                limit getValue(4)
                where e.id == value || e.id == 6 || e.id == 7 || e.id != 1  && e.id >= 1 && e.id <= 20 && e.name == getStringValue("Person2")
                group by var id3 = getValue(4), var name = e.name, var age = e.age
                select {id: id3, name: name , age: age};

function getValue(int value) returns int {
    return value;
}

function getStringValue(string value) returns string {
    return value;
}
```
**Equivalent SQL Query**
```
SELECT `Product`.`id` AS `id`,`Product`.`name` AS `name`,`Product`.`age` AS `age` FROM `Product` AS `Product` WHERE  id = 5  OR id = 6 OR id = 7 OR id <> 1 AND id >= 1 AND id <= 20 AND name = Person2  GROUP BY  4, name, age ORDER BY  name ASC , age DESC LIMIT  4
```
**Modified code for the above samples**
```ballerina
entities:Product[] output = check from entities:Product e in mcClient->/products(targetType = entities:Product, whereClause = ` id = ${value}  OR id = 6 OR id = 7 OR id <> 1 AND id >= 1 AND id <= 20 AND name = ${getStringValue("Person2")} `, orderByClause = ` ${getStringValue("name")} ASC , age DESC `, groupByClause = ` ${getValue(4)}, name, age`, limitClause = ` ${getValue(4)}`)
                    order by getStringValue("name") ascending, e.age descending
                    limit getValue(4)
                    where e.id == value || e.id == 6 || e.id == 7 || e.id != 1  && e.id >= 1 && e.id <= 20 && e.name == getStringValue("Person2")
                    group by var id3 = getValue(4), var name = e.name, var age = e.age
                    select {id: id3, name: name , age: age};

```

**Comment by kalaiyarasiganeshalingam** [comment]
Close this issue as this feature is added now.
