### ISSUE TITLE
Update XSLT processor to Saxon-HE in module-ballerina-xslt

### ISSUE THREAD

**Issue by sahanHe** [ballerina-platform/ballerina-standard-library#3568]
**Description:**
To support graalvm native-image, XSTL processor of ballerina XSLT library has to be changed to Saxon-HE version 11.4. 

**Describe your task(s)**
Add the saxon dependancy, change Java code and tests according to the new XSLT processor

**Related Issues (optional):**
[ballerina-standard-library/issues/3462](https://github.com/ballerina-platform/ballerina-standard-library/issues/3462)

**Comment by daneshk** [comment]
This task is done. Hence resolving
