### ISSUE TITLE
Observability context is not closed during the ResponseErrorInterceptor

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#3582]
**Description:**
> $subject and related to https://github.com/ballerina-platform/ballerina-lang/issues/38157

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
Closing this issue since the issue is fixed with the above referenced PRs
