### ISSUE TITLE
Remove SQL_901 diagnostic hint with Update 4 dependency

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3609]
**Description:**
Currently, the following HINT is added to the ERROR scenario.
```
_ = check charInOut.get();
```
```
ERROR: cannot infer type for parameter ''typeDesc''
HINT: parameter 'typeDesc' should be explicitly passed when the return data is ignored
```

With the Update 4 the error message is improved so that the message is more clear,
```
_ = check charInOut.get();
```
```
ERROR: cannot infer the ''typedesc'' argument for parameter ''typedesc'': expected an argument for the parameter or a contextually-expected type to infer the argument
```
With the improved error message the HINT is now obsolete and can be removed.

**Comment by anupama-pathirage** [comment]
Can we close the issue since all PRs are merged? This issue is moved to done column without closing the issue @niveathika

**Comment by niveathika** [comment]
We cannot merge the changes to the master branch, due to a constraint in `stdlib release workflow`. There is no way to configure the branch the release should be done.

Due to that reason this changes are kept in an upstream branch till the Update 3 releases are done. Since only syncing the change is remaining, I have moved this to done state. I will close this once the changes are merged to master

**Comment by niveathika** [comment]
Closing this as all changes are synced to master
