### ISSUE TITLE
Builds Hang Frequently in the GitHub Workflows

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#3610]
**Description:**
>$subject

Even though the build is not hanged in locally, it hangs in the GitHub workflow frequently.

![Screenshot from 2022-11-04 19-56-25](https://user-images.githubusercontent.com/35717653/199999781-c11acf16-73a9-42d5-b420-33f480ecf020.png)

**Comment by DimuthuMadushan** [comment]
It seems this happens frequently and caused load test failures as well. we need to resolve this ASAP.
![Screenshot from 2023-01-18 14-21-40](https://user-images.githubusercontent.com/35717653/213126517-d2689a33-5e94-4672-ac06-86b0a2009eed.png)

**Comment by ThisaruGuruge** [comment]
Closing as this is now completed. Re-open in case this happens again.
