### ISSUE TITLE
Migrate persist and persist-tools to Ballerina Update 4

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3611]
**Description:**
$subject

**Comment by anupama-pathirage** [comment]
Why this is moved to done with out PR? And still the issue is open even it is done in project board @niveathika

**Comment by niveathika** [comment]
We cannot merge the changes to the master branch, due to a constraint in `stdlib release workflow`. 

Due to that reason this changes are kept in an upstream branch till the Update 3 releases are done. Since only syncing the change is remaining, I have moved this to done state. I will close this once the changes are merged to master

**Comment by niveathika** [comment]
Closing this as changes are now synced to master
