### ISSUE TITLE
Build with bal test native workflow failing for graphql module

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#3634]
**Description:**
$Subject

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Workflow is falling in both windows and linux due to following issues
https://github.com/ballerina-platform/ballerina-lang/issues/38613
https://github.com/ballerina-platform/ballerina-lang/issues/38614

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Removing the bug label, since this is not a bug in the GraphQL package.

**Comment by ThisaruGuruge** [comment]
Closing as this is now fixed.
