### ISSUE TITLE
Define the persist annotations as const annotations

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#3635]
**Description:**

It seems that the annotations defined in the [module-ballerina-persist](https://github.com/ballerina-platform/module-ballerina-persist/blob/e663c4f2e190970ec0bbc9d8ffeecc051fe754c6/ballerina/annotation_types.bal#L29) are not const annotations. To generate the entity diagram in the `Application Architecture View` (vs-code), the values given in the annotations need to be accessed in the compiler time. Non-const annotations are unable to access in the compiler time. 

Is there a possibility to update these annotations to const annotations. 
@daneshk @hevayo @NipunaRanasinghe 

Please refer to the below examples. 

**Sample Ballerina code**

```bal
import ballerina/persist;
import ballerina/time;

@persist:Entity {
    key: ["userId"]
}
public type User record {
    readonly string userId;
    string name;
    string contactNo;
    string email;
    @persist:Relation {keyColumns: ["profileId"], reference: ["id"]}
    Profile profile;
};

@persist:Entity {
    key: ["userId"]
}
public type Kid record {
    *User;
    string level;
    @persist:Relation {keyColumns: ["guardianId"], reference: ["userId"]}
    Adult guardian;
};

@persist:Entity {
    key: ["userId"]
}
public type Adult record {
    *User;
    string occupation;
    string officeContactNo?;
};

@persist:Entity {
    key: ["id"]
}
public type Profile record {
    readonly string id;
    string username;
    time:Date createdDate;
    @persist:Relation {keyColumns: ["subscriptionId"], reference: ["id"]}
    MonthlySub subscription; // persist client does not support union types
};

@persist:Entity {
    key: ["id"]
}
type AnuualSub record {
    int id;
    int 'limit;
    float fee;
};

@persist:Entity {
    key: ["id"]
}
public type MonthlySub record {
    readonly int id;
    float fee; 
};
``` 

**Sample ER diagram**
![Er](https://user-images.githubusercontent.com/34091327/201061260-6791bd0c-67ad-45b3-ac54-7b075e073075.png)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
I have created another issue, discussing the language behaviour aspects of making the annotation const. The discussion can be moved to https://github.com/ballerina-platform/ballerina-standard-library/issues/3635
