### ISSUE TITLE
Add `persist db push` command tests related to one-to-one and one-to-many relations

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#3645]
**Description:**

$Subject

**Describe your task(s):**
Need to execute bal persist db push command and validate the metadata of the created tables corresponding to the entities including

- Table name
- Column names
- Column types
- Auto-increment
- Nullable
- Foreign keys

Related Issues (optional):
https://github.com/ballerina-platform/ballerina-standard-library/issues/3157

**Comment by daneshk** [comment]
This is related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3838. We will capture all the test scenarios related to the push and add test cases. Check the issue https://github.com/ballerina-platform/ballerina-standard-library/issues/3838 for the status
