### ISSUE TITLE
Request from the Browser is blocked by CORS

### ISSUE THREAD

**Issue by shayanmalinda** [ballerina-platform/ballerina-standard-library#3647]
**Description:**

I am getting following **intermittent** error when **local Ballerina Service** is called from the **Browser**.

```
Access to fetch at 'http://localhost:8090/app/users' from origin 'http://localhost:5001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

This issue will not occur when service is called from the **Postman**.
Also this issue will not occur when service is deployed in **Choreo**.

Only happens when **local ballerina service** is called through the **Browser**.

**Steps to reproduce:**

Tried to narrow down the root cause for this issue and identified this happens within the following `jwtDecode` function.

```
public isolated function jwtDecoder(string jwt) returns types:JwtRecord|error {
    [jwt:Header, jwt:Payload] [_, payload] = check jwt:decode(jwt);
    types:JwtPayload|error jwtPayload = payload.cloneWithType();
    string[] roles = [];
    string? email = ();
    if jwtPayload is types:JwtPayload {
        email = jwtPayload.email;
        roles = jwtPayload.groups;
    }
    if email is () {
        return error("Could not fetch email from JWT");
    } else {
        types:JwtRecord returnInfo = {
            email: email,
            roles: roles
        };
        return returnInfo;
    }
}
```

This function is called within the **Request Interceptor**

Below is the `ServiceConfig` I used.

```
@http:ServiceConfig {
    cors: {
        allowOrigins: ["http://localhost:5001/"],
        allowCredentials: false,
        allowHeaders: ["*"],
        allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        maxAge: 84900
    },
    interceptors: [jwtInterceptor]
}
```

**Suggested Assignees :**
@chamil321

**Comment by TharmiganK** [comment]
Closing this issue since the internal issue is closed. The reason for this behaviour is that the preflight option request is internally handled by a request interceptor. Ideally these requests are handled internally, so overriding this behaviour caused some unexpected errors
