### ISSUE TITLE
Update CLI tools for the persist module according to design changes

### ISSUE THREAD

**Issue by sahanHe** [ballerina-platform/ballerina-standard-library#3663]
**Description:**
Functionalities of the CLI tools has to be updated according to the design changes and this task was created to track the progress.

Following are the required changes in the CLI tools,

`bal persist init`
- `Persist.toml` file is generated inside Persist subdirectory containing place holders to database configurations.
- Generate the `database_configuration.bal` file in init command instead of the generate command.
- Add database driver as a import to `database_configuration.bal` instead of a dependancy in `Ballerina.toml`
- Call Generate command to generate clients if there are any entities present inside the project.

`bal persist generate`
- Remove the `database_configuration.bal` generation step from the generate step.

`bal persist db push`
- Add functionality to check the local cache to resolve the jdbc driver dependancy.
- Migrate the functionality to generate the SQL schema to the db push command from the compiler plugin
- Add functionality to read the database configuration from the placeholders in Persist.toml file

## Checklist
- [ ] persist init
- [ ] persist generate
- [ ] persist db push

**Comment by niveathika** [comment]
@sahanHe Could you give more description on what are the changes we are doing here?

**Comment by sahanHe** [comment]
> @sahanHe Could you give more description on what are the changes we are doing here?

Updated the issue to include more description

**Comment by daneshk** [comment]
Find the latest requirement in #3724

**Comment by daneshk** [comment]
Closing this issue as requirements changed. Please refer https://github.com/ballerina-platform/ballerina-standard-library/issues/3724 to track the latest changes
