### ISSUE TITLE
Make the persist annotations constants

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3675]
**Description:**
Currently, persist module consist of 3 annotations,
```ballerina
@persist:Entity
@persist:AutoIncrement
@persist:Relation
```

These annotations must be resolved at compile time and not at runtime. For instance the annotation attachment,
```ballerina
string[] keyArray = ["needId"];

@persist:Entity {
    key: keyArray
}
public type MedicalNeed record {|
    readonly int needId = 1;
    int? itemId;
    int beneficiaryId;
    string period;
    string urgency;
    int quantity;
|};
```

The above should not be valid as the keys must be defined and processed at compile time.

The above requirement can be achieved by making the annotation constant,
```
public const annotation EntityConfig Entity on type;
```

This has additional value sine this will make tooling experience much cleaner(Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3635)

**Comment by niveathika** [comment]
When looking into this aspect, I found that annotation with array type fields cannot be made constant. This is valid even if user defines in-line array as such,
```
@persist:Entity {
    key: ["needId"]
}
```

@MaryamZi Is there any workaround for this?

**Comment by MaryamZi** [comment]
> When looking into this aspect, I found that annotation with array type fields cannot be made constant. This is valid even if user defines in-line array as such,
> 
> ```
> @persist:Entity {
>     key: ["needId"]
> }
> ```

Please create a lang issue for this. Right now, we only support a limited set of constant expressions. For annotations though, we allow some extra expressions with source-only annotations. We should be able to do the same with non-source const annotations.

> 
> @MaryamZi Is there any workaround for this?

Are these annotations required at runtime too? If not, you could make this a source-only annotation as a workaround for now.

```ballerina
public const annotation EntityConfig Entity on source type;
```

**Comment by niveathika** [comment]
After trying out source annotation, I found a blocker https://github.com/ballerina-platform/ballerina-lang/issues/38743

Pausing this effort till the 2201.3.0-rc3 is released with the fix

**Comment by niveathika** [comment]
After testing on RC3 pack the final conclusions are,

1. All persist annotations can be defined as source annotation.  source annotation are only read at compile time. This matches with the persist module use case.
2. Further validation we have to do is not support referring const variables in annotation declaration. This should be a custom restriction for persist module on top of Conclusion 1. This is because these values are used for client generation and not available at syntax tree when generated clients, thus cannot be processed.

**Comment by niveathika** [comment]
This is on hold due to persist module design V2

**Comment by niveathika** [comment]
This can be an issue when we support constraint annotation. https://github.com/ballerina-platform/ballerina-standard-library/issues/3360

Constraint usecase has to be looked into.
