### ISSUE TITLE
Enable database transaction logs for persist module usage

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3678]
**Description:**
Currently, all the database queries are constructed in Generic Persist Client. There is no way for the user to identify the queries except from database logs. This experience can be improved by adding debug logs to all generated persist client functions. 

These can be enabled through Config.toml and allow user to debug,
1. Error cases
2. Performance issues

**Comment by kalaiyarasiganeshalingam** [comment]
Close this issue as this feature is added now.
