### ISSUE TITLE
Improvements to persist annotations

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3683]
**Description:**
1. Both `persist:Relation` and `persist:AutoIncrement` can be added to records without `persist:Entity`
2. Even if `persit:Entity` annotation is not present this is taken into validation for duplicate records

**Comment by kalaiyarasiganeshalingam** [comment]
The existing implementation allow `persist:Relation` without `persist:Entity`. 
```ballerina
import ballerina/persist;

public type Profile record  {|
    readonly int id;
    string name;
    @persist:Relation {keyColumns: ["userId"], reference: ["id"]}
    MultipleAssociations user?;
|};

public type MultipleAssociations record {|
    readonly int id;
    string name;
|};
```
But `persist:AutoIncrement` is related to the primary key. `persit:Entity` must be added to add primary key. Therefore, restricted by the current implementation.

**Comment by niveathika** [comment]
IMO  this is valid only if both records are marked as `persist:Entity`.

Also the same for AutoIncrement.

Looping in @kaneeldias for clarifications

**Comment by kaneeldias** [comment]
> IMO this is valid only if both records are marked as `persist:Entity`.
> 
> Also the same for AutoIncrement.
> 
> Looping in @kaneeldias for clarifications

+1 both `@persist:Entity` and `@persist:AutoIncrement` should be allowed only inside records marked with `@persist:Entity`

**Comment by kalaiyarasiganeshalingam** [comment]
Closing this issue as this is fixed now.
