### ISSUE TITLE
Stop the native level logs from appearing in FTP, Kafka

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#3698]
**Description:**
Need to stop logs like these from appearing,
```
Nov 23, 2022 8:26:15 AM org.apache.kafka.common.config.AbstractConfig logAll
INFO: ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9093]
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
	client.id = consumer-group-id-q901r-1
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = group-id-q901r
	group.instance.id = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	internal.throw.on.fetch.stable.offset.unsupported = false
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2

```

**Comment by dilanSachi** [comment]
FTP logs are removed in the above tagged PR.

**Comment by dilanSachi** [comment]
In java kafka client, when a broker is not available, the producer/consumer does not throw an error. Instead it logs a warning on the console as follows.
```
[Tue Nov 29 15:13:20 IST 2022] WARNING: org.apache.kafka.clients.NetworkClient processDisconnection - [Consumer clientId=consumer-order-group-id-1, groupId=order-group-id] Connection to node -1 (localhost/127.0.0.1:9098) could not be established. Broker may not be available. 
[Tue Nov 29 15:13:20 IST 2022] WARNING: org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater handleServerDisconnect - [Consumer clientId=consumer-order-group-id-1, groupId=order-group-id] Bootstrap broker localhost:9098 (id: -1 rack: null) disconnected
```
```
[Tue Nov 29 15:36:03 IST 2022] WARNING: org.apache.kafka.clients.NetworkClient processDisconnection - [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:9098) could not be established. Broker may not be available. 
[Tue Nov 29 15:36:03 IST 2022] WARNING: org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater handleServerDisconnect - [Producer clientId=producer-1] Bootstrap broker localhost:9098 (id: -1 rack: null) disconnected
```
If these native logs are removed, user doesnt have a way to identify whether the broker is down since the console will be empty.
Therefore, IMO, we need to add a way to log logs in ballerina side before removing these native logs.

WDYT? @shafreenAnfar @aashikam

**Comment by aashikam** [comment]
Hmm...I don't think removing the logs altogether is a good idea. As you said maybe presenting them differently from ballerina side would be nice. (although not sure if this is possible). If the broker is not available does it retry and timeout?

**Comment by dilanSachi** [comment]
It doesn't. It retries from time to time according to the `retryBackoff` config.

One option is to tweak the log output so that it doesnt show `org.apache.kafka.clients.NetworkClient` part in the log.

```
WARNING: [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:9099) could not be established. Broker may not be available. 
WARNING: [Producer clientId=producer-1] Bootstrap broker localhost:9099 (id: -1 rack: null) disconnected
```

**Comment by aashikam** [comment]
Doesn't ballerina program exit while the java connection retries to connect? 
 
> One option is to tweak the log output so that it doesnt show `org.apache.kafka.clients.NetworkClient` part in the log.

Yeah that would be nice. Will be some work though.

**Comment by dilanSachi** [comment]
> Doesn't ballerina program exit while the java connection retries to connect?

Nope

> Yeah that would be nice. Will be some work though.

We can edit the logs easily using the logging configuration. But that way, the logging configs will be hardcoded. I think we will have to add a way for the users to stop the logs if they want. We may have to add a way similar to trace logs in grpc [1]

[1] https://github.com/ballerina-platform/module-ballerina-grpc/pull/413/files

**Comment by dilanSachi** [comment]
Sorry missed the timeout part.
> If the broker is not available does it retry and timeout?

It eventually timesout

**Comment by dilanSachi** [comment]
Closing this task since this is completed now
