### ISSUE TITLE
Check GraalVM native support in Ballerina external modules

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3702]
**Description:**
$Subject

**Describe your task(s)**

The following modules should be checked with GraalVM native support

1. Observability modules
    - [x] [ballerinax/jaeger](https://github.com/ballerina-platform/module-ballerinax-jaeger)
    - [x] [ballerinax/prometheus](https://github.com/ballerina-platform/module-ballerinax-prometheus)

2. Database modules
    - [x] [ballerinax/mysql](https://github.com/ballerina-platform/module-ballerinax-mysql)
    - [x] [ballerinax/mssql](https://github.com/ballerina-platform/module-ballerinax-mssql)
    - [x] [ballerinax/oracledb](https://github.com/ballerina-platform/module-ballerinax-oracledb)
    - [x] [ballerinax/postgresql](https://github.com/ballerina-platform/module-ballerinax-postgresql)
    - [x] [ballerinax/java.jdbc](https://github.com/ballerina-platform/module-ballerinax-java.jdbc)
    - [x] [ballerinax/redis](https://github.com/ballerina-platform/module-ballerinax-redis) (Tracked via https://github.com/wso2-enterprise/choreo/issues/16729)

2. Database drivers (Tracked via https://github.com/ballerina-platform/ballerina-standard-library/issues/3692)

**Comment by niveathika** [comment]
Driver support is tracked in https://github.com/ballerina-platform/ballerina-standard-library/issues/3692

**Comment by TharmiganK** [comment]
> Driver support is tracked in #3692

Ack

**Comment by TharmiganK** [comment]
The GraalVM native support for `ballerinax/prometheus` is blocked due to this [issue](https://github.com/ballerina-platform/ballerina-lang/issues/38968).

**Comment by TharmiganK** [comment]
All the external modules are now GraalVM compatible
