### ISSUE TITLE
Major revamp of the documentation is needed

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3712]
**Description:**
1. 
<img width="393" alt="Screenshot 2022-11-26 at 16 33 18" src="https://user-images.githubusercontent.com/27669465/204085486-9dd05b99-ed46-42cc-8e58-8b9ae66a4335.png">
Unnecessary annotation for xml to record

2. Does not mention if xml element contains a prefix, this should be available in the record field name.
<img width="844" alt="Screenshot 2022-11-26 at 16 34 37" src="https://user-images.githubusercontent.com/27669465/204085530-449c43ba-5e2e-4807-8f7f-c96d3d82f98c.png">

3. What does this even mean?
<img width="844" alt="Screenshot 2022-11-26 at 16 35 33" src="https://user-images.githubusercontent.com/27669465/204085553-b5a189e1-4eb8-4350-99e5-511c04c75a7a.png">

4. It is not mentioned if the annotations are used for which APIs.
    Namespace is only used for writes.
    Attribute for both writes and reads    
   Name not even clear when this can be used

**Comment by kalaiyarasiganeshalingam** [comment]
The answer
Q1: Annotation is needed to find the value of the namespace and attribute in the record. Here, the status value will be added if add attribute annotation. Otherwise, it will return the error.
```
import ballerina/io;
import ballerina/xmldata;

type Invoice record {|
    int id;
    @xmldata:Attribute
    string 'xmlns?;
    string status;
|};

public function main() returns error? {
    xml data = xml `<ns:Invoice xmlns="example.com"
                        xmlns:ns="http://sdf.com" status="paid">
                        <id>1</id>
                    </ns:Invoice>`;
    Invoice output = check xmldata:fromXml(data);
    io:println(output);
}
```
2. Fixed. https://github.com/ballerina-platform/module-ballerina-xmldata/pull/470/files#diff-ecda4f4acb566335c5b8a6598ba4ffc0002c3cf114c6867b20c16bb26d67780bR388
3. Fixed. https://github.com/ballerina-platform/module-ballerina-xmldata/pull/470/files#diff-ecda4f4acb566335c5b8a6598ba4ffc0002c3cf114c6867b20c16bb26d67780bR26 
4. All annotations are used for reading and writing. Therefore, not specified.
    Found the following issue when adding the annotation:
    https://github.com/ballerina-platform/ballerina-standard-library/issues/3802
    https://github.com/ballerina-platform/ballerina-standard-library/issues/4036

**Comment by niveathika** [comment]
Is `Namespace` annotation needed for the xml to record transformation? 

IMO there is no need for the user to filter/validate the xml in this API. We just have to give the required values to records dont we?

**Comment by kalaiyarasiganeshalingam** [comment]
Yes. `Namespace` annotation can be added. 
Prefix and URI are validated with XML values if add the namespace annotation in the record.

**Comment by niveathika** [comment]
Shall we add this here? IMO validation is an additional feature on top of conversion.
https://github.com/ballerina-platform/module-ballerina-xmldata/blob/master/ballerina/xmldata.bal#L44

Shall we run the documentation through Grammerly atleast?
https://github.com/ballerina-platform/module-ballerina-xmldata/blob/master/ballerina/xmldata.bal#L386
This is really convoluted.
```
# Converts an XML to its `Map` or `Record` representation.
# Additionally, when converting to a record, XML `namespaces` and `attributes` can be validated through `xmldata:Namespace` annotation.
```

Check for all API descriptions.

**Comment by kalaiyarasiganeshalingam** [comment]
Close this issue as updated the API in the https://github.com/ballerina-platform/module-ballerina-xmldata/pull/479
