### ISSUE TITLE
It is not clear from the API alone that fromXML can used to convert XML to record

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3713]
**Description:**
<img width="1033" alt="Screenshot 2022-11-26 at 16 40 05" src="https://user-images.githubusercontent.com/27669465/204085743-9ddea7d3-abd6-4c05-b25f-1ce0e74d829b.png">

This implies this API can only used to convert XML to map<anydata>. Not to a record, typesdes<map<anydata>|record {}> will be much more user friendly.

**Comment by kalaiyarasiganeshalingam** [comment]
Since record is a subtype of map<anydata>, changing types to <map<anydata>|record {}> may cause confusion. So, I have included the `record` in the description.
