### ISSUE TITLE
Creating schema for specific database in postgresql script

### ISSUE THREAD

**Issue by Akshay-De-Silva** [ballerina-platform/ballerina-standard-library#3722]
**Description:**
Figure out a method to get a newly created schema to fall under a specific database for testing.

@daneshk

**Comment by niveathika** [comment]
@Akshay-De-Silva Is this valid anymore?

**Comment by Akshay-De-Silva** [comment]
> @Akshay-De-Silva Is this valid anymore?

Apologies I didn't see this message, We can close this issue :+1:
