### ISSUE TITLE
[Design] Ballerina Persistance tooling changes with generated modules

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3724]
**Description:**
This task is to discuss changes we need to make in persistent CLI tooling to align with the generated module feature. Currently, we are generating all clients inside the `clients` submodule that needs to change along with the project API feature.

related spec issue: https://github.com/ballerina-platform/ballerina-spec/issues/1179

**Comment by daneshk** [comment]
The following things get invalid once we have the `generated` directory support.

1. Create the `clients` submodule when initializing the persistence support.
2. Add configurable variables inside the `clients` submodule and refer them in both the `Config.toml` file and the `Persist.toml` file.
3. Copy Entities into the `clients` submodule.
4. Add all generated clients to the `clients` submodule.

**Comment by daneshk** [comment]
One option is to lock defining entities to one module(either default/root module or sub module). We need to do this when initializing the persistence in the Ballerina project. There are few user scenarios to address with possible actions,

1. User already defined entities inside the Ballerina project. Entities are defined in a single module(either default/root module or sub module)
   - Discover the module in which the user define entities and lock the module for entity definitions.
   - Generate clients and `database-configuration.bal` file under the same module inside the `generated` directory.
   - Update `Config.toml` and `Persist.toml` files
2. User already defined entities inside the Ballerina project. But entities are defined in two or more module.
   - Discover modules in which the user define entities and stop execution by returning an error. 
3. User don't define any entities inside the Ballerina project and no intention to define entities in a separate module.
   - Lock the default/root module for entity definitions
   - Generate `database-configuration.bal` file inside the `generated` directory.
   - Update `Config.toml` and `Persist.toml` files
4. User don't define any entities inside the Ballerina project, but he/she wants to define entities in a separate module.
   - Provide argument to specify the module in which they need to define entities like, `bal persist init --module foo`
   - Verify there is no entities defined already.
   - Create a sub-module and directory inside `generated` directory.
   - Generate `database-configuration.bal` file inside the `generated` directory.
   - Update `Config.toml` and `Persist.toml` files

**Comment by daneshk** [comment]
**Why we need to lock to a single module**

- We need to keep configurable variables within the module to avoid cyclic dependency.
  - Let's say we define configurable variables in the root module and define entities in a sub module. The generated clients are also generated within the sub module(inside `generated` directory). In order to access configurable variables from the generated clients, we need to import root module in the sub module. When we are going to use generated client in the root module, we get cyclic dependency.
- We need to keep the same db configuration for every sub module that define entities.

**Comment by daneshk** [comment]
**How we can lock the module**

One option is to maintain separate lock file `persist_lock.toml` inside the persist directory, with the following configs,

```
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "mysql"
module = "foo"
```

Once we do persist init, we discover the module which contains entities or set the default package if there is no entity defined. We only look into that module in the generate and push commands. We are not considering any entities defined outside the module.

**Comment by sameerajayasoma** [comment]
Let's address the provider lock when we are designing the migrations feature. 

But I don't think we should lock a particular module. Users should be able to freely move everything (db_connections.bal, entities, and generated clients) to any module of their choice. Bal persist tool needs to verify whether everything is in one module.  

Why do you think that we should lock a module?

**Comment by daneshk** [comment]
> Why do you think that we should lock a module?

We have to do most of the tasks we do in the `init` command, both in `generate` and `push`. If the user moves entities to another module after the `init` command, the following tasks need to redo

* Discover the module in which the user defines entities.
* Generate clients and `database-configuration.bal` file under the same module inside the generated directory.
* Remove any existing modules which are created in the `init` command inside the `generate` directory.
* Update Config.toml and Persist.toml files.

we only need the `init` command to get the provider. all those tasks are redone at the `generate` and `push` commands.

**Comment by daneshk** [comment]
With the proposed design, The user can change the module by reinitializing the persistence layer. by deleting the persist directory in the package and executing the `init` command.

**Comment by daneshk** [comment]
If we can get at least configurable variables defined in the root module, visible to submodules without importing the root module. all our limitations are solved, and we don't need to lock entities to a single module.

**Comment by daneshk** [comment]
As per the offline chat, we decided to go without locking the module name at persist init. Below is the suggested approach.

In the initial phase, we support 03 CLI commands for init, generate and push.

* `bal persist init`
   * Check whether the user is already defined entities. If so, discover the module in which the user defines entities.
   * Check whether the user is defined entities in multiple modules. If so, give an error. if not, get the module that defined entities as the entity module.
   * If no entities are defined, set the default/root module as the entity module.
   * Generate a directory corresponding to the entity module and add `database-configuration.bal` with configurable variables.
   * If entities are defined, Generate clients inside the module directory in the generated directory.
   * Add/Update the `Config.toml` file with the necessary config parameters.
   * Generate persist directory with the `Persist.toml` file.

* `bal persist generate`

   * Check all the entities defined in the project.
   * Check whether the user is defined entities in multiple modules. If so, give an error. if not, get the module that defined entities as the entity module.
   * If the module directory is already created inside the `generated` directory, regenerate the clients for the entities. 
   * If the module directory doesn't exist (this happens when entities are moved to another module after persist init), Generate a directory corresponding to the entity module and add `database-configuration.bal` with configurable variables, and generate clients.

* `bal persist push`
   
   * Check all the entities defined in the project.
   * Check whether the user is defined entities in multiple modules. If so, give an error. if not, get the module that defined entities as the entity module.
   * Generate the SQL schema for the entities and save it under the `persist` directory.


**Things to discuss**

* If entities are moved to another module after `persist init`, the generated configs in the `Config.toml` file are invalid now. Can we change it in `generate` and `push` commands? If we can have an interactive session, we can get the consent from the user to do a re-init. 
* If entities are moved to another module after `persist init` or `persist generate` commands, how do we cleanup already created modules and clients which are now invalid?

@sameerajayasoma @niveathika please share your thought? add any missing steps

**Comment by daneshk** [comment]
Create a separate issue to discuss what we do when user change the entity module https://github.com/ballerina-platform/ballerina-standard-library/issues/3764
