### ISSUE TITLE
Improve client tool constant generation code

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#3731]
**Description:**
Refer this comment https://github.com/ballerina-platform/module-ballerina-grpc/pull/1095#discussion_r1034627827

**Comment by rashmibharambe** [comment]
@dilanSachi , @keizer619 - I can pick this up. Please assign to me..

**Comment by dilanSachi** [comment]
Hi @rashmibharambe   🚀

We value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

- Understanding Ballerina Platform: Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)
- How to Contribute: Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- Learn Ballerina: If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)
- Get Help and Connect: Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!

Happy coding! 🎉

**Comment by dilanSachi** [comment]
@rashmibharambe   
Let me give you some context regarding this specific issue.

In Ballerina gRPC, we use the `protoc-tool`[1] to generate the ballerina files needed for the gRPC client and service. Earlier this tool was combined with the gRPC runtime in the `module-ballerina-grpc`, hence you see the above comment in that repo. What you have to do is follow the review comment and use a constant map instead of the switch case.

Also, if you want learn about gRPC and the protoc-tool you can follow these.
* https://ballerina.io/learn/by-example/grpc-service-simple/
* https://ballerina.io/learn/grpc-tool/

[1] https://github.com/ballerina-platform/protoc-tools

**Comment by rashmibharambe** [comment]
@dilanSachi I have raised PR please check and let me know if any comments. Thanks.

**Comment by dilanSachi** [comment]
@rashmibharambe Merged your PR. Great work and thanks for your contribution. You are always welcome to contribute to other existing issues.
