### ISSUE TITLE
Parsing Error: SQL type 'TIMESTAMP' cannot be mapped to Ballerina type time:Utc

### ISSUE THREAD

**Issue by yuk7hi** [ballerina-platform/ballerina-standard-library#3739]
**Description:**
Ballerina throws a parsing error when you try to map values from SQL `TIMESTAMP` columns to variable of type `time:Utc`.
N.B. This used to work fine in **Ballerina Swan Lake 2201.1.2 (Update 1)**

**Steps to reproduce:**
Consider the following MySQL table with `created_at` field of type TIMESTAMP.
| id        | created_at                  |
| -----: | ---------------------: |
| 1         | 2022-11-18 11:53:15  | 
| 2        | 2022-11-20 12:35:28 |

<br/>

In Ballerina, when you try to map the values in `created_at` column to a Ballerina field of type `time:Utc` as follows,
```ballerina
type TestDBResult record {|
    int id;
    time:Utc created_at; 
|};

sql:ParameterizedQuery query = `
    SELECT id, created_at
    FROM test_table`;

TestDBResult result = check dbClient->queryRow(query);
```

Ballerina throws the following error.
```
The field 'created_at' of type Utc cannot be mapped to the column 'created_at' of SQL type 'TIMESTAMP'
```

<br/>

**Affected Versions:**
Ballerina Swan Lake 2201.2.3 (Update 2)

**OS, DB, other environment details and versions:**
OS: MacOS Monterey
Database: MySQL 5.7.39

**Suggested Labels (optional):**
Type/Bug, module/sql

**Comment by yuk7hi** [comment]
Ref: This service used to run fine with the following implementation in Ballerina SL 2201.1.2 (Update 1)
- [DB mapping record](https://github.com/wso2-enterprise/internal-app-website-integrations/blob/994462e6b31a8eba8d959810ad1acc698d152c4d/resource-download-process/modules/database/types.bal#L28)
- [DB function](https://github.com/wso2-enterprise/internal-app-website-integrations/blob/994462e6b31a8eba8d959810ad1acc698d152c4d/resource-download-process/modules/database/download_request.bal#L20)

**Comment by niveathika** [comment]
@yuk7hi SW Update 2 consists of some breaking changes in behaviour. When migrating could you delete the Dependencies.toml file and rebuilt this again?

**Comment by yuk7hi** [comment]
@niveathika This was fixed by the suggested resolution. Thank you :)

**Comment by niveathika** [comment]
@yuk7hi It is great to hear that!
