### ISSUE TITLE
[HTTP][CircuitBreaker] Make it possible to specify thresholds per error type

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#375]
**Description:**
In the current Circuit Breaker, the type of error is not considered for the failure threshold. It would be useful to make it configurable in a more fine grained manner (i.e: make it possible to configure a threshold per error type).

**Suggested Labels (optional):**
Type/Feature

**Comment by shafreenAnfar** [comment]
Closing this as it is not high priority task. Please do feel free to reopen the issue if you come across the same requirement.
