### ISSUE TITLE
Revamp Persist entity annotations based on Design V2

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3765]
**Description:**
Based on the V2 design[1]. The following changes need to do,

- [ ] Remove all the fields in Entity Annotation. The new design doesn't have any fields in the Entity annotation
- [ ] Introduce new @Id field annotation, which has autogenerate field.
- [ ] Introduce new @unique annotation
- [ ] Update relation annotation. field names are changed. Check the referential actions.

1. https://docs.google.com/document/d/1uq3JKklYA9jQGR-BGSWNEI_oGbH1Bsz0HhP-ChHaQM0/edit#

**Comment by daneshk** [comment]
We need to make all annotations compile-time constants. Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3675

**Comment by daneshk** [comment]
Please refer to the V2 design document for the latest update.

**Comment by niveathika** [comment]
I have listed all the tasks needs for annotation revamp and plugin revamp based on annotation behaviour here, 
https://docs.google.com/spreadsheets/d/1JyrE5WDtWfFouC-bO_OutyOFkVLHI2JM54TthzGrayo/edit?usp=sharing

I will start working on the tasks.
