### ISSUE TITLE
Java dependencies have not been included with group id & artifact id in GRPC module

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-standard-library#3789]
**Description:**
Java dependencies should be included with group id and artifact id in order to check the version of the same dependency in two modules and pick the latest version. Otherwise it will give a warning message about the conflict.

In grpc module, some dependencies have been included without group id & artifact id and it has been led to conflict warning messages.

https://github.com/ballerina-platform/module-ballerina-grpc/blob/master/ballerina/Ballerina.toml#L38

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dilanSachi** [comment]
I was under the impressions this was needed only for Ballerina native jar dependencies.
This is the same way done in `http` as well.
https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/Ballerina.toml#L30

**Comment by dilanSachi** [comment]
Had an offline discussion with @azinneera.

We need to update the libraries that has a chance to be used in other libraries. To be on the safe side, we can update all the dependencies.
