### ISSUE TITLE
Error message in `FormatError` needs to be improved

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#3808]
Tried to convert a string to `time:Utc` and got the following error:

```
error {ballerina/time:2}FormatError ("Provided '2022-12-04T17:56:00+0500' is not adhere to the expected format '2007-12-03T10:15:30.00Z'")
```

The error message is misleading + needs to be refined. Misleading because it gives a sample timestamp as the expected format when it really should be mentioning the exact format the function expects. i.e., mention that a string in the RFC 3339 format is expected. 

From a perspective of how the message is phrased, maybe something like the following would be better:
```
Expected a value conforming to the RFC 3339 format, but found '2022-12-04T17:56:00+0500'
```
or
```
'2022-12-04T17:56:00+0500' is not in the RFC 3339 format
```

**Comment by sahanHe** [comment]
As we use the RFC 3339 UTC format, it might mislead the user if only the RFC 3339 format is mentioned. Thus, we changed the error message to `Provided '2022-12-04T17:56:00+0500' is not adhere to the expected RFC 3339 format '2007-12-03T10:15:30.00Z'` in [453](https://github.com/ballerina-platform/module-ballerina-time/pull/453)

**Comment by pubudu91** [comment]
Didn't get that. What do you mean by RFC 3339 UTC format? :thinking: And still need to fix how the message is phrased (grammar issues).

**Comment by sahanHe** [comment]
By RFC 3339 UTC format what I meant was the time expressed with 0 zone offset. For example, even though `2020-12-31T21:07:14-05:00` is in RFC 3339 format, we only accept the one defined in UTC/Zulu/GMT time which is `2021-01-01T02:07:14Z`. Let us check the error message again.
