### ISSUE TITLE
Identified gaps in persist annotation validations

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3822]
**Description:**
Following scenarios are not properly validated,
- [x] Duplicated fields in both Key and uniqueConstraints on Entity annotation
- [x] Empty values for fields in both Key and uniqueConstraints on Entity annotation mixed with valid ones
- [x] Empty unique constraints values are not validated, [], [[]]
- [x] Add validations for simple type fields defined as non mandatory field
- [x] Referred record w/o an entity:Relation -Validate persist:Relation is attached to a record without an entity annotation (ln: 528)

**Comment by kalaiyarasiganeshalingam** [comment]
@niveathika Skipped empty list validation of `key` and `unique constraints` as a table may not contain any keys. Should we check this?

**Comment by niveathika** [comment]
For key shouldn't it be an error? -> At this point we are not supporting tables w/o primary key. 
Unique Constraint: If there is no constraint user need not add the field. If they add it we have to assume there will be a constraint.
