### ISSUE TITLE
Add new testcase to cover all the cases in persist push command

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3838]
**Description:**
This is related to issues #3785 and #3811
We need to figure out all the scenarios for the `push` command covering all the edge cases based on the V2 design and write most test cases for them.

Let's come up with a list of the scenarios we need to cover and review them, and then add test cases for each of them.

**Comment by sahanHe** [comment]
Following is the list of the scenario that should be covered in `push` command

- [ ] The command is executed outside of a ballerina project
- [ ] The command is executed inside a project with syntax/semantic errors
- [ ] The command is executed inside a project where the database had to be created 
- [ ] The command is executed inside a project where the database is already there
- [ ] The command is executed inside a uninitialised project
- [ ] The command is executed inside a project where credentials are wrong
- [ ] The command is executed inside a project where database name contains illegal characters
- [ ] The command is executed inside a project where entities are changed and have to update the existing tables
- [ ] The command is executed for projects with one-one relations
- [ ] The command is executed for projects with one-many relationships
