### ISSUE TITLE
Add new testcase to cover all the cases in persist init command

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3839]
**Description:**
This is related to issues #3783 and #3811
We need to figure out all the scenarios for the `init` command covering all the edge cases based on the V2 design and write most test cases for them.

Let's come up with a list of the scenarios we need to cover and review them and then add test cases for each of them

**Comment by sahanHe** [comment]
Following is the list of the scenario that should be covered in `init` command

- [ ] Command is used outside of a ballerina project.
- [ ] Command is used inside a proper ballerina project(Without entities).
- [ ] Command is used inside a ballerina project with syntax/semantic errors.
- [ ] Command is used inside an already initialised project.
- [ ] Command is used inside a project with entities.
- [ ] Command is used inside a project with entities and clients.
- [ ] Command is used inside a project with entities and different clients.
- [ ] Command is used inside a project with entities defined in several places

**Comment by daneshk** [comment]
This task is addressed in https://github.com/ballerina-platform/persist-tools/pull/82. hence closing the issue
