### ISSUE TITLE
Add new testcase to cover all the cases in persist generate command

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3840]
**Description:**
This is related to issues #3784 and #3811
We need to figure out all the scenarios for the `generate` command covering all the edge cases based on the V2 design and write most test cases for them.

Let's come up with a list of the scenarios we need to cover and review them and then add test cases for each of them

**Comment by sahanHe** [comment]
Following is the list of the scenario that should be covered in `generate` command

General
- [ ] Run generate command outside of ballerina project.
- [ ] Run generate command inside a project with syntax/semantic errors
- [ ] Run generate command inside an uninitialised project.
- [ ] Run generate command inside a project without entities.
- [ ] Run generate command inside a project with all possible data types
- [ ] Run generate command inside a project with unsupported data types
- [ ] Run generate command inside a project with clients
- [ ] Run generate command inside a project with different clients
- [ ] Run generate command inside a project with comments in entity records
- [ ] Run generate command inside a project with entities defined in multiple places

One to One
- [ ] Run generate command inside a project with a pair of one-one related entities
- [ ]  Run generate command inside a project with a several of one-one related entities
- [ ]  Run generate command inside a project with a several of one-one related entities where entities act as both parent and child
- [ ]  Run generate command inside a project with a one-one related entities and comments

One to Many
- [ ] Run generate command inside a project with a pair of one-many related entities
- [ ] Run generate command inside a project with a several of one-many related entities
- [ ] Run generate command inside a project with a several of one-many related entities where entities act as both parent and child
- [ ]  Run generate command inside a project with a one-many related entities and comments

**Comment by daneshk** [comment]
Shall we also add scenarios with different field types?

**Comment by sahanHe** [comment]
> Shall we also add scenarios with different field types?
> 
> * supported basic field types
> * unsupported basic field types.
> * optional fields and optional value fields
> * record type fields (entity record and non-entity records)
> * union types, tuple types

First two scenarios were already there, I added the next three in to the checklist

**Comment by niveathika** [comment]
Closing as all tests are added
