### ISSUE TITLE
GraphQL compiler errors inconsistent with regular compiler errors

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#3854]
For example, this is a compiler error I got for a GraphQL service:
```
ERROR [test2.bal:(12:5,14:6)] Invalid GraphQL union type member. Only distinct service types are allowed
```
For compiler errors (including for compiler plugins provided by the Ballerina platform) the convention we have used is to start the message with a lower case letter. The above will look inconsistent, especially in the presence of other errors which adheres to the regular convention. e.g.,
```
ERROR [test2.bal:(12:5,14:6)] Invalid GraphQL union type member. Only distinct service types are allowed
ERROR [test2.bal:(6:42,6:43)] invalid resource parameter type: future<int>
```

**Comment by MohamedSabthar** [comment]
Completed via [#1149](https://github.com/ballerina-platform/module-ballerina-graphql/pull/1149)
