### ISSUE TITLE
Duplicate error messages reported

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#3855]
Consider the following:
```ballerina
service /gql on new graphql:Listener(4000) {
    resource function get greet () returns Greeting|Error {
        return error Error("Request failed", error("ERROR1", error("ERROR2")));
    }
}

type Greeting record {|
   string msg = "Hello World!"; 
|};

type Error error;
```
Getting the following errors for the above:
```
ERROR [test2.bal:(12:5,14:6)] Invalid GraphQL union type member. Only distinct service types are allowed
ERROR [test2.bal:(12:5,14:6)] Invalid GraphQL union type member. Only distinct service types are allowed
```
If the intention was to give the error message to each individual union member in the return type, it'd be better if that can be explicitly mentioned. e.g.,
```
union type member expected to be a distinct service type, but found 'Greeting'
union type member expected to be a distinct service type, but found 'Error'
```
Also, the diagnostic locations for the error messages need to be more precise. The above error messages are given to the whole resource method (`12:5 to 14:6`). These need to give the location of the relevant union type member. For example, for `Greeting`, it should be `12:44, 12:52` in the above case.

**Comment by MohamedSabthar** [comment]
The error messages are already improved with this PR: https://github.com/ballerina-platform/module-ballerina-graphql/pull/936

The mentioned program will return the following errors:
 ```
ERROR [err.bal:(5:5,7:6)] Invalid GraphQL union type member `Greeting` found. Only distinct service types are allowed
ERROR [err.bal:(5:5,7:6)] Invalid GraphQL union type member `Error` found. Only distinct service types are allowed
```
Issue related to error location already tracked via https://github.com/ballerina-platform/ballerina-standard-library/issues/2450
