### ISSUE TITLE
Improve API docs based on Best practices

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3857]
**Description:**
For instance, a client should be kept open throughout the entitreity of the application, this can be indicated as a note in both Module/Package md as well as [function description](https://lib.ballerina.io/ballerinax/mysql/1.6.1/clients/Client#close).

Likewise all recommendations must be indicated from the API docs, https://stackoverflow.com/collectives/wso2/articles/74843098/guidelines-and-best-practices-for-ballerina-sql-client-usages

**Comment by niveathika** [comment]
This should be fixed in both 3.x and master branch.

@kalaiyarasiganeshalingam Could you send the fixes for one module first, once its approved we can add it to all other connectors.

**Comment by kalaiyarasiganeshalingam** [comment]
Closing this issue as all DB docs were updated.
