### ISSUE TITLE
[gRPC] Ballerina client cannot send error messages in streaming scenarios

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#386]
**Description:**
In gRPC client/bidirectional streaming scenarios, the client should be able to close the connection in the middle of the operation by sending an error message to the server. In Ballerina, we provide an API to send Error on the client-side. but when the user sends an error message, that message sends as a LastHttpContent message at the transport level. So on the server-side, it is a normal connection closer. 

Normally we need to send `RSTFrame` from the client-side, but in Ballerina, we don't have the way to do it.

Check the possibility of implementing it.

**Comment by dilanSachi** [comment]
For now, we can use a RST Frame to reset the stream from client's side using the functionality in `http` [1]. In this instance, let's say a user calls the `streamClient->receiveData()` after calling `streamClient->sendError(...)`. What should be the expected response in this instance?
@daneshk @BuddhiWathsala any thoughts?

[1] https://github.com/ballerina-platform/module-ballerina-http/blob/f4c122d73adc03d118087330c95cda015b0567c8/native/src/main/java/io/ballerina/stdlib/http/transport/contractimpl/sender/http2/Http2TargetHandler.java#L80

**Comment by daneshk** [comment]
> For now, we can use a RST Frame to reset the stream from client's side using the functionality in `http` [1]. In this instance, let's say a user calls the `streamClient->receiveData()` after calling `streamClient->sendError(...)`. What should be the expected response in this instance?
> @daneshk @BuddhiWathsala any thoughts?

`streamClient->receiveData()` should return an connection already closed error.
> 
> [1] https://github.com/ballerina-platform/module-ballerina-http/blob/f4c122d73adc03d118087330c95cda015b0567c8/native/src/main/java/io/ballerina/stdlib/http/transport/contractimpl/sender/http2/Http2TargetHandler.java#L80
