### ISSUE TITLE
Remove unnecessary warnings in the native build after netty version update

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3861]
**Description:**

Due to the recent [update of the `netty` version](https://github.com/ballerina-platform/module-ballerina-http/pull/1366) in the `http` module, the following warnings are printed when executing the `bal build --native` command.

1. Warnings from the GraalVM:
```
Warning: Could not register io.netty.handler.proxy.Socks5ProxyHandler: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: io/netty/handler/codec/socksx/v5/Socks5InitialRequest.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
```

2. Warning from netty during the `Performance analysis` step :
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/user/Documents/GraalVM/ballerina-bbes/http-bbes/01-REST-API/01-service-path-and-resource-path/target/bin/service_path_and_resource_path.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The first one is printed because of [the native image reflection configs which are added to the above netty version](https://github.com/netty/netty/pull/12951).  The [same issue](https://github.com/quarkusio/quarkus/issues/29413) was there in Quarkus. And as a solution they have excluded those reflection configs during the build.

The second one is related to some netty level logs.

**Describe your task(s)**

- Need to add a similar fix like Quarkus for fist set of warnings since they are unnecessary.
- Need to check if there is a way to disable the netty logs during the analysis

**Comment by TharmiganK** [comment]
These warnings are resolved by removing those reflection configs. The following directives should be passed along with the `native-image` build command :
```
--exclude-config target/bin/*.jar /META-INF/native-image/io.netty/netty-handler/generated/handlers/reflect-config.json 
--exclude-config target/bin/*.jar /META-INF/native-image/io.netty/netty-handler-proxy/generated/handlers/reflect-config.json
--exclude-config target/bin/*.jar /META-INF/native-image/io.netty/netty-codec/generated/handlers/reflect-config.json
```

With the latest version of GraalVM,[ adding these from the module level `native-properties.json` is not possible.](https://github.com/oracle/graal/pull/3749#issuecomment-1144961962) So these should be added from `bal build --native` build tool.

**Comment by TharmiganK** [comment]
Another workaround is adding the following dependencies(which are unnecessary) in http module. This resolved the warnings :
```
io.netty:netty-codec-socks:4.1.86-Final
net.jpountz.lz4:lz4:1.3.0
org.jboss.marshalling:jboss-marshalling:2.0.5.Final
com.google.protobuf:protobuf-java:2.6.1
```

But still getting this warning at `Performing analysis` step of the native build :
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/user/Documents/GraalVM/ballerina-bbes/http-bbes/01-REST-API/01-service-path-and-resource-path/target/bin/service_path_and_resource_path.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by chamil321** [comment]
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/user/Documents/GraalVM/ballerina-bbes/http-bbes/01-REST-API/01-service-path-and-resource-path/target/bin/service_path_and_resource_path.jar) to constructor java.nio.DirectByteBuffer(long,int)
> WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

The ideal and the easy solution would be update the build tool with configs to remove those reflection configs. Otherwise adding unnecessary dependencies to fix this problem is complex as it should be done to all Netty dependent modules and still there will be warning as mentioned above.

**Comment by TharmiganK** [comment]
To resolve the netty-level warning at `Performing analysis` step of the native build, we may use a GraalVM Feature class like [this](https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/graal/DisableLoggingFeature.java), which is used in quarks to change log level during the native build.
I'll check the feasibility of adding this to http-native

**Comment by TharmiganK** [comment]
I have tried to add a GraalVM Feature class in http to resolve the following log:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/user/Documents/GraalVM/ballerina-bbes/http-bbes/01-REST-API/01-service-path-and-resource-path/target/bin/service_path_and_resource_path.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

But I couldn't find the logger which prints this warnings yet. 

Btw how about passing the following property when building the native image:
```
io.netty.tryReflectionSetAccessible=false
```
Actually this is the default behavior when we run `bal build` \ `bal run`

**Comment by TharmiganK** [comment]
In the above PRs, only the GraalVM warnings are fixed by adding the required dependencies. The netty warning regarding the illegal reflection access can be resolved by a similar approach used in this [issue](https://github.com/ballerina-platform/ballerina-standard-library/issues/1136).
