### ISSUE TITLE
The errors occur at the SSL Connection creation are hidden

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#3862]
**Description:**
Experience the $subject during the https://github.com/ballerina-platform/ballerina-standard-library/issues/2873 and Netty update to 4.1.86.

Even-though the connection creation is not succeeded, the hander returns a connection. Hence the error occures during the runtime without proper error message.

**Steps to reproduce:**
```ballerina
import ballerina/http;

service / on new http:Listener(9090) {
    resource function get greeting() returns string|error {
         final http:Client clientEndpoint = check new ("https://run.mocky.io/v3/164eda0f-9980-4aa1-9e09-94d8ac6ca6e0");
         json resp = check clientEndpoint->get("/");
         return "Resp: " + resp.toBalString();
    }
}
```

**Affected Versions:**
Update 2

**Comment by Bhashinee** [comment]
Tried reproducing the issue mentioned above. Used the same code sample and ran it locally as well as in a docker environment. 
The code sample used,
```
import ballerina/http;

service / on new http:Listener(9090) {
    resource function get greeting() returns string|error {
        final http:Client clientEndpoint = check new ("https://run.mocky.io/v3/164eda0f-9980-4aa1-9e09-94d8ac6ca6e0",
                secureSocket = {
                    cert: "/home/ballerina/test/public.crt"
                }
        );
         json resp = check clientEndpoint->get("/");
         return "Resp: " + resp.toBalString();
    }
}
```
Copied a wrong certificate to the docker image and used it in the code.

used commands

To build the docker image,

`bal build --cloud="docker"`

Run the docker image

`docker run -p 9090:9090 -p 9091:9091  -v $(pwd)/public.crt:/home/ballerina/test/public.crt test_ssl:latest
`

Invoke the service

`curl -v http://localhost:9090/greeting`

Response

```
> GET /greeting HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< content-type: text/plain
< content-length: 120
< server: ballerina
< date: Mon, 20 Feb 2023 12:29:54 GMT
< 
* Connection #0 to host localhost left intact
SSL connection failed:javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem run.mocky.io/185.42.117.108:443* Closing connection 0
```

Server log

`error: SSL connection failed:javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem run.mocky.io/46.252.181.104:443`

It shows the SSL error logs as given above. Agreeing that it doesn't provide a detailed explanation of the error. Unlike running on JDK SSL when using Open SSL this is the maximum we get as the error message.
