### ISSUE TITLE
[MSSQL] Error when accessing generated keys in batch execute

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#3892]
**Description:**
```
Error while executing batch command starting with: \'INSERT INTO IDN_CLAIM_PROPERTY (LOCAL_CLAIM_ID, PROPERTY_NAME, PROPERTY_VALUE, TENANT_ID) 
                VALUES ( ? ,  ? ,  ? ,  ? )\'. The statement must be executed before any results can be obtained..
```

The issue seems to be when retrieving generated keys in batch execute

**Affected Versions:**
MSSQL: 
Ballerina version
```
Ballerina 2201.2.3 (Swan Lake Update 2)
Language specification 2022R3
Update Tool 1.3.10
```

SQL - 1.4.1
MSSQL Driver
```
version = "9.2.1.jre11"
groupId = "com.microsoft.sqlserver"
```

**Comment by kalaiyarasiganeshalingam** [comment]
Reproduced the error, but the problem is in the SQL server. 

It seems the SQL server does not support the retrieval of generated keys with batch execute functions.
https://github.com/Microsoft/mssql-jdbc/issues/245
https://github.com/microsoft/mssql-jdbc/issues/358
