### ISSUE TITLE
`bal test --native` fails on windows for log module

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/ballerina-standard-library#3899]
**Description:**
$subject
https://github.com/ballerina-platform/module-ballerina-log/actions/runs/3836463743/jobs/6531632104#step:10:305

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Thevakumar-Luheerathan** [comment]
I printed `outText` (https://github.com/ballerina-platform/module-ballerina-log/blob/804cd0a0ded17f5eedcd6ad6fd0ab767f757a5ad/integration-tests/tests/tests_json.bal#L217) for native build in windows (https://github.com/Thevakumar-Luheerathan/module-ballerina-log/actions/runs/3845874517/jobs/6550530705#step:10:1646) and ubuntu (https://github.com/Thevakumar-Luheerathan/module-ballerina-log/actions/runs/3845874517/jobs/6550530573#step:9:1447). I can see `Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8` string additionally in the windows build. It seems to be causing failures.

**Comment by TharmiganK** [comment]
`JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8` is set by default in the workflow for the windows build. May be disabling that setting will work. Will check on that.

**Comment by TharmiganK** [comment]
The above PR will fix the issue due to setting `JAVA_TOOL_OPTIONS` unnecessarily.

Successful workflow run with this fix : https://github.com/TharmiganK/module-ballerina-log/actions/runs/3846503187
