### ISSUE TITLE
Check on codecov pr check intermittent failures

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#3908]
**Description:**
This is related to failures like https://github.com/ballerina-platform/module-ballerina-io/actions/runs/3870418888/jobs/6597323580#step:5:34

logs
```
[2023-01-09T03:14:02.553Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

This is due to rate limits related to tokens

**Comment by dilanSachi** [comment]
The ongoing issue can be referred from here https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

**Comment by dilanSachi** [comment]
There are two options to avoid this.
1. Adding in the [Codecov upload token 46](https://docs.codecov.com/docs/codecov-uploader#upload-token) even if the project is public.
Even if the upload token is added, it will not be available to PRs from forked repos. We cannot [publicly add](https://github.com/codecov/codecov-action/issues/557#issuecomment-1306088202) the token due to potential misuse issues.

But if we add the token as a secret, we can reduce the failures at least for the PRs from the same repo (load test result prs).

2. Re-trying the upload step in CI/CD.
We can try this step, but cannot guarantee the success in 1 retry though.

**Comment by dilanSachi** [comment]
This action can be used to add the retry policy for the codecov upload step in PRs.
https://github.com/marketplace/actions/retry-action

But it is from a 3rd party provider

**Comment by dilanSachi** [comment]
What @shafreenAnfar suggested offline where we can reduce the amount of PRs by making the load tests run every 2 days will not be a solution AFAIK since anyway we are using the token of codecov and there is a chance that the rate limit is exceeded for any given PR.

**Comment by dilanSachi** [comment]
@shafreenAnfar @ThisaruGuruge WDYT?

**Comment by dilanSachi** [comment]
In an offline discussion @shafreenAnfar and I discussed to go with solution 1 by using `CODECOV_TOKEN` as a repository secret.

**Comment by ThisaruGuruge** [comment]
CodeCov is also going to make some improvements to the GitHub integration. They are planning to [migrate to GitHub apps, instead of OAuth application](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=email&utm_source=marketo&utm_campaign=jan_23_newsletter&utm_department=marketing&ajs_uid=2692077&ajs_event=clicked%20email&mkt_tok=MzMyLUxWWC03NDEAAAGJTBbuJakAcQ97yGq0srV9Fgwcwc9TJADt8eWq1tFZpE5kusxEdfWdBgwHaLXk7myqdxKBjNU-KPt5XT3UxjatEQuZh-epVcaWNcnofiTn9g).

**Comment by shafreenAnfar** [comment]
Any idea on when they are planning to complete aforementioned improvements?

**Comment by ThisaruGuruge** [comment]
They haven't provided a strict timeline. But they mention that this will be completed sometime around March. (As per the post, they are waiting for the affected users to become 5% before completely remove the OAuth app, but are migrating continuously).

**Comment by dilanSachi** [comment]
There is another issue in this approach. The organization upload token which we can add to the ballerina-platform is only available in the enterprise pricing scheme. As far as we know, we are using the opensource scheme (free scheme)(yet to confirm). In that case, we will have to get the upload token for each standard library and add them as individual repository secrets. I feel this will not be a flexible approach since there is a chance we may not need this after codecov fixes the issue from their side.
WDYT @ThisaruGuruge @shafreenAnfar

**Comment by shafreenAnfar** [comment]
As an intermediate solution can we do the retry thing?

**Comment by dilanSachi** [comment]
Found another issue where even though the files are uploaded successfully, the result has not been reported.

https://github.com/ballerina-platform/module-ballerinax-oracledb/actions/runs/4037863065/jobs/6941453266#step:5:36

**Comment by dilanSachi** [comment]
> Found another issue where even though the files are uploaded successfully, the result has not been reported. PR - [ballerina-platform/module-ballerinax-oracledb#570](https://github.com/ballerina-platform/module-ballerinax-oracledb/pull/570) Run - https://github.com/ballerina-platform/module-ballerinax-oracledb/actions/runs/4037863065/jobs/6941453266#step:5:36

Seems like a rare intermittent issue. Will open the issue if this is raised agian.

**Comment by dilanSachi** [comment]
Retrying does not work even with 4 tries. So decided to use the `CODECOV_TOKEN` approach.

**Comment by dilanSachi** [comment]
Adding codecov token works as expected

**Comment by dilanSachi** [comment]
> Found another issue where even though the files are uploaded successfully, the result has not been reported. PR - [ballerina-platform/module-ballerinax-oracledb#570](https://github.com/ballerina-platform/module-ballerinax-oracledb/pull/570) Run - https://github.com/ballerina-platform/module-ballerinax-oracledb/actions/runs/4037863065/jobs/6941453266#step:5:36

Saw this issue again in `oauth2`
https://github.com/ballerina-platform/module-ballerina-oauth2/pull/930
logs,
```
==> linux OS detected
https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
==> SHASUM file signed by key id 806bb28aed[7](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:8)79[8](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:9)6[9](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:10)
==> Uploader SHASUM verified (080b43eaec3434326bb0f61653a82d27aba15c311ddde9d3f68cb364314f7aae  codecov)
==> Running version latest
==> Running version v0.3.5
/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov -n  -Q github-action-2.1.0 -C fa2871dcc35a951305412c717d7652fb73c343c0
[2023-03-09T17:22:25.232Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.3.5
[2023-03-09T17:22:25.242Z] ['info'] => Project root located at: /home/runner/work/module-ballerina-oauth2/module-ballerina-oauth2
[2023-03-09T17:22:25.246Z] ['info'] ->  Token found by environment variables
[2023-03-09T17:22:25.256Z] ['info'] Searching for coverage files...
[2023-03-09T17:22:25.486Z] ['info'] Warning: Some files located via search were excluded from upload.
[2023-03-09T17:22:25.486Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2023-03-09T17:22:25.486Z] ['info'] => Found 1 possible coverage files:
  ballerina/target/report/oauth2/coverage-report.xml
[2023-03-09T17:22:25.486Z] ['info'] Processing /home/runner/work/module-ballerina-oauth2/module-ballerina-oauth2/ballerina/target/report/oauth2/coverage-report.xml...
[2023-03-09T17:22:25.493Z] ['info'] Using manual override from args.
[2023-03-09T17:22:25.493Z] ['info'] Detected GitHub Actions as the CI provider.
[2023-03-09T17:22:25.495Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.3.5&token=*******&branch=load-test-results&build=4376805991&build_url=https%3A%2F%2Fgithub.com%2Fballerina-platform%2Fmodule-ballerina-oauth2%2Factions%2Fruns%2F4376805991&commit=fa2871dcc35a951305412c717d7652fb73c343c0&job=PR+build&pr=930&service=github-actions&slug=ballerina-platform%2Fmodule-ballerina-oauth2&name=&tag=&flags=&parent=
[2023-03-09T17:22:37.896Z] ['info'] https://app.codecov.io/github/ballerina-platform/module-ballerina-oauth2/commit/fa2871dcc35a951305412c717d7652fb73c343c0
https://storage.googleapis.com/codecov/v4/raw/2023-03-09/ED1151E2687A8D369723D81C2DB4238C/fa2871dcc35a951305412c717d7652fb73c343c0/39a39006-d023-4ad6-9a5f-1419e509c715.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EJOGFN2JQ4OCTGA2MU5AEIT7OT5Z7HTFOAN2SPG4NWSN2UJYOY5U6LZQ%2F20230309%2FUS%2Fs3%2Faws4_request&X-Amz-Date=20230309T172237Z&X-Amz-Expires=[10](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:11)&X-Amz-SignedHeaders=host&X-Amz-Signature=6ab9a3d28e85b04ff773d95[11](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:12)d41fa0f7da7459aed8b1ccbee97292a3b788f26
[2023-03-09T17:22:37.897Z] ['info'] Uploading...
[2023-03-09T17:22:38.078Z] ['info'] {"status":"success","resultURL":"https://app.codecov.io/github/ballerina-platform/module-ballerina-oauth2/commit/fa2871dcc35a9513054[12](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:13)c7[17](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:18)d7652fb73c[34](https://github.com/ballerina-platform/module-ballerina-oauth2/actions/runs/4376805991/jobs/7659433665#step:5:35)3c0"}
`

**Comment by ThisaruGuruge** [comment]
Shall we start a discussion on [codecov community](https://community.codecov.com/)? This probably an issue from their side.

**Comment by dilanSachi** [comment]
> Shall we start a discussion on [codecov community](https://community.codecov.com/)? This probably an issue from their side.

Created.
https://community.codecov.com/t/codecov-report-does-not-get-generated-without-any-upload-errors/4194

**Comment by dilanSachi** [comment]
According to the responses from the codecov team, this is mostly because of down times in the codecov side and we cannot do anything about it apart from doing a retry of the build. Hence closing this issue.
