### ISSUE TITLE
[Asgardeo to Choreo Hub] Research on using azure-service bus administration-client for topics/subscription creation

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#3911]
**Description:**
$subject

Related to [#3768](https://github.com/ballerina-platform/ballerina-standard-library/issues/3768)

ASB admin-client documentation: 
- https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-java-stable

**Comment by ayeshLK** [comment]
When we start working on the Azure AdminClient [1] we have used latest SDK for azure service bus [2]. But, in ballerinax-asb connector [3], the connector team has used the previous SDK for azure service bus [4]. But, when we try to write an intergration test using both connectors we get the following runtime error:
```
error: java.lang.LinkageError {"message":"Package versions: jackson-core=2.10.1, jackson-databind=2.10.1, jackson-dataformat-xml=2.14.1, jackson-datatype-jsr310=2.14.1, azure-core=1.35.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot","cause":error("java.lang.NoSuchMethodError",message="'com.fasterxml.jackson.databind.cfg.MutableCoercionConfig com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()'")}
	at xlibb.asb.admin.0.Client:createTopic(admin_client.bal:48)
	   ayesh.bal_asb_sample.administration.0:createTopic(administration.bal:7)
	   ayesh.bal_asb_sample.0.$anonType$_0:onRegisterTopic(hub_service.bal:29)
```

As per the error this is due to version miss-match in jackson dependencies. 

Did some background check on the old azure SDK and found that it also has the administration capabilities [5]. Due to this we might have to re-structure the newly written Azure AdminClient to use the old azure SDK.

@shafreenAnfar / @chamil321 WDYT ?

[1] - https://github.com/xlibb/module-asb
[2] - https://mvnrepository.com/artifact/com.azure/azure-messaging-servicebus/7.13.0
[3] - https://github.com/ballerina-platform/module-ballerinax-azure-service-bus
[4] - https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus/3.5.1
[5] - https://javadoc.io/doc/com.microsoft.azure/azure-servicebus/3.5.1/com/microsoft/azure/servicebus/management/ManagementClient.html

**Comment by chamil321** [comment]
> 

@azinneera This is due to the usage of the multiple versions of the same dependency. What is the possible solution going forward?

 - Ballerinax ASB connector uses an older SDK which contains old jackson dependencies and Azure AdminClient uses the latest SDK with some latest jackson dependency. Issue can be resolved if Azure AdminClient's SDK is downgraded to Ballerinax ASB's SDK. But would that be a sustainable solution? In future, if once of the connectors upgrades, the other also require an upgrade

**Comment by ayeshLK** [comment]
As discussed we will be downgrading the Azure SDK used in Azure AdminClient for the time-being.

**Comment by ayeshLK** [comment]
Since, Choreo team is currently working on the upgrade for `ballerinax-azure-service-bus` connector will put this task on-hold.

Related Choreo Issue:
- https://github.com/wso2-enterprise/choreo/issues/17916

**Comment by ayeshLK** [comment]
Released `xlibb/asb.admin` package `v0.1.0`
- https://github.com/xlibb/module-asb/releases/tag/v0.1.0
