### ISSUE TITLE
Union types are restricted by complier plugin

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3929]
See the below image.

<img width="1298" alt="Screenshot 2023-01-12 at 11 25 13" src="https://user-images.githubusercontent.com/6178058/212024456-578a6915-375d-4f50-9f36-94120f8dc5e9.png">

[snowtooth_rest.zip](https://github.com/ballerina-platform/ballerina-standard-library/files/10399965/snowtooth_rest.zip)

**Comment by TharmiganK** [comment]
This is even reproducible with this simple code :
```ballerina
import ballerina/http;

type Record record {|
    string name;
|};

type TestRecord string|Record;

service on new http:Listener(4000) {

    resource function 'default [string ...path]() returns TestRecord[] {
        return [{name: "Hello, World"}];
    }
}
```

I think the array of union types are not allowed by the compiler.
