### ISSUE TITLE
Timestamp record type is not generated for protobuf Timestamp

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#393]
**Description:**
When we import **google/protobuf/timestamp.proto** is the proto file, corresponding ballerina record is not generated.

**Steps to reproduce:**
Make the proto definition like below and generate ballerina code,

```proto
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service FooService {
    rpc getTime(google.protobuf.Empty) returns (Timestamp) {}
}
```

**Affected Versions:**
1.0.1

**OS, DB, other environment details and versions:**
Not platform specific

**Comment by dilanSachi** [comment]
Im working on this

**Comment by dilanSachi** [comment]
In both `java` and `python` type `Timestamp` is introduced as a `class` with fields `seconds` and `nanoseconds`.

**Comment by BuddhiWathsala** [comment]
@dilanSachi, therefore, we can directly use the `time:Utc` type here.
https://github.com/ballerina-platform/module-ballerina-time/blob/309892278a4b911dc1c8ee3f64b847d44bb60197/time-ballerina/time_types.bal#L40

**Comment by dilanSachi** [comment]
at the moment, if the proto file is,

```
message Greeting {
    string name = 1;
    google.protobuf.Timestamp time = 2;
}

service FooService {
    rpc getTime(google.protobuf.StringValue) returns (Greeting) {}
}
```

the generated `_pb.bal` file contains,
```
public type Greeting record {|
    string name = "";
    Timestamp time = {};
|};
```
where `Timestamp` -> `unknown type 'Timestamp'`
So what should be generated is 
```
public type Greeting record {|
    string name = "";
    time:Utc time = [];
|};
```
is this the expected behaviour?
@daneshk @BuddhiWathsala

**Comment by daneshk** [comment]
yes, we need to use `time:Utc` for the protobuf `TimeStamp`. There can also be a case like below, where user use timestamp directly in both request and response.

* proto definition
```proto
service FooService {
    rpc getTime(google.protobuf.StringValue) returns (google.protobuf.Timestamp) {}
}
```

for that, generated code will be like,

```ballerina
service "FooService" {
  remote isolated function getTime(string) returns time:Utc|error {
    // 
  }
} 
```
