### ISSUE TITLE
Improve default error format and message

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3961]
This is what we get at the moment.

```
HTTP/1.1 404 Not Found
content-type: text/plain
connection: close
server: ballerina
date: Fri, 20 Jan 2023 15:15:52 +0530
content-encoding: gzip
content-length: 89

no matching resource found for path : /dept/userss , method : GET
```
But many clients these days expect a `application/json` response. Therefore, the better default would be `json`.
```
HTTP/1.1 404 Not Found
content-type: application/json
connection: close
server: ballerina
date: Fri, 20 Jan 2023 15:15:52 +0530
content-encoding: gzip
content-length: 89

{
  "timestamp": "2023-01-20T09:44:16.252+00:00",
  "status": 404,
  "reason": "not found",
  "message": "no matching resource found for path",
  "path": "/dept/userss",
  "method": "GET"
}
```
I think the below would be a better response.

**Comment by TharmiganK** [comment]
**Question 1:** Is this applicable for both error types: transport level and application level?


**Question 2:** Are we using an interceptor or are we going to change the native code where we return the status code errors (only for the application errors)?

> With the introduction of `StatusCodeError` type, we have made application level errors as a part of this status code errors. And since this status code errors return an error with a `body` detail which can be `anydata`. Currently `body` field is not populated from the native code and by default we return the message of the error as the response payload. So setting this `body` as a `map<json`> in the native code, should give the requested improvement. So we have to change in all the places where we return status code error type.

> We could have the logic in an `ResponseErrorInterceptor` and add it to the end of the interceptor pipeline (so that it will be executed first). But if an error occur at a `RequestInterceptor` then it might not hit this last `ResponseErrorInterceptor`.


**Question 3:** Are we returning different structure of json for different type of application errors(like service dispatching error, resource dispatching error, databinding error - path, query, header and payload, etc.), or is it the same structure for all of them?


**Question 4:** Are we going to overwrite the current behaviour or are we going to support both and default to the json payload?

> If we are supporting both then we may have to have a configurable to choose the type.

> If we are overwriting the error response payload type to json, then most of our test cases will break, since we are asserting the response payload. So we need to fix the test cases as well.

**Comment by TharmiganK** [comment]
@shafreenAnfar @MadhukaHarith92 and myself had a discussion on this. And following are the conclusions.

> Concern 1: Is this applicable for both error types: transport level and application level?

This is applicable for all the errors that can be intercepted. And @MadhukaHarith92 will check on the transport level errors and how there are handled in other frameworks like springboot, expressjs, etc.

> Concern 2: Are we using an interceptor or are we going to change the native code where we return the status code errors (only for the application errors)?

Yes, we are going to add this change to the last `DefaultErrorInterceptor`[https://github.com/ballerina-platform/module-ballerina-http/blob/ced835c7705eca1863712fb0b5769834a5c57b38/ballerina/http_interceptors.bal#L46]

> Concern 3: Are we returning different structure of json for different type of application errors(like service dispatching error, resource dispatching error, databinding error - path, query, header and payload, etc.), or is it the same structure for all of them?

No, we are going to have the same structure and we just have to populate the fields. Since we can now access the `request` object in the response interceptors, it is possible to access the path and method from the request object.

> Concern 4: Are we going to overwrite the current behaviour or are we going to support both and default to the json payload?

No, we want to overwrite the existing behaviour. We need to fix our tests as well. Also it may be a breaking change for some connectors, so we have to check on them as well.

**Comment by MadhukaHarith92** [comment]
Spring Boot uses the HTTP status codes to handle transport-level errors. When an error occurs during a transport-level activity such as sending or receiving data over a network, Spring Boot logs the error information and returns an appropriate HTTP response code to the client.

The error format in Spring Boot is a JSON object that contains details about the error. 
```json
{
  "status": 404,
  "error": "Not Found",
  "message": "The resource you are looking for cannot be found.",
  "path": "/example/api/users/123"
}
```

**Comment by dilanSachi** [comment]
Following are the related transport level status code errors.

1. 502 - Could not resolve host
2. 502 - SSL connection failed
3. 502 - Remote host closed the connection while SSL handshake
4. 413 - Request entity too large
5. 414 - Request uri too large
6. 431 - Request Header Fields Too Large
7. 505 - HTTP version not supported

Following are related existing error structures.

1.
2.
3.
4. ```error: Request Entity Too Large {"statusCode":413,"headers":{"connection":["close"],"content-length":["0"],"server":["ballerina"]},"body":null}```
5. ```error: Request-URI Too Long {"statusCode":414,"headers":{"connection":["close"],"content-length":["0"],"server":["ballerina"]},"body":null}```
6. ```error: Request Header Fields Too Large {"statusCode":431,"headers":{"connection":["close"],"content-length":["0"],"server":["ballerina"]},"body":null}```
7.


For cases 1, 2, 3, 7, couldnt get the correct error msgs (only tested 1, 7). As the error msgs are replaced by `Something wrong with the connection` in https://github.com/ballerina-platform/module-ballerina-http/blob/master/native/src/main/java/io/ballerina/stdlib/http/api/HttpUtil.java#L581

Therefore, until that is fixed, will only update the error msgs of 4, 5, 6. Will track the fix in another issue.

**Comment by dilanSachi** [comment]
For the cases 4, 5, 6 above, we can easily update the error structure for `HTTP/1` as we can handle it in the ballerina level error interceptors. However, for `HTTP/2` it is a bit difficult because the errors are handled in netty level and also case 5 is not applicable for `HTTP/2` as well.

However, for cases 1, 2, 3, and 7, we can handle those in the interceptor level as these are gateway level errors.

**Comment by dilanSachi** [comment]
> Therefore, until that is fixed, will only update the error msgs of 4, 5, 6. Will track the fix in another issue.

This will be fixed in the same issue as that change is needed for this change as well.
