### ISSUE TITLE
[Asgardeo to Choreo Hub] Troubleshoot issue in publishing content to the `hub`

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#3965]
**Description:**
> When trying to publish content to the `hub`, there is an intermittent error while responding to the publish request.

**Comment by ayeshLK** [comment]
During the initial investigation it was found that when the asgardeo-publisher send a content-publish request to the `hub` there will be an idle-timeout error in the client side. When checking the logs in the `hub` it was found that there is a remote-client connection closed error while responding to the request. The time difference between client-timeout and the connection-closed error is about 30 seconds. 

Hence, it is assumed that the `hub` is taking at-least 30 seconds to process a content-publish event.

**Comment by ayeshLK** [comment]
To narrow down the issue we will add debug logs to the content-publish workflow of the `hub`.

**Comment by ayeshLK** [comment]
Added new debug logs for the content-publish workflow. These changes are now in the production environment. Following is a log for content-publish request initiated during the integration tests.
```sh
"1/24/2023, 10:34:49.316 AM","time = 2023-01-24T10:34:49.315Z level = DEBUG module = wso2/azureWebsubHub message = ""Received content-publish request"" topic = ""test-topic"""
"1/24/2023, 10:34:49.316 AM","time = 2023-01-24T10:34:49.316Z level = DEBUG module = wso2/azureWebsubHub message = ""Started processing conent-publish request"" topic = ""test_topic"""
"1/24/2023, 10:34:49.317 AM","time = 2023-01-24T10:34:49.316Z level = DEBUG module = wso2/azureWebsubHub message = ""Topic test_topic is available. Hence, publishing content to azure event-hub"""
"1/24/2023, 10:34:49.317 AM","time = 2023-01-24T10:34:49.317Z level = INFO module = wso2/azureWebsubHub message = ""Relevant event-hub information"" eventHub = ""evh-websubhub-eh1-prod-westus3-001"" partition = 12"
"1/24/2023, 10:34:49.525 AM","time = 2023-01-24T10:34:49.525Z level = DEBUG module = wso2/azureWebsubHub message = ""Published content to azure event-hub successfully"""
"1/24/2023, 10:34:49.525 AM","time = 2023-01-24T10:34:49.525Z level = DEBUG module = wso2/azureWebsubHub message = ""Successfully processed content-publish request"" topic = ""test-topic"""
"1/24/2023, 10:34:49.530 AM","172.20.194.4 - - [24/Jan/2023:10:34:49 +0000] ""POST /hub?hub.mode=publish&hub.topic=test-topic HTTP/1.1"" 200 17 ""-"" ""ballerina"" "'
```

The above log indicates the content-publish request for integration-tests. When look at the time taken for the request to be processed it seems like about `214 ms` is taken to respond to the request. And about `208 ms` is taken when publishing the content to azure event-hub. 

But, this is an intermittent behavior. Following is another set of logs for same integration-test.
```sh
"1/24/2023, 10:34:49.548 AM","time = 2023-01-24T10:34:49.548Z level = DEBUG module = wso2/azureWebsubHub message = ""Received content-publish request"" topic = ""test-topic"""
"1/24/2023, 10:34:49.548 AM","time = 2023-01-24T10:34:49.548Z level = DEBUG module = wso2/azureWebsubHub message = ""Started processing conent-publish request"" topic = ""test_topic"""
"1/24/2023, 10:34:49.549 AM","time = 2023-01-24T10:34:49.548Z level = DEBUG module = wso2/azureWebsubHub message = ""Topic test_topic is available. Hence, publishing content to azure event-hub"""
"1/24/2023, 10:34:49.549 AM","time = 2023-01-24T10:34:49.549Z level = INFO module = wso2/azureWebsubHub message = ""Relevant event-hub information"" eventHub = ""evh-websubhub-eh1-prod-westus3-001""partition = 12"
"1/24/2023, 10:34:49.603 AM","time = 2023-01-24T10:34:49.603Z level = DEBUG module = wso2/azureWebsubHub message = ""Published content to azure event-hub successfully"""
"1/24/2023, 10:34:49.604 AM","time = 2023-01-24T10:34:49.603Z level = DEBUG module = wso2/azureWebsubHub message = ""Successfully processed content-publish request"" topic = ""test-topic"""
"1/24/2023, 10:34:49.605 AM","172.20.194.4 - - [24/Jan/2023:10:34:49 +0000] ""POST /hub?hub.mode=publish&hub.topic=test-topic HTTP/1.1"" 200 17 ""-"" ""ballerina"" "
```
As per the logs this requests were processed within `57 ms`.

But, it was noticed that during the 1st content-publish request flow `hub` was also trying to deliver content to several subscribers. And during the 2nd content-publish request flow `hub` was at rest.
```sh
"1/24/2023, 10:34:49.318 AM","time = 2023-01-24T10:34:49.318Z level = DEBUG module = wso2/azureWebsubHub message = ""Publishing content-for subscriber godwinshrimal_USER_OPERATIONS___https___c4940d00_9dbf_45e0_b5da_00f6cd610979_prod_e1_us_east_azure_choreoapis_dev_zknv_asgardeowebhook_1_0_0"" numOfRecords = 0"
"1/24/2023, 10:34:49.339 AM","time = 2023-01-24T10:34:49.338Z level = DEBUG module = wso2/azureWebsubHub message = ""Content publish is successful for topic godwinshrimal_USER_OPERATIONS and subscriber godwinshrimal_USER_OPERATIONS___https___c4940d00_9dbf_45e0_b5da_00f6cd610979_prod_e1_us_east_azure_choreoapis_dev_zknv_asgardeowebhook_1_0_0"""
"1/24/2023, 10:34:49.339 AM","time = 2023-01-24T10:34:49.339Z level = DEBUG module = wso2/azureWebsubHub message = ""Polling updates for topic godwinshrimal_USER_OPERATIONS and subscriber godwinshrimal_USER_OPERATIONS___https___c4940d00_9dbf_45e0_b5da_00f6cd610979_prod_e1_us_east_azure_choreoapis_dev_zknv_asgardeowebhook_1_0_0"""
"1/24/2023, 10:34:49.386 AM","time = 2023-01-24T10:34:49.385Z level = DEBUG module = wso2/azureWebsubHub message = ""Publishing content-for subscriber asgardeodemo_REGISTRATIONS___https___42807e1f_07ba_4fb0_a6d2_ecc7b41dd143_dev_e1_us_east_azure_choreoapis_dev_yphf_asgardeo_webhook_dki_1_0_0"" numOfRecords = 0"
"1/24/2023, 10:34:49.405 AM","time = 2023-01-24T10:34:49.405Z level = DEBUG module = wso2/azureWebsubHub message = ""Content publish is successful for topic asgardeodemo_REGISTRATIONS and subscriber asgardeodemo_REGISTRATIONS___https___42807e1f_07ba_4fb0_a6d2_ecc7b41dd143_dev_e1_us_east_azure_choreoapis_dev_yphf_asgardeo_webhook_dki_1_0_0"""
"1/24/2023, 10:34:49.405 AM","time = 2023-01-24T10:34:49.405Z level = DEBUG module = wso2/azureWebsubHub message = ""Polling updates for topic asgardeodemo_REGISTRATIONS and subscriber asgardeodemo_REGISTRATIONS___https___42807e1f_07ba_4fb0_a6d2_ecc7b41dd143_dev_e1_us_east_azure_choreoapis_dev_yphf_asgardeo_webhook_dki_1_0_0"""
"1/24/2023, 10:34:49.422 AM","time = 2023-01-24T10:34:49.422Z level = DEBUG module = wso2/azureWebsubHub message = ""Publishing content-for subscriber kfone_USER_OPERATIONS___https___bc5814d2_4d31_4a9e_be2d_fdb955e394fd_dev_e1_us_east_azure_choreoapis_dev_hvwp_e2e_test_webhook_1_0_0"" numOfRecords = 0"
"1/24/2023, 10:34:49.446 AM","time = 2023-01-24T10:34:49.445Z level = DEBUG module = wso2/azureWebsubHub message = ""Publishing content-for subscriber kfone_REGISTRATIONS___https___bc5814d2_4d31_4a9e_be2d_fdb955e394fd_dev_e1_us_east_azure_choreoapis_dev_hvwp_asgardeo_user_registration_webhook_1_0_0"" numOfRecords = 0"
"1/24/2023, 10:34:49.447 AM","time = 2023-01-24T10:34:49.447Z level = DEBUG module = wso2/azureWebsubHub message = ""Content publish is successful for topic kfone_USER_OPERATIONS and subscriber kfone_USER_OPERATIONS___https___bc5814d2_4d31_4a9e_be2d_fdb955e394fd_dev_e1_us_east_azure_choreoapis_dev_hvwp_e2e_test_webhook_1_0_0"""
"1/24/2023, 10:34:49.447 AM","time = 2023-01-24T10:34:49.447Z level = DEBUG module = wso2/azureWebsubHub message = ""Polling updates for topic kfone_USER_OPERATIONS and subscriber kfone_USER_OPERATIONS___https___bc5814d2_4d31_4a9e_be2d_fdb955e394fd_dev_e1_us_east_azure_choreoapis_dev_hvwp_e2e_test_webhook_1_0_0"""
"1/24/2023, 10:34:49.466 AM","time = 2023-01-24T10:34:49.465Z level = DEBUG module = wso2/azureWebsubHub message = ""Content publish is successful for topic kfone_REGISTRATIONS and subscriber kfone_REGISTRATIONS___https___bc5814d2_4d31_4a9e_be2d_fdb955e394fd_dev_e1_us_east_azure_choreoapis_dev_hvwp_asgardeo_user_registration_webhook_1_0_0"""
"1/24/2023, 10:34:49.466 AM","time = 2023-01-24T10:34:49.466Z level = DEBUG module = wso2/azureWebsubHub message = ""Polling updates for topic kfone_REGISTRATIONS and subscriber kfone_REGISTRATIONS___https___bc5814d2_4d31_4a9e_be2d_fdb955e394fd_dev_e1_us_east_azure_choreoapis_dev_hvwp_asgardeo_user_registration_webhook_1_0_0"""
"1/24/2023, 10:34:49.468 AM","time = 2023-01-24T10:34:49.468Z level = DEBUG module = wso2/azureWebsubHub message = ""Publishing content-for subscriber ascension_REGISTRATIONS___https___4c13fc94_370d_47e5_8ea1_6853c40eccba_dev_e1_us_east_azure_choreoapis_dev_xhcs_registrationwebhook_1_0_0"" numOfRecords = 0"
"1/24/2023, 10:34:49.486 AM","time = 2023-01-24T10:34:49.486Z level = DEBUG module = wso2/azureWebsubHub message = ""Content publish is successful for topic ascension_REGISTRATIONS and subscriber ascension_REGISTRATIONS___https___4c13fc94_370d_47e5_8ea1_6853c40eccba_dev_e1_us_east_azure_choreoapis_dev_xhcs_registrationwebhook_1_0_0"""
"1/24/2023, 10:34:49.486 AM","time = 2023-01-24T10:34:49.486Z level = DEBUG module = wso2/azureWebsubHub message = ""Polling updates for topic ascension_REGISTRATIONS and subscriber ascension_REGISTRATIONS___https___4c13fc94_370d_47e5_8ea1_6853c40eccba_dev_e1_us_east_azure_choreoapis_dev_xhcs_registrationwebhook_1_0_0"""
"1/24/2023, 10:34:49.493 AM","time = 2023-01-24T10:34:49.493Z level = DEBUG module = wso2/azureWebsubHub message = ""Content publish is successful for topic tdorg_REGISTRATIONS and subscriber tdorg_REGISTRATIONS___https___2797021b_f8e4_4a2b_b82a_3028e9de647e_dev_e1_us_east_azure_choreoapis_dev_memu_asgardeo_registration_webhook_2_1_0_0"""
"1/24/2023, 10:34:49.493 AM","time = 2023-01-24T10:34:49.493Z level = DEBUG module = wso2/azureWebsubHub message = ""Polling updates for topic tdorg_REGISTRATIONS and subscriber tdorg_REGISTRATIONS___https___2797021b_f8e4_4a2b_b82a_3028e9de647e_dev_e1_us_east_azure_choreoapis_dev_memu_asgardeo_registration_webhook_2_1_0_0"""
```

**Comment by ayeshLK** [comment]
Checked the production logs for the `hub` for 12 hours (11.00 PM 24th January 2023 - 11.00 AM 25th January 2023) and the timeout error has not been reproduced. Asgardeo team has confirmed that the request timeout from there side is `300 ms` and due to above mentioned behavior it is possible that this timeout will exceed during while responding to content-publish request. As a work around we can update the time-out value to at least `5 seconds` in Asgardeo side.

**Comment by ayeshLK** [comment]
Had a chat with @shafreenAnfar / @chamil321 / @dilanSachi on this issue. Following are the discussion points:
- Update the number of threads in ballerina thread-pool (in `hub` deployment)
- Refactor kafka-producer to work as non-blocking
- Check the possibility to update the time-out value for content-publish request with with Asgardeo team

**Comment by ayeshLK** [comment]
Following are the current system configurations for `hub` pod:
- CPU: 0.5
- Memory: 256MB

Hence, currently a `hub` pod will have only 1 thread in ballerina thread-pool (default ballerina thread count = number of processors * 2). After considering the default java thread size (256 KB) [1] and the current memory limit I think we could set the `BALLERINA_MAX_POOL_SIZE` environment variable to `50`. 

@janethavi pls note.

But, as per the current system limits on a `hub` pod. I think we could update it as follows:
- CPU: 1
- Memory: 512MB

@shafreenAnfar / @chalitha1989 / @xlight05 what are your thought on this ?

[1] - https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html#wp1024112

**Comment by xlight05** [comment]
> Following are the current system configurations for `hub` pod:
> 
> * CPU: 0.5
> * Memory: 256MB
> 
> Hence, currently a `hub` pod will have only 1 thread in ballerina thread-pool (default ballerina thread count = number of processors * 2). After considering the default java thread size (256 KB) [1] and the current memory limit I think we could set the `BALLERINA_MAX_POOL_SIZE` environment variable to `50`.
> 
> @janethavi pls note.
> 
> But, as per the current system limits on a `hub` pod. I think we could update it as follows:
> 
> * CPU: 1
> * Memory: 512MB
> 
> @shafreenAnfar / @chalitha1989 / @xlight05 what are your thought on this ?
> 
> [1] - https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html#wp1024112

I believe Increasing the memory and CPU would be a quick fix for this issue. Even during our load tests, we use the following numbers as we observed it gave the optimal performance in ballerina (We haven't checked websubhub specifically). 
```toml
min_memory="256Mi"
max_memory="512Mi"
min_cpu="200m"
max_cpu="1000m"
```

From the stdlib side, we could try to optimize the resource usage. We should probably do some own benchmarks to see the resource consumption using websubhub as well.

**Comment by dilanSachi** [comment]
> Had a chat with @shafreenAnfar / @chamil321 / @dilanSachi on this issue. Following are the discussion points:
> 
> * Update the number of threads in ballerina thread-pool (in `hub` deployment)
> * Refactor kafka-producer to work as non-blocking
> * Check the possibility to update the time-out value for content-publish request with with Asgardeo team

We have updated kafka-producer to work as non-blocking with the patch version `3.5.1` in update 3

**Comment by janethavi** [comment]
Following are the new resource requirements.
```
limits:
      memory: "512Mi"
      cpu: "1"
requests:
      memory: "400Mi"
      cpu: "800m"
```

**Comment by ayeshLK** [comment]
Regarding this particular issue we have done several improvements to azure-websubhub deployment.
- Increased memory/CPU limits in `hub` pods
- Increased ballerina thread-pool in `hub` pods
- Update ballerina kafka-producer to use non-blocking execution logic

Apart from that Asgardeo team has also updated their client-timeout to `5 seconds`. 

Currently all the changes relevant to azure-websubhub deployment are in production environment and we have monitored the logs for past 24 hours and the error is not reproducible. Hence we will close the issue which was opened to track the progress of troubleshooting the timeout problem.

**Comment by ayeshLK** [comment]
Analyzed the logs for last 7 days (2nd Feb 2023 - 9th Feb 2023) [1] and the issue was not reproduced in the production. 

[1] - https://drive.google.com/drive/folders/187OM0CIPpiXIe0vS9SfEpzEmVgetIuNz?usp=sharing
