### ISSUE TITLE
[gRPC] Deadline support

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-standard-library#398]
**Description:**
Deadlines allow gRPC clients to specify how long they are willing to wait for an RPC to complete before the RPC is terminated with the error DEADLINE_EXCEEDED. This feature is required to implement efficient failover mechanisms to the gRPC services.  Would be a very useful feature for ballerina ;)

**Suggested Labels (optional):**
Component/stdlib ,  Component/gRPC ,  Type/Improvement 

**Suggested Assignees (optional):**
@daneshk

**Comment by BuddhiWathsala** [comment]
With the recent swan lake changes, we are planning to add the deadline support. To enable that, I suggest to introduce two high-level APIs as follows:

```ballerina
// Set the deadline value as a header(in client-side)
time:Time deadline = ...;
map<string|string[]> headers = ...;
map<string|string[]> headers = grpc:setDeadline(headers, deadline);

// Check the specified deadline is exceeded or not(in server-side)
map<string|string[]> headers = ...;
boolean cancelled = grpc:isCancelled(headers);
```

@daneshk @shafreenAnfar, please provide your suggestions.

**Reference**
[1] https://grpc.io/blog/deadlines/

**Comment by daneshk** [comment]
+1 for the two APIs. can you also check how we can support propagating the deadline from one service to another? 
similar to: https://docs.microsoft.com/en-us/aspnet/core/grpc/deadlines-cancellation?view=aspnetcore-5.0#propagating-deadlines

**Comment by BuddhiWathsala** [comment]
@daneshk, I checked the .NET approach. They have used an internal caller context to propagate the deadline. I think there are two possible ways to do that. 

#### Option 01
We can use an internal context that is specific to the gRPC calls.

#### Option 02
If we are going to introduce a global context for Ballerina, then we will be able to achieve this easily using that global context.

Please provide your suggestions on this.

**Comment by daneshk** [comment]
As discussed, let's give a high-level API to read the deadline value. User can read and set the deadline if he/she needs to propogate
