### ISSUE TITLE
When the project name is equal to the submodule name, the execution results in unexpected results

### ISSUE THREAD

**Issue by sahanHe** [ballerina-platform/ballerina-standard-library#3993]
**Description:**
when the project is defined as follows in the ballerina.toml, 
```
[package]
org = "foo"
name = "medical_center"
version = "0.1.0"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = false
```
and the entities are defined in the a file with the same name as project, it gives the following errors in runtime.

```
error: [Config.toml:(1:1,6:31)] invalid toml structure found for module 'medical_center.medical_center'. Please provide the module name as '[medical_center.medical_center]'
        at foo/medical_center.medical_center:0.1.0(database_configuration.bal:8)
error: [Config.toml:(3:1,3:12)] unused configuration value 'medical_center.medical_center.port'
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
We are not generating another submodule when package name and model definition file is same. So this issue will not affect for the persist module
