### ISSUE TITLE
Generate command does not work if I run after renaming the file

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#4005]
**Description:**
```
Error while generating types and client for the definition file(testpersistcli-2.bal). Failed to write the types for the testpersistcli-2 data model to the generated_types.bal file. /Users/niveathika/WSO2/temp/testpersistcli/generated/testpersistcli-2/generated_types.bal (No such file or directory)
```

**Comment by daneshk** [comment]
This is expected behavior, if the user renames the definition life, he should do `bal init` to generate configs and module directories. we will improve the error message.

**Comment by niveathika** [comment]
Cant we say, "found new file" and call the initialisation from within generate command?

**Comment by daneshk** [comment]
Added this comment `The generated source directory: /Users/danesh/ballerina-platform/persist-tools/persist-cli-tests/build/generated-sources/tool_test_generate_32/generated/entities doesn't exist. Please run `bal persist init` to initiate the project before generation.
`
