### ISSUE TITLE
Improve `generate` command execution time

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#4006]
**Description:**
Currently it takes about 5-7 seconds for the command even without any entities present. We should improve this if possible.

**Comment by daneshk** [comment]
This is mainly due to the project loading logic to check whether we are in the Ballerina project. Changed the logic to check only Ballerina.toml file in the directory. Will check after this change and close if it is improved.

**Comment by sahanHe** [comment]
Currently the more than 70% of the execution time is consumed by the validation step to detect syntax errors in the project. for example, if it take 7 seconds to execute the generate command, it will take around 5 seconds to run the code validation.

**Comment by sahanHe** [comment]
After the compiling step of the validation was changed to offline, the overall execution time was improved to to 3 seconds from the previous 5-7 seconds. This gets further reduced to 2.5 seconds for the empty entities.

**Comment by niveathika** [comment]
@sahanHe Could you open a separate issue to track that we are building in offline mode?
This means we can't send patch fixes for the validator.
