### ISSUE TITLE
Ballerina GraphQL mutation won't properly invoke when Enum is used as a parameter of the input object

### ISSUE THREAD

**Issue by shayanmalinda** [ballerina-platform/ballerina-standard-library#4015]
**Description:**
When GraphQL mutation has a record type which contains an Enum attribute, that endpoint will not be invoked properly. It will indefinetely try to invoke the endpoint.

**Steps to reproduce:**

GraphQL endpoint Definition
```
remote function createUser(types:UserInput input) returns User|error {
    log:printInfo("Test log");
    ...
}
```

Record type definition of the `UserInput`
```
public type UserInput record {|
    ...
    UserType userType;
|};
```

Definition of the `UserType` enum
```
public enum UserType {
    OWN_CONTACT = "OWN CONTACT",
    PARTNER_CONTACT = "PARTNER CONTACT"
}
```

"Test log" won't logged out in above case.
Above issue won't occur when `userType` is defined as `string userType`.

**Affected Versions:**

`2201.3.2`

**Suggested Assignees (optional):**

@ThisaruGuruge

**Comment by ThisaruGuruge** [comment]
This is a known bug due to a Ballerina runtime API limitation. This has been fixed now and will be available with GraphQL 1.6.0 release (which will be released with Ballerina 2201.4.0: SwanLake Update 4).

Related: https://github.com/ballerina-platform/ballerina-standard-library/issues/3721
