### ISSUE TITLE
[Intern Project] Write proposal for project `GraphQL Federation Gateway in Ballerina`

### ISSUE THREAD

**Issue by Ishad-M-I-M** [ballerina-platform/ballerina-standard-library#4028]
**Description:**
Project is to implement a graphQL federation gateway in Ballerina. 

**Describe your task(s)**
* Write the proposal for the intern project `GraphQL Federation Gateway in Ballerina`

**Related Issues (optional):**
#3982 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Closing since this is now completed.
