### ISSUE TITLE
[Intern Project] Write proposal for the project `Generate Ballerina Service from GraphQL Schema` 

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [ballerina-platform/ballerina-standard-library#4030]
**Description:**
The project is to develop a tool to generate ballerina service from GraphQL schema. 

**Describe your task(s)**
Research about the already implemented solutions and provide an approach to build the tool.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
Proposal: https://github.com/ballerina-platform/ballerina-standard-library/issues/4127
