### ISSUE TITLE
 Unexpected behavior when "+" character is included in the request payload

### ISSUE THREAD

**Issue by Miranlfk** [ballerina-platform/ballerina-standard-library#4082]
**Description:**
$title

The following example image 1 shows a case where using character `+` , a ` ` is added instead of the `+` and it doesn't return the desired result, thus needs to be encoded to `%2B`, the result is acquired. 

```
import ballerina/http;

type Dependency readonly & record {|
    string name;
    string hash;
|};

table<Dependency> key(name) dependencies = table [
    {name: "abcd+efgh", hash: "3e658c4207d316bf4df3c87a66caa96bef94d202"},
    {name: "abcd efgh", hash: "3e658c4207d316bf4df3c87a66caa96bef94d202"}
];

service / on new http:Listener(9090) {

    resource function get dependencies(string name) returns Dependency[] {
        return from Dependency dependencies in dependencies
            where dependencies.name == name
            select dependencies;
    }
}

```
The table `dependecies` shows 2 values, `abcd+efgh` and `abcd efgh`. In the example the real dependency is `abcd+efgh` and we've used `abcd efgh` as a 2nd dependency to replicate/explain the behaviour noticed.

Image 1- 
![4](https://user-images.githubusercontent.com/85722530/219581254-51efcbd1-5ffe-4feb-8453-d91540dad51c.png)

Image 2 -
![image](https://user-images.githubusercontent.com/85722530/219581161-9acd9b49-826c-4045-a270-d5ea6e8406e8.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
module/http

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
There is a similar behavior in `post` requests as well. If the `+` character is in the json payload, it gets replaced with an empty string and gets stored in the DB at the backend.

**Comment by Bhashinee** [comment]
I think this is the correct behavior. When sending a special character as a query parameter it must be encoded accordingly. So when '+' sign is added in the query part of the URL, it is decoded as the ' '. Please refer,
https://stackoverflow.com/questions/2678551/when-should-space-be-encoded-to-plus-or-20

If you want to send the '+' sign, as it is a special character, you have to encode it accordingly as given in Image 2.

**Comment by Bhashinee** [comment]
Closing the issue as per the above comment. Please reopen if you any concerns.
