### ISSUE TITLE
NPE thrown when trying to use SQL IN operator

### ISSUE THREAD

**Issue by wx-yz** [ballerina-platform/ballerina-standard-library#4119]
**Description:**
I have an SQL query that's using the IN operator. I'm getting the input for the in operator via an array. I tried creating a string and use that in a parameterized query like `SELECT ... IN (${arrStr})`

This throws the below error,
```
class io.ballerina.runtime.internal.types.BMapType cannot be cast to class io.ballerina.runtime.api.types.RecordType (io.ballerina.runtime.internal.types.BMapType and io.ballerina.runtime.api.types.RecordType are in unnamed module of loader \'app\')
```
Then I tried directly using the array like `SELECT ... IN ${arr}` and this throws an NPE,
```
Error while executing SQL query: select ... in ( ? ). java.lang.NullPointerException
```

I had to look at the test cases to figure out the correct form SQL statement that use arrayFlattenQuery. It would be helpful if the error message can be improved to point to the right direction

**Affected Versions:**
Ballerina 2201.3.2 (Swan Lake Update 3)
Language specification 2022R4
Update Tool 1.3.12

**Comment by niveathika** [comment]
> I have an SQL query that's using the IN operator. I'm getting the input for the in operator via an array. I tried creating a string and use that in a parameterized query like `SELECT ... IN (${arrStr})`

@wx-yz Could you give more information regarding the code you used? Is it similar to the following?
```
string[] arrStr = [];
sql:ParameterizedQuery query = `SELECT ... IN (${arrStr})`;
```

**Comment by niveathika** [comment]
This seems to be a combination of 2 bugs,
1. https://github.com/ballerina-platform/ballerina-standard-library/issues/4200
2. https://github.com/ballerina-platform/ballerina-standard-library/issues/4201

We will be fixing this for Update 5.

**Comment by niveathika** [comment]
Both fixes are merged and will be released in Update 5.

Thank you for reporting the issue.
