### ISSUE TITLE
cannot create path parameter with "-"

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [ballerina-platform/ballerina-standard-library#4128]
**Description:**

I need to use "-" in one of my path parameters like this. account/[string account-id].
I tried escaping the "-" by account/[string account\\-id]. But the service crashes with the following error.
error: service registration failed: Invalid character: '\\' in expression.

bal version: 2201.3.1 

discord - https://discord.com/channels/957996897782616114/1017493204326686860/threads/1078525077789880360

**Comment by TharmiganK** [comment]
Reproducible code :
```bal
import ballerina/http;

type Account record {
    string id;
    string name;
    string email;
    string phone;
};

service on new http:Listener(9090) {

    resource function get account/[string account\-id]() returns Account {
        return {
            id: account\-id,
            name: "John Doe",
            email: "john.doe@email.com",
            phone: "1234567890"
        };
    }
}
```

**Comment by Bhashinee** [comment]
Will be fixed, once this issue gets fixed. https://github.com/ballerina-platform/ballerina-lang/issues/39770
