### ISSUE TITLE
Change the names for generated files in persist tooling

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#4131]
**Description:**
$subject please.

Names of the generated files are as follows,
* database_configuration.bal
* generated_client.bal
* generated_types.bal
* <schema_filename>_db_script.sql

since these are already inside the generated directory. we don't need to prefix as generated. 
suggested names are,

* db_config.bal
* <schema_filename>_clients.bal
* <schema_filename>_types.bal
* <schema_filename>_db_script.sql

**Comment by daneshk** [comment]
@sameerajayasoma any thoughts on suggested names

**Comment by sameerajayasoma** [comment]
Multiple `.bal` files can be in the `persist` directory. In that case, we don't have a single schema file name. 

What do you think about using the following file names?
`persist_client.bal`
`persist_types.bal`
`persist_db_config.bal`
`db_script.sql`

**Comment by sameerajayasoma** [comment]
By the way, I just realized I've already proposed these names in the design doc.  :) 
https://docs.google.com/document/d/1LxJ8IwR-5DDSCdP-8gVmnPL43rauKC_AukqWraimvEs/edit#heading=h.giyefyn0p5dt

**Comment by sahanHe** [comment]
This change was implemented in [71bc0ce](https://github.com/ballerina-platform/persist-tools/pull/161/commits/71bc0cec11e3d502e63bb11c9390a9e25eccab41)

**Comment by daneshk** [comment]
Fixes are merged to the main branch. hence closing the issue
