### ISSUE TITLE
Check the possibility to give a more intuitive function in UUID module

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#4147]
**Description:**
Quoted from the discord question [1]

```
Currently, the UUID package has a cryptic set of functions like createType1AsString(), etc. Can't we provide a more intuitive newRandomUuid() kind of function with a reasonable default? IMO most devs don't want to go into this level to get a simple random UUID.
```

1. https://discord.com/channels/957996897782616114/1080308368801005631/1080308368801005631

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ImeshBalasuriya** [comment]
Hi,

I'd like to contribute to this issue. 

At a glance, it seems like the best option is to create an additional function `newRandomUuid()` which takes in the UUID type as an optional argument and makes calls to the existing functions to generate the UUID. This will solve the issue without introducing any breaking changes.

Please let me know your suggestions.

**Comment by daneshk** [comment]
Thanks, @ImeshBalasuriya for your interest.

Yes, We were thinking of introducing a new function as you suggested. How about having a function like the below,

```ballerina
public isolated function createRandomUuid() returns string;
```
API doesn't have any arguments, it will generate a UUID of type 04 similar to the Java API[1]. Since we already have APIs to create other types, if user needs to generate UUID with different type, he/she can use other API

1. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/UUID.html#randomUUID()
