### ISSUE TITLE
Compiler Extension Failed to Complete in GraphQL Package

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#4156]
**Description:**
When using the GraphQL package that was published to local central returns the following error.
```shell
error: compilation failed: The compiler extension in package 'ballerina:graphql:1.6.1' failed to complete. 'void io.ballerina.stdlib.graphql.commons.types.Field.<init>(java.lang.String, java.lang.String, io.ballerina.stdlib.graphql.commons.types.Type, boolean, java.lang.String, io.ballerina.stdlib.graphql.commons.types.Position)'
```
However, after reverting the https://github.com/ballerina-platform/module-ballerina-graphql/pull/1238 PR, it works as expected. This can be reproduced with the master branch of GraphQL package.

**Comment by DimuthuMadushan** [comment]
Steps to reproduce:
1. Clone the  GraphQL master and publish to the local central using  `./gradlew clean build -x test -PpublishToLocalCentral=true`.
2. Run a simple GraphQL service using the published version. To use the published version, add following to the `ballerina.toml` file in the GraphQL project.
```shell
[[dependency]]
org = "ballerina"
name = "graphql"
version = "published version"
repository= "local"
```

**Comment by azinneera** [comment]
The reason is that there are two versions of the same class getting added to the classpath. One version is from a compiler-plugin dependency jar and the other is from the graphql-cli jar (added by the system classloader). The issue happens when the wrong class is loaded. We cannot control the jar that gets loaded and so to resolve this, we need to make sure to use a single version of the class.

**Comment by DimuthuMadushan** [comment]
This is not considered a bug. created an issue to track this: https://github.com/ballerina-platform/ballerina-standard-library/issues/4186

**Comment by DimuthuMadushan** [comment]
This error can happen when testing the GraphQL module with lang update 4. As a workaround, the intermediate pack generated from the GraphQL package can be used without any issues.
