### ISSUE TITLE
Change one-to-one association owner retrieval logic

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#4163]
**Description:**
Currently, this is done based on the insertion order of the entities. but this can retrieve based on the required field. the other side is always the child side of the association.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
This can be divided into following subtasks,
- [ ] Update documentation related to 1-1 relation owner derivation
- [ ] Update compiler validations of the EMD file for the 1-1 relation owner derivation
- [ ] Update tool generation for the 1-1 relation owner derivation
