### ISSUE TITLE
Ballerina persist push fails if the record name is a SQL key word

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-standard-library#4175]
**Description:**
Consider following model 
```ballerina
type Order record {|
    readonly int orderId;
    ...
```
When you try to push the tables to the database with `bal persist push` it will give the following error. 

```
ERROR: failed to read the SQL schema file(/home/jo/shipping/persist/shipping_db_script.sql). You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1
```
It will be nice if we can escape the generated sql queries so that records can have SQL keywords.

Affected version: update4

**Comment by daneshk** [comment]
@kalaiyarasiganeshalingam Shall we wrap `table name` and `column name` with backticks to avoid failing for SQL keywords
