### ISSUE TITLE
[IO]Implement a method to check the EoF in  Character I/O

### ISSUE THREAD

**Issue by sachiniSam** [ballerina-platform/ballerina-standard-library#418]
**Description** - Currently, EoF is detected as an empty string in Readable Character Channel. It would be better if we can check it using a method whether we have reached the EoF.

**Comment by BuddhiWathsala** [comment]
In the new I/O API design for Swan Lake, when you are using the API `io:fileReadLinesAsStream()`, it will return a stream of strings. Here at the end of the stream, it will return an EoFError to indicate the end. I think it will address this issue.

**Comment by BuddhiWathsala** [comment]
Also, when you read character by character, if the readable character channel reaches the end, it will return the EoFError. 

Please, reopen the ticket if you have further queries.
