### ISSUE TITLE
Enable Code Coverage for Compiler Plugins

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#4195]
**Description:**
Current code coverage reports in Ballerina standard library repos does not cover the code coverage for the compiler plugins. This can cause issues in compiler plugins and violates the 80% coverage rule in Standard Library repos. 

We should add the compiler plugin code coverage to the code coverage repos, where compiler plugins are present.

**Comment by niveathika** [comment]
This is done for all sql connectors https://github.com/ballerina-platform/ballerina-standard-library/issues/3119

**Comment by ThisaruGuruge** [comment]
Closing this as the task is almost complete.
