### ISSUE TITLE
Revisit `File` APIs, design and implement

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#420]
**Description:**
This is a part of revisiting the Standard Library module for Swan Lake release.

- [x] Draft initial Design( Modify https://docs.google.com/document/d/1dO7nBtXHWmrvKqEbqODNjpEjDj66NN8W4qQcQGjhnF0/edit#heading=h.tcrgtde9y2z5)
- [x] Get feedback from others and finalize the design
- [x] Estimate Timeline
- [ ] Implement

**Comment by ThishaniLucas** [comment]
The design has been completed and the design doc can be found here: https://docs.google.com/document/d/1dAyJ_vqkL0OfPdbx-iJVAvbWx2zOf2xGPSH8dHh8InM/edit?usp=sharing

Closing this issue and proceeding with the implementation.
