### ISSUE TITLE
Proposal: GraphQL ID scalar type

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#4202]
## Summary

The ID scalar type in GraphQL is often numeric, it should always serialize as a String. This proposal intends to introduce the annotation `@graphql:ID` in order to differentiate the scalar type ID. 

## Motivation

The ID scalar type is a unique identifier, often used to refetch an object or as the key for a cache. It is important to know for sure that it's a unique identifier which will be useful when you paginate records, modify cache etc. So in practice, it has a very practical implication, it conveys important meaning for the programmer that the field is unique for the type.

## Description

The annotation `@graphql:ID` will be introduced to GraphQL package which then can be used to define the ID in GraphQL objects in Ballerina as given below.

```ballerina
# Represents the annotation of the ID type.
public annotation ID on record field, parameter, return;
```

```ballerina
service /graphql on new graphql:Listener(4000) {
    isolated resource function get name() returns Student {
        return new Student("Jesse Pinkman", 25, "student-1");
    }
}

public isolated distinct service class Student {
    final string name;
    @graphql:ID final string id;
    final int age;

    isolated function init(string name, int age, @graphql:ID string id) {
        self.name = name;
        self.age = age;
        self.id = id;
    }

    isolated resource function get name() returns string {
        return self.name;
    }

    isolated resource function get age() returns int {
        return self.age;
    }

    isolated resource function get id() returns @graphql:ID string {
        return self.id;
    }
}
```

## Alternatives

The type `graphql:ID` can be introduced to the GraphQL package which then can be used to define the ID in GraphQL objects in Ballerina as given below.

```ballerina
distinct service class Person {
    graphql:ID id;
    private string name;

    public function init(int id, string name) {
        self.id = id;
        self.name = name;
    }

    resource function get id() returns graphql:ID {
        return self.id;
    }

    resource function get name() returns string {
        return self.name;
    }
}

```

```ballerina
public type Person record {|
    graphql:ID id;
    int age;
    string city;
|};

service /graphql on new graphql:Listener(4000) {
    private Person profile;
    function init() {
        self.profile = { name: "Walter White", age: 50, city: "Albuquerque" };
    }
    resource function get profile() returns Person {
        return self.profile;
    }
    remote function updateName(string name) returns Person {
        self.profile.name = name;
        return self.profile;
    }
    remote function updateCity(string city) returns Person {
        self.profile.city = city;
        return self.profile;
    }

```

**Comment by shafreenAnfar** [comment]
The requirement of the `ID` type is
- Values must be unique 
- Must be serialised into `string`

I am just wondering if using union types is the best option because,

- There is no boundary in possible types as ID could be in many formats (eg. int|string|uuid:Uuid or something else)
- When ID is used it is guaranteed to be string, so having a union type doesn't help

So, I am thinking if ID should be just,

```ballerina
# Represents the Scalar type ID supported by the Ballerina GraphQL module.
public type ID string;
```

**Comment by shafreenAnfar** [comment]
However, doing the above leads to usabilities issues as we always have to do to-string. There, I feel what is proposed in the alternate is better as it does not have any of the above issues.

**Comment by ThisaruGuruge** [comment]
> * There is no boundary in possible types as ID could be in many formats (eg. int|string|uuid:Uuid or something else)

Agreed. But any of these formats can be represented by either `string` or `int`. So I don't think we have an issue there.

> * On the client side when ID is used it is guaranteed to be string, so having a union type doesn't help

This isn't the case. When receiving a GraphQL response, it is guaranteed to be a `string`. But when sending a request (Eg.: in an input), it can be either a `string` or an `int`. The GraphQL client should be smart enough to serialize it correctly - similar to what the GraphQL engine is doing on the server side. 

Therefore, using only `string` is not optimal IMO. We should allow using `int` as well. 

IMHO, using a separate type is more intuitive than using a separate annotation since `ID` is a pre-defined scalar type in the GraphQL schema. Using an annotation to define a pre-defined scalar might seem like it's not first-class. WDYT?

**Comment by aashikam** [comment]
In a discussion with @ThisaruGuruge  we changed this proposal to use the annotation type `@graphql:ID` as  the design and added the `graphql:ID` as the alternative. But on further studying the other libraries I feel like @ThisaruGuruge's last comment makes the most sense.  

Here’s why having an annotation such as `@graphql:ID` to mark a field as an ID can be an issue,

1. It deviates from the spec: GraphQL is a strongly typed language, and its type system is designed to be explicit and clear. The GraphQL specification defines a set of scalar types, including ID, that can be used to define the type of a field. Using an annotation instead of a scalar type for ID would deviate from this specification and make the API less intuitive for users.
2. It may not be compatible with other GraphQL tools: Many GraphQL tools and libraries, such as GraphiQL, rely on the GraphQL specification to generate schema documentation, type-check queries, and perform other operations. Using an annotation for ID may not be compatible with these tools and could result in compatibility issues.
3. It adds complexity: Introducing a new annotation for ID would add unnecessary complexity to the language. Defining ID as a scalar type, on the other hand, is more in line with the GraphQL specification and is easier for users to understand and use.

**Graphene Python (Strong/Dynamic Typing)**
```python
import graphene

class User(graphene.ObjectType):
    id = graphene.ID(required=True) 
    name = graphene.String(required=True)
    email = graphene.String()

class Query(graphene.ObjectType):
    user = graphene.Field(User, id=graphene.ID(required=True))

    def resolve_user(self, info, id):
        # Retrieve user data from database using id
        user_data = {'id': id, 'name': 'John Doe', 'email': 'john.doe@example.com'}

        # Create and return a User object
        return User(
            id=user_data['id'],
            name=user_data['name'],
            email=user_data.get('email')
        )

schema = graphene.Schema(query=Query)

```


**GraphQL Java (Strong Typing)**

GraphQL Java library provides a `graphql.ID` scalar type that represents a unique identifier, just like `graphene.ID` in Python's Graphene library. 

```java
import graphql.annotations.GraphQLField;
import graphql.annotations.GraphQLNonNull;
import graphql.annotations.GraphQLObjectType;
import graphql.annotations.GraphQLQuery;
import graphql.annotations.GraphQLScalar;

@GraphQLObjectType("User")
public class User {
    @GraphQLField
    @GraphQLNonNull
    public graphql.ID id; 

    @GraphQLField
    @GraphQLNonNull
    public String name;

    @GraphQLField
    public String email;
    
    // ...
}

```

Introducing ID as a new GraphQL scalar type in Ballerina would be a more appropriate approach compared to using it as an annotation. Scalar types are fundamental building blocks of a GraphQL API, and they define the type of values that can be passed as input arguments and returned as query results. Overall, while the `@graphql:ID` syntax may be possible to use, using the `graphql:ID` syntax is more consistent with Ballerina's syntax and is likely to be more user-friendly.
