### ISSUE TITLE
Add short samples to each function on the ballerina Lib documentations pages

### ISSUE THREAD

**Issue by vordimous** [ballerina-platform/ballerina-standard-library#4207]
## Description
> Add samples for each library function, specifically those used in the data mapping UI.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

## Describe the problem(s)
> The small sample describing how the method/function is used can be very helpful. The [array:reduce](https://lib.ballerina.io/ballerina/lang.array/0.0.0/functions#reduce) function is one example that is good but could still be improved. 
The problem is more noticeable in the new data mapper design UI:
![image](https://user-images.githubusercontent.com/3012311/201794143-b0794e35-9555-40ec-b16a-174bf6bc619a.png)
Even the reduce function's example doesn't stand out very clearly:
![image](https://user-images.githubusercontent.com/3012311/201794188-dd9383a0-c683-4363-8e01-94171f3103e9.png)

## Describe your solution(s)
> Each function description would be improved by adding the example as a first class attribute.

**Comment by praneesha** [comment]
@daneshk @shafreenAnfar

**Comment by daneshk** [comment]
We already have one line sample for all possible functions in Standard Library API Docs. 
e.g: https://lib.ballerina.io/ballerina/uuid/1.5.0#createType1AsRecord
