### ISSUE TITLE
Revisit `System` APIs, design and implement

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#421]
**Description:**
This is a part of revisiting the Standard Library module for Swan Lake release.

- [ ] Draft initial Design
- [ ] Get feedback from others and finalize the design
- [ ] Estimate Timeline
- [ ] Implement

**Comment by MadhukaHarith92** [comment]
Duplicate issue of https://github.com/ballerina-platform/ballerina-standard-library/issues/571
