### ISSUE TITLE
[http:client] timeout not triggering

### ISSUE THREAD

**Issue by AbdulHakkam** [ballerina-platform/ballerina-standard-library#4214]
**Description:**
Timeouts dont trigger for specific API call

**Steps to reproduce:**
`    http:Client client = check new (url, {
        timeout: 10,
        auth: {
            token: token
        },
        socketConfig: {
            connectTimeOut: 5
        }
    });
     json response = check client->get(pathValue); `
_fossaUrl = "https://app.fossa.com"_

**Affected Versions:**
unsure

**OS, DB, other environment details and versions:**
- OS - Ubuntu 20.04
- Bal version - 2201.3.2
- http connector - ballerina/http 2.6.0

**Comment by TharmiganK** [comment]
@AbdulHakkam The `http` version you have specified is not associated with the `2201.3.x`. Can you check again? It should be `2.5.x`.

Also this is not reproducible with `2201.4.0` version right?

**Comment by AbdulHakkam** [comment]
@TharmiganK  Checked again and the `http` version is 2.5.3, the issue was also not reproducible in `2201.4.0`.

**Comment by shafreenAnfar** [comment]
Closing the issue as per the above comment.
