### ISSUE TITLE
Improve `asb:Message` record to be cloneable

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#4215]
**Description:**
> $subject

Related to: [#19457](https://github.com/wso2-enterprise/choreo/issues/19457)

**Comment by ayeshLK** [comment]
The improvement is done via following PR:
- https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/135

**Comment by LakshanSS** [comment]
This improvement is released with https://central.ballerina.io/ballerinax/asb/3.0.4

**Comment by ayeshLK** [comment]
Added the improvement via following PRs:
- https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/135
- https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/136

And the improvement is released [1] to the central.

[1] - https://central.ballerina.io/ballerinax/asb/3.0.4
