### ISSUE TITLE
In `Specification: Ballerina GraphQL Library` website, one table doesn't render properly (displays backticks)

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [ballerina-platform/ballerina-standard-library#4224]
**Description:**
Backticks are displayed in the table provided in the `Specification: Ballerina GraphQL Library` website under the topic 13.1.2. 
link - https://ballerina.io/spec/graphql/#131-federated-subgraph

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Under the contents in the same web page, click on the topics (13.1.1, 13.1.2, 13.1.3) doesn't jump to the respective area in the web page. 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Looks like the backticks are not correctly removed when rendering the HTML components in the `md` file. We might have to discuss this with doc team.
The subtopic link issue might be due to having `@` in the title.

**Comment by MohamedSabthar** [comment]
We could remove the markdown code blocks and simply use \<pre\> tags here. Similar to what we have done in serdes module

**Comment by ThisaruGuruge** [comment]
> We could remove the markdown code blocks and simply use \<pre\> tags here. Similar to what we have done in serdes module

+1

**Comment by ThisaruGuruge** [comment]
How does it affect the doc generation? Will the syntax highlighting work in this case?

**Comment by MohamedSabthar** [comment]
> How does it affect the doc generation? Will the syntax highlighting work in this case?

I have checked the generated doc of serdes module. Seems syntax highlighting not added with **\<pre\>** tag alone, we could try  adding this tag with lang property **\<pre lang="java"\>**. As I checked this works in [GitHub](https://github.com/MohamedSabthar/module-ballerina-graphql/blob/spec-table-update/docs/spec/spec.md#1312-the-subgraphentity-annotation). @sm1990 looking into possibility of generating doc with syntax highlighting using this tag.

**Comment by ThisaruGuruge** [comment]
Great. If we can sort out how this is displayed on the website, +1 for this approach.
