### ISSUE TITLE
onPing and onPong remote functions display wrong error messages when parameters are incorrect

### ISSUE THREAD

**Issue by thushalya** [ballerina-platform/ballerina-standard-library#4294]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/89528929/229127202-d853938a-fe3d-4bda-9b20-7b4a9166f74d.png">

**Comment by MohamedSabthar** [comment]
Fixed with: https://github.com/ballerina-platform/module-ballerina-websocket/pull/998
