### ISSUE TITLE
`io:print` and `io:println` do not show `null` for `()`

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-standard-library#4295]
**Description:**

`io:print`, `io:println` do not show `null` for `()`. Instead it shows nothing.

[`ToString`](https://ballerina.io/spec/lang/master/#ToString) of `()` is `null` in both informal and direct styles.

**Steps to reproduce:**
```bal
import ballerina/io;

public function main() {
    io:println(()); //
    io:print(()); //
    io:println([()]); // [null]
    io:print([()]); // [null]
}
```

**Affected Versions:**
Ballerina 2201.4.0 (Swan Lake Update 4)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sahanHe** [comment]
Hi @Nadeeshan96,

I checked both of following methods and the output aligns with the output of `io:println` and `io:print` methods.
```
string nullString = ().toString(); \\ output : ""
string nullString2 = [()].toString(); \\ output: "[null]"
```

In this case, current behaviour of the print functions should be correct

**Comment by Nadeeshan96** [comment]
My mistake: ToString of `()` is `""` (i.e. an empty string) in direct style. Since `io:println` and `io:print` functions use `StringUtils.getStringValue()` method, thus direct style, the above behaviour is correct. Hence, closing the issue. Please reopen if the `io:println` and `io:print` functions should use informal or expression style.
