### ISSUE TITLE
Support for providing configs to an annotation using a file without explicitly specifying each config

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#430]
Currently, to provide configs to an annotation (e.g., the `ServiceConfig` annotation in HTTP), one needs to call the relevant functions in the config API for each of the attributes in the annotation one wants to configure. 

It would be great instead of having to call the functions explicitly, the user just provides a config file with configurations for the attributes which need to be configured and automatically map and populate the attributes using these configurations.

**Comment by daneshk** [comment]
This module is deprecated and is not maintained in Ballerina now. Hence closing the issue.
