### ISSUE TITLE
The scan API does not properly handle newline characters in windows OS

### ISSUE THREAD

**Issue by madhukaw** [ballerina-platform/ballerina-standard-library#4338]
**Description:**

$Subject

This is because the check here[[1]](https://github.com/ballerina-platform/module-ballerina-toml/blob/6e481a93fb394a05cc9199ebd4fc33e376212ca1/ballerina/modules/lexer/context.bal#L21) becomes false in windows, but in ubuntu, it becomes true and works as expected.

**Steps to reproduce:**
Run this test case in windows:

```ballerina
@test:Config {
    groups: ["api"]
}
function testReadTOMLString() returns error? {
    map<json> output = check readString(string
        `bool = true
        int = 1
        float = 1.1
        arr = [1,2]
        obj = {str = "text"}

        [[date]]
        ld = 2022-06-02

        [[date]]
        ld = 2022-06-03

        [date.time]
        lt = 07:30:12`);

    test:assertEquals(output, {
        "bool": true,
        "int": 1,
        "float": <decimal>1.1,
        "arr": [1, 2],
        "obj": {
            "str": "text"
        },
        "date": [
            {"ld": "2022-06-02"},
            {
                "ld": "2022-06-03",
                "time": {
                    "lt": "07:30:12"
                }
            }
        ]
    });
}
```

**Affected Versions:**
0.1.0

**OS, DB, other environment details and versions:**
Windows

[1] https://github.com/ballerina-platform/module-ballerina-toml/blob/6e481a93fb394a05cc9199ebd4fc33e376212ca1/ballerina/modules/lexer/context.bal#L21

**Comment by nipunayf** [comment]
Currently, there is no API to determine the running OS during runtime in Ballerina. Waiting for an API as tracked here: https://github.com/ballerina-platform/ballerina-standard-library/issues/4931 to resolve this issue.
