### ISSUE TITLE
Find out a way to setting up the database tables/spreadsheet in consistent way

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#4352]
**Description:**
Currently, we are generating SQL scripts as we only have a DB Client. Since we are supporting spreadsheet support as well. We need to find a consistent way to support setting up the servers for the persistent application.

@sahanHe Can you list down the steps we need with the HTTP endpoint to setup gsheet to startwith.

**Comment by daneshk** [comment]
One option is to create an HTTP Client script like in the plugin [1] for the gsheets API. And keep SQL scripts for the DB Client

1. https://marketplace.visualstudio.com/items?itemName=humao.rest-client

**Comment by sahanHe** [comment]
We can use ballerina google sheets connector to generate a `.bal ` file containing the required code to create spreadsheets and worksheets to store the data. We can ask the user to run the generated `.bal` file. A sample `.bal` file to create spreadsheets/sheets for a single entity would look like following.

```ballerina
import ballerina/io;
import ballerinax/googleapis.sheets;

sheets:ConnectionConfig sheetsClientConfig = {
        auth: {
            clientId: clientId,
            clientSecret: clientSecret,
            refreshUrl: sheets:REFRESH_URL,
            refreshToken: refreshToken
            }
        };

sheets:Client spreadsheetClient = check new (sheetsClientConfig);

public function main() returns error? {
    sheets:Spreadsheet spreadSheet = check spreadsheetClient->createSpreadsheet(worksheetName);
    io:println("SpreadSheet ID :" + spreadSheet.spreadsheetId);
    sheets:Sheet workSheet = check spreadsheetClient->addSheet(spreadSheet.spreadsheetId, "OrderItems");
    _ = check spreadsheetClient->appendRowToSheet(spreadSheet.spreadsheetId, workSheet.properties.title, ["orderId", "itemId", "quantity", "notes"], "A:E", "USER_ENTERED");
    _ = check spreadsheetClient->removeSheet(spreadsheetId, 0);
}

```

**Comment by sahanHe** [comment]
If we use the http endpoint to initialise the spreadsheets, steps would be similar to following.

1. Create the spreadsheet using [create](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/create) API and return the spreadsheetId to the user.
2. For each entity, a sheet will be created in the spreadsheet using [batchUpdate](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchUpdate) API.
3. For each entity, the column headers should be appended using [append](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append) API

**Comment by daneshk** [comment]
Decided to use app scripts for google sheets and SQL scripts for RDMS. Hence closing the issue
