### ISSUE TITLE
[Persist] Refactor error messages to be consistent across datasources

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#4360]
**Description:**
Currently, the error messages given (e.g. when a record doesn't exist, duplicate record etc.) is different when MySQL is used as a datasource vs. when Ballerina tables is used as a datasource.

The objective is the ensure that regardless of the data source, the same error message is given

**Comment by kaneeldias** [comment]
## Proposed error message formats

### `NotFoundError`
A record with the key '`{Key}`' does not exist for the entity '`{EntityName}`'.

e.g.:
- A record with the key '{id: "b746bad4-c8ae-425b-ae32-c857228dd969"}' does not exist for the entity 'User'
- A record with the key '(studentId: 1, subjectId: "maths 1"}' does not exist for the entity 'Score'



### `AlreadyExistsError`
A record with the key '`{Key}`' already exists for the entity '`{EntityName}`'.

e.g.:
- A record with the key '{id: "b746bad4-c8ae-425b-ae32-c857228dd969"}' already exists for the entity 'User'
- A record with the key '(studentId: 1, subjectId: "maths 1"}' already exists for the entity 'Score'

### `ConstraintViolationError`
This would simply wrap and return the error message generate by the database.

e.g.: 

- Cannot add or update a child row: a foreign key constraint fails (\`test\`.\`Employee\` CONSTRAINT \`Employee_ibfk_2\` FOREIGN KEY (\`workspaceWorkspaceId\`) REFERENCES \`Workspace\` (\`workspaceId\`)).

**Comment by daneshk** [comment]
Looks good @kaneeldias

**Comment by daneshk** [comment]
This issue is already fixed. Hence closing the issue.
