### ISSUE TITLE
[Persist][Compiler Validator] Limit schema field types based on the data store provider

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#4391]
**Description:**
Google Sheets store only supports very few datatypes like string, decimal, boolean, int, float, etc. And we decided to the support date/time type by converting it to the string. So from the compiler validator, we need to restrict setting unsupported data types. 

e.g:
If the user tries to add byte[] type for the google sheets store, we need to give an error.

We need to maintain a supported type list for each data store and validate based on the configured data store in the `Ballerina.toml` file.

**Comment by daneshk** [comment]
@sahanHe Please add gsheet-supported data types

**Comment by kaneeldias** [comment]
Supported data types for each datastore

**MySQL**
- `()`
- `boolean`
- `int`
- `string`
- `float`
- `decimal`
- `byte[]`
- `time:Date`
- `time:TimeOfDay`
- `time:Civil`
- `time:Utc`

*In-Memory*
- `any`
- `error`

*Google Sheets*
- `()`
- `boolean`
- `int`
- `string`
- `float`
- `decimal`
- `time:Date`
- `time:TimeOfDay`
- `time:Civil`
- `time:Utc`
