### ISSUE TITLE
Task Scheduler intermittently freezes

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-standard-library#440]
**Description:**
`ListenerImapReceiveTest` and `ListenerPopReceiveTest` are intermittently freezes in Email Connector integration tests as the Scheduler freezes intermittently. 

**Steps to reproduce:**
When running the Integration tests where the above test cases are enabled, the process hangs on at the above tests intermittently.

**Comment by kalaiyarasiganeshalingam** [comment]
Closing this due to this fixed in https://github.com/ballerina-platform/ballerina-standard-library/issues/59
