### ISSUE TITLE
Implement listener level interceptors using `createInterceptors` function.

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#4420]
**Description:**
```ballerina
import ballerina/http;

service class MyRequestInterceptor {
    *http:RequestInterceptor;

	resource function 'default [string... path](http:RequestContext ctx) returns http:NextService|error? {
		return ctx.next();
	}
}

service class MyResponseInterceptor {
    *http:ResponseInterceptor;

	remote function interceptResponse(http:RequestContext ctx) returns http:NextService|error? {
		return ctx.next();
	}
}

// Ideally, this will be a part of `http` module
public type CreateInterceptorsFunction function () returns http:Interceptor[];

// The function implementation. Note the tuple return type.
function createInterceptors() returns [MyResponseInterceptor, MyRequestInterceptor] {
    return [new MyResponseInterceptor(), new MyRequestInterceptor()];
}

// This class is just to mock the `http:Listener`
public class Listener {
	http:Interceptor[] interceptors;
	int port;

	function init(int port, CreateInterceptorsFunction interceptors) {
		self.port = port;
		self.interceptors = interceptors();
	}
}

Listener serverEP = new(9090, interceptors = createInterceptors);
```

For the discussion see https://github.com/ballerina-platform/ballerina-standard-library/issues/4300

**Comment by dilanSachi** [comment]
- [ ] Add runtime support for the change
- [ ] Add compiler level deprecations
- [ ] Update BBEs and samples

**Comment by dilanSachi** [comment]
The issue here when adding a new parameter for the `http:Listener` initialization is it may break the existing users.
```bal
public isolated function init(int port, CreateInterceptorsFunction? interceptorsFunction, *ListenerConfiguration config)
            returns ListenerError? {
```
As a solution we can add the `interceptorsFunction` as a field in `http:ListenerConfiguration`.
```bal
public type ListenerConfiguration record {|
    ...
    # interceptors - An array of interceptor services
    # # Deprecated
    # Defining interceptor pipeline in `http:ListenerConfiguration` is deprecated. Define the interceptor pipeline
    # via `http:InterceptableService` service type
    @deprecated
    Interceptor|Interceptor[] interceptors?;
    ...
    CreateInterceptorsFunction interceptorsFunction?;
|};
```

However this may introduce some complexities when giving compiler errors to the user.

**Comment by dilanSachi** [comment]
> We can add the default value as `nil` for `interceptorsFunction` right? Then it won't be a breaking change

No right?
For a old listener initialization as follows,
```bal
http:Listener ls = check new (5005, "localhost");
```
This will give an error as `incompatible types: expected 'ballerina/http:2.7.1:CreateInterceptorsFunction?', found 'string'` right

**Comment by TharmiganK** [comment]
> > We can add the default value as `nil` for `interceptorsFunction` right? Then it won't be a breaking change
> 
> No right? For a old listener initialization as follows,
> 
> ```ballerina
> http:Listener ls = check new (5005, "localhost");
> ```
> 
> This will give an error as `incompatible types: expected 'ballerina/http:2.7.1:CreateInterceptorsFunction?', found 'string'` right

Yes, it will break if we have given the config map directly as the second parameter. 

So we have three options here:
Options | Pros | Cons
--------|------|------
Have two different fields in the `ListenerConfiguration` and deprecate one|- Meaningful separation|- Need to add a runtime error when the two fields are used<br>- Connectors need to update their configurations
Change the `interceptors` type to be union with `CreateInterceptorsFunction`|- Can only use one way to define the interceptor|- Field name does not match with the type<br>- Connectors need to update their configurations
Wrap `http:Listener` into `http:InterceptableListener`|- Can only use one way to define the interceptor|- Connectors need to use `http:InterceptableListener` instead if they are having interceptors<br>- Abstraction is not perfect since the `http:Listener` anyway have the `DefaultInterceptor`

**Comment by dilanSachi** [comment]
Decided go ahead with option 2

**Comment by dilanSachi** [comment]
Decided to stop supporting interceptors in listener level.
1. Even if we provide the interceptors as a function, it is difficult for openapi to read the types from that.
2. We can do the same things we do by using service level interceptors. (However there are some challenges in this).
      - To handle `not found` cases when there are multiple service attached. Decided to resolve this by needing to add a root level (`/`) interceptor.
