### ISSUE TITLE
Work on springboot and ballerina comparison

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#4454]
**Description:**
- [ ] Check if its reactive
- [ ] Code concise
- [ ] Concurrent safe by default
- [ ] Do load test for both
           - Get thread dump while running
           - Before and after
- [ ] Writing tests
           - How to mock

**Comment by dilanSachi** [comment]
@ayeshLK tagged you incase you need to track the things.

**Comment by ayeshLK** [comment]
Following structure will be followed in the comparison:
1. Overview
2. Features
 2.1. Exposing REST APIs
 2.2 Request validation
 2.3 Error handling
 2.4 Consuming REST APIs
 2.5 Interacting with relational databases
 2.6 OpenAPI specification support
 2.7 Configurability
 2.8 Code to cloud

@shafreenAnfar WDYT ?

**Comment by shafreenAnfar** [comment]
Lets add GraalVM as well.

**Comment by ayeshLK** [comment]
Following doc [1] contains the initial draft for the proposed comparison.

[1] - https://docs.google.com/document/d/12usMKYH80zY0y0J6lV53QChA4FaGeNpfgJ-9AJcWP2I/edit?usp=sharing

**Comment by ayeshLK** [comment]
Currently this changes are in the pre-prod deployment [1]. Hence, closing the issue.

[1] - https://pre-prod.ballerina.io/usecases/integration/replace-springboot/
