### ISSUE TITLE
[WebSocket] Skipped some WebSocket testcases 

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#446]
**Description:**

Couldn't migrate the following tests  due to some issues 

- The Websocket client doesn't support to send the corrupted frame[[25669](https://github.com/ballerina-platform/ballerina-lang/issues/25699)]

   https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M4/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/IsOpenTest.java#L63 

   https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M4/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ServerErrorsTest.java#L44

   https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M4/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/OnErrorWebSocketTest.java#L55

- __gracefullyStop() didn't work properly[[25675](https://github.com/ballerina-platform/ballerina-lang/issues/25675)]

  https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M4/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/RetryClientTest.java

  https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M4/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/FailoverClientTest.java#L109

   https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M4/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/FailoverClientTest.java#L126
  
   https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M4/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/FailoverClientTest.java#L142

**Comment by Bhashinee** [comment]
These test cases are no longer valid
