### ISSUE TITLE
[Websocket] Couldn't send the corrupted frame by using WebSocket client

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#447]
**Description:**
$Subject

**Comment by Bhashinee** [comment]
This is covered with newly added https://github.com/ballerina-platform/module-ballerina-websocket/blob/main/websocket-ballerina/tests/corrupted_frame_client_test.bal, https://github.com/ballerina-platform/module-ballerina-websocket/blob/main/websocket-ballerina/tests/corrupted_frame_server_test.bal
tests
