### ISSUE TITLE
MSSQL support for Ballerina persist

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-standard-library#4506]
**Description:**

Currently, Ballerina persist module does not support MSSQL. I modified the generated code to use MSSQL and tried in my use case.  This request is to prioritise MSSQL support. 

**Describe your problem(s)**

Specific issue I am facing is related to `Updates` and `Deletes` for MSSQL. However, `Adds` did work. I got below error in my case.
 
```
Error: Error while executing SQL query: UPDATE StoreAPI StoreAPI SET  name =  ? , version =  ? , description =  ? , idlPath =  ? , thumbnailPath =  ? , documentationPath =  ? , updatedTime =  ?  WHERE  StoreAPI.apiId =  ? . Incorrect syntax near 'StoreAPI'..
```

**Describe your solution(s)**
N/A

**Comment by sameerajayasoma** [comment]
I can see two `StoreAPI` components in the SQL statement. Is that the issue?

**Comment by abeykoon** [comment]
@sameerajayasoma I and @daneshk had a look. 
@daneshk's thinking was in MSSQL the query structure is bit different.

**Comment by daneshk** [comment]
@abeykoon  Can you test your failed scenarios in update 06?

**Comment by abeykoon** [comment]
Thanks. Will test and get back.
