### ISSUE TITLE
Need to improve the error message when inserting the `time:civil` field without `utcOffset` value

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#4533]
**Description:**
Getting the following error when inserting the civil field without `utcOffset` value to the Google sheet datastore. 
```
error: civil.utcOffset must not be null
```
This error returns when converting `time:Civil` value to String. I think we have to validate the given civil value in our module and return the custom error.

**Steps to reproduce:**
Run the following code with this entity to reproduce this error.

Entity:
```
type MedicalNeed record {|
    readonly int needId;
    int itemId;
    int beneficiaryId;
    time:Civil period;
    string urgency;
    int quantity;
|};
```

```ballerina
import ballerina/io;
import foo/medical_center.entities;

public function main() returns error? {
    entities:Client mcClient = check new ();
    entities:MedicalNeed mnItem2 = {
        needId: 2,
        itemId: 2,
        beneficiaryId: 2,
        period: {year: 2021, month: 10, day: 10, hour: 1, minute: 2, second: 3},
        urgency: "NOT URGENT",
        quantity: 5
    };
    int[] needIds = check mcClient->/medicalneeds.post([mnItem2]);
    io:println("Created need id: ", needIds[0]);
    check mcClient.close();
}
```

**Comment by sahanHe** [comment]
After the fix in [26](https://github.com/ballerina-platform/module-ballerinax-persist.googlesheets/pull/26) we no longer employ `ballerina/time` module for converting `time:civil` values to string. So this issue is no longer valid for the persist module as the value will be saved and retrieved without any redundant validations
