### ISSUE TITLE
Support subtypes of `int` in protoc-tool and gRPC

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#4543]
**Description:**
At the moment, for types like uint32, uint16 we generate the type as `int`. However we need to support these subtypes as ballerina now supports some of these subtypes in proto definitions.

[ ] Update the protoc-tool.
[ ] Update the runtime impelementation in gRPC (AFAIR, this was fixed earlier. Need to reconfirm).

**Comment by MadhukaHarith92** [comment]
Need to support the following types

- Signed8
- Signed16
- Signed32
- Unsigned8
- Unsigned16
- Unsigned32
