### ISSUE TITLE
Add support for executing native queries in SQL databases

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#4546]
**Description:**
The user should be able to execute native queries directly from the generated clients in SQL databases like,

```ballerina
// return actual rows
stream<Employee, persist:Error?> employees = sClient->nativeQuery(`SELECT * FROM EMPLOYEE`);

// execute create/update queries
persist:ExecutionResult|persist:Error result = sClient->nativeExecute(`UPDATE ....`);
```

**Describe your problem(s)**
With the current support, the user can't execute advanced queries efficiently. He needs to load all the results to in-memory and process them using Ballerina query syntaxes. This is not an efficient way to do it when there are a lot of records. In order to cater to all requirements, especially for the SQL databases, better if we can give support to execute native queries.

**Describe your solution(s)**

In the generated clients for SQL databases, provide new a `remote function` to pass Parameterized Queries like in normal SQL connectors.

```ballerina
  remote isolated function nativeQuery(sql:ParameterizedQuery sqlQuery, typedesc<record {}> rowType = <>)
  returns stream<rowType, persist:Error?> = @java:Method {
      'class: "io.ballerina.stdlib.persist.sql.QueryProcessor"
  } external;

  remote isolated function nativeExecute(sql:ParameterizedQuery sqlQuery)
   returns persist:ExecutionResult|persist:Error = @java:Method {
       'class: "io.ballerina.stdlib.persist.sql.ExecuteProcessor"
  } external;
```

**Reference**
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access

**Comment by daneshk** [comment]
@sameerajayasoma WDYT?

**Comment by sameerajayasoma** [comment]
Looks good.

We have `query()` and `execute()` functions in our `ballerina/sql` package. 

Shall we use the same naming convention? Something like this: `queryNativeSQL()` and `executeNativeSQL()`. These two names are a tad long, but it's okay, as they are part of the escape hatch.  Also, these names start with a verb :)

**Comment by daneshk** [comment]
@kaneeldias Can you check this

**Comment by kaneeldias** [comment]
This issue is currently blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/40825

**Comment by sameerajayasoma** [comment]
Any update on this issue? Can we push this to update 8? @hasithaa
