### ISSUE TITLE
Add Support to Define Constraints on Scalar Args

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#4596]
**Description:**
Currently, the GraphQL package has input constraints validation support only for the input objects. Since GraphQL doesn't allow to define of type aliases for primitive types, there is no way to define constraints on Scalar inputs. It needs to define an annotation that can apply to a function parameter to define the constraints on scalar-type arguments.

**Comment by DimuthuMadushan** [comment]
This needs the [custom scalar type support](https://github.com/ballerina-platform/ballerina-standard-library/issues/4182) as a prerequisite.

**Comment by ThisaruGuruge** [comment]
Closing this as we do not have plans to implement this anytime soon. We can reopen it if the requirement arises again.
