### ISSUE TITLE
GraphQL Error Path Does not Use Aliases

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#4634]
**Description:**
According to the [GraphQL specification](https://spec.graphql.org/October2021/#sec-Errors), the error path should include the alias if there's an alias. Check the excerpt from the spec:

> If the error happens in an aliased field, the path to the error should use the aliased name, since it represents a path in the response, not in the request.

But the current Ballerina GraphQL implementation does not adhere to this. 
Check the following code:

```ballerina
import ballerina/graphql;

service on new graphql:Listener(9090) {
    resource function get greeting() returns Person {
        return new;
    }
}

service class Person {
    resource function get name() returns string|error {
        return error("Name not found");
    }
}
```

Send the following document to this service:

```graphql
{
  greeting {
    fname: name
    lname: name
  }
}
```

This returns the following response:

```json
{
  "errors": [
    {
      "message": "Name not found",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "greeting",
        "name"
      ]
    },
    {
      "message": "Name not found",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "greeting",
        "name"
      ]
    }
  ],
  "data": null
}
```

In the above response, the error path is using the field name instead of the alias. 

The correct response should be the following:

```json
{
  "errors": [
    {
      "message": "Name not found",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "greeting",
        "fname"
      ]
    },
    {
      "message": "Name not found",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "greeting",
        "lname"
      ]
    }
  ],
  "data": null
}
```

**Comment by Ishad-M-I-M** [comment]
@ThisaruGuruge can you assign this to me?
I already opened a PR on this

**Comment by ThisaruGuruge** [comment]
> @ThisaruGuruge can you assign this to me? I already opened a PR on this

Hi @Ishad-M-I-M, Thank you for the contribution. I've assigned the issue to you. I will check on the PR.
