### ISSUE TITLE
Records serialized using toString() when sending an HTTP response

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#464]
When setting a record as the payload in an HTTP response, it seems to get serialized using the string obtained by calling `toString()` on it. IINM, it should instead be serialized as a JSON object, which can be done by calling `toJsonString()` on the value.

**Comment by chamil321** [comment]
Issue seems to be no longer valid for the current source code. The `anydata` is treated as follows [1]
```ballerina
isolated function processJsonContent(anydata message) returns json|ClientError {
    var result = trap val:toJson(message);
    if result is error {
        return error InitializingOutboundRequestError("json conversion error: " + result.message(), result);
    }
    return result;
}
```

[1] https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/http_commons.bal#L99
