### ISSUE TITLE
Listing the Ballerina GraphQL Under the Apollo Federation Supported Libraries

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#4676]
**Description:**
>$subject

Federation-compatible subgraph implementations: https://www.apollographql.com/docs/federation/building-supergraphs/supported-subgraphs/

**Comment by ThisaruGuruge** [comment]
Closing the issue as this is now completed. (The changes are not yet reflected on the website, even though the changes are merged. To reflect the changes on the website, the maintainers of the [Apollo Federation Subgraph Compatibility](https://github.com/apollographql/apollo-federation-subgraph-compatibility) repo should release the repo, which [hasn't happened yet](https://github.com/apollographql/apollo-federation-subgraph-compatibility/releases)).
