### ISSUE TITLE
Ballerina app stuck

### ISSUE THREAD

**Issue by chipsmaster** [ballerina-platform/ballerina-standard-library#468]
**Description:**

Hello, we have a ballerina app in production and sometimes it "hangs", it's stuck in various cases, it can be during a http client request or when doing nothing

It's not reproducible, i'd just like hints or advice to troubleshoot this

The application contains :
- 3 rabbitmq consumer services, each one with their dedicated connection and listener (although it's on the same rabbitmq server)
- 1 ftp listener service with ballerina/ftp aditional module (version 0.5.0)
- 1 scheduled task (triggers 1 time at night, just enqueues a message)

It does not contain http services.

Each service seem to not share any global object, it creates dedicated objects (like a new rabbitmq connexion to send messages)

Is there any logging option that i can enable to have more information when it does this ?

**Affected Versions:**
1.2.4

**OS, DB, other environment details and versions:**
Debian buster

**Comment by chamil321** [comment]
@chipsmaster Were you able to reproduce the same issue in later ballerina versions?

**Comment by ayeshLK** [comment]
@chipsmaster currently we are unable to reproduce this issue since we do not have any steps to reproduce this. Could you please share some sample code which we could use to reproduce the issue ?

**Comment by chamil321** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack](https://ballerina.io/community/slack/) or discuss the issue in ballerina-dev@googlegroups.com. Thank you for your contributions!
