### ISSUE TITLE
Avoid Adding All Possible Federated Directives to SDL String in GraphQL Subgraph

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-standard-library#4681]
**Description:**
The Current Implementation of Subgraph Includes All the Federated Directives Listed Here: https://www.apollographql.com/docs/federation/subgraph-spec.

Since the current implementation only supports the @key directive, we should only add this directive to the auto-generated SDL string.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
Closing as this has to be confirmed from the Apollo federation spec. @DimuthuMadushan let's link the issue here.

**Comment by DimuthuMadushan** [comment]
issue: https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/475

**Comment by DimuthuMadushan** [comment]
Re-open the issue since this has confirmed by the Apollo federation. https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/475#issuecomment-1654246013
