### ISSUE TITLE
Config related exceptions thrown aren't formatted as a launcher exception

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#473]
Any issues related to configs should be reported as a launcher exception and rendered to the user in the console with the `error:` prefix. 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ballerina-dev/JICqg6YrRjk/AzuubwtWFAAJ

**Comment by daneshk** [comment]
This module is deprecated and is not maintained in Ballerina now. Hence closing the issue.
