### ISSUE TITLE
`int range overflow` error when using valid range in `random:createIntInRange` function

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-standard-library#4744]
**Description:**

$title

**Steps to reproduce:**
```bal
import ballerina/io;
import ballerina/random;

public function main() returns error? {
    int intResult = check random:createIntInRange(int:MIN_VALUE, int:MAX_VALUE);
    io:println(intResult);
}
```

I see we doing `endRange - startRange` in `natives.bal` file which give this. But I think we need to support the whole int range to give a random number. The documentation also says `Generates a random number between the given start(inclusive) and end(exclusive) values`.

**Affected Versions:**
1.5.0-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vil02** [comment]
Would you consider the following modification of the [`createIntInRange`](https://github.com/ballerina-platform/module-ballerina-random/blob/2dbd7fc982c6014c2439450492950fb46e7fe95f/ballerina/natives.bal#L44) function as a fix for this issue?


```ballerina
public isolated function createIntInRange(int startRange, int endRange) returns int|Error {
    if startRange > endRange {
        return error Error("End range value must be greater than the start range value");
    }
    if startRange == int:MIN_VALUE && endRange == int:MAX_VALUE {
        if createIntInRange(0, 2) == 0 {
            return createIntInRange(startRange, 0);
        }
        else {
            return createIntInRange(0, endRange);
        }
    }
    return <int>(lcg() / m * <decimal>(endRange - startRange - 1) + <decimal>startRange);
}
```

**Comment by Shivamkotalia2002** [comment]
@Nadeeshan96 can i fix this issue?

**Comment by Nadeeshan96** [comment]
👋 Welcome, @vil02 and @Shivamkotalia2002! 🚀

We're thrilled to have you join the Ballerina Lang community! Whether you're a seasoned developer or just starting your journey with Ballerina, we value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

1. Understanding [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md):
Learn what Ballerina is all about: Ballerina Platform
2. How to Contribute:
Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
3. Contributing to the Ballerina library:
If you're interested in contributing to our library, here are the guidelines: [Library Contribution Guide](https://github.com/ballerina-platform/ballerina-standard-library/blob/main/CONTRIBUTING.md)
4. [Learn Ballerina](https://ballerina.io/learn/):
If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: Learn Ballerina
5. Get Help and Connect:
Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!
Happy coding! 🎉

**Comment by Nadeeshan96** [comment]
> Would you consider the following modification of the [`createIntInRange`](https://github.com/ballerina-platform/module-ballerina-random/blob/2dbd7fc982c6014c2439450492950fb46e7fe95f/ballerina/natives.bal#L44) function as a fix for this issue?
> 
> ```ballerina
> public isolated function createIntInRange(int startRange, int endRange) returns int|Error {
>     if startRange > endRange {
>         return error Error("End range value must be greater than the start range value");
>     }
>     if startRange == int:MIN_VALUE && endRange == int:MAX_VALUE {
>         if createIntInRange(0, 2) == 0 {
>             return createIntInRange(startRange, 0);
>         } else {
>             return createIntInRange(0, endRange);
>         }
>     }
>     return <int>(lcg() / m * <decimal>(endRange - startRange - 1) + <decimal>startRange);
> }
> ```

With this also if you pass the args `(int:MIN_VALUE, int:MAX_VALUE)` it will give the `int range overflow` error, because it produce it should produce a value out of integer's range. And the other thing is it needs to be handled for all the possible arguments. For example passing `(int:MIN_VALUE + 20, int:MAX_VALUE - 20)` should work also. Having a single if condition is not enough. It is also better to produce a uniformly distributed int value with the given range.

**Comment by Shivamkotalia2002** [comment]
@Nadeeshan96          

                                                                                                                                                                                                            import ballerina/io;
import ballerina/random;

public function main() returns error? {
    int intResult = check random:createIntInRange(int:MIN_VALUE, int:MAX_VALUE - 1);
    io:println(intResult);
}


this code may solve the issue

**Comment by Nadeeshan96** [comment]
> @Nadeeshan96 can i fix this issue?

@vil02 , @Shivamkotalia2002 Sure! You can fix the issue and send PR to https://github.com/ballerina-platform/module-ballerina-random repository. It is better to add tests along with the fix. Please feel free to raise any issue you come across in the Ballerina Library.

**Comment by vil02** [comment]
@Nadeeshan96 could you please assign me to this issue?
