### ISSUE TITLE
enhancement : allow config file path as an URL

### ISSUE THREAD

**Issue by crognon** [ballerina-platform/ballerina-standard-library#475]
**Description:**
It would be nice to be able to provide a config file as an url ! 

If the config API can use a url path to the file it would be easy to use the Spring cloud config server combined with ballerina and it would rock. Or any url based config system.

**Suggested Labels (optional):**
config integration usability

Thanks
Cyril

**Comment by daneshk** [comment]
This module is deprecated and is not maintained in Ballerina now. Hence closing the issue.
