### ISSUE TITLE
Map Ballerina Number Constraints to OpenAPI Specification

### ISSUE THREAD

**Issue by SachinAkash01** [ballerina-platform/ballerina-standard-library#4796]
**Description:**

Map following Ballerina constraints to OpenAPI specification,
- `@constraints:Int {}`
- `@constraints:Float {}`
- `@constraints:Number {}`

**Duration:** 3 days

**Comment by ayeshLK** [comment]
Fixed with: 
- https://github.com/ballerina-platform/openapi-tools/pull/1541
