### ISSUE TITLE
Revisit gRPC BBEs and support testing them in distribution build

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#48]
**Description:**
Current BBE modules need to revisit and incorporate with the new changes.

**Comment by BuddhiWathsala** [comment]
As a subtask, we need a better way to pass this(https://github.com/ballerina-platform/ballerina-distribution/commit/4af483997d546e843b1d8c51b23099ca04d205fc) keystore and truststore file to the gRPC service and client.

**Comment by daneshk** [comment]
This is supported now, hence closing the issue
