### ISSUE TITLE
Write a Real World Example for Auth

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#4819]
**Description:**
Currently, there is an [example](https://github.com/ballerina-platform/module-ballerina-auth/tree/master/examples/order-management-service) in the Ballerina auth repository that utilizes the LDAP user store. We need to add another example to the auth module, preferably one that incorporates file user store with scopes.

**Comment by ThisaruGuruge** [comment]
Hi @DevTomilola-OS! 🚀

We value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

- Understanding Ballerina Platform: Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)
- How to Contribute: Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- Learn Ballerina: If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)
- Get Help and Connect: Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!

Happy coding! 🎉

**Comment by DevTomilola-OS** [comment]
Hello @keizer619 I'm sorry I won't be working on this issue anymore. Thank you.

**Comment by harshalkh** [comment]
@DevTomilola-OS please assign to me, I can work on this.

**Comment by ThisaruGuruge** [comment]
> @keizer619 @ThisaruGuruge can you please assign this to me, I can work on this. As @DevTomilola-OS won't be working on this as per his comments.

Hi @harshalkh,

Thank you for considering this issue. I have assigned it to you now.

**Comment by harshalkh** [comment]
@ThisaruGuruge @DimuthuMadushan I am trying to setup few things and giving a try to execute APIs. Got some strange issue - /foo/bar works without any issue, whereas /accounts/account not...

https://github.com/harshalkh/module-ballerina-auth/pull/3
GitHub workflow to test my code - https://github.com/harshalkh/module-ballerina-auth/blob/master/.github/workflows/ballerina.yml
Any help that you can provide?

**Comment by harshalkh** [comment]
@DimuthuMadushan as per suggestion I have enabled SSL as well as added test cases. Still not able to figure out where it's failing. Can you pls refer above links and suggest?
Latest run where tests also failing - https://github.com/harshalkh/module-ballerina-auth/actions/runs/6512926615/job/17691536843

**Comment by harshalkh** [comment]
@DimuthuMadushan / @ThisaruGuruge  Finally I am able to raise PR - https://github.com/ballerina-platform/module-ballerina-auth/pull/1057 

Please review and let me know if any suggestions.

**Comment by DimuthuMadushan** [comment]
Hi @harshalkh That's great! I glanced at the PR and made a few minor suggestions.

**Comment by harshalkh** [comment]
@DimuthuMadushan @ThisaruGuruge - I have made requested changes. Please verify and let me know if anything needs to change.
Thanks.

**Comment by harshalkh** [comment]
> @DimuthuMadushan @ThisaruGuruge - I have made requested changes. Please verify and let me know if anything needs to change. Thanks.

@DimuthuMadushan @ThisaruGuruge - I have done requested changes and verified test cases as well.. please check.

**Comment by DimuthuMadushan** [comment]
Hi @harshalkh we have approved your PR. Thank you for your valuable contribution. :tada:
