### ISSUE TITLE
[HTTP/2] Unnecessary  TCP connection creation to upstream 

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-standard-library#494]
Tested scenario: With 300 concurrency and 50 streams per connection(default stream count), during the first second 196 connections were created for just one upstream. This behavior is seen across all concurrency levels and defeats the whole purpose of HTTP/2. 

According to the spec https://tools.ietf.org/html/rfc7540

"Clients SHOULD NOT open more than one HTTP/2 connection to a given
   host and port pair"

That being said since ballerina client can have thousands of requests between a given server-upstream pair, it is okay to create multiple connections but that should be governed by the maxActiveStream property. Current behavior which creates arbirtraty number of connections at the beginnning is unacceptable and goes against the spec.

**Comment by chamil321** [comment]
Following improvements were found:
- Allow the first thread to initiate the target channel and add to the PerRouteConnectionPool.

> Previous implementation had a concurrency issue to initiate the pool and add channels to the pool. Due to asynchronous behaviour every thread tries to add new channels when the channel queue is empty in the PerRouteConnectionPool.

- Allow other strands also to have pass properties. Outbound calls which done in workers do not have related Source handler info.
> Previous implementation had only passed properties from main stand without considering the workers. Hence request flow is has been different from the expected flow.

**Comment by shafreenAnfar** [comment]
I and @chamil321 had a call on this and decided to do the following.  The below is a code snippet from the current code. 

```ballerina
public Http2ClientChannel borrowChannel(Http2SourceHandler http2SrcHandler, HttpRoute httpRoute) {
    EventLoopPool eventLoopPool;
    String key = generateKey(httpRoute);
    EventLoopPool.PerRouteConnectionPool perRouteConnectionPool;

    if (http2SrcHandler != null) {
        eventLoopPool = getOrCreateEventLoopPool(http2SrcHandler.getChannelHandlerContext().channel().eventLoop());
        perRouteConnectionPool = getOrCreatePerRoutePool(eventLoopPool, key);

    } else {
        if (eventLoops.isEmpty()) {
            return null;
        }
        eventLoopPool = getOrCreateEventLoopPool(eventLoops.peek());
        perRouteConnectionPool = getOrCreatePerRoutePool(eventLoopPool, key);
    }

    Http2ClientChannel http2ClientChannel = null;
    if (perRouteConnectionPool != null) {
        http2ClientChannel = perRouteConnectionPool.fetchTargetChannel();
    }
    return http2ClientChannel;
}
```
If the source handler is available we create a connection pool attached to that if not we create a connection pool attached to the client. In the case of HTTP/1.1 it makes sense to do this but in the case of HTTP/2 I don't think it makes sense to do the same. Because in the case of HTTP/2 we can multiplex many requests using a single connection. The connection is represented using `Http2ClientChannel` and as long as it is thread safe it is good enough.

If we see any contentions or any performance hit we can look into introducing HTTP/1.1 like source handler based connection pools.

**Comment by chamil321** [comment]
Further removed the H2Connection manager pool which kept against the h1 channel event loop. Hence only 1 channel pool will be maintained in the H2ChannelPool Class and clients will get a per route pool.

Eg: If the maxActiveStreamsPerConnection is 50, then with 300 concurrancy, only 6 channel will get created and maintained.

## Load test results
#### h2_h2_passthrough
Client : JMeter
Passthrough : h2 ballerina Listener and h2 ballerina client
Backend : h2 ballerina Listener
<img width="535" alt="Screenshot 2022-07-05 at 13 59 16" src="https://user-images.githubusercontent.com/8381003/177291496-2cfd47f5-d27f-4ae5-9d72-a435a0f976fb.png">

300C 10min new implementation

<img width="1033" alt="300New10Min" src="https://user-images.githubusercontent.com/8381003/177291649-33477f1a-82aa-46f6-9485-bdeebdc56c9b.png">

300C 10min old implementation
<img width="1048" alt="300Old10Min" src="https://user-images.githubusercontent.com/8381003/177291704-8741d44b-5f8a-4c53-a574-6eb1ed7b49ea.png">

**Comment by chamil321** [comment]
### HTTP Pass-through Load Tests
#### Sample Code
```ballerina
import ballerina/http;

listener http:Listener securedEP = new(9090,
    httpVersion = "2.0",
    secureSocket = {
        key: {
            path: "certsandkeys/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }
);

final http:Client nettyEP = check new("https://localhost:8688",
    httpVersion = "2.0",
    secureSocket = {
        cert: {
            path: "certsandkeys/ballerinaTruststore.p12",
            password: "ballerina"
        },
        verifyHostName: false
    }
);

service /passthrough on securedEP {
    resource function post .(http:Caller caller, http:Request clientRequest) returns error? {
        http:Response response = check nettyEP->forward("/service/EchoService", clientRequest);
        return caller->respond(response);
    }
}
```

#### Results

|Label                         |# Samples|Average|Median|90% Line|95% Line|99% Line|Min|Max|Error %|Throughput|Received KB/sec|Std. Dev.|# Users|
|------------------------------|---------|-------|------|--------|--------|--------|---|---|-------|----------|---------------|---------|-------|
|H2-H2 (Ayesh )                         |8951044  |19     |19    |27      |31      |41      |1  |660|0.00%  |4973.0    |1549.2         |6.55     |100    |
|H2-H2 (No channel improvement )                         |8951044  |19     |19    |27      |31      |41      |1  |660|0.00%  |4973.0    |1549.2         |6.55     |100    |
|H2-H2 (Ayesh )                         |7194501  |24     |23    |36      |41      |55      |1  |372|0.00%  |3997.1    |936.8          |9.06     |100    |
