### ISSUE TITLE
[HTTP/2] A new connection should be created to handle requests when the the available range of stream identifiers are exhausted in HTTP/2

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-standard-library#495]
> A client that is unable to establish a new stream identifier can establish a new connection for new streams.  
> A server that is unable to establish a new stream identifier can send a GOAWAY frame so that the client is forced to open a new connection for new Streams. (Follow spec)

Subtasks
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/14380
- [ ] [[HTTP/2] Handle exhausted Stream Id for server ](https://github.com/ballerina-platform/ballerina-lang/issues/14382)

**Comment by dilanSachi** [comment]
The client side is already implemented and we decided not to implement the server side as new streams by the server is created when doing server push scenarios and it is not used widely and also the chance of exhausting the stream ids is extremely low.
