### ISSUE TITLE
[HTTP2] Add proxy support for HTTP2

### ISSUE THREAD

**Issue by isudana** [ballerina-platform/ballerina-standard-library#498]
**Description:**
Need to introduce proxy support for HTTP2. 
CONNECT method in HTTP/2.0 behaviour is different than the HTTP/1.x case.
https://tools.ietf.org/html/rfc7540#page-64
So Netty ProxyHandler might not work for HTTP/2 case (not tested).

However most of the well know proxies does not have the support for HTTP/2 protocol at the moment. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
> https://stackoverflow.com/questions/50437228/netty-proxyhandler-for-http-2

I think now Netty has a way to do it. Check this issue https://github.com/netty/netty/issues/12088.
Norman's first comment says that answer to this question https://stackoverflow.com/questions/50437228/netty-proxyhandler-for-http-2 is wrong

@Bhashinee

**Comment by Bhashinee** [comment]
> > https://stackoverflow.com/questions/50437228/netty-proxyhandler-for-http-2
> 
> I think now Netty has a way to do it. Check this issue [netty/netty#12088](https://github.com/netty/netty/issues/12088). Norman's first comment says that answer to this question https://stackoverflow.com/questions/50437228/netty-proxyhandler-for-http-2 is wrong
> 
> @Bhashinee

As per the offline discussion we had, when we use the existing proxy handler for HTTP2, it is applied to the whole channel instead of a stream. In the spec it says that the the proxy tunnel should be created per stream. But in Ballerina what ever the configs given to the client gets applied to the whole channel, I will proceed adding the proxy handler for HTTP2.
