### ISSUE TITLE
Details of 'http : HttpClient' object is visible to the public through Ballerina api-docs

### ISSUE THREAD

**Issue by NipunaDilhara** [ballerina-platform/ballerina-standard-library#504]
**Description:**
The 'http: HttpClient' object details (which should be private) can still be seen in the ballerina api-docs [1].

[1] https://ballerina.io/learn/api-docs/ballerina/http/clients/HttpClient.html

**Comment by chamil321** [comment]
Possible solution: 
```
Public client classes
  http:Client
  http:LoadBalanceClient
  http:FailoverClient


Internal Client classes
  HttpClient - which is native client connector
  HttpSecureClient
  RetryClient
  RedirectClient
  HttpCachingClient
  CircuitBreakerClient
  CookieClient
```

All these internal clients are structurally equal. So whatever we do, should be done to all of them. When trying to make the private, it blocks at CircuitBreakerClient level. because CircuitBreakerClient some additional APIs also. Eg: forceClose(), forceOpen(). 

So as a solution, we can make CircuitBreakerClient a public client and hide all other clients. 

```
Public client classes
 http:Client
 http:LoadBalanceClient
 http:FailoverClient
 http:CircuitBreakerClient
 ```

**Comment by chamil321** [comment]
> Possible solution:
> 
> ```
> Public client classes
>   http:Client
>   http:LoadBalanceClient
>   http:FailoverClient
> 
> 
> Internal Client classes
>   HttpClient - which is native client connector
>   HttpSecureClient
>   RetryClient
>   RedirectClient
>   HttpCachingClient
>   CircuitBreakerClient
>   CookieClient
> ```
> 
> All these internal clients are structurally equal. So whatever we do, should be done to all of them. When trying to make the private, it blocks at CircuitBreakerClient level. because CircuitBreakerClient some additional APIs also. Eg: forceClose(), forceOpen().
> 
> So as a solution, we can make CircuitBreakerClient a public client and hide all other clients.
> 
> ```
> Public client classes
>  http:Client
>  http:LoadBalanceClient
>  http:FailoverClient
>  http:CircuitBreakerClient
> ```
> 
> This API change is not backward compatible and can affect the users

When checking the implementation, it was found that http:HttpClient was visible for circuit breaker to execute 3 methods. 
1. [forceClose()](https://github.com/ballerina-platform/module-ballerina-http/blob/v2.2.1/ballerina/resiliency_http_circuit_breaker.bal#L378)
2. [forceOpen()](https://github.com/ballerina-platform/module-ballerina-http/blob/v2.2.1/ballerina/resiliency_http_circuit_breaker.bal#L388)
3. [getCurrentState()](https://github.com/ballerina-platform/module-ballerina-http/blob/v2.2.1/ballerina/resiliency_http_circuit_breaker.bal#L398)

So moved them to http:Client and hide all the subtypes of http:Client via https://github.com/ballerina-platform/module-ballerina-http/pull/994

Hence only the following clients will be public
```
Public client classes
 http:Client
 http:LoadBalanceClient
 http:FailoverClient
```
