### ISSUE TITLE
Behaviour when trying to access the payload after responding

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-standard-library#514]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/http;
import ballerina/io;

service foo on new http:Listener(8080) {

    @http:ResourceConfig {
        methods: ["POST"]
    }
    resource function bar(http:Caller caller, http:Request req) {
        var result = caller->respond("Accepted!");
        io:println("BAR");
        io:println(req.getJsonPayload());
        io:println("BAR2");
    }
}
```

When invoking the service, execution seems to hang at `req.getJsonPayload()` eventually resulting in a timeout error.
```cmd
$ curl -v http://localhost:8080/foo/bar -d '{ "name": "Anne", "age": 25 }' -H "Content-Type:application/json"
```

```cmd
$ ballerina run foo.bal 
[ballerina/http] started HTTP/WS listener 0.0.0.0:8080
BAR
error {ballerina/http}GenericClientError message=Error occurred while retrieving the json payload from the request cause=error {ballerina/mime}ParsingEntityBodyFailed message=Error occurred while extracting json data from entity: No entity was added to the queue before the timeout
BAR2
```

As pointed out by @arukshani, this works if we've accessed the payload prior to responding.

Is this the correct behaviour?
- don't we allow accessing the payload for the first time after responding?
- if we don't do we still need the timeout?

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0
Language specification 2019R3
```

**Comment by chamil321** [comment]
> The reason for releasing content at the final state of response path is to avoid potential memory leak ( [ballerina-platform/ballerina-lang#12815](https://github.com/ballerina-platform/ballerina-lang/issues/12815) ) which can occur when the request is not dispatched to a particular resource.
> 
> One thing we can do is moving that content release to all possible inbound request failure paths.

And do a load test by monitoring memory behaviour in following cases

```
1. Successful return value from resource flow
2. checkpanic from resource flow
3. Dispatching/data binding response flow
4. OPTIONS call response flow
```

**Comment by ayeshLK** [comment]
Following are the load test profiling results for above scenarios after proposed changed. (Load test concurrency 50)

1. Successful return value from resource flow
![success](https://user-images.githubusercontent.com/77491511/125772114-13a65395-88bb-43b3-8aff-4c062038962a.png)

2. checkpanic from resource flow
![error](https://user-images.githubusercontent.com/77491511/125772163-9b6807f2-3871-4906-b430-f4dc679a5f87.png)

3. Dispatching/data binding response flow
![not-found](https://user-images.githubusercontent.com/77491511/125772193-3c11e044-5e8d-416f-91b5-45380c1e70ca.png)

4. OPTIONS call response flow
![options](https://user-images.githubusercontent.com/77491511/125772228-c6a3d6d4-dd6e-4849-9969-de7a82bf9889.png)

**Comment by chamil321** [comment]
Reopen due to https://github.com/ballerina-platform/ballerina-standard-library/issues/1731
