### ISSUE TITLE
Support Link Header

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-standard-library#522]
**Description:**
HTTP client may support `Link` entity header field.
Its used for cases like pagination

MDN Doc: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link
RFC: https://tools.ietf.org/html/rfc5988

Maybe native support is not needed and this could be provided by a separate module

**Comment by shafreenAnfar** [comment]
As mentioned specific support link header can be done as a separate module. It is not part of HTTP or standard library. Hence closing this issue.
