### ISSUE TITLE
Implement a way to plug different load balance and fail-over algorithms

### ISSUE THREAD

**Issue by VijithaEkanayake-zz** [ballerina-platform/ballerina-standard-library#524]
**Description:**
we can implement some static member election algorithm with this. However, if we are to do this member election based on the endpoint availability or response time like parameters we will not be able to get that done. Implement a general solution to achieve this requirement.

**Comment by shafreenAnfar** [comment]
Client side load balancing is not a priority as it is not the 80% case. Hence closing this. Do feel free to reopen if there is a need.
