### ISSUE TITLE
Investigate Performance improvements points related to GW scenarios

### ISSUE THREAD

**Issue by VijithaEkanayake-zz** [ballerina-platform/ballerina-standard-library#526]
**Description:**
We need to figure out the area which can be improved to gain higher performance numbers when using the Ballerina. This could involve identifying improvement areas of each component used in Ballerina.

**Comment by shafreenAnfar** [comment]
A lot of improvements are done in this area. Hence closing this issue as this analysis is done on old version of HTTP.
