### ISSUE TITLE
Need an API to print to standard error stream

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-standard-library#558]
**Description:**
io:println currently prints to std out stream. But we also need an API where the user can get the std err stream to print any messages. This is specially helpful when printing some log messages that should go to err stream in the cases for error like messages.

For example, jvm_backend prints the compilation time error messages that can come from java interop validation to the console using the io:println which goes to std out stream. But this should ideally go to the std err stream.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by BuddhiWathsala** [comment]
Based on the approaches followed by other languages, there are two approaches we can address this issue.

### Approach 01
Introduce two new APIs to provide this requirement:
```ballerina
public function eprint((any|error)... values) {};
public function eprintln((any|error)... values) {};
```
Similar to the approach @casidiablo suggested and also Rust followed a similar approach.

### Approach 02
Improve the existing print APIs to take another optional parameter. This parameter will indicate, which output stream the user wants to print, either standard out or standard error. However, with the rest parameter, we cannot have another param afterwards. Therefore, I guess, this approach won't be the best option.

@daneshk and others WDYT?

**Comment by BuddhiWathsala** [comment]
ATM, the `ballerina/log` module supports this print error capability(https://github.com/ballerina-platform/module-ballerina-log/pull/37/commits/e1e3610144909ebfed2dc620e631b9f83b998d1d). Therefore, we are not prioritizing to implement the same thing in the I/O module. If someone has a special use case, please reopen the issue.
