### ISSUE TITLE
Properly handle strand state in standard library extern functions

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-standard-library#560]
**Description:**
In places where [NonBlockingCallback ](https://github.com/ballerina-platform/ballerina-lang/blob/v1.0.0-beta/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/NonBlockingCallback.java#L32) is used in Standard Library, we are [setting the strand state to BLOCK_AND_YIELD at the very beginning ](https://github.com/ballerina-platform/ballerina-lang/blob/v1.0.0-beta/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/NonBlockingCallback.java#L40)of the extern function.

Consider the following scenario.

We have a database, an HTTP service with a resource that talks to the database and fetches data, creates a JSON payload and responds to the client. 

eg:
```ballerina
import ballerina/http;
import ballerina/log;
import ballerinax/java.jdbc;

// Create MySQL client.
jdbc:Client testDB = new({
    url: "jdbc:mysql://localhost:3306/testdb",
    username: "test",
    password: "test"
});

// Create an HTTP service and bind it to a listener on port 9090.
service dataService on new http:Listener(9090) {

    resource function getData(http:Caller caller, http:Request req) {
        http:Response res = new;

        // Invoke `select` remote function on the MySQL database client
        // and obtain a large amount of data.
        var selectRet = testDB->select("SELECT * FROM Data", ());
        if (selectRet is table <record {}>) {
            // Convert the obtained data to `json`. Note that this conversion
            // does not load all the data into memory.
            // The `table` can be converted to `xml` in a similar manner.
            var jsonConversionRet = typedesc<json>.constructFrom(selectRet);
            if (jsonConversionRet is json) {
                // Set the `json` payload to the response. This is streamed
                // to the client once the service is invoked.
                res.setPayload(<@untainted> jsonConversionRet);
            } else {
                // Set a payload indicating an error in case the `json`
                // conversion fails.
                res.setPayload({ "Error": "Error occured while converting the
                data to JSON" });
                res.statusCode = http:STATUS_INTERNAL_SERVER_ERROR;
            }
        } else {
            // Set a payload indicating an error in case the data retrieval
            // fails.
            res.statusCode = http:STATUS_INTERNAL_SERVER_ERROR;
            res.setPayload({ "Error": "Error occured while retrieving data
            from the database" });
        }

        // Respond to the client.
        var respondRet = caller->respond(res);
        if (respondRet is error) {
            log:printError("Sending response failed", respondRet);
        }
    }
}
```

Here, the actual data fetching and JSON conversion happens when we are responding to the client since we don't pre fetch data and load it to memory.

In such a case, the respond extern function does a considerable amount of work while having the strand state set to BLOCK_AND_YIELD. (Ideally, if we are doing some work, we should have the state set to RUNNABLE and do the work and return.) This breaks in a case where an exception is thrown while doing that intermediate work. (eg: Losing database connectivity). Then the strand state is set to BLOCK_AND_YIELD but an exception has occurred which causes the flow to deviate from the happy path, hence resulting in a strand with no one to unblock it. This would cause the strand to block forever causing rest of the following code to remain un-executed.

1. We should not set the strand state to BLOCK_AND_YIELD at the very beginning and keep working on the Ballerina thread. 
2. Ideally if we are doing some heavy work, we should do it with a different thread and return the Ballerina thread. Later once the work is over, we can unblock the strand.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
This issue was created initially for Ballerina 1.2.x versions.

The async functionality is handled for swan lake versions through https://github.com/ballerina-platform/module-ballerina-sql/pull/331. It is verified that this behaviour is handled.
