### ISSUE TITLE
string.isBlank() & string.isEmpty() functions

### ISSUE THREAD

**Issue by vlgunarathne** [ballerina-platform/ballerina-standard-library#563]
**Description:**
Is it possible to implement $subject to the list of string related functions similar to the java StringUtils.isBlank(str) and StringUtils.isEmpty(str) which can check for null, "", " " .
```
string str1 = "";
string str2 = " ";
string str3;
string str4 = "something";

boolean isBlank_str1 = str1.isBlank()           // true
boolean isBlank_str2 = str2.isBlank()           // true
boolean isBlank_str3 = str3.isBlank()           // true
boolean isBlank_str4 = str4.isBlank()           // false

boolean isEmpty_str1 = str1.isEmpty()           // true
boolean isEmpty_str2 = str2.isEmpty()           // false
boolean isEmpty_str3 = str3.isEmpty()           // true
boolean isEmpty_str4 = str4.isEmpty()           // false
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
Closing this issue. since we are not maintaining this module now. Please use `lang.string` module.
