### ISSUE TITLE
HTTP Client panics with type cast error when calling an endpoint

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#566]
## Description
The HTTP client panics when an SSL error occurs. Following is the log:

```
error: {ballerina}TypeCastError message=incompatible types: 'error' cannot be cast to 'http:Response|http:FailoverAllEndpointsFailedError|http:FailoverActionFailedError|http:UpstreamServiceUnavailableError|http:AllLoadBalanceEndpointsFailedError|http:AllRetryAttemptsFailed|http:IdleTimeoutError|http:AuthenticationError|http:AuthorizationError|http:InitializingOutboundRequestError|http:WritingOutboundRequestHeadersError|http:WritingOutboundRequestBodyError|http:InitializingInboundResponseError|http:ReadingInboundResponseHeadersError|http:ReadingInboundResponseBodyError|http:UnsupportedActionError|http:Http2ClientError|http:MaximumWaitTimeExceededError|http:SslError|http:GenericClientError|http:CookieHandlingError'
	at ballerina.http:externExecuteClientAction(http_client.bal:235)
	   ballerina.http.HttpClient:get(http_client.bal:109)
	   ballerina.http:invokeEndpoint(http_commons.bal:303)
	   ballerina.http.resiliency.http_retry_client:performRetryAction(resiliency/http_retry_client.bal:304)
	   ballerina.http.RetryClient:get(resiliency/http_retry_client.bal:188)
	   ballerina.http.Client:get(client_endpoint.bal:139)
```

Even when we remove the retry configs, the error remains the same with the following log:

```
error: {ballerina}TypeCastError message=incompatible types: 'error' cannot be cast to 'http:Response|http:FailoverAllEndpointsFailedError|http:FailoverActionFailedError|http:UpstreamServiceUnavailableError|http:AllLoadBalanceEndpointsFailedError|http:AllRetryAttemptsFailed|http:IdleTimeoutError|http:AuthenticationError|http:AuthorizationError|http:InitializingOutboundRequestError|http:WritingOutboundRequestHeadersError|http:WritingOutboundRequestBodyError|http:InitializingInboundResponseError|http:ReadingInboundResponseHeadersError|http:ReadingInboundResponseBodyError|http:UnsupportedActionError|http:Http2ClientError|http:MaximumWaitTimeExceededError|http:SslError|http:GenericClientError|http:CookieHandlingError'
	at ballerina.http:externExecuteClientAction(http_client.bal:235)
	   ballerina.http.HttpClient:get(http_client.bal:109)
	   ballerina.http.Client:get(client_endpoint.bal:139)
```

This seems like an issue when returning an error from the native code, which isn't an `HTTP:ClientError`. Ideally, this should return an `HTTP:ClientError`

### Steps to reproduce

This was encountered while the Ballerina Standard Library build process. Try the following code: (May need to provide a `GITHUB_ACCESS_TOKEN` value).

```ballerina
import ballerina/http;

http:Client httpClient = new ("https://api.github.com/repos/ballerina-platform");

public function main() {
    
    http:Request request = ();
    request.setHeader("Accept", "application/vnd.github.v3+json");
    request.setHeader("Authorization", "bearer <GITHUB_ACCESS_TOKEN>");

    var result = httpClient->get("/module-ballerina-io/actions/workflows/build-master.yml/runs?per_page=1", request);
}
```

This `get()` call sometimes panic due to the aforementioned issue.

### Affected Versions
Ballerina 1.2.9

**Comment by chamil321** [comment]
**Root cause:** 
The response is received at the transport but an SSLException occurs when the channel gets closed. Due to that error, the exception is thrown from the external client action. 

_**USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)**_

This exception could occur if the connection was closed before finishing the SSL handshake, but as per the tracelog, the response is already received to the client. 

Tested the same with `{ http1Settings : { keepAlive: http:KEEPALIVE_NEVER }}` config to close the connection after the request/response completion to avoid connection reuse, but still getting the same exception. 

```
[2020-11-03 15:44:04,069] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] READ COMPLETE  
[2020-11-03 15:44:04,093] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] OUTBOUND: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
GET /repos/ballerina-platform/module-ballerina-io/actions/workflows/build-master.yml/runs?per_page=1 HTTP/1.1
Authorization: Bearer <GITHUB_ACCESS_TOKEN>
host: api.github.com
user-agent: ballerina
connection: keep-alive  
[2020-11-03 15:44:04,101] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] OUTBOUND: DefaultLastHttpContent(data: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0), decoderResult: success), 0B  
[2020-11-03 15:44:04,101] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] FLUSH  
[2020-11-03 15:44:04,515] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] READ COMPLETE  
[2020-11-03 15:44:04,526] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Date: Tue, 03 Nov 2020 10:14:04 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 11966
Server: GitHub.com
Status: 200 OK
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
ETag: "862a6613b342706f9a6100c58c8ea0b74c9a8eb9ff8ca15e22a22bece59d5661"
X-OAuth-Scopes: admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, read:packages, repo, user, workflow, write:discussion, write:packages
X-Accepted-OAuth-Scopes: 
X-GitHub-Media-Type: github.v3; format=json
Link: <https://api.github.com/repositories/288615254/actions/workflows/build-master.yml/runs?per_page=1&page=2>; rel="next", <https://api.github.com/repositories/288615254/actions/workflows/build-master.yml/runs?per_page=1&page=198>; rel="last"
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4992
X-RateLimit-Reset: 1604400948
X-RateLimit-Used: 8
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
Vary: Accept-Encoding
X-GitHub-Request-Id: 0B8E:11D7:5050C2:6772B9:5FA12D6B  
[2020-11-03 15:44:04,566] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] CLOSE  
[2020-11-03 15:44:04,598] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
{"total_count":198,"workflow_runs":[{"id":343318360,"node_id":"MDExOldvcmtmbG93UnVuMzQzMzE4MzYw","head_branch":"master","head_sha":"66fbb060fc847e741cf43acda4c453951b6a0665","run_number":198,"event":"repository_dispatch","status":"completed","conclusion":"success","workflow_id":2406342,"check_suite_id":1442375125,"check_suite_node_id":"MDEwOkNoZWNrU3VpdGUxNDQyMzc1MTI1","url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360","html_url":"https://github.com/ballerina-platform/module-ballerina-io/actions/runs/343318360","pull_requests":[],"created_at":"2020-11-03T09:40:00Z","updated_at":"2020-11-03T09:41:58Z","jobs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/jobs","logs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/logs","check_suite_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/check-suites/1442375125","artifacts_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/artifacts","cancel_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/cancel","rerun_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/rerun","workflow_url":"https://api.github.com/re  
[2020-11-03 15:44:04,605] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
pos/ballerina-platform/module-ballerina-io/actions/workflows/2406342","head_commit":{"id":"66fbb060fc847e741cf43acda4c453951b6a0665","tree_id":"3b050ada9e6fdb8f625733f8afe8bf027363e4d2","message":"Merge pull request #32 from ballerina-platform/update-repository-dispatch-path\n\nUpdate repository dispatch path for dependent module builds","timestamp":"2020-11-03T05:33:05Z","author":{"name":"Thisaru Guruge","email":"thisaru@wso2.com"},"committer":{"name":"GitHub","email":"noreply@github.com"}},"repository":{"id":288615254,"node_id":"MDEwOlJlcG9zaXRvcnkyODg2MTUyNTQ=","name":"module-ballerina-io","full_name":"ballerina-platform/module-ballerina-io","private":false,"owner":{"login":"ballerina-platform","id":34733518,"node_id":"MDEyOk9yZ2FuaXphdGlvbjM0NzMzNTE4","avatar_url":"https://avatars2.githubusercontent.com/u/34733518?v=4","gravatar_id":"","url":"https://api.github.com/users/ballerina-platform","html_url":"https://github.com/ballerina-platform","followers_url":"https://api.github.com/users/ballerina-platform/followers","following_url":"https://api.github.com/users/ballerina-platform/following{/other_user}","gists_url":"https://api.github.com/users/ballerina-platform/gists{/gist_id}","starred_url":"https://api.github.com/users/ballerina-platform/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ballerina-platform/subscription  
[2020-11-03 15:44:04,609] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
s","organizations_url":"https://api.github.com/users/ballerina-platform/orgs","repos_url":"https://api.github.com/users/ballerina-platform/repos","events_url":"https://api.github.com/users/ballerina-platform/events{/privacy}","received_events_url":"https://api.github.com/users/ballerina-platform/received_events","type":"Organization","site_admin":false},"html_url":"https://github.com/ballerina-platform/module-ballerina-io","description":"Ballerina io Module","fork":false,"url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io","forks_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/forks","keys_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/keys{/key_id}","collaborators_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/teams","hooks_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/hooks","issue_events_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/issues/events{/number}","events_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/events","assignees_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/assignees{/user}","branches_url":"https://api.github.  
[2020-11-03 15:44:04,615] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
com/repos/ballerina-platform/module-ballerina-io/branches{/branch}","tags_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/tags","blobs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/refs{/sha}","trees_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/trees{/sha}","statuses_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/statuses/{sha}","languages_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/languages","stargazers_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/stargazers","contributors_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/contributors","subscribers_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/subscribers","subscription_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/subscription","commits_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/commits{/sha}","git_commits_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/commits{/sha}","comments_url":"ht  
[2020-11-03 15:44:04,619] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
tps://api.github.com/repos/ballerina-platform/module-ballerina-io/comments{/number}","issue_comment_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/issues/comments{/number}","contents_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/contents/{+path}","compare_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/compare/{base}...{head}","merges_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/merges","archive_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/downloads","issues_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/issues{/number}","pulls_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/pulls{/number}","milestones_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/milestones{/number}","notifications_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/labels{/name}","releases_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/releases{/id}","deployments_url":"https://api.github.  
[2020-11-03 15:44:04,620] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] READ COMPLETE  
[2020-11-03 15:44:04,622] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)  
[2020-11-03 15:44:04,628] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INACTIVE  
[2020-11-03 15:44:04,629] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] CLOSE  
[2020-11-03 15:44:04,630] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] UNREGISTERED  

```

**Comment by ThisaruGuruge** [comment]
> **Root cause:**
> The response is received at the transport but an SSLException occurs when the channel gets closed. Due to that error, the exception is thrown from the external client action.
> 
> _**USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)**_
> 
> This exception could occur if the connection was closed before finishing the SSL handshake, but as per the tracelog, the response is already received to the client.
> 
> Tested the same with `{ http1Settings : { keepAlive: http:KEEPALIVE_NEVER }}` config to close the connection after the request/response completion to avoid connection reuse, but still getting the same exception.
> 
> ```
> [2020-11-03 15:44:04,069] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] READ COMPLETE  
> [2020-11-03 15:44:04,093] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] OUTBOUND: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
> GET /repos/ballerina-platform/module-ballerina-io/actions/workflows/build-master.yml/runs?per_page=1 HTTP/1.1
> Authorization: Bearer <GITHUB_ACCESS_TOKEN>
> host: api.github.com
> user-agent: ballerina
> connection: keep-alive  
> [2020-11-03 15:44:04,101] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] OUTBOUND: DefaultLastHttpContent(data: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0), decoderResult: success), 0B  
> [2020-11-03 15:44:04,101] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] FLUSH  
> [2020-11-03 15:44:04,515] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] READ COMPLETE  
> [2020-11-03 15:44:04,526] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
> HTTP/1.1 200 OK
> Date: Tue, 03 Nov 2020 10:14:04 GMT
> Content-Type: application/json; charset=utf-8
> Content-Length: 11966
> Server: GitHub.com
> Status: 200 OK
> Cache-Control: private, max-age=60, s-maxage=60
> Vary: Accept, Authorization, Cookie, X-GitHub-OTP
> ETag: "862a6613b342706f9a6100c58c8ea0b74c9a8eb9ff8ca15e22a22bece59d5661"
> X-OAuth-Scopes: admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, read:packages, repo, user, workflow, write:discussion, write:packages
> X-Accepted-OAuth-Scopes: 
> X-GitHub-Media-Type: github.v3; format=json
> Link: <https://api.github.com/repositories/288615254/actions/workflows/build-master.yml/runs?per_page=1&page=2>; rel="next", <https://api.github.com/repositories/288615254/actions/workflows/build-master.yml/runs?per_page=1&page=198>; rel="last"
> X-RateLimit-Limit: 5000
> X-RateLimit-Remaining: 4992
> X-RateLimit-Reset: 1604400948
> X-RateLimit-Used: 8
> Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
> Access-Control-Allow-Origin: *
> Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
> X-Frame-Options: deny
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
> Content-Security-Policy: default-src 'none'
> Vary: Accept-Encoding, Accept, X-Requested-With
> Vary: Accept-Encoding
> X-GitHub-Request-Id: 0B8E:11D7:5050C2:6772B9:5FA12D6B  
> [2020-11-03 15:44:04,566] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] CLOSE  
> [2020-11-03 15:44:04,598] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
> {"total_count":198,"workflow_runs":[{"id":343318360,"node_id":"MDExOldvcmtmbG93UnVuMzQzMzE4MzYw","head_branch":"master","head_sha":"66fbb060fc847e741cf43acda4c453951b6a0665","run_number":198,"event":"repository_dispatch","status":"completed","conclusion":"success","workflow_id":2406342,"check_suite_id":1442375125,"check_suite_node_id":"MDEwOkNoZWNrU3VpdGUxNDQyMzc1MTI1","url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360","html_url":"https://github.com/ballerina-platform/module-ballerina-io/actions/runs/343318360","pull_requests":[],"created_at":"2020-11-03T09:40:00Z","updated_at":"2020-11-03T09:41:58Z","jobs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/jobs","logs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/logs","check_suite_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/check-suites/1442375125","artifacts_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/artifacts","cancel_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/cancel","rerun_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/actions/runs/343318360/rerun","workflow_url":"https://api.github.com/re  
> [2020-11-03 15:44:04,605] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
> pos/ballerina-platform/module-ballerina-io/actions/workflows/2406342","head_commit":{"id":"66fbb060fc847e741cf43acda4c453951b6a0665","tree_id":"3b050ada9e6fdb8f625733f8afe8bf027363e4d2","message":"Merge pull request #32 from ballerina-platform/update-repository-dispatch-path\n\nUpdate repository dispatch path for dependent module builds","timestamp":"2020-11-03T05:33:05Z","author":{"name":"Thisaru Guruge","email":"thisaru@wso2.com"},"committer":{"name":"GitHub","email":"noreply@github.com"}},"repository":{"id":288615254,"node_id":"MDEwOlJlcG9zaXRvcnkyODg2MTUyNTQ=","name":"module-ballerina-io","full_name":"ballerina-platform/module-ballerina-io","private":false,"owner":{"login":"ballerina-platform","id":34733518,"node_id":"MDEyOk9yZ2FuaXphdGlvbjM0NzMzNTE4","avatar_url":"https://avatars2.githubusercontent.com/u/34733518?v=4","gravatar_id":"","url":"https://api.github.com/users/ballerina-platform","html_url":"https://github.com/ballerina-platform","followers_url":"https://api.github.com/users/ballerina-platform/followers","following_url":"https://api.github.com/users/ballerina-platform/following{/other_user}","gists_url":"https://api.github.com/users/ballerina-platform/gists{/gist_id}","starred_url":"https://api.github.com/users/ballerina-platform/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ballerina-platform/subscription  
> [2020-11-03 15:44:04,609] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
> s","organizations_url":"https://api.github.com/users/ballerina-platform/orgs","repos_url":"https://api.github.com/users/ballerina-platform/repos","events_url":"https://api.github.com/users/ballerina-platform/events{/privacy}","received_events_url":"https://api.github.com/users/ballerina-platform/received_events","type":"Organization","site_admin":false},"html_url":"https://github.com/ballerina-platform/module-ballerina-io","description":"Ballerina io Module","fork":false,"url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io","forks_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/forks","keys_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/keys{/key_id}","collaborators_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/teams","hooks_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/hooks","issue_events_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/issues/events{/number}","events_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/events","assignees_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/assignees{/user}","branches_url":"https://api.github.  
> [2020-11-03 15:44:04,615] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
> com/repos/ballerina-platform/module-ballerina-io/branches{/branch}","tags_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/tags","blobs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/refs{/sha}","trees_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/trees{/sha}","statuses_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/statuses/{sha}","languages_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/languages","stargazers_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/stargazers","contributors_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/contributors","subscribers_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/subscribers","subscription_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/subscription","commits_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/commits{/sha}","git_commits_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/git/commits{/sha}","comments_url":"ht  
> [2020-11-03 15:44:04,619] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INBOUND: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 1370, cap: 1370/1370, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1370, widx: 1370, cap: 1399)), decoderResult: success), 1370B
> tps://api.github.com/repos/ballerina-platform/module-ballerina-io/comments{/number}","issue_comment_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/issues/comments{/number}","contents_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/contents/{+path}","compare_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/compare/{base}...{head}","merges_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/merges","archive_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/downloads","issues_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/issues{/number}","pulls_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/pulls{/number}","milestones_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/milestones{/number}","notifications_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/labels{/name}","releases_url":"https://api.github.com/repos/ballerina-platform/module-ballerina-io/releases{/id}","deployments_url":"https://api.github.  
> [2020-11-03 15:44:04,620] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] READ COMPLETE  
> [2020-11-03 15:44:04,622] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)  
> [2020-11-03 15:44:04,628] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] INACTIVE  
> [2020-11-03 15:44:04,629] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] CLOSE  
> [2020-11-03 15:44:04,630] TRACE {http.tracelog.upstream} - [id: 0xe66dfbb4, correlatedSource: n/a, host:/192.168.1.6:58420 - remote:api.github.com/13.250.168.23:443] UNREGISTERED  
> ```

My concern is that even if the channel gets closed, we should return a proper `http:ClientError`. But in this case, the client panics. We need to avoid that. If this is a proper `http:ClientError`, that can be handled by the client (or the user) using resiliency stuff. Here, it just panics.

**Comment by chamil321** [comment]
Fixed via [commit,](https://github.com/ballerina-platform/module-ballerina-http/commit/98b0af2#diff-c98563b49551260a73837b32fe727cc79a39f93ae4fbfd454c5a645c7315bbd6R561) Hence closing the issue
