### ISSUE TITLE
Enable test cases

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#592]
Integration tests were failing because there is an extra line in the outputs of all the test cases: 
```error: module not found for: ballerinai/transaction:1.0.0_java11```

Because of this, the actual number of lines is always greater than expected number of lines by 1. Therefore the assertion fails. Hence, test cases were temporarily disabled in the build. Need to fix this and re-enable the test cases.

**Comment by MadhukaHarith92** [comment]
Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/26875

**Comment by gimantha** [comment]
@MadhukaHarith92 We have merged the https://github.com/ballerina-platform/ballerina-lang/pull/26875

**Comment by MadhukaHarith92** [comment]
> @MadhukaHarith92 We have merged the [ballerina-platform/ballerina-lang#26875](https://github.com/ballerina-platform/ballerina-lang/pull/26875)

Verified the fix and re-enabled the test cases. Therefore closing this issue.
