### ISSUE TITLE
Update persist documentation in Ballerina website

### ISSUE THREAD

**Issue by hasathcharu** [ballerina-platform/ballerina-standard-library#6239]
**Description:**
This task is to update the persist documentation in the Ballerina website to include documentation related to newly added SQL annotations, the introspection feature and the newly added data store PostgreSQL.

**Describe your task(s)**
- Add documentation for introspection
- Add documentation for SQL annotations
- Add documentation for the data store PostgreSQL

**Comment by daneshk** [comment]
The documentation changes are merged into the release-2201.9.0 branch. Hence closing the issue.
