### ISSUE TITLE
module-ballerinax-mysql uses crypto:Keystore instead of crypto:Truststore for trust certificate

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-standard-library#678]
## Description

The module [ballerinax-mysql](https://github.com/ballerina-platform/module-ballerinax-mysql) uses a record to define the SSL parameters when initializing a client. This record is defined in the file [client.bal line 175](https://github.com/ballerina-platform/module-ballerinax-mysql/blob/4745d88118c88c5024f0f3cc1880931fb5bc5dae/mysql-ballerina/client.bal#L175). 

``` ballerina
# SSL Configuration to be used when connecting to mysql server.
#
# + mode - `SSLMode` to be used during the connection
# + clientCertKeystore - Keystore configuration of the client certificates
# + trustCertKeystore - Keystore configuration of the trust certificates
#
public type SSLConfig record {|
    SSLMode mode = SSL_PREFERRED;
    crypto:KeyStore clientCertKeystore?;
    crypto:KeyStore trustCertKeystore?;
|};
```
In line 178 it defines a trust store named `trustCertKeystore`, but it is of the type of record [crypto:KeyStore](https://ballerina.io/learn/api-docs/ballerina/crypto/records/KeyStore.html). But the `crypto` module contains a seperate record named [crypto:TrustStore](https://ballerina.io/learn/api-docs/ballerina/crypto/records/TrustStore.html). 

## Suggestion

Change the type of `trustCertKeystore` from `KeyStore` to `TrustStore`.

**Comment by niveathika** [comment]
As per the offline discussion, since keystores are coupled tightly with Java, we should move to just using certs. It seems the underlying Hikkari CP also supports setting a custom SSL Context with cert filepaths.

Sample: https://www.programcreek.com/java-api-examples/?api=com.zaxxer.hikari.HikariConfig Example 7

**Comment by lahirusamith** [comment]
Try to address this issue in this PR: https://github.com/ballerina-platform/module-ballerinax-mysql/pull/96

**Comment by lahirusamith** [comment]
> As per the offline discussion, since keystores are coupled tightly with Java, we should move to just using certs. It seems the underlying Hikkari CP also supports setting a custom SSL Context with cert filepaths.
> 
> Sample: https://www.programcreek.com/java-api-examples/?api=com.zaxxer.hikari.HikariConfig Example 7

@niveathika This Sample is given for the postgres. mysql connector/j does not have properties to add cert files.

**Comment by daneshk** [comment]
This issue is addressed in ballerina-platform/module-ballerinax-mysql#96
