### ISSUE TITLE
Timestamp data values return from sql queries assigned to the user define record types without validating its fields.

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-standard-library#679]
When assigning timestamp data values returned from sql queries to a user defined record, the keys in the later are not validated.

Following code demonstrate the above condition.
```
import ballerina/io;
import ballerina/java.jdbc;
import ballerina/sql;

public type RandomType record {|
    
|};

public type ResultType record {|

    int id;
    RandomType timezoneValue;
    
|};


public function main() {
    jdbc:Client|sql:Error jdbcClient =  new ("jdbc:postgresql://localhost:5432/testdb","postgres","postgres");
           
    if (jdbcClient is jdbc:Client) {

        string dropQuery = "Drop table If exists test";
        
        sql:ExecutionResult|sql:Error dropResult = jdbcClient->execute(dropQuery);

        string createQuery = "Create table test(id serial, timezoneValue timestamptz)";
        
        sql:ExecutionResult|sql:Error createResult = jdbcClient->execute(createQuery);

        string insertQuery1 = "Insert into test(timezoneValue) Values ('2004-10-19 10:23:54+02')";
        
        sql:ExecutionResult|sql:Error insertResult1 = jdbcClient->execute(insertQuery1);

        string insertQuery2 = "Insert into test(timezoneValue) Values ('2003-04-12 04:05:06 America/New_York')";
        
        sql:ExecutionResult|sql:Error insertResult2 = jdbcClient->execute(insertQuery2);

        string selectQuery = "Select * from test";

        //Incorrect record type( ResultType ) use for data selection. But it works


        stream<record{}, error> resultStream =  jdbcClient->query(selectQuery, ResultType);

        stream<ResultType, sql:Error> resultRows =  <stream<ResultType, sql:Error>>resultStream;
        
        sql:Error? e = resultRows.forEach(function(ResultType rec) {
            io:println("\n");
            io:println(rec.id);
            io:println(rec.timezoneValue);
            io:println("\n");
        });
        
        if (e is error) {
            io:println(e);
        }


        sql:Error? err = jdbcClient.close();  

        if(e is sql:Error){
            io:println("Conection close failed!!");
        } 
    } 
    else {
        io:println("Initialization failed!!");
        io:println(jdbcClient);
    }
}
```

**Comment by lahirusamith** [comment]
Since we have changed the time module APIs, we now support time:Utc for the timestamp datatype. but for the "timestamptz" data type we can not use time module APIs for the moment. As a workaround we can use string data type for now.

**Comment by lahirusamith** [comment]
@daneshk @BuddhiWathsala @niveathika , After looking into the issue, It is found that, in ballerina sql module, if we expect DB level time related ResultSet values rather than as int or String, it always gives a time:Utc Record which is incorrect for TIME, DATE and DATETIME sql data types. and also we can not map Type [int,decimal] & readonly which is the time:Utc type to TIMESTAMP sql data type. 

@BuddhiWathsala , As we discussed earlier, need to have APIs in either in sql or time module to convert java.sql.Time to time:TimeOfDay, java.sql.Date to time:Date and java.sql.Timestamp to time:Civil as well. please note that all the java.sql.Time, java.sql.Date and java.sql.Timestamp classes are extended from java.utils.Date class.

**Comment by daneshk** [comment]
As we are constructing Ballerina types using `java.sql.Time`, We need to support these native APIs in the SQL module. WDYT?

**Comment by daneshk** [comment]
@SasinduDilshara Can you check whether this is fixed with latest time changes
