### ISSUE TITLE
Normative DateTime creation not working as expected

### ISSUE THREAD

**Issue by rapport** [ballerina-platform/ballerina-standard-library#69]
**Description:**

I am having problems creating dates in Ballerina and attempting to format the output and am finding the documentation confusing to work with.

If I create a time with time:currentTime() time:createTime() or time:parse() I would expect the same normative time object but I am not getting this... It is also not clear how to read in values from a text document construct a time object and reformat the output of the time from the object in the output format. 

Things appear to work as I would expect when I start with either a time:currentTime() or an epoch along the lines
time:Time time = { time: 1498488382000, zone: noZoneValue };

as I can then start extracting out the the data from time
int day = time:getDay(time);

But whenever I try to to either read and parse or CreateTime I cannot extract the elements out of the time. So for example if I were to instead createTime

time:Time time = { time:createTime(2020, 3, 28, 23, 42, 45, 554, "America/Panama"), zone: noZoneValue };

Then the above ( int day = time:getDay(time); ) would complain about either having the wrong type or something else. 

Hope someone can help or provide examples to follow and/or provide a function to convert everything to epoch as it may be easier to process data that way!

**Comment by ThishaniLucas** [comment]
It has been our design decision to return an error in case of a failure. A sample way to handle such errors is as follows.

```time:Time|error createdTime = time:createTime(2015, 3, 28, 23, 42, 45, 554, "America/Panama");
if (createdTime is time:Time) {
   //success path
} else {
   log:printError("Error creating time!");
}
//continue
```

Here we have used the `log` standard library package and printed an error message. If the creation of time fails, a message will be logged like below and the flow simply continues.

`time = 2021-02-12 23:00:13,080 level = ERROR module = ballerina/test message = "Error creating time!"`

Closing this issue with this comment. Please reopen if there're any concerns.
