### ISSUE TITLE
Move UDP Module to an External Repository

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-standard-library#694]
$subject.

**Comment by MohamedSabthar** [comment]
UDP module moved to external repository

**Comment by Maninda** [comment]
Sabthar moved the UDP functionality to the new repo with the following PRs.
1. https://github.com/ballerina-platform/module-ballerina-tcp/pull/82
2. https://github.com/ballerina-platform/module-ballerina-udp/pull/1
