### ISSUE TITLE
time:parse fails for given date string in type "yyyy-MM-dd'T'HH:mm:ss.SSSZ"

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-standard-library#70]
**Description:**

Tried to parse the date string `2020-04-09T06:00:14.584Z` using `time:parse` and it returned the following error.

```
error {ballerina/time}TimeError message=parse date "2020-04-09T06:00:14.584Z" for the format "yyyy-MM-dd'T'HH:mm:ss.SSSZ" failed:Text '2020-04-09T06:00:14.584Z' could not be parsed at index 23
```
Code:
```
var parsedTime = time:parse("2020-04-09T06:00:14.584Z", "yyyy-MM-dd'T'HH:mm:ss.SSSZ");
io:println(parsedTime);
```

**Affected Versions:**
Ballerina 1.2.0

**Related Issues:**
[#17830](https://github.com/ballerina-platform/ballerina-lang/issues/17830)

**Suggested Labels:**
>Area/StandardLibs
>Component/Time
>Type/Bug

**Comment by ThishaniLucas** [comment]
The pattern that has been used here to parse the time string "2020-04-09T06:00:14.584Z" is incorrect. [Java's parse method](https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html#parse-java.lang.CharSequence-) uses the ISO_ZONED_DATE_TIME formatter. A sample pattern that matches this formatter is "yyyy-MM-dd'T'HH:mm:ss.SSSXXX" (please refer https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html for more info about X's and Z's).

Alternatively, you can use the below code to parse this particular time string.
`var parsedTime = time:parse("2020-04-09T06:00:14.584Z", time:ISO_ZONED_DATE_TIME);`
