### ISSUE TITLE
Time module, current time parsing fails

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-standard-library#72]
**Description:**
Is the following code snippet valid?

```ballerina
time:Time currentTime = time:currentTime();
var k = time:parse(time:toString(currentTime), "yyyy-MM-dd'T'HH:mm:ss.SSSZ");
io:println(k);
```
It prints the following, but I expect it to parse the current time properly.
```
error {ballerina/time}TimeError message=parse date "2019-08-16T09:15:01.758+05:30" for the format "yyyy-MM-dd'T'HH:mm:ss.SSSZ" failed:Text '2019-08-16T09:15:01.758+05:30' c
ould not be parsed at index 23
```
**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT

**Comment by ThishaniLucas** [comment]
The time:tostring API formats a time record using the ISO_OFFSET_DATE_TIME (eg: 2021-01-20T12:44:47.421+05:30). The pattern used to parse the time string, in this case, is incorrect. A sample pattern that could be used is "yyyy-MM-dd'T'HH:mm:ss.SSSXXX". The pattern used here can be used to parse a value like "2021-01-20T12:44:47.421+0530".
