### ISSUE TITLE
[StandardLib][Time] Provide constants for commonly used date/time patterns

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#73]
**Description:**
Although there is a `format()` function for formatting a given time, the user always have to type in the format. It would make it easier for the user if a few string constants are provided for some of the most commonly used date/time formats such as ISO zoned date time, RFC 1123 date time etc.

**Suggested Labels (optional):**
Type/Improvement

**Comment by ThishaniLucas** [comment]
Improved with https://github.com/ballerina-platform/ballerina-standard-library/issues/655
