### ISSUE TITLE
Remove config api module

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#745]
$subject. We need to remove the config API module from the Ballerina Swan Lake release as we are introducing a new config model. Remove it in alpha release

**Comment by daneshk** [comment]
Need to check how many modules will get impact by this and migrate them to the new model.

**Comment by daneshk** [comment]
New config design is not supported in test cases. We need to check how many modules use config API for test cases as well. If there are, we have to wait till we get the support

**Comment by MadhukaHarith92** [comment]
Closing since this is completed.
