### ISSUE TITLE
RabbitMQ Tests Not Running when Build Master Workflow Triggers 

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#767]
Check this run:
https://github.com/ballerina-platform/module-ballerinax-rabbitmq/runs/1568961512?check_suite_focus=true

This did not run the tests when the `Build` workflow triggered. Due to this, we missed the Log API changes in RabbitMQ module.

**Comment by niveathika** [comment]
Found the same for NATS and Streaming NATS component

**Comment by niveathika** [comment]
Should check Kafka too

**Comment by niveathika** [comment]
Post-release master sync PR is failing for STAM

**Comment by ThisaruGuruge** [comment]
> Should check Kafka too

Kafka has the same issue.

**Comment by aashikam** [comment]
Fixed in all modules, RabbitMQ, Kafka, NATS and STAN
