### ISSUE TITLE
Standard Library Dependency Resolution

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#789]
**Description:**
With the new Project API [1], all the implementation dependencies (direct dependencies) of a particular module are packed to its `balo`. With the current standard library project build structure, those direct dependencies and their transitive dependencies are packed into the distribution. If the first statement is true, why can't we get those transitive dependencies from the `balo` of the direct dependency?

This concern leads to a problem like, if my module `foo` is depending on some module `bar`, I must pack all the direct dependencies + transitive dependencies in my module, which is `foo`. If the module `bar` decide to depend on something completely new dependency with a new feature implementation, I must add that new dependency in `foo` module as well. The problem is there, other way round as well. This is not scalable.

There should be a straightforward way to resolve the transitive dependencies.

[1] https://github.com/ballerina-platform/ballerina-spec/blob/master/project/proposals/packages/packages.md

**Comment by ThisaruGuruge** [comment]
This should be handled by the ballerina build, IINM. Anyways, let's discuss on this more later and come up with a solution.

**Comment by ldclakmal** [comment]
This issue is based on the statement below statement, which is wrong.
> all the implementation dependencies (direct dependencies) of a particular module are packed to its `balo`

All the dependencies should be resolved from any mode of store (Ballerina central, intermediate distribution, etc.). Hence, there is no any issue to be solved.
