### ISSUE TITLE
Dependabot PRs aren't Distinguishable

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#792]
Currently the Standard Library Dependabot PRs are not distinguishable from the other PRs by looking at the title. The PR title should be changed to `[Dependabot] ___`.

@TharindaDilshan

**Comment by niveathika** [comment]
Have we looked into whether we can use the name "Dependabot"? This is referring to a specific product isn't it?

**Comment by ThisaruGuruge** [comment]
> Have we looked into whether we can use the name "Dependabot"? This is referring to a specific product isn't it?
> 
> Do they have copyrights for the name?

Thanks for pointing this out. Let's use keep the `[Automated]` for now.
