### ISSUE TITLE
Add support for authentication when calling OAuth2 introspection

### ISSUE THREAD

**Issue by sellerin** [ballerina-platform/ballerina-standard-library#794]
Hi,

First of all thank you for this project. I'm really enjoying ballerina and I am amazed by the quality of documentation https://ballerina.io/learn/by-example/. I'm using ballerina as a replacement of python when I need quick automatization

However I had some difficulties to make a fully running example of oauth2 client and service. I chose Keycloak for the identity provider and after some debugging it appeared that authentication was missing when calling  introspect endpoint:

```
oauth2:InboundOAuth2Provider oauth2Provider = new ({
    url: "http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token/introspect"
});
```

Please find bellow a suggestion of improvement.

**Description:**

oauth2:InboundOAuth2Provider doesn't allow to specify client_id and client_secret.
These parameters are necessary for example with the identity provider Keycloak

According to the spec: https://tools.ietf.org/html/rfc7662#section-2.1

>    To prevent token scanning attacks, the endpoint MUST also require
>    some form of authorization to access this endpoint, such as client
>    authentication as described in OAuth 2.0

For now it is only possible to make a call like this:

`token=xxx`

or 

`token=xxx&tokenTypeHint=access_token`

It would be more secure to also support:

`client_id=hello-service&client_secret=37455380-7fd2-45f9-850b-52189a5062c0&token=xxx`

**Comment by ldclakmal** [comment]
Hi @sellerin 

Thank you for reaching out. The requested feature is already supported in Ballerina `1.2.x` channel. But, in Swan Lake channel, there are few limitations and we need to improve that.

According to your code sample, seems like you are using the `1.2.x` version for your use case.
Here [1], you can pass the client configurations, which need to authenticate with the introspection endpoint. As you pointed out the RFC [2], that can be anything like Bearer auth, OAuth2 etc.

>   To prevent token scanning attacks, the endpoint MUST also require
   some form of authorization to access this endpoint, such as client
   authentication as described in OAuth 2.0 [RFC6749] or a separate
   OAuth 2.0 access token such as the bearer token described in OAuth
   2.0 Bearer Token Usage [RFC6750].

You can refer to "Secured Client" BBEs [3] and configure the client for the required use case.

Here is an example for the secured introspection endpoint with OAuth2 client credentials grant type and the credentials are passed in request body.

```ballerina
import ballerina/oauth2;

oauth2:OutboundOAuth2Provider outboundOAuth2Provider = new ({
    tokenUrl: "<Token URL for the authorization endpoint>",
    clientId: "<Client ID for the client credentials grant authentication>",
    clientSecret: "<Client secret for the client credentials grant authentication>",
    credentialBearer: oauth2:POST_BODY_BEARER
    clientConfig: {
        secureSocket: {
            trustStore: {
                path: "/path/to/ballerinaTruststore.p12",
                password: "ballerina"
            }
        }
    }
});
http:BearerAuthHandler bearerAuthHandler = new(outboundOAuth2Provider);

oauth2:InboundOAuth2Provider oauth2Provider = new ({
    url: "http://localhost:8080/token/introspect",
    clientConfig: {
        auth: {
            authHandler: bearerAuthHandler
        }
    }
});
```

[1] https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal#L201
[2] https://tools.ietf.org/html/rfc7662#section-2.1
[3] https://ballerina.io/learn/by-example/

**Comment by sellerin** [comment]
Hi @ldclakmal 

Thank you for the help. I will try like this
regards.
