### ISSUE TITLE
java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#821]
Above error is return from POST action in tests/http_client_continue_test.bal class `testContinueAction` test case when it was run last with other two test cases. When the order is preserved to run it at first, nothing wrong. This error was induced during https://docs.google.com/document/d/1eSuPkdTo6Fk__9wUZ8_LsQNZp_ceMTVpemFu8a8Rgm8/edit# migration.
```
error = "java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest, state: 1" 
```

To reproduce the error, run `http_client_continue_test` without the depends on condition.

**Comment by ayeshLK** [comment]
Since this issue is not reproducible closing the issue.
