### ISSUE TITLE
Handle Multiple versions of socket native functions

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-standard-library#84]
**Description:**
ex.
With pr [1] we can use multiple versions of the same module at runtime. But when we have native functions with java interops, developers need to handle the versions of java externs. If not there may be classpath issues during runtime. One approach would be to append the package name in native code packages related to modules. ex org.ballerinalang.stdlib.socket.v0_6_0

We also need to modify the interop function definitions in the bal files as well.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/22902

**Comment by Bhashinee** [comment]
Closing the issue as this is invalid now.
