### ISSUE TITLE
[gRPC] The intermittently failing unavailable service test

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#841]
The `testInvokeUnavailableService` test case is failing intermittently after returning the following error.

```
[ballerina/grpc] stopped HTTP/WS listener localhost:9110

		[fail] testInvokeUnavailableService:

		    {ballerina}TypeCastError {"message":"incompatible types: 'handle' cannot be cast to '[anydata,map<string[]>]|grpc:CancelledError|grpc:UnKnownError|grpc:InvalidArgumentError|grpc:DeadlineExceededError|grpc:NotFoundError|grpc:AlreadyExistsError|grpc:PermissionDeniedError|grpc:UnauthenticatedError|grpc:ResourceExhaustedError|grpc:FailedPreconditionError|grpc:AbortedError|grpc:OutOfRangeError|grpc:UnimplementedError|grpc:InternalError|grpc:UnavailableError|grpc:DataLossError|grpc:AllRetryAttemptsFailed|grpc:StreamClosedError|grpc:DataMismatchError|grpc:EOS'"}

		    	at ballerina.grpc.0_7_5:externExecuteSimpleRPC(client_endpoint.bal:198)
		    	ballerina.grpc.0_7_5.Client:executeSimpleRPC(client_endpoint.bal:71)
		    	ballerina.grpc.0_7_5.HelloWorld16Client:hello(tests/16_unavailable_service_client.bal:52)
		    	ballerina.grpc.0_7_5.tests.16_unavailable_service_client:testInvokeUnavailableService(tests/16_unavailable_service_client.bal:26)
```

**Comment by BuddhiWathsala** [comment]
Temporarily disable this test case here https://github.com/ballerina-platform/module-ballerina-grpc/pull/71/commits/7ac58b7ce33db5517bcf96c223296ddef59753a4

**Comment by dilanSachi** [comment]
Tried out building the module locally multiple times and the issue could not be reproduced. When the build is run on git workflow, a new error is found in the same test.
```
cannot complete the same future twice.
```
If I understood correctly, this gets triggered when the original expected error occurs and the code execution takes a little more time to complete the `Future` in [here](https://github.com/ballerina-platform/module-ballerina-grpc/blob/84cfc9df02cc32fe40acccfe9e5fad8ecbd16d52/grpc-native/src/main/java/org/ballerinalang/net/grpc/nativeimpl/client/FunctionUtils.java#L237).

**Comment by BuddhiWathsala** [comment]
Recently failing intermittent tests.

```sh
[ballerina/http] stopped HTTPS/WSS listener 0.0.0.0:9401

		[fail] testBidiTimestampWithGreeting:

		    Invalid message type

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertFail(assert.bal:236)
		    	ballerina.grpc.0_8_0-beta_3.tests.48_bidi_timestamp_client:testBidiTimestampWithGreeting(tests/48_bidi_timestamp_client.bal:36)

[ballerina/http] stopped HTTPS/WSS listener 0.0.0.0:9401

		[fail] testNestedMessagesWithClientStreaming:

		    Failed to send the message. java.io.IOException: Inbound response message already received

		    	at ballerina.grpc.0_8_0-beta_3:streamSend(streaming_client.bal:113)
		    	ballerina.grpc.0_8_0-beta_3.StreamingClient:send(streaming_client.bal:32)
		    	ballerina.grpc.0_8_0-beta_3.NestedMsgClientStreamingStreamingClient:sendNestedMsg(tests/43_nested_record_with_streams_pb.bal:87)
		    	ballerina.grpc.0_8_0-beta_3.tests.43_nested_record_with_streams_client:testNestedMessagesWithClientStreaming(tests/43_nested_record_with_streams_client.bal:58)

[ballerina/http] stopped HTTPS/WSS listener 0.0.0.0:9401

		[fail] testNestedMessagesWithBidirectionalStreaming:

		    Failed to send the message. java.io.IOException: Inbound response message already received

		    	at ballerina.grpc.0_8_0-beta_3:streamSend(streaming_client.bal:113)
		    	ballerina.grpc.0_8_0-beta_3.StreamingClient:send(streaming_client.bal:32)
		    	ballerina.grpc.0_8_0-beta_3.NestedMsgBidirectionalStreamingStreamingClient:sendNestedMsg(tests/43_nested_record_with_streams_pb.bal:155)
		    	ballerina.grpc.0_8_0-beta_3.tests.43_nested_record_with_streams_client:testNestedMessagesWithBidirectionalStreaming(tests/43_nested_record_with_streams_client.bal:88)
```

**Comment by dilanSachi** [comment]
The following test also fails intermittently.

```
[fail] testDurationBidirectionalStreaming:

		    Assertion Failed!
		    	
		    	expected: '4'
		    	actual	: '3'

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertEquals(assert.bal:112)
		    	ballerina.grpc.0_8_0-beta_3.tests.49_duration_client:testDurationBidirectionalStreaming(tests/49_duration_client.bal:92)
```

**Comment by BuddhiWathsala** [comment]
Recent failure https://github.com/ballerina-platform/module-ballerina-grpc/runs/4537201141?check_suite_focus=true

```sh
[fail] testRouteGuideMessagesWithClientStreaming:

		  java.io.IOException: Inbound response message already received

		   at ballerina.grpc.1:streamComplete(streaming_client.bal:118)
		   ballerina.grpc.1.StreamingClient:complete(streaming_client.bal:42)
		   ballerina.grpc_tests.1.RecordRouteStreamingClient:complete(tests/44_route_guide_pb.bal:138)
		   ballerina.grpc_tests.1.tests.44_route_guide_client:testRouteGuideMessagesWithClientStreaming(tests/44_route_guide_client.bal:61)
```

**Comment by dilanSachi** [comment]
> The following test also fails intermittently.
> 
> ```
> [fail] testDurationBidirectionalStreaming:
> 
> 		    Assertion Failed!
> 		    	
> 		    	expected: '4'
> 		    	actual	: '3'
> 
> 		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
> 		    	ballerina.test.0_8_0:assertEquals(assert.bal:112)
> 		    	ballerina.grpc.0_8_0-beta_3.tests.49_duration_client:testDurationBidirectionalStreaming(tests/49_duration_client.bal:92)
> ```

Focused more on failures like this.

Here, the client sends 4 requests and the grpc server responds with 4 responses.

In the http2 state machine, when the sender finishes and sends `LastHttpContent`, the state transitions from `SendingEntityBody` to `RequestCompleted` according to [here](https://github.com/ballerina-platform/module-ballerina-http/blob/ed9591cea12d07e861cf1146d02bde3d26fc7438/native/src/main/java/io/ballerina/stdlib/http/transport/contractimpl/sender/states/http2/SendingEntityBody.java#L157). But, if the server is sending entitiy body at that moment, https://github.com/ballerina-platform/module-ballerina-http/blob/ed9591cea12d07e861cf1146d02bde3d26fc7438/native/src/main/java/io/ballerina/stdlib/http/transport/contractimpl/sender/states/http2/RequestCompleted.java#L86 gets invoked and that response gets ignored and grpc client does not receive the message.

Is this the expected behaviour from the http transport side @chamil321 @TharmiganK

**Comment by dilanSachi** [comment]
Apparently tests with exception `java.io.IOException: Inbound response message already received` are due to not consuming the `clientStreaming` in the server side. These tests were fixed and are now enabled.

Tests with exception `Assertion Failed!` are due to a issue in `http` statemachine and will be fixed with the PR #796. This PR is on hold to check whether the `http` statemachine implementation is correct.

**Comment by dilanSachi** [comment]
`testBidiStreamingDefaultHttpsPortWithNoService` fails intermittently. Noticed only in windows

**Comment by BuddhiWathsala** [comment]
> `testBidiStreamingDefaultHttpsPortWithNoService` fails intermittently. Noticed only in windows

Log for this failure, but I noticed this on both Linux and Windows.

```
time = 2022-02-08T11:13:56.373Z level = INFO module = ballerina/grpc_tests message = "Request Header: 1234567890"
		[fail] testBidiStreamingDefaultHttpsPortWithNoService:

		    Failed to send the message. java.io.IOException: Remote host closed the connection before initiating outbound request

		    	at ballerina.grpc.1:streamSend(streaming_client.bal:113)
		    	ballerina.grpc.1.StreamingClient:send(streaming_client.bal:32)
		    	ballerina.grpc_tests.1.ChatStreamingClient:sendChatMessage(tests/03_bidirectional_streaming_service_pb.bal:44)
```

**Comment by dilanSachi** [comment]
```
[fail] testRouteGuideMessagesWithBidirectionalStreaming:

Assertion Failed!
	
	expected: '3'
	actual	: '2'

	at ballerina.test.0:createBallerinaError(assert.bal:43)
	ballerina.test.0:assertEquals(assert.bal:112)
```

Noticed this test failure too. This must also be due to same issue as above mentioned in https://github.com/ballerina-platform/ballerina-standard-library/issues/841#issuecomment-998575456

**Comment by dilanSachi** [comment]
Reproduced the above issue locally with running the same bidirectional call for around 2000 times. Ran the same setup using the new `grpc` version with the `http` change and it did not reproduce.
Hence closing the issue.
