### ISSUE TITLE
Check Each Module for Spotbugs and Checkstyle Validations

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#852]
Seems like some of the modules are missing the `spotbugs` and `checkstyle` validation. 

These two checks should be added to the every module build

Additionally, we should also fix the module builds which aren't configured to skip tests when `./gradlew build -x test` is not skipping tests. Please tick the box if both the tasks are completed.

Let's verify each module here:

- [x] http 
- [x] io 
- [x] encoding 
- [x] java.arrays
- [x] jsonutils 
- [x] random
- [x] runtime
- [x] regex
- [x] task
- [x] time
- [x] xmlutils
- [x] crypto
- [x] os 
- [x] xslt
- [ ] ~config~
- [x] reflect
- [x] uuid
- [x] log
- [x] cache 
- [x] file
- [x] ftp
- [x] mime
- [x] nats
- [x] stan 
- [x] tcp
- [x] udp 
- [x] auth
- [x] email 
- [x] jwt 
- [x] oauth2 
- [x] graphql 
- [x] grpc 
- [x] websocket 
- [x] websub 
- [x] websubhub
- [x] kafka
- [x] rabbitmq 
- [x] sql
- [x] java.jdbc
- [x] mysql

**Comment by aashikam** [comment]
Messaging modules: 
https://github.com/ballerina-platform/module-ballerinax-kafka/pull/56
https://github.com/ballerina-platform/module-ballerinax-nats/pull/43
https://github.com/ballerina-platform/module-ballerinax-rabbitmq/pull/46

**Comment by ThishaniLucas** [comment]
Checkstyle & Spotbugs validations are invalid for regex module since it doesn't have any native code.

**Comment by ThisaruGuruge** [comment]
Completed
