### ISSUE TITLE
On java.jdbc does parameterized query parameter needs to be marked @untainted

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-standard-library#86]
**Description:**
It's weird that parameterized query parameter of `query` action is marked `@untainted` as we no longer support 
`testDB->select("SELECT NAME FROM STUDENT WHERE ID = ?", ResultStudent, paramId);` like functionality.

Parameterized query on a select action feels like similar to a prepared statement, and it's natural for a person who is familiar with SQL/JDBC to expect this kind of syntax to be SQL injection safe.

**Steps to reproduce:**

**Affected Versions:**
SLP4
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
@niveathika Can you please point a sample code  with `string` where this `@untained` annotation was intended ?

**Comment by niveathika** [comment]
This effort is paused now since the `@untainted` check is now disabled in Swanlake alpha
