### ISSUE TITLE
Discontinuing WebSub Subscriber extension model from Swan Lake

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#876]
### Current Approach 
Old implementation of webusb subscriber allows you to implement custom subscriber Listeners/Services via an extension model. This extension model is simply a bunch of mappings configured in subscriber-listener-configuration which defines how the dispatching should be done.

Say you are implementing a websub-subscriber Listener/Service for github webhooks. In that case configuration would look like below. 

```ballerina
websub:ExtensionConfig extensionConfig = {
    topicIdentifier: websub:TOPIC_ID_HEADER_AND_PAYLOAD,
    topicHeader: "<HEADER_TO_CONSIDER>",
    headerAndPayloadKeyResourceMap: {
        "issue" : {
            "<PAYLOAD_KEY_TO_CONSIDER>" : {
                "opened": ["onIssueOpened", IssueOpenedEvent],
                "closed": ["onIssueClosed", IssueClosedEvent]
            }
        }
    }
};
```

For more information see [here](https://ballerina.io/learn/api-docs/ballerina/websub/index.html).

### Problems in Current Approach 

This approach seems to be a slippery slope as we continue to implement different custom Subscribers due to following reasons,

1. WebSub spec does not discuss anything on extending it for custom events. Therefore, dispatching logic could be depending headers, body, headers and body, etc.
2. There can be different types of content-types which makes the implementation fragile. 
3. There can be no payload at all in certain events. 
4. Some of the Hub implementations use slight variations of websub spec itself.

Since there is no standard spec on websub extension there could be many unforeseen ones too as Hub implementors can follow different approaches. 

**Already reported issues** 
#846, #748, #818

### Alternate Approach 

Due to aforementioned issues the alternate approach would be to wrap the websub subscriber Service/Listener and write your own custom ones. Only difference here is instead of writing down the mapping in a declarative way, you can simply write the dispatching logic in the websub subscriber service itself.

**The catch** 
The only catch with this approach is Ballerina does not support invoking remote functions using Ballerina itself for the moment. Therefore, implementors will have to write a utile extern functions to invoke remote methods. 

A similar approach was used when implementing HubService and it worked without any issue. In that case, HTTP service/listener was wrapped to implement HubService and Listener.

### Conclusion 

While we can improve the `Current Approach` to work, I see very little value in it. On the other hand, IMO, the `Alternate Approach` not only eliminates above issues in a straight forward way (except point 4) but also more aligned with Ballerina way of doing things.

**Comment by aneeshafedo** [comment]
Alternative approach seems practical in the scenarios where remote function mapping deviate from the current websub implementation.  As an example in Slack Listener Implementation there is requirement to map remote functions with a nested key in the payload. 

However it is still unclear how the current approach will address the issue mentioned in [#818](https://github.com/ballerina-platform/ballerina-standard-library/issues/818)

**Comment by shafreenAnfar** [comment]
Yeah, #818 falls under point 4 and in the `Conclusion` it is mentioned that it does not address point 4. Because point 4 is about spec violations. When the Hub implementor does not follow the spec it is very difficult to provide a generic client for that Hub. In this case it seems they have deviated a lot from the [spec](https://github.com/w3c/websub). 

Therefore, may be the only option is to use standard HTTP listener and client.
