### ISSUE TITLE
[SQL Module Refactor] Add ClientProcessor Class

### ISSUE THREAD

**Issue by trajinthan** [ballerina-platform/ballerina-standard-library#891]
The `ClientProcessor` class is created in the native package.

It is used to expose the `createclient` and `close` functionalities to the connector modules through the static methods `createClient` and `close`.
```java
public class ClientProcessor{
   public static Object createClient(
           BObject client,
           SQLDatasource.SQLDatasourceParams sqlDatasourceParams
   ){
       ...
   }
   public static Object close(BObject client){
       ...
   }
}
````
>Sub Task of #879

**Comment by gayaldassanayake** [comment]
Closed with https://github.com/ballerina-platform/module-ballerina-sql/pull/104
