### ISSUE TITLE
JDBC API for Database/Table Metadata Retrieval

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-standard-library#91]
JDBC contains functionality to query database [1] and table metadata. In this way, we can lookup information such as available tables, and table information, such as primary/foreign key information, field data types etc... This information are not provided by all JDBC drivers, but some do, with different level of functionality. But this information, when available, is very useful especially when we create tools on top of Ballerina for database access. 

[1] https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html

**Comment by niveathika** [comment]
Please find the proposal for this feature, https://github.com/ballerina-platform/ballerina-standard-library/issues/2965

Let's move all discussions to the above issue.
