### ISSUE TITLE
HTTP Request 'Content-Type' header value is overriden while setting the payload

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#920]
* When setting the `payload` for `http:Request` it is overriding the `content-type` header value with a default value derived from the payload itself. 
* It is better if we could allow to pass the `content-type` to `setPayload` method as well.

**Comment by chamil321** [comment]
Assignee: @Tharmigan

**Comment by chamil321** [comment]
@TharmiganK Let's do the same for the `http:Response` as well as we have symmetric methods in both objects
