### ISSUE TITLE
Introduce XML writing operations for I/O

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#941]
Here, we are going to improve the XML writing operation(`io:fileWriteXml`) by introducing XML writing options. 

The motivations of this task are as follows:
- allow the users to write different types of XMLs such as documents and parsed entities
- allow the users to append XML parsed entities
- enable DOCTYPE support

### Related Discussion
https://ballerina-platform.slack.com/archives/C47EAELR1/p1612497228099000

###  Design
```ballerina
public enum FileWriteOption {
    OVERWRITE,
    APPEND
}

public enum XmlContentType {
    DOCUMENT,
    EXTERNAL_PARSED_ENTITY
}

public type XmlWriteOptions record {|
    XmlContentType xmlContentType = DOCUMENT;
    string? docType = ();
    FileWriteOption fileWriteOption = OVERWRITE;
|};

// API
public function fileWriteXml(@untainted string path, xml content, *XmlWriteOptions xmlWriteOptions) returns Error? {}
```

### Remarks
Need to check whether we need to enable XML prolog as `docType`.

**Comment by BuddhiWathsala** [comment]
@jclark please provide your suggestion about the aforementioned design.

**Comment by jclark** [comment]
I would make `fileWriteOption` a separate option, so it is uniform with the other `fileWrite*` functions. Call the parameter `options` or `xmlOptions`: `xmlWriteOptions` is redundant.

`XmlContentType` is not correct XML terminology.

```
public enum XmlEntityType {
   DOCUMENT, // or DOCUMENT_ENTITY
   EXTERNAL_PARSED_ENTITY
}
```

I am not clear what your semantics for doctype are.

**Comment by BuddhiWathsala** [comment]
Here I used the `docType` parameter to allow the user to specify the XML `DOCTYPE` block.

**Comment by jclark** [comment]
I don't know what that means.  Are you saying they would write?

```
docType = "<!DOCTYPE html SYSTEM>"
```

If so, my thoughts are:

- don't camel case docType: it's doctype not docType
- a document type has three parts
   1. the name - this should be generated from the name of the document element, the user should not specify it
   2. optionally an external id consisting of an optional public id and public system id
   3. an internal subset

Please read the spec: https://www.w3.org/TR/xml/#NT-doctypedecl

I would do something like this:

```
type XmlDoctype record {|
   string? system = ();
   string? 'public = ();
   string? internalSubset = ();
|};

type XmlWriteOptions record {|
    // etc;
     XmlDoctype? doctype = ();
|};
```
