### ISSUE TITLE
Server time zone related Error in mysql library

### ISSUE THREAD

**Issue by kasthuriraajan** [ballerina-platform/ballerina-standard-library#952]
**Description:**
When we use mysql library to create a mysql client , there is no way to define `serverTimezone` configuration property . This cause to an error in SQL connector configuration and failed to initialize pool at some time.

Eg: I tried to connect Azure mysql db using ballerina mysql client. The connection string should contain following details for that [1]
```
url=jdbc:mysql://$AZ_DATABASE_NAME.mysql.database.azure.com:3306/demo?serverTimezone=UTC
user=demo@$AZ_DATABASE_NAME
password=$AZ_MYSQL_PASSWORD
```

But in mysql client there is no way to configure `serverTimezone`

If we try to use the mysql client without using `serverTimezone` , it produces the following error:

`error: Error in SQL connector configuration: Failed to initialize pool: The server time zone value 'Coordinated Universal Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support. Caused by :The server time zone value 'Coordinated Universal Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support. Caused by :The server time zone value 'Coordinated Universal Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specific time zone value if you want to utilize time zone support.`

![image](https://user-images.githubusercontent.com/26266914/107495709-72d95e00-6bb6-11eb-909d-8f41f9cf37da.png)

**Solutions for the above issue:**
Allow an option to include the severTimeZone property in the connection string. 

**Workaround**
We can use the jdbc library instead of mysql library. So we can give entire connection string to jdbc client initiation. 

[1][https://docs.microsoft.com/en-us/azure/mysql/connect-java](https://docs.microsoft.com/en-us/azure/mysql/connect-java)

**Comment by lahirusamith** [comment]
As per the documentation[[1]](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html), mysql j/connector is using MysqlDataSource.class to set different client configuration properties, in this case 'serverTimezone', and currently ballerina mysql db connector is not capable of setting those all mentioned configuration properties.

 1. https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html
