### ISSUE TITLE
Research and suggest more useful APIs to Regex module

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-standard-library#954]
Do research on useful APIs for the Regex module and suggest for development.

**Comment by spencerwi** [comment]
Some support for regex matching (with capture groups, ideally even named capture groups) would be useful. Right now, text parsing in Ballerina is painful unless the text is already structured as JSON or XML.

**Comment by kalaiyarasiganeshalingam** [comment]
As per comments[1], We planned to maintain the regex lib with the existing APIs. If any requirements come to introduce new APIs, we will check and implement them by creating new issues. So, we don't need this issue to track tasks.

Hence, closing this issue.

[1] https://github.com/ballerina-platform/ballerina-standard-library/issues/2689#issuecomment-1050657949
