### ISSUE TITLE
Need to update all the build scripts to support `-alpha`

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#957]
Follow the instructions as in https://github.com/ballerina-platform/module-ballerina-os/pull/58/files

- [x] io 
- [x] encoding 
- [x] java.arrays
- [x] jsonutils 
- [x] random
- [x] runtime
- [x] regex
- [x] task
- [ ] time
- [x] xmlutils
- [x] crypto
- [x] os 
- [x] xslt
- [x] reflect
- [x] uuid
- [x] log
- [x] cache 
- [ ] file
- [x] ftp
- [x] mime
- [x] nats
- [x] stan 
- [x] tcp
- [x] udp 
- [x] auth
- [x] email 
- [x] http
- [x] jwt 
- [x] oauth2 
- [x] graphql 
- [x] grpc 
- [x] websocket 
- [ ] websub 
- [ ] websubhub
- [x] kafka
- [x] rabbitmq
- [ ] transaction 
- [x] sql
- [ ] java.jdbc
- [x] mysql

**Comment by aashikam** [comment]
**Kafka/RabbitMQ/STAN/NATS**

Publishing to central:
https://github.com/ballerina-platform/module-ballerinax-nats/pull/75
https://github.com/ballerina-platform/module-ballerinax-stan/pull/18
https://github.com/ballerina-platform/module-ballerinax-rabbitmq/pull/71
https://github.com/ballerina-platform/module-ballerinax-kafka/pull/83

Version update: 
https://github.com/ballerina-platform/module-ballerinax-stan/pull/32
https://github.com/ballerina-platform/module-ballerinax-rabbitmq/pull/86
https://github.com/ballerina-platform/module-ballerinax-kafka/pull/99
https://github.com/ballerina-platform/module-ballerinax-nats/pull/89

**Comment by ThishaniLucas** [comment]
**Regex, Time & File**
https://github.com/ballerina-platform/module-ballerina-regex/pull/11
https://github.com/ballerina-platform/module-ballerina-time/pull/52
https://github.com/ballerina-platform/module-ballerina-file/pull/64
