### ISSUE TITLE
Representing durations in the standard library such as timeouts, intervals, etc

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#967]
At the moment we follow the below convention,

```ballerina
int timeoutInMillis;
int timeoutInSeconds;
```

As recommended we will be updating all those into the below,

```ballerina
decimal timeout;
```

Here the time unit will be `seconds` across all the packages.

**Comment by niveathika** [comment]
@lahirusamith Could you check for SQL modules?

**Comment by lahirusamith** [comment]
> @lahirusamith Could you check for SQL modules?

Will do

**Comment by pubudu91** [comment]
Does this make sense to change everything to `decimal`? Just noticed that cache directives such as `max-age`, `max-stale` have also been changed to `decimal`. The HTTP caching spec explicitly states that these are integers: https://tools.ietf.org/html/rfc7234#section-1.2.1. So having them as decimals in our API just doesn't make sense.

**Comment by shafreenAnfar** [comment]
Thanks @pubudu91 for pointing out. We will have a look. I think it should be okay as this does not make much difference as per user experience. Anyway, I am closing this issue as overall task is compeleted.
