### ISSUE TITLE
HTTP Client default mappings of data types

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#976]
Following is the subset of `anydata` type that can be directly sent from the client. Current HTTP client needs to be improved to support this along with the mapping of default media types.

Type | Media Type
-- | --
xml | application/xml
string | text/plain
byte[] | application/octet-stream
map<json>, table<map\<json\>>, (map\<json\>\|table<map\<json\>>)[] | application/json
int, float, decimal, boolean | application/json

**Comment by chamil321** [comment]
Improved both request and response types as follows
```
# The types of messages that are accepted by HTTP `client` when sending out the outbound request.
public type RequestMessage Request|string|xml|json|byte[]|int|float|decimal|boolean|map<json>|table<map<json>>|
                           (map<json>|table<map<json>>)[]|mime:Entity[]|stream<byte[], io:Error>|();

# The types of messages that are accepted by HTTP `listener` when sending out the outbound response.
public type ResponseMessage Response|string|xml|json|byte[]|int|float|decimal|boolean|map<json>|table<map<json>>|
                            (map<json>|table<map<json>>)[]|mime:Entity[]|stream<byte[], io:Error>|();
```

**Comment by chamil321** [comment]
Updated types via https://github.com/ballerina-platform/module-ballerina-http/pull/560
Type | Media Type
-- | --
xml | application/xml
string | text/plain
byte[] | application/octet-stream
map\<anydata\>, table<map\<anydata\>>, anydata[] | application/json
int, float, decimal, boolean | application/json
