### ISSUE TITLE
HTTP client caching uses lot of memory, leading to 'Java heap space' error

### ISSUE THREAD

**Issue by Mirage20** [ballerina-platform/ballerina-standard-library#989]
We are running our Ballerina applications in memory-restricted (limit set to 350MB) containers. Recently, we discovered the HTTP client caching causes `java.lang.OutOfMemoryError: Java heap space`  for a response payload of around 25KB (Sample payload https://jsonplaceholder.typicode.com/todos). This is a simple service that calls another endpoint and sends the response to the caller. When we disable the client caching, the application works without any issue. 

Is there anything we can do to tune the memory utilization when running in containers? Currently, we increased the heap memory percentage using JVM param MaxRAMPercentage.

### Steps to reproduce

1. Create a test directory `mkdir -p /tmp/bal-test && cd /tmp/bal-test`

2. Add sample code

    ```
    cat <<EOF > test.bal
    import ballerina/http;
    
    service on new http:Listener(8090) {
        resource function get todo(http:Caller caller, http:Request req) {
            http:Client httpEndpoint = new ("https://jsonplaceholder.typicode.com/todos");
    
            http:Response getResponse = <http:Response>checkpanic httpEndpoint->get("/");
    
            var jsonPayload = checkpanic getResponse.getJsonPayload();
    
            checkpanic caller->respond(jsonPayload);
        }
    }
    EOF
    ```
3. Run the application with limited memory `docker run -v /tmp/bal-test/test.bal:/home/ballerina/test.bal -p8090:8090 --memory 350m ballerina/ballerina:swan-lake-preview8.1 ballerina run test.bal`
4. Call the endpoint `curl localhost:8090/todo -v`

### Additional Information
* We are currently using Ballerina slp8.1
* We can see the following logs inside the `ballerina-internal.log`
    
    ```
    [2021-02-18 05:12:54,767] SEVERE {b7a.log.crash} - Java heap space
    java.lang.OutOfMemoryError: Java heap space
            at java.base/java.util.concurrent.ConcurrentHashMap.initTable(ConcurrentHashMap.java:2293)
            at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1017)
            at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
            at org.ballerinalang.stdlib.cache.nativeimpl.Cache.externPut(Cache.java:46)
            at ballerina.cache.2_0_4.cache.externPut(cache.bal:275)
            at ballerina.cache.2_0_4.$value$Cache.put(cache.bal:155)
            at ballerina.cache.2_0_4.$value$Cache.call(cache.bal)
            at ballerina.http.1_0_4.caching_http_cache.addEntry(caching_http_cache.bal:174)
            at ballerina.http.1_0_4.$value$HttpCache.put(caching_http_cache.bal:64)
            at ballerina.http.1_0_4.$value$HttpCache.call(caching_http_cache.bal)
            at ballerina.http.1_0_4.caching_http_caching_client.getCachedResponse(caching_http_caching_client.bal:371)
            at ballerina.http.1_0_4.$value$HttpCachingClient.get(caching_http_caching_client.bal:198)
            at ballerina.http.1_0_4.$value$HttpCachingClient.call(caching_http_caching_client.bal)
            at ballerina.http.1_0_4.$value$Client.get(http_client_endpoint.bal:191)
            at ballerina.http.1_0_4.$value$Client.call(http_client_endpoint.bal)
            at $value$$anonType$_0.$get$todo(test.bal:7)
            at $value$$anonType$_0.call(test.bal)
            at io.ballerina.runtime.api.Runtime.lambda$invokeMethodAsync$1(Runtime.java:95)
            at io.ballerina.runtime.api.Runtime$$Lambda$88/0x0000000100216840.apply(Unknown Source)
            at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:546)
            at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:283)
            at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:251)
            at io.ballerina.runtime.internal.scheduling.Scheduler$$Lambda$24/0x00000001000ab040.run(Unknown Source)
            at java.base/java.lang.Thread.run(Thread.java:834)
    ```

**Comment by chamil321** [comment]
JFR before the fix for sequential continuous request 
BALLERINA_MAX_POOL_SIZE = 2
Xmx = 350m

<img width="1016" alt="Screenshot 2021-07-01 at 18 27 17" src="https://user-images.githubusercontent.com/8381003/124128036-0219dc00-da9a-11eb-8f4e-3998a052e9c8.png">

JFR after the fix for sequential continuous request 
BALLERINA_MAX_POOL_SIZE = 2
Xmx = 350m
<img width="1016" alt="Screenshot 2021-07-01 at 18 20 50" src="https://user-images.githubusercontent.com/8381003/124127869-db5ba580-da99-11eb-91b2-deb2e52c9fd4.png">

**Comment by chamil321** [comment]
Update on the testing :

Created two service by mocking both covid19 and world bank 2 APIs (getStatusByCountry() and getPopulationByCountry()) deployed in separate docker containers

Created passthrough service as same as the above tested code, and the only change is that the Client is created with mock URLs and deployed in docker.Java heap size is configured to -xmx=350M inside the docker.
```ballerina
covid19:Client covid19Client = check new (serviceUrl = "http://169.254.60.13:9090");
covid19:CovidCountry statusByCountry = check covid19Client->getStatusByCountry(country);
```
Source can be found here: https://github.com/chamil321/perf-resources/tree/main/swanlake_5_7_oom_issue_test

To confirm the setup, I initially ran passthrough service using swanlake-alpha5.7 version, then within a few mins the OOM occurred.

![image](https://user-images.githubusercontent.com/8381003/125467369-dea76b3e-b04a-4349-a20a-8390eeb91c76.png)

Then built the image using the swanlake-alpha5.8 version and used the following vegeta cmd to run for 2 hours with the rate of 30.

```
echo 'GET http://localhost:8090/stats/LK' | vegeta attack -rate 30 -duration 120m -output=attack5.bin
```

I used     
```
    -Xlog:gc:GC_LOGS_FILE.txt \
    -Xlog:gc* \
```    
As alternative to the aforementioned flags and got the logs as attached


![image](https://user-images.githubusercontent.com/8381003/125467714-06b87c84-0fdf-48ab-81e8-3d650aa2f792.png)

[GC_LOGS_FILE_5.txt](https://github.com/ballerina-platform/ballerina-standard-library/files/6809511/GC_LOGS_FILE_5.txt)

```
{
   "latencies":{
      "total":4303727912967,
      "mean":19924666,
      "50th":19618442,
      "90th":23177354,
      "95th":24633269,
      "99th":27356303,
      "max":1831278187,
      "min":12946688
   },
   "bytes_in":{
      "total":16416000,
      "mean":76
   },
   "bytes_out":{
      "total":0,
      "mean":0
   },
   "earliest":"2021-07-03T02:11:31.407415971+05:30",
   "latest":"2021-07-03T04:11:31.369112233+05:30",
   "end":"2021-07-03T04:11:31.386042132+05:30",
   "duration":7199961696262,
   "wait":16929899,
   "requests":216000,
   "rate":30.000159599757396,
   "throughput":30.00008905792688,
   "success":1,
   "status_codes":{
      "200":216000
   },
   "errors":[
      
   ]
}
```

**Comment by chamil321** [comment]
After running the same test for 6 hours with the enabled  JFR
```
Summary
Requests      [total, rate, throughput]         648000, 30.00, 30.00
Duration      [total, attack, wait]             6h0m0s, 6h0m0s, 32.871ms
Latencies     [min, mean, 50, 90, 95, 99, max]  13.098ms, 24.789ms, 21.77ms, 35.197ms, 37.299ms, 42.652ms, 30.002s
Bytes In      [total, mean]                     49247685, 76.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           100.00%
Status Codes  [code:count]                      0:1  200:647994  500:5  
Error Set:
500 Internal Server Error
Get "http://localhost:8090/stats/LK": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
We see that 5 requests have failed with 500 responses

![image](https://user-images.githubusercontent.com/8381003/125468416-27df2623-ddd1-4b1c-8309-76d9abd20345.png)
[GC_LOGS_FILE_6.txt](https://github.com/ballerina-platform/ballerina-standard-library/files/6809534/GC_LOGS_FILE_6.txt)
![image](https://user-images.githubusercontent.com/8381003/125468519-4c249528-7faf-43c7-98ad-e30509513973.png)

**Comment by chamil321** [comment]
Update with 0.5 cpu usage

Used flags - --cpus=".5" --memory="350m"

Ran the test for a few minutes with the passthrough service which built on swanlake-alpha5.7 version, then within a few mins the OOM error occurred.
![image](https://user-images.githubusercontent.com/8381003/125468698-71dd01cf-908f-40c2-864a-7b0a4070c6ef.png)
Built the image using the swanlake-alpha5.8 version and ran for 2 hours with the rate of 30.
```
Requests      [total, rate, throughput]         216000, 30.00, 29.99
Duration      [total, attack, wait]             2h0m0s, 2h0m0s, 17.768ms
Latencies     [min, mean, 50, 90, 95, 99, max]  87.931µs, 52.896ms, 20.128ms, 31.672ms, 33.234ms, 56.961ms, 11.487s
Bytes In      [total, mean]                     16409144, 75.97
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           99.96%
Status Codes  [code:count]                      0:86  200:215907  500:7  
Error Set:
Get "http://localhost:8090/stats/LK": dial tcp: lookup localhost: no such host
500 Internal Server Error
```
We see that 7 requests have failed with 500 responses which needs to be investigated

![image](https://user-images.githubusercontent.com/8381003/125468836-8ed4501a-0697-4587-98a3-7578d5f3d3af.png)

![image](https://user-images.githubusercontent.com/8381003/125468891-107c1864-0f54-4ef5-84d5-fbb37b8d8736.png)

**Comment by shafreenAnfar** [comment]
The root cause of this issue is due to a misconfiguration in the default cache capacity value. Here the capacity means the number of entries in the map. But it has been accidentally set thinking the capacity here refers to bytes, which led to a large number of entries which takes around 60 MB. 

Therefore, when services are written in such a way that http clients are created and then thrown away for each request, it creates a lot of garbage which eventually leads to OOM.

The PR linked to this issue corrects the default cache capacity value.

**Comment by shafreenAnfar** [comment]
We will add this as part of our long/running perf test scenarios which will avoid such incidents. https://github.com/ballerina-platform/ballerina-standard-library/issues/1681
