### ISSUE TITLE
Failed to initialize File server connector for Service: ftpServerConnector$$service$0

### ISSUE THREAD

**Issue by msigis** [ballerina-platform/ballerina-standard-library#99]
java -jar file_integration_using_ftp.jar   or  ballerina run  file_integration_using_ftp.bal
error: org.wso2.ei.b7a.ftp.core.util.BallerinaFTPException message=Unable to initialize the FTP listener: Failed to initialize File server connector for Service: ftpServerConnector$$service$0 cause=error org.wso2.transport.remotefilesystem.exception.RemoteFileSystemConnectorException message=Failed to initialize File server connector for Service: ftpServerConnector$$service$0

import ballerina/ftp;
import ballerina/log;

listener ftp:Listener remoteServer = new({
    protocol: ftp:FTP,
    host: "lb-ingestion.infocert.it",
    secureSocket: {
        basicAuth: {
            username: "*****",
            password: "*****"
        }
    },
    port:990,
    path: "/COLL/IMPORT",
    pollingInterval: 60
});

service ftpServerConnector on remoteServer {
    resource function onFileChange(ftp:WatchEvent fileEvent) {

        foreach ftp:FileInfo addedFile in fileEvent.addedFiles {
            log:printInfo("Added file path: " + addedFile.path);
        }
        foreach string deletedFile in fileEvent.deletedFiles {
            log:printInfo("Deleted file path: " + deletedFile);
        }
    }
}

**Comment by Bhashinee** [comment]
This error occurs because the username in basic auth becoming empty. There should be a non-empty string for the username.
